### ISSUE TITLE
Rough Plan

### ISSUE THREAD

**Issue by Qstick** [Prowlarr/Prowlarr#1]
**Plan**
- UI
  - [x] Rip out things from Front
  - [x] Icon
  - [x] Color schemes
  - [x] Basic History UI
  - [x] Basic Indexer UI (@Qstick )
    - [x] Rework Add Indexer to table 
  - [x] Basic Search UI (rework interactive search to a main page) (@Qstick )
    - [x] Manual Search by Indexer
    - [x] Manual Search by CAT
  - [x] Apps (@austinwbest)
    - [x] Basic Application Support
    - [x] Applications
      - [x] Lidarr 
      - [x] Radarr
      - [x] Readarr
      - [x] Sonarr
    - [x] App Syncing
    - [x] App Status

- Backend
  - [x] Rip out everything we don’t need (File Handling, Metadata, Extras, etc) from Backend
  - [x] History for Indexer Queries
    - [x] Hook into search service
    - [x] Change to send back a QueryResults object from HttpIndexerBase with Results and Actually HTTP Response Times (more accurate)
  - [x] Build Newznab Compatible API Controller for CAPs and Results 
    - [x] Caps API Function
    - [x] GetNzb Dowmload Endpoint (Ref or Proxy)
    - [x] Search API Function
      - [x] Hookup Newznab request to Indexer query/Search Criteria (figure out what we want)
  - [x] Expand Release Info
    - [x] Hookup Category Mapping (pending indexer rework for yml templates)
  - [x] Cardigann Indexer yml support 
  - [ ] Newznab ymls (Quick Templates to Define URL and Caps so we don't have to rely on calling them)
  - [x] Separate update system for indexer definitions to prevent constant app updates
  - [x] Net 5 (should we also kill framework support off?) - Release in Nov
  - [x] Nancy Replace

- Services
  - [x] Domain
  - [x] Azure
    - [x] Setup DockerHub Link
    - [x] Sentry Auth Variables
    - [x] Setup Hooks to Update (After Update is Deployed)
  - [x] Update
    - [x] Deploy Update Server with Prowlarr project variable 
  - [x] Discord (later)
  - [x] Sentry
  - [x] Definition Server (@ta264 )

**Comment by bakerboy448** [comment]
Icon can be marked off
