### ISSUE TITLE
Search indexers by description

### ISSUE THREAD

**Issue by Alaksin** [Prowlarr/Prowlarr#1000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When adding an indexer, the search only searches in the Name column of the table. If I want to find an indexer for Japanese content for example, I can only do so by scrolling the list and check every indexer. This makes it difficult to use it for finding new indexers based on what they are providing. 

### Describe the solution you'd like

Searching should be done in the **description**, as well as the **name**

### Describe alternatives you've considered

.

### Anything else?

.

[AB#3140](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3140)

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/en/prowlarr/supported-indexers can be searched as well

**Comment by VorlonCD** [comment]
Searching not only by Name and Description but ALSO search all supported categories would be really helpful.
