### ISSUE TITLE
Broken support with XenForo - PotUK

### ISSUE THREAD

**Issue by KyleSanderson** [Prowlarr/Prowlarr#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Prowlarr fails to login to PotUK which is running XenForo. I was suspecting the code path hadn't been exercised in Prowlarr as the entry has yet to be called out by name anywhere (thus suspecting I'm the first user). I've just confirmed this still works in Jackett, so it's 100% Prowlarr at this point.

After speaking with some kind folks on Discord I've opened a new issue from the previous one: https://github.com/Prowlarr/Indexers/issues/191

Specifically the issue seems to be Prowlarr doesn't expect the login page to return 403 - but that's just what I'm seeing as an end-user.

cc https://github.com/Prowlarr/Prowlarr/issues/29

### Expected Behavior

Feature parity with Jackett, be able to enable PotUK which is a listed indexer.

### Steps To Reproduce

add PotUK as an indexer.

### Environment

```markdown
- OS: Linux
- Prowlarr: 0.3.0.1755
- k8s Install: true
- Using Reverse Proxy: false
- Browser: lynx
```

### What branch are you running?

Develop

### Trace Logs?

[Trace.txt](https://github.com/Prowlarr/Prowlarr/files/8691910/Trace.txt)

[AB#3144](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3144)

**Comment by KyleSanderson** [comment]
For completeness this is still an issue on 0.4.0.1766

**Comment by Qstick** [comment]
Still an issue?

**Comment by KyleSanderson** [comment]
> Still an issue?

Not sure, I had to move back to Jackett because there's no caching on Prowlarr.

**Comment by KyleSanderson** [comment]
Still an issue (caching, as well).

**Comment by Qstick** [comment]
I'll need an invite code to try and fix this.

**Comment by bakerboy448** [comment]
Still an issue with v1.3+? (Current nightly)
