### ISSUE TITLE
Add indexer binnews.ninja (Public)

### ISSUE THREAD

**Issue by the-lazy-fox** [Prowlarr/Prowlarr#1006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Hi,
Currently binnews.ninja is missing from the indexers list.
Thank you!

### Describe the solution you'd like

Hi,
This is a feature request to add binnews.ninja in the list of nzb indexers.
Thank you!

### Describe alternatives you've considered

The alternative is to search manually which is not the purpose of Prowlarr :)

### Anything else?

Thank you for taking this into consideration

[AB#3160](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3160)

**Comment by bakerboy448** [comment]
Indexer Requests belong on the request site linked on the readme, not GitHub Issues.
