### ISSUE TITLE
Segmentation fault from version 0.2.0.1678 and up

### ISSUE THREAD

**Issue by kamakamadaun** [Prowlarr/Prowlarr#1007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I run prowlarr in docker on a synology host.
develop-version-0.2.0.1448 works fine. When I upgrade to version 0.2.0.1678 OR develop OR nightly prowlarr never really starts. The logs ends with:
```
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
When I log into the docker container it looks like in `top` that it starts and crashes continuously. If I try to start it manually from inside the container with `/app/prowlarr/bin/Prowlarr -nobrowser -data=/config` I get `Segmentation fault (core dumped)`. 
So it seems something happened from version  0.2.0.1678 that makes it unable to run on my system.

### Expected Behavior

Graceful quitting with an error message or no error at all.

### Steps To Reproduce

* prowlarr in docker on a synology host (DS412+ with DSM v6.2.4)
* add a container with version 0.2.0.1678 or higher.
* Check logs --> it is not really running.
* Run manually inside the container --> `Segmentation fault (core dumped)`

### Environment

```markdown
- OS: Synology DSM 6
- Prowlarr: 0.2.0.1678 or higher (develop and nightly-0.4 also tested)
- Docker Install: yes
- Using Reverse Proxy: No? Not sure what it is.
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

This is the log before it crashes:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Prowlarr: https://opencollective.com/prowlarr

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1024
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
```

[AB#3161](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3161)

**Comment by kamakamadaun** [comment]
Erh OK? It is not a bug report that it crashes? I will try reddit tomorrow.

**Comment by bakerboy448** [comment]
no it's not a bug that your hardware is presumably old and unsupported and does not support the modern alpine docker containers

This was researched and discussed on discord last night....conclusion was the NAS's kernel  is too old to support the docker images. That was a DS1512+ With `3.10.105 #25556 SMP Sat Aug 28 02:15:10 CST 2021 x86_64 GNU/Linux synology_cedarview_1512+`

> So my guess is your kernel is too old to support the recent alpine in use

Discord convo:
https://discord.com/channels/767843854736949299/767843854824374281/975451918258286592

get newer hardware, or try to (beta) official Servarr native packages 

https://wiki.servarr.com/synology-packages

**Comment by kamakamadaun** [comment]
Thanks for the heads up. That seems very likely the issue.
