### ISSUE TITLE
Pull Jackett Commit 'GazelleTracker: fix GroupTime processing. resolves #13015'

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#1008]
https://github.com/Jackett/Jackett/commit/7adc26966d469debc8a0d7b4afdbfb831d5493fd

[AB#3162](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3162)

**Comment by Qstick** [comment]
Same as #773
