### ISSUE TITLE
UI - Dark Mode - Mobile Dropdown

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#1009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Uploading 416CC151-5724-436D-9A87-D9709C4ED6BA.jpeg…]()

### Expected Behavior

dropdown should be dark not light

### Steps To Reproduce

Visit indexer baseurl dropdown on mobile

### Environment

```markdown
- OS: agnostic
- Prowlarr: 0.4.0.1788
- Docker Install: agnostic
- Using Reverse Proxy: yes
- Browser: 101.0.4951.58 (Chrome iOS)
```

### What branch are you running?

Nightly

### Trace Logs?

N/A

[AB#3164](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3164)

**Comment by Qstick** [comment]
https://github.com/Prowlarr/Prowlarr/commit/5d14d2c134766aa1cb002f745c16ab1c8c725d1c
