### ISSUE TITLE
Handling of 429 errors dynamically / per indexer

### ISSUE THREAD

**Issue by ionred** [Prowlarr/Prowlarr#1022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When receiving a 429 error, Prowlarr only recognizes (in the UI, at least) that there was a problem connecting to a specific indexer. It does not appear to handle these errors in a specific graceful way UI side, rather just providing a generic "can't connect" error message, even upon testing.

### Describe the solution you'd like

Dynamic handling of 429 at the tracker level. If a 429 is received, process any messages regarding wait times and potentially reset the API search count to 0 for that tracker for the provided amount of time. 

### Describe alternatives you've considered

Basic recognition of 429 errors with a default retry time of X hours instead of continuing to retry. 

### Anything else?

I was told in discord they may be another issue open for HTTP message handling but I didn't see anything in search specific to that. If I missed on I apologize.

This is partially covered by issue #910 but I wanted to provide a more generic issue as even non-Newznab indexers may provide 429 errors with or without specific retry times. Even without a specific time, if an HTTP 429 is received a hold can be put on that indexer for a default wait time (an hour? 6 hours?)

[AB#3235](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3235)

**Comment by bakerboy448** [comment]
- BHD 500 error should result in some backing off

**Comment by bakerboy448** [comment]
@mynameisbogdan considered closed or needs to knock this out?

**Comment by bakerboy448** [comment]
- https://github.com/Prowlarr/Prowlarr/commit/7820a83a5d6823c7d0c08cef20a5ec3d374743c8
- https://github.com/Prowlarr/Prowlarr/commit/8e1771b5a91faa1f12875115a091f6bb419e4143
- https://github.com/Prowlarr/Prowlarr/commit/cd3e99ad874d0c766bb0e7c66541b05dfeb9efb3

and others should collectively cover this as far as messaging goes.  If there is something else specific OP is looking for, more details are needed.
