### ISSUE TITLE
"Unknown" Category Column for All IPTorrents Search Results

### ISSUE THREAD

**Issue by ekk88d** [Prowlarr/Prowlarr#1023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Any search for the IP Torrents tracker results in Category column = **Unknown**.

When hovering over the red **Unknown** block, it says:
`Please report this issue to GitHub as this shouldn't be happening`

Only limited info can be extracted from filenames, which depends heavily on groups' file naming schemes.
The Category column is necessary for choosing releases from the results table.
In addition, the Search function needs categories reporting correctly to operate as intended.

When I searched GitHub for duplicates of this ticket, I found an old closed bug, which could be related:
https://github.com/Prowlarr/Prowlarr/issues/305

### Expected Behavior

The red **Unknown** block is replaced, in the search results list, with each release's category/quality like _Movies/Foreign_ or _TV/HD_.

### Steps To Reproduce

1. Search Prowlarr for movie/show with IPTorrents selected as Tracker
2. Check the search results' Category tab.
3. Each result reports as **Unknown**, which also causes Prowlarr to add search results from every other category.

Note: of my five current torrent trackers in Prowlarr, only IPT has this category issue

### Environment

```markdown
- OS: Win10 v10.0.19044 Build 19044
- Prowlarr: 0.3.0.1730-ls54
- Docker Install: "docker -v" SSH command returns "Docker version 20.10.10, build b485636"
- Using Reverse Proxy: No
- Browser: Chrome v102.0.5005.63 (Official Build) (64-bit)
```

### What branch are you running?

Develop

**Comment by bakerboy448** [comment]
Screenshots of the results from it?

> 2022-06-06 15:50:01.8|Trace|IndexerHttpClient|Res: [GET] https://iptorrents.com/t?q=%2B(jeepers+creepers)&72=&87=&77=&101=&89=&90=&96=&6=&48=&54=&62=&38=&68=&20=&7=&100=: 200.OK (89 ms)

what does that URL return on the site?  

This was not able to be reproduced with one of their alt URLs and numerous users have reported that the .com domain no longer works.

**Comment by bakerboy448** [comment]
What do you have Torrents - Category column' option set to?

Based on your site screenshot, I don't see any categories in your search results.

**Comment by bakerboy448** [comment]
Not Prowlarr, on IPTorrents. The site screenshot you provided had no categories in your results and given this isn't reproducible, it seems it's a user config option on IPTorrents side?
