### ISSUE TITLE
Windows - Removing Previous Service Fails; Installer Broken (Nightly) (Postgres caused)

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#1025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`C:\ProgramData\Prowlarr\bin\Prowlarr.Console.exe /u`

whisparr error, but same issue
```
[Fatal] ConsoleApp: EPIC FAIL!

[v0.1.0.47] DryIoc.ContainerException: code: Error.UnableToResolveUnknownService;
message: Unable to resolve Microsoft.Extensions.Options.IOptions<NzbDrone.Core.Datastore.PostgresOptions> as parameter "postgresOptions" (IsSingletonOrDependencyOfSingleton)
  in Singleton NzbDrone.Core.Configuration.ConfigFileProvider: NzbDrone.Core.Configuration.IConfigFileProvider as parameter "configFileProvider" FactoryId=866 (IsSingletonOrDependencyOfSingleton)
```

"it's a problem with the way we do postgres configuration" per Ta

### Expected Behavior

Service Uninstall should work as expected

### Steps To Reproduce

Use the installer which gets stuck and fails at removing existing service or run the command manually

### Environment

```markdown
- OS: Windows 10
- Prowlarr: v0.3.0.1730+
- Docker Install: No
- Using Reverse Proxy: N/A
- Browser: N/A
```

### What branch are you running?

Nightly

### Trace Logs?

-xref https://github.com/Whisparr/Whisparr/issues/25
-xref https://github.com/Radarr/Radarr/issues/7343

[AB#3241](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3241)

**Comment by Qstick** [comment]
I'm confused how we are seeing this in Prowlarr if the PR for this isn't even merged yet

https://github.com/Prowlarr/Prowlarr/pull/838

**Comment by bakerboy448** [comment]
Guess I'm from the future xD
