### ISSUE TITLE
[NORBITS] Error during attempt !

### ISSUE THREAD

**Issue by tordenflesk** [Prowlarr/Prowlarr#1029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Norbits indexer doesn't login

"Error during attempt !"

### Expected Behavior

Norbits indexer working.

### Environment

```markdown
- OS: Debian 11
- Prowlarr:0.3.0.1730
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/8882480/prowlarr.trace.txt)

[AB#3253](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3253)

**Comment by Qstick** [comment]
```2022-06-11 00:00:25.5|Warn|NorBits|Indexer returned result for RSS URL, Credentials appears to be invalid: Error during attempt !```

**Comment by tordenflesk** [comment]
Quite sure. I even disabled 2Fa and logged out and back in to a fresh browser.

**Comment by tordenflesk** [comment]
I've Added Jackett as a Generic Torznab indexer and am able to search NorBits that way.

**Comment by Qstick** [comment]
Had a couple users on discord test this and nobody could reproduce it.
