### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by Feifei4256** [Prowlarr/Prowlarr#1033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installing the program in docker

### Expected Behavior

2022/6/13 0:10:17  Failed to create CoreCLR, HRESULT: 0x80004005

### Environment

```markdown
- OS: nas
- Prowlarr:all
- Docker Install:yes
- Using Reverse Proxy:no
- Browser:edge
```

### What branch are you running?

Develop

### Trace Logs?

M2022-06-12T16:10:24.675472516Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:25.685090753Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:26.992458529Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:27.711940660Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:28.701746117Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:29.703612876Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:30.695879960Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:31.711994141Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:32.714490280Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:33.731499249Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:34.774501763Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:35.737257734Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:36.756880370Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:37.735431576Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:39.023585504Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:39.758846769Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:40.782678607Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:41.774166427Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:42.771523814Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:43.771104253Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:44.798381343Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:45.781701407Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:46.805389798Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:47.812654656Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:48.792031361Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:49.796805171Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:51.135390975Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:51.812590683Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:52.811293656Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:53.825365619Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:54.818430708Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:55.839159788Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:10:56.824861717Z Failed to create CoreCLR, HRESULT: 0x80004005
U2022-06-12T16:10:57.861509642Z [cont-finish.d] executing container finish scripts...
52022-06-12T16:10:57.866407697Z [cont-finish.d] done.
A2022-06-12T16:10:57.867502470Z [s6-finish] waiting for services.
R2022-06-12T16:10:58.098619395Z [s6-finish] sending all processes the TERM signal.
^2022-06-12T16:11:01.122631253Z [s6-finish] sending all processes the KILL signal and exiting.
m2022-06-12T16:11:04.297724903Z [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
e2022-06-12T16:11:04.516000989Z [s6-init] ensuring user provided files have correct perms...exited 0.
W2022-06-12T16:11:04.520717312Z [fix-attrs.d] applying ownership & permissions fixes...
32022-06-12T16:11:04.525911511Z [fix-attrs.d] done.
[2022-06-12T16:11:04.528978637Z [cont-init.d] executing container initialization scripts...
G2022-06-12T16:11:04.537155170Z [cont-init.d] 01-envfile: executing... 
C2022-06-12T16:11:04.609801085Z [cont-init.d] 01-envfile: exited 0.
J2022-06-12T16:11:04.617651760Z [cont-init.d] 01-migrations: executing... 
42022-06-12T16:11:04.633129917Z [migrations] started
@2022-06-12T16:11:04.633315965Z [migrations] no migrations found
F2022-06-12T16:11:04.636048006Z [cont-init.d] 01-migrations: exited 0.
L2022-06-12T16:11:04.642501802Z [cont-init.d] 02-tamper-check: executing... 
H2022-06-12T16:11:04.725862468Z [cont-init.d] 02-tamper-check: exited 0.
G2022-06-12T16:11:04.731265727Z [cont-init.d] 10-adduser: executing... 
32022-06-12T16:11:04.839980914Z usermod: no changes
 2022-06-12T16:11:04.840261074Z 
E2022-06-12T16:11:04.840359498Z -------------------------------------
62022-06-12T16:11:04.840462068Z           _         ()
;2022-06-12T16:11:04.840562799Z          | |  ___   _    __
<2022-06-12T16:11:04.840652760Z          | | / __| | |  /  \
=2022-06-12T16:11:04.840741441Z          | | \__ \ | | | () |
<2022-06-12T16:11:04.840839701Z          |_| |___/ |_|  \__/
 2022-06-12T16:11:04.840924624Z 
 2022-06-12T16:11:04.841001343Z 
@2022-06-12T16:11:04.841072422Z Brought to you by linuxserver.io
E2022-06-12T16:11:04.841162713Z -------------------------------------
 2022-06-12T16:11:04.841251531Z 
@2022-06-12T16:11:04.841353829Z To support the app dev(s) visit:
M2022-06-12T16:11:04.853675058Z Prowlarr: https://opencollective.com/prowlarr
 2022-06-12T16:11:04.854165985Z 
?2022-06-12T16:11:04.854392204Z To support LSIO projects visit:
B2022-06-12T16:11:04.854493723Z https://www.linuxserver.io/donate/
E2022-06-12T16:11:04.854617511Z -------------------------------------
'2022-06-12T16:11:04.854723665Z GID/UID
E2022-06-12T16:11:04.854824366Z -------------------------------------
 2022-06-12T16:11:04.885885494Z 
12022-06-12T16:11:04.886070538Z User uid:    1000
12022-06-12T16:11:04.886170422Z User gid:    1000
E2022-06-12T16:11:04.886271113Z -------------------------------------
 2022-06-12T16:11:04.886411842Z 
C2022-06-12T16:11:04.944181676Z [cont-init.d] 10-adduser: exited 0.
F2022-06-12T16:11:04.949661785Z [cont-init.d] 30-config: executing... 
B2022-06-12T16:11:05.008760317Z [cont-init.d] 30-config: exited 0.
N2022-06-12T16:11:05.012735618Z [cont-init.d] 90-custom-folders: executing... 
J2022-06-12T16:11:05.073823168Z [cont-init.d] 90-custom-folders: exited 0.
L2022-06-12T16:11:05.079877769Z [cont-init.d] 99-custom-files: executing... 
N2022-06-12T16:11:05.166765436Z [custom-init] no custom files found exiting...
H2022-06-12T16:11:05.169265433Z [cont-init.d] 99-custom-files: exited 0.
32022-06-12T16:11:05.172458004Z [cont-init.d] done.
>2022-06-12T16:11:05.176955476Z [services.d] starting services
22022-06-12T16:11:05.213634471Z [services.d] done.
M2022-06-12T16:11:05.576482651Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:11:06.364726176Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:11:07.383512561Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:11:08.369842409Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:11:09.378163229Z Failed to create CoreCLR, HRESULT: 0x80004005
M2022-06-12T16:11:10.358390868Z Failed to create CoreCLR, HRESULT: 0x80004005
U2022-06-12T16:11:10.558524065Z [cont-finish.d] executing container finish scripts...
52022-06-12T16:11:10.561443224Z [cont-finish.d] done.
A2022-06-12T16:11:10.562586794Z [s6-finish] waiting for services.
R2022-06-12T16:11:10.779933468Z [s6-finish] sending all processes the TERM signal.
^2022-06-12T16:11:13.795202892Z [s6-finish] sending all processes the KILL signal and exiting.

[AB#3258](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3258)

**Comment by Roxedus** [comment]
Need info about your NAS
