### ISSUE TITLE
Exclude Search Terms

### ISSUE THREAD

**Issue by annomatik** [Prowlarr/Prowlarr#1034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not really, but kind of. NZBGet crashes for me, if the nzb title contains something like [MAGAZINE) in it. I'd like to feed NZBGet witht an RSS, which works fine, if the search result does not contain square brackets. As soon as it does and NZBGet tries to load it, I get a SegVault in NZBGet.

Probably something that needs to be sorted out in NZBGet, but anyways, I would like to be able to exclude search terms, like e.g. in "Some Ebook -[MAGAZINE]", which should return everything that contains "Some Ebook" in its title, but exclude stuff that contains "[MAGAZINE]".

### Describe the solution you'd like

I would like to be able to exclude search terms, like e.g. in "Some Ebook -[MAGAZINE]", which should return everything that contains "Some Ebook" in its title, but exclude stuff that contains "[MAGAZINE]".

### Describe alternatives you've considered

I tried excluding the [MAGAZINE] things in NZBGet, unfortunatelly, that makes it crash as well. Also, being able to exclude stuff in search terms would be cool, regardless of NZBGet crashing or not.

### Anything else?

Not really. Thanks for your Work!

[AB#3287](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3287)

**Comment by bakerboy448** [comment]
Covered under #27  10. Global restrictions (word filters, forbidden posters, max results age, min seeders, ignore passworded releases)
