### ISSUE TITLE
Add Application modal doesn't use the configured port for prowlarr

### ISSUE THREAD

**Issue by addisonbabcock** [Prowlarr/Prowlarr#104]
The Add Application dialog uses the hardcoded default port of 9696 instead of the configured port that prowlarr is using. This starts as a small problem but can result in silent failures because there is no validation of the sonarr -> prowlarr connection. 

**To Reproduce**
1. Start prowlarr on a non-default port (I'm using 9695 in this case).
2. Try to add a new application (I'm using sonarr)
3. The Prowlarr Server default value is using the default 9696 port. 

**Expected behavior**
I would expect prowlarr to pull the host and port out of the URL in the browser. The theory being that if a browser can access it then hopefully so can sonarr. 

**Screenshots**

![image](https://user-images.githubusercontent.com/2836233/120915862-5381a780-c663-11eb-834c-46f4a419f347.png)

**Platform Information (please complete the following information):**
 - OS: Windows 10 20H2
 - Docker: No
 - .NET Version (System -> Status): 5.0.6
 - Browser and Version (Only needed for UI issues): Edge dev 92.0.902.4 (reprod in private mode, no extensions)
 - Prowlarr Version:  0.1.0.361
 - Prowlarr Branch:  nightly

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6603777/prowlarr.trace.txt)

[AB#41](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/41)

**Comment by Qstick** [comment]
We should just change this to a placeholder instead of a default value @RobinDadswell, per your work on Radarr
