### ISSUE TITLE
Prowlarr reporting VIP is expiring on index, but I have 312 days left....

### ISSUE THREAD

**Issue by herkalurk** [Prowlarr/Prowlarr#1043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a status message that vip is expiring soon.

![image](https://user-images.githubusercontent.com/2532699/175426772-00813c39-33cd-46d7-84a0-57cff156f763.png)

![image](https://user-images.githubusercontent.com/2532699/175427122-c8ac4e86-ddc9-4bdd-ad9b-f5133b948137.png)

### Expected Behavior

Would not expect this to occur unless actually close to expiration date

### Steps To Reproduce

Go to prowlarr web UI, see alert

### Environment

```markdown
- OS: Centos 7
- Prowlarr: 0.3.0.1730
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox
```

### What branch are you running?

Master

### Trace Logs?

I do not see any indication in logs about this, if you can tell me what messages to search for I can provide more debugging info.

[AB#3315](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3315)

**Comment by bakerboy448** [comment]
- there's no master branch
- the indexer's VIP on the site doesn't matter, need a screenshot of what you've set the VIP Expiration to in Prowlarr for that indexer

**Comment by herkalurk** [comment]
Apparently I have it set to 2022-06-27.  I didn't realize I had done that during setup manually and thought it was perhaps being pulled via API.

**Comment by herkalurk** [comment]
> * there's no master branch

That is a pulldown menu in the new bug report form, perhaps it should be removed.

![image](https://user-images.githubusercontent.com/2532699/175428833-14d9c285-5b04-4439-8940-c5cde45efdf5.png)
