### ISSUE TITLE
MoreThanTV parsing issue

### ISSUE THREAD

**Issue by klepp0906** [Prowlarr/Prowlarr#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was using MTV as a generic torznab for awhile and saw it in the preset/trackers list and so tried to add it the "right" way.  unfortunately i'm greeted with a red exclamation point saying the indexer failed roughly 10 seconds after testing succeeding and adding it.

### Expected Behavior

For it to function the same as any other preset indexer. 

### Steps To Reproduce

1. search and add the morethantv indexer preset using a cookie
2. it fails within a few seconds after adding

### Environment

```markdown
- OS: Win11
- Prowlarr: 0.4.2.1843
- Docker Install:
- Using Reverse Proxy:
- Browser: Brave
```

### What branch are you running?

Nightly

### Trace Logs?

https://0bin.net/paste/w3eUthTs#8CJuHKujCO00+bSXRH4yyvLP8bzBZnYEx1fAm4P5ECB

[AB#3323](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3323)

**Comment by bakerboy448** [comment]
Logs expired

**Comment by nathanvdh** [comment]
> Logs expired

Here I just took some: https://privatebin.net/?786ab1ff8ad253ab#6QwS4fDq2XrhTjb7bj8oU9mdHB2o7cB1m7gvuuWbxP1C

**Comment by describe19** [comment]
> Logs expired

Here I just took some: https://privatebin.net/?786ab1ff8ad253ab#6QwS4fDq2XrhTjb7bj8oU9mdHB2o7cB1m7gvuuWbxP1C
