### ISSUE TITLE
ArabaFenice - Query successful, but no results were returned from your indexer

### ISSUE THREAD

**Issue by Jorman** [Prowlarr/Prowlarr#1048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error when adding tracker ArabaFenice

### Expected Behavior

Adding without errors

### Environment

```markdown
- OS: Linux Debian
- Prowlarr:0.4.2.1846-ls365 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Nightly

### Trace Logs?

Hi to all, I got error when I try to add ArabaFenice torrent, here all the logs
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/9011950/prowlarr.txt)
[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/9011952/prowlarr.debug.txt)
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/9011953/prowlarr.trace.txt)

If I remember correctly on Jackett works, but I don't use Jackett anymore so I haven't tried.

Is a bad error?

J

[AB#3324](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3324)

**Comment by Qstick** [comment]
Dupe #185
