### ISSUE TITLE
Prowlarr not pulling correct episodes

### ISSUE THREAD

**Issue by kyleslaw88** [Prowlarr/Prowlarr#1049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Searching for episodes using episode name and sXXeYY yields incorrect/unrelated results.

Similar issue found here:
https://github.com/Prowlarr/Prowlarr/issues/165#issue-915100847

### Expected Behavior

Searching for Peppa Pig S07E54 (or similarly searching for Friends SXXEYY) should yield results for the correct episode.

### Steps To Reproduce

1. Open Prowlarr
2. Search for series name, season, and episode number
3. Browse results
<img width="1719" alt="Prowlar Results - PP" src="https://user-images.githubusercontent.com/108549712/176955083-21e56457-9328-415e-97e7-cb4411b146d1.png">

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr:0.4.1.1838
- Docker Install: Yes - 0.4.1.1838-ls56 by linuxserver.io
- Using Reverse Proxy: Yes - haugene/transmission-openvpn-proxy	
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

[Prowlarr Trace Logs.txt](https://github.com/Prowlarr/Prowlarr/files/9031115/Prowlarr.Trace.Logs.txt)

[AB#3329](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3329)

**Comment by bakerboy448** [comment]
EZTV only returns results for specific series it has. If it can't match the series, it returns garbage results. Not a prowlarr issue

**Comment by kyleslaw88** [comment]
> EZTV only returns results for specific series it has. If it can't match the series, it returns garbage results. Not a prowlarr issue

Understood. However, as I have roughly 10 indexers for this category and I am not getting relevant results on a large number of what I would consider common shows, I thought perhaps Prowlarr was either (1) not communicating properly with the indexers or (2) it was not sending the correct search criteria.

**Comment by kyleslaw88** [comment]
> Subreddit

Thanks... as there was a previous bug identified with an earlier version of Prowlarr, I had thought perhaps the issue was related. I'll take a look at the other support channels.
