### ISSUE TITLE
Indexer - Sportscult - Search Error

### ISSUE THREAD

**Issue by manderss99** [Prowlarr/Prowlarr#105]
Searching using Sportscult indexer causes error message

**To Reproduce**
1. add Sportscult as indexer
2. go to search page
3. search anything, for example motogp
4. error message is displayed: There was an error loading this page

**Expected behavior**
list of search results

**Platform Information (please complete the following information):**
 - OS:  Ubuntu 21.04 
 - Docker:  Yes
 - .NET Version (System -> Status): 
 - Browser and Version (Only needed for UI issues): 
 - Prowlarr Version:  0.1.0.361
 - Prowlarr Branch:  nightly

**Comment by manderss99** [comment]
details show this message:
TypeError: Cannot read property 'filter' of undefined

same problem happens with rutracker.ru as well

**Comment by Qstick** [comment]
Need full logs or an invite

**Comment by manderss99** [comment]
I can get you an invite, which email should I sent it to?

**Comment by bakerboy448** [comment]
logs would be helpful as well https://wikijs.servarr.com/prowlarr/troubleshooting

**Comment by manderss99** [comment]
here are logs, I dont see anything obvious
https://pastebin.ubuntu.com/p/5jyjggSVq2/

**Comment by manderss99** [comment]
![image](https://user-images.githubusercontent.com/3218274/121322068-edb94800-c90e-11eb-8a73-894fe36fc3df.png)

**Comment by Qstick** [comment]
> I can get you an invite, which email should I sent it to?

qstick@protonmail.com

**Comment by manderss99** [comment]
invite sent, thanks for looking into this issue.

**Comment by Qstick** [comment]
Thanks, hopefully next nightly build fixes this
