### ISSUE TITLE
Allow DDL sites AKA HTTP/S protocol

### ISSUE THREAD

**Issue by BakasuraRCE** [Prowlarr/Prowlarr#1050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

For some time I have been looking for a good solution to search among multiple sites that have no type of API or standard to download from them, however, they are very good places.

Well, Prowlarr is so good that you can even look for those pages using cardigann (I have already made a YML with a test site and it works really well)

### Describe the solution you'd like

Well, I am aware that trying to automate obtaining links from any DDL site is a difficult task, and many times it simply is not worth it.

That is why this functionality is focused on one thing: "seek quickly in multiple places at the same time," that's all.

The rest of the tasks in the flow, such as obtaining links, and sending them to the download customer, pass the infinite advertising. These are things that for DDL sites are easier to do by hand in most cases

In particular, creating a new protocol called "http/s" would allow these searches to be performed in all "DDL indexers". And as I said, its only objective would be to save time looking for each other.

### Describe alternatives you've considered

I have tried to use Scrapy (Python library) to do the job, and implement a pretty interface with Vuejs, then the "indexers" are required...

You know, the way at the end, leads you to modify software that already does this.

### Anything else?

Good open-source download client for DDL: https://pyload.net/

[AB#3330](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3330)

**Comment by bakerboy448** [comment]
Per https://github.com/Prowlarr/Prowlarr/issues/510#issuecomment-926228254
> No plans to have Prowlarr direct download anything.
