### ISSUE TITLE
Can't add indexers m-team (mteam)

### ISSUE THREAD

**Issue by luckyboy** [Prowlarr/Prowlarr#1061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Add indexer m-team always show "Unable to connect to indexer, check the log for more details"

### Expected Behavior

Indexer added successfully

### Environment

```markdown
- OS: Synology DSM 7.1
- Prowlarr:0.4.2.1879
- Docker Install:Yes
- Using Reverse Proxy:No
- Browser:Chrome newest version
```

### What branch are you running?

develop

### Trace Logs?

https://pastebin.com/R321SeGg

**Comment by bakerboy448** [comment]
Please remove the extremely lengthy set of info logs that make your GitHub issue unreadable.

And then provide the required TRACE logs that the template calls for: https://wiki.servarr.com/prowlarr/troubleshooting#logging-and-log-files

**Comment by bakerboy448** [comment]
the trace logs required for bug reports still have not been provided.  info logs saying there is an error is not valid for bug reports

**Comment by bakerboy448** [comment]
```
2022-07-23 03:12:56.0|Trace|IndexerHttpClient|Req: [GET] https://kp.m-team.cc/torrents.php?search=&incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc
2022-07-23 03:12:56.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-07-23 03:12:56.3|Trace|IndexerHttpClient|Res: [GET] https://kp.m-team.cc/torrents.php?search=&incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc: 302.Redirect (145 bytes) (364 ms)
2022-07-23 03:12:56.3|Trace|IndexerHttpClient|Response content (145 bytes): <html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.16.1</center>
</body>
</html>

2022-07-23 03:12:56.3|Debug|FlareSolverr|CF Protection not detected, returning original response
2022-07-23 03:12:56.3|Warn|Cardigann|Unable to connect to indexer

[v0.4.3.1908] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannException: Got redirected to another domain. Try changing the indexer URL to https://www.google.com/.
   at NzbDrone.Core.Indexers.Cardigann.CardigannRequestGenerator.CheckIfLoginIsNeeded(HttpResponse response) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannRequestGenerator.cs:line 942
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 378
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 314
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 511


2022-07-23 03:12:56.3|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.4.3.1908] FluentValidation.ValidationException: Validation failed: 
```
From https://github.com/Prowlarr/Prowlarr/issues/1073#issuecomment-1192864880

> Their domain is redirecting to google which then seems to redirect to cloudflare...we're now handling the redirect well it seems
> 
> Seems even flaresolverr itself has issues with this site [FlareSolverr/FlareSolverr#414](https://github.com/FlareSolverr/FlareSolverr/issues/414)
https://github.com/Prowlarr/Prowlarr/issues/1073#issuecomment-1192867886

**Comment by FlameSky-S** [comment]
Same issue here, waiting for a fix.

**Comment by AbuRyu** [comment]
Waiting for the fix.....

**Comment by Qstick** [comment]
You guys can always stop waiting and fix it yourselves, it's all open source.

**Comment by bakerboy448** [comment]
Still an issue on FS's side anyway.

https://github.com/FlareSolverr/FlareSolverr/issues/414#issuecomment-1200313005

**Comment by AbuRyu** [comment]
> You guys can always stop waiting and fix it yourselves, it's all open source. 

If we could do that, we wouldn't come here asking about it, duuh.

**Comment by AbuRyu** [comment]
> Still an issue on FS's side anyway.
> 
> https://github.com/FlareSolverr/FlareSolverr/issues/414#issuecomment-1200313005

Alright, I guess we'll have to wait then. Thanks man!

**Comment by FlameSky-S** [comment]
> You guys can always stop waiting and fix it yourselves, it's all open source.

Not everyone is an experienced programmer, and this is what issues are about, isn't it

**Comment by Qstick** [comment]
Asking and nagging in this way, you've quickly made it to the bottom of a very long list. So might be time to learn.

**Comment by bakerboy448** [comment]
The main development team is split across 5 apps: Lidarr, Prowlarr, Radarr, Readarr, and Whisparr.
There are only ~3 active developers who work on this, and of those 3 exactly zero work on this fulltime. Exactly zero of any members involved (developers / support) get paid to do this. Everyone has fulltime real jobs. Everyone has kids and family. Everyone works on more than just this project.

As you can imagine between the five projects (in addition to the various backends and other modules), the todo list is long and time short.

Nagging in the ways done here and asking why something isn't done, combined with the 👎 reactions do not do any favors for getting an issue resolved sooner. Quite the opposite as Q said.

**Comment by FlameSky-S** [comment]
I know it's gonna take weeks or months to fix an issue in a project like this, and I didn't mean to push you guys in the first place, just wanted to report that I've experienced the same problem. 

I was on a bad day and Q's comment and the 👎 reaction on AbuRyu's comment somehow became the last straw.  I apologize for my reactions before and thank you guys for the great work in this project.

**Comment by TinPoChan** [comment]
FS just updated to 2.2.6 and it works with Jackett, those using m-team as indexers can switch to Jackett temporarily until Prowlarr fixes it.

And again, really appreciate the "arr" development team, you guys are awesome and created something amazing.

**Comment by luckyboy** [comment]
> FS just updated to 2.2.6 and it works with Jackett, those using m-team as indexers can switch to Jackett temporarily until Prowlarr fixes it.
> 
> And again, really appreciate the "arr" development team, you guys are awesome and created something amazing.

Agree, "arr" dev team is creating excellent software, let's just wait.
