### ISSUE TITLE
Update categories on Locadora tracker

### ISSUE THREAD

**Issue by costaht** [Prowlarr/Prowlarr#1069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Categories of Locadora tracker are outdated

### Describe the solution you'd like

Would you please translate/apply these configs to Prowlarr? 

```
caps:
  categorymappings:
    - {id: 1, cat: Movies}
    - {id: 2, cat: TV}
    - {id: 6, cat: TV/Anime}
    - {id: 7, cat: Movies, desc: "Concerts"}
```
Full config is here: https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/locadora.yml

We removed some descriptions from the categories because they were causing the category to be duplicated on Sonarr/Radarr. So if you can make those changes to reflect the config above, I would appreciate it.

Thank you

### Describe alternatives you've considered

No alternatives considered

### Anything else?

Before:
![image](https://user-images.githubusercontent.com/50637431/179425136-2452708b-b6e6-428b-bed6-9233136f2261.png)

After:
![image](https://user-images.githubusercontent.com/50637431/179425143-5635a6aa-4522-47e7-9a1a-1731b088f81c.png)

[AB#3369](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3369)

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/202b2ff1f6e81321d2eef9d997929ba4e63d3dd9
