### ISSUE TITLE
Add: prioritization of indexers

### ISSUE THREAD

**Issue by michpas** [Prowlarr/Prowlarr#108]
**Is your feature request related to a problem? Please describe.**
Currently in Radarr/Sonarr there is an option to give an indexer priority
This helps, when the same file is found on multiple indexers, it will grap the stamp-file from the highest priority
This prioritization is not available in Prowlarr. 

**Describe the solution you'd like**
Would be great to be able to set this as a default that that copies over the indexer profiles in Radarr/Sonarr

**Describe alternatives you've considered**
Manually change each profile in each Radarr/Sonarr instance.

**Additional context**

**Comment by Qstick** [comment]
It’s already there, just turn on advanced settings (not super intuitive as of yet from indexer screen)

**Comment by michpas** [comment]
Hi. that is great. But are you sure ?where do you see the advanced setting? I looked at all pages and menus don't see any advance button.
Running the nightly of Hotio

![image](https://user-images.githubusercontent.com/66222810/120938403-d57cd980-c712-11eb-81d5-d1a566b373ce.png)

**Comment by misleadingrhino** [comment]
If you go to settings in the left column, at the top, under the search bar you'll see Show Advanced. If you click that, then go back and configure an indexer (the little wrench all the way on the right), indexer priority will be there with an orange title at the bottom.

**Comment by michpas** [comment]
Thanks. got it. indeed a bit hidden. But works great!
