### ISSUE TITLE
Prowlarr doesn't find Movie but if the indexer is in Radarr

### ISSUE THREAD

**Issue by sNor4pro** [Prowlarr/Prowlarr#1081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hey,
the Indexer in Prowlarr doesn't find the same results as directly in Radarr.
Example: nzb.su (looking for The Medium or Chariot in german) 
This indexer is in Radarr added by me and one time added by Prowlarr (for testing)
Only the one directly in Radarr finds this movie in german for me. 
Foreign catergory is checked everywhere.
(nzb.su is only searched with imdb number not extra with movie title)

### Expected Behavior

Find the same movies with Prowlarr like integrated in Radarr 
Looking on nzb.su via IMDB/tmdb number and if nothing is found look for movie title.

### Steps To Reproduce

1. Add movie 
2. Search for it via nzb.su + german
3. looking for german movie  Prowlarr doesn't find anything in german.

### Environment

```markdown
- OS: unRAID 6.10.3
- Prowlarr:0.4.4.1928
- Docker Install: Yes
- Using Reverse Proxy: No
```

### What branch are you running?

Nightly

### Trace Logs?

2022-07-31 16:50:50.9|Info|ReleaseSearchService|Searching indexer(s): [Nzb.su] for Term: [] | ID(s): IMDbId:[13446168], Offset: 0, Limit: 100, Categories: [2000, 2010, 2020, 2030, 2035, 2040, 2045, 2050, 2060]

[AB#3407](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3407)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

- info logs are invalid for bug reports
- This is not a bug. Prowlarr searches what the user tells it to. There is not nor does it make sense to add any fallback logic....why should prowlarr search for something the user didn't tell it to? Radarr/Sonarr fallback and do a text query if the id query returns no results
- If you need to search by title....then search by title.
