### ISSUE TITLE
[ABB Indexer] https support

### ISSUE THREAD

**Issue by meapwork** [Prowlarr/Prowlarr#1083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems recently Audiobookbay (ABB) has added support for https making the base url list not working.

### Expected Behavior

 These seem to be working fine but are not currently in the base url list (all https now)
  - https://audiobookbay.fi
  - https://audiobookbay.se
  - https://audiobookbay.ch

### Steps To Reproduce

1. Add a new Indexer
2. Choose AudioBookBay
3. Select base url and test either http://audiobookbay.fi or http://audiobookbay.se
4. "Unable to connect to indexer, check the log for more details"

### Environment

```markdown
- OS: Windows 10
- Prowlarr: 0.4.3.1921
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome 103
```

### What branch are you running?

Develop

### Trace Logs?

2022-08-01 18:32:44.9|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details

[AB#3410](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3410)

**Comment by bakerboy448** [comment]
A single line validation error is not valid for bug reports.


This should get taken care of with the next set of jackett pulls
