### ISSUE TITLE
Data not persistent, losing indexers every few days

### ISSUE THREAD

**Issue by BrodyStone21** [Prowlarr/Prowlarr#1096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every few days, I'll lose all indexers that I set up. They'll survive container restarts, complete container deletion and reconfiguration, but out of nowhere, the indexers will just disappear. 

### Expected Behavior

Expected behaviour is that the indexers don't automatically delete themselves and require manual reconfiguration. 

### Steps To Reproduce

1. Run Prowlarr in Docker.
2. Attach Prowlarr to Sonarr and Radarr
3. Configure indexers
4. Restart container, delete and upgrade container, whatever else you feel like doing. Notice the indexers are still there
5. Wait a few days and notice the indexers have vanished out of nowhere

### Environment

```markdown
- OS: Ubuntu 20.04.4 LTS
- Prowlarr: 0.4.3.1921
- Docker Install: Yes (Linux Server)
- Using Reverse Proxy:
- Browser: Google Chrome (Latest)
```

### What branch are you running?

Master

### Trace Logs?

https://pastebin.com/raw/aX8ZDGqV

I can't find anything relevant in here, but you're welcome to take a look. 

[AB#3465](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3465)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

 Nothing in Prowlarr would cause the database to be cleared. You probably do not have /config persisted
