### ISSUE TITLE
Add support for application Mylar3

### ISSUE THREAD

**Issue by kingfenix** [Prowlarr/Prowlarr#110]
Please add support for mylar3 in addition to the existing arr's like Sonarr/Radarr/Lidarr/Readarr

**Comment by Qstick** [comment]
Added to #86, thanks

**Comment by bakerboy448** [comment]
Landed https://github.com/Prowlarr/Prowlarr/commit/77892a3885a0675e9cc53a48a6fe9b28011cb7a6
