### ISSUE TITLE
AvistaZ trackers freeleech only toggle

### ISSUE THREAD

**Issue by akesher123** [Prowlarr/Prowlarr#1108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I don't believe this is related to an problem; this is just a wish. I would love for Prowlarr to support freeleech/halfleech with the AvistaZ family of trackers. I'm not sure if this is possible with their API (I couldn't find docs for it anywhere), so I understand if this is not possible until they do something on their end.

### Describe the solution you'd like

A simple "Search freeleech only" toggle like is common on other indexers.

### Describe alternatives you've considered

It's possible to have a freeleech-only RSS feed, and I've added this to prowlarr. However, 99% of my usage is searching for old torrents, so very rarely does a successful hit come from an RSS feed. This suggestion would be more useful for automatic/manual searching than RSS feeds.

Theoretically this could also be accomplished by using whatever methodology they use for determining if a torrent is FL. It seems to me that on Avistaz >=10gb, <20gb is HL and >=20gh is FL. This could maybe be used as a proxy though it wouldn't account for things like featured torrents.

### Anything else?

If this is an API issue on their end, I'll see if there's any feedback I could get as a feature request in their forums. Thanks

[AB#3678](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3678)

**Comment by bakerboy448** [comment]
Would need their api docs for how to search freeleech only

**Comment by akesher123** [comment]
https://github.com/Jackett/Jackett/issues/8727#issuecomment-632649313 Not true documentation but it looks like the `download_multiply` in the response shown here is the relevant parameter

**Comment by bakerboy448** [comment]
> https://github.com/Jackett/Jackett/issues/8727#issuecomment-632649313 Not true documentation but it looks like the `download_multiply` in the response shown here is the relevant parameter

Response != query parameters

**Comment by akesher123** [comment]
True. I suppose it's out of the question to filter results based on responses instead of having a query that can return only FL?

**Comment by akesher123** [comment]
Actually, farther down in the comment they pass a `discount` param in the request that could be of interest. I'm not sure how the number there correlates with which level, but I believe that's the answer

**Comment by akesher123** [comment]
Looking at the url on the search page manually it appears that adding `&discount%5B%5D=1` is for freeleech, 2 halfleech, 3 double upload. These can be added independently with each other where the search results are ORed from each tag.

**Comment by bakerboy448** [comment]
So adding `&discount%5B%5D=1` to the request would search freeleech only on all 3 sites?

**Comment by ilike2burnthing** [comment]
I don't have a PrivateHD account, but AvistaZ, CinemaZ, and ExoticaZ all use `&discount%5B%5D=1` to search freeleech only. I don't expect PrivateHD to be any different.

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/68df4394986e66a26413fcfff350239b01cf8a5d

**Comment by TheRedSpy15** [comment]
Changing the freeleech setting to "true" fails when testing

Works if left to false

**Comment by bakerboy448** [comment]
> Changing the freeleech setting to "true" fails when testing
> 
> Works if left to false

Please open a bug report with all the required information
