### ISSUE TITLE
Not working with cathode-ray.tube

### ISSUE THREAD

**Issue by jsmdy** [Prowlarr/Prowlarr#1109]

**Comment by bakerboy448** [comment]
- there is no master branch
- logs provided are not the required trace logs
- logs provided saying validation failed are not of any use for a bug report....needs the context and details prior to that 
- logs shouldn't simply be dumped and pasted straight to GitHub.   Read and follow the 6 wiki steps the bug report template links to

**Comment by mhbates** [comment]
Same issue here. Log: https://gist.github.com/mhbates/c3e98091cf01040234a1b0f0be36b6a7

**Comment by bakerboy448** [comment]
- closing Op removed their bug report
- based on @mhbates's logs this is already fixed. https://github.com/Prowlarr/Prowlarr/commit/5a278f4e9d48869b8676fb0413751bc1b5a5d9cc
