### ISSUE TITLE
Login at Bittorrentfiles not working

### ISSUE THREAD

**Issue by imba3r** [Prowlarr/Prowlarr#1110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Login at Bittorrentfiles is no longer working because the change that fixed it was reverted.
The orginal issue is #666.

I opened another Pull Request that fixes the login (again): https://github.com/Prowlarr/Indexers/pull/249

### Expected Behavior

Login works and change gets not reverted again.

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: latest
```

### What branch are you running?

Master

### Trace Logs?

Nothing new..

[AB#3689](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3689)

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/851aedb41cea063a302551bf5868ec5e94118525
