### ISSUE TITLE
NZBIndex API

### ISSUE THREAD

**Issue by Y0ngg4n** [Prowlarr/Prowlarr#1111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

NZBIndex has a new API https://nzbindex.com/api/v3
Would be nice to integrate it into Prowlarr.

### Describe the solution you'd like

Add NZBIndex as Indexer

### Describe alternatives you've considered

Writing a API converter to Newznab

### Anything else?

No

[AB#3692](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3692)

**Comment by bakerboy448** [comment]
Indexer Requests belong on the requests site
https://requests.prowlarr.com/
