### ISSUE TITLE
YGGtorrent gives a "connection refused" error since a few days

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [Prowlarr/Prowlarr#1112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Prowlarr can't connect to yggtorrent, even witth flaresolverr. If deleted, can't add the indexer again. Ygg account is not banned. See trace logs for details.

### Expected Behavior

Prowlarr should be able to add yggtorrent without issues.

### Environment

```markdown
- OS: DietPi 8.8
- Prowlarr: 0.4.5.1955
- Docker Install: Yes (linuxserver)
- Using Reverse Proxy: Yes (Nginx)
- Browser: Firefox
```

### What branch are you running?

Nightly

### Trace Logs?

https://privatebin.fr/?18dbe5aa5b62fdcf#GfuQJVjiRKraChrjaXrNG1knaFFY1jS3Nxady8nCtiX1

[AB#3697](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3697)

**Comment by hgfi** [comment]
I'm getting the same error with a similar setup.

- OS: Debian 11
- Prowlarr: 0.4.5.1955
- Docker Install: Yes (linuxserver)
- Using Reverse Proxy: Yes (Nginx)
- Browser: Firefox

My account isn't banned, I can download torrents and add them to my seedbox manually.
I've tried reverting to older versions of prowlarr but I have the same issue. I think they've changed something on the website.

**Comment by florianess** [comment]
Same issue with my Raspberry PI. I tried on my windows desktop and it works!

**Comment by vavenCV** [comment]
I'm getting the same error with a similar setup.

    OS: Ubuntu 22.04.1 LTS
    Prowlarr: 0.4.5.1960
    Docker Install: No
    Using Reverse Proxy: No
    Browser: Firefox

**Comment by YDeltagon** [comment]
Same with Jackett

**Comment by SlimGary** [comment]
Same thing here:
OS: Ubuntu 22.04.1 LTS
Prowlarr: 0.4.4.1947
Docker Install: Yes
Using Reverse Proxy: No
Browser: Chrome

**Comment by bakerboy448** [comment]
Logs for posterity

```
2022-09-03 20:30:28.1|Trace|IndexerHttpClient|Req: [GET] https://www5.yggtorrent.fi/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date
2022-09-03 20:30:28.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-09-03 20:30:28.1|Warn|Cardigann|Unable to connect to indexer

[v0.4.5.1955] System.Net.Http.HttpRequestException: Connection refused (www5.yggtorrent.fi:443)
 ---> System.Net.Sockets.SocketException (111): Connection refused
 ```

Not a prowlarr nor jackett bug if the tracker is actively refusing connections

**Comment by YDeltagon** [comment]
Work today ;)

**Comment by Visual-Love** [comment]
> Work today ;)

Still broken for me, is there anything you did to fix it? What's your setup?

**Comment by florianess** [comment]
Work for me now after updating the docker image with the new release!

**Comment by SlimGary** [comment]
This fixed the issue for me:

https://github.com/Jackett/Jackett/issues/13541#issuecomment-1249924496

**Comment by bakerboy448** [comment]
So use cloudflare's DNS servers not your ISP's makes sense
