### ISSUE TITLE
JDownloader2 support

### ISSUE THREAD

**Issue by np000001** [Prowlarr/Prowlarr#1114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Manually using JDownloader2 next to Prowlarr.

### Describe the solution you'd like

Could Prowlarr add support for JDownloader2? It would bring support for a third technology, - next to usenet and torrent - HTTP (hosters).

JDownloader2 is a free, open-source download management tool with a huge community that makes downloading easy and fast.

Some of it's features are:

- Plugins for **3798 sites** available inside the app
- Platform independent / Runs on Java 1.5 or higher
- Download several files at once, with multiple connections
- Powerful OCR module
- Automatic extractor (including password list search)

Download link: https://jdownloader.org/JDownloader2

### Describe alternatives you've considered

Manually using JDownloader2 next to Prowlarr.

### Anything else?

None.

[AB#3706](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3706)

**Comment by bakerboy448** [comment]
Per https://github.com/Prowlarr/Prowlarr/issues/510#issuecomment-926228254
> No plans to have Prowlarr direct download anything.

_Originally posted by @bakerboy448 in https://github.com/Prowlarr/Prowlarr/issues/1050#issuecomment-1191627105_
