### ISSUE TITLE
Animebytes improvements due to api change

### ISSUE THREAD

**Issue by nonamethanks** [Prowlarr/Prowlarr#1115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Submitting this after a discord discussion with @DevYukine.

 Animebytes support has historically been a pain in the ass due to shortcomings of their api. They have recently (today) made a change to their API, so now a list of filenames is returned for every torrent. See for example https://animebytes.tv/scrape.php?type=anime&searchstr=darker+than+black&username=username&torrent_pass=torrent_pass:

These are the unchanged filenames from anime "scene" releases, so they're as close to release names as we'll ever get.

![image](https://user-images.githubusercontent.com/12946050/188635410-c9031c06-6d5b-45ad-a31c-a20d4983be01.png)

### Describe the solution you'd like

In theory this should make it possible to have a much more accurate support for anime releases.

There's still no overall release name, but maybe these can be treated as mixed season packs for the purpose of matching? I'm not familiar with the code much but I'm sure there's something that can be done with this. 

### Describe alternatives you've considered

-

### Anything else?

-

[AB#3707](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3707)

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/6f122fb2e4abc4b3a7f3c5f1edfa6d5909273c6d

**Comment by nonamethanks** [comment]
@bakerboy448 this is not fully implemented yet, it only works for single episodes.

**Comment by bakerboy448** [comment]
@DevYukine any plans or possibilities to get season pack support from these changes?

I didn't think there was and it doesn't appear feasible really anything would be very messy.

**Comment by DevYukine** [comment]
@bakerboy448 I'm not sure its a good idea to actually implement that

It would be super hacky and also would decrease Sonarr (with/by XEM) compatibility even more which already is kinda wanky with how it was working before

i'm also not even sure how i would properly implement that for season packs as numbering is different from release to release and without proper XEM support would break more than is broken right now, i personally do not think its a good idea to implement more than what i did with single episodes right now

**Comment by bakerboy448** [comment]
Tagging for future consideration.

But like Yukine said, there's really no non-problematic way to implement this now and actually improve the status quo.
