### ISSUE TITLE
SceneNZBs Custom Categories (German Usenet) Etc

### ISSUE THREAD

**Issue by Y0ngg4n** [Prowlarr/Prowlarr#1117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The Problem is, that i can´t use full sync with SceneNZBs because SceneNZBs uses custom Categories, but i can´t select them at the Prowlarr Sync View.
Prowlarr Categories:
![image](https://user-images.githubusercontent.com/30302975/188756218-112e8578-7bbf-46b8-8f5b-aec9f6cdfb04.png)
SceneNZBs Categories:
![image](https://user-images.githubusercontent.com/30302975/188756323-5e72340e-25e9-4d21-b333-cd408ebde23b.png)

### Describe the solution you'd like

It would be nice if Prowlarr could check if some of the Indexers with Movies for example have custom Categories and add them to the dropdown view. Currently i have to set the indexer for each instance by hand.

### Describe alternatives you've considered

Setting it everywhere by hand

### Anything else?

https://scenenzbs.com/

[AB#3711](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3711)

**Comment by bakerboy448** [comment]
Requires newznab to be YML based

https://github.com/Prowlarr/Prowlarr/pull/823

**Comment by thirionlogan** [comment]
I have the same problem, with [animetorrents](https://animetorrents.me/)

**Comment by bakerboy448** [comment]
again, it'll be done when #823  is finished and everything is YAML defs.
