### ISSUE TITLE
Global Custom Mappings 

### ISSUE THREAD

**Issue by sarakha63** [Prowlarr/Prowlarr#1124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Some indexers does provide some text replacements options such as replace multi with .......
replace SUBFRENCH with .....

this is great but some other indexers doesnt provide those kind of options. All nzb indexers doesnt

So i had an idea

### Describe the solution you'd like

The idea would be to have a custom mapping options at prowlarr level 

the user if he wants could add custom mappings and those will be used by prowlarr on a global level

Those mappings could be text replacements / regexp replacements

Prowlarr will then look if the result is in a custom mapping and will do the replacement before transmitting the result to sonarr radarr and so on

The config pasge should have a button to add a mapping

and the mapping will have an input /  an output / and a indexer multiselect to select on what indexers this should apply

We could even imagine to have a selector to tell if the mapping should occur on the result, or why not on the query

But the most usefull case would be on result, this will help radarr and sonarr consider 

multi release as multi with french or whatever the user would like as replacements

### Describe alternatives you've considered

The only alternative would be to allow this kind of replacement on NZB items for example or all indexers

As you can see somm indexers have this kind of options
![image](https://user-images.githubusercontent.com/2008029/190173566-5dbcd448-a4e9-49b4-92ec-fdd240177703.png)

But my proposal seems better as it could be used for any kind of mappings

### Anything else?

![image](https://user-images.githubusercontent.com/2008029/190172766-ab0cf17e-e1d8-440c-a61b-1373d27b5b27.png)
![image](https://user-images.githubusercontent.com/2008029/190173266-17715843-4745-42a8-b89b-2fa2b21f2c63.png)

[AB#3734](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3734)

**Comment by bakerboy448** [comment]
- This is something that should be done at the indexer specific level not a global level.
- Radarr has specific settings to specify what languages Multi means on a specific tracker
- Usenet can't have any replacements done until the switch to YML definitions
- only a small handful of indexers need their release titles modified with settings like this. It doesn't make sense to apply that to all 500+ indexers and give users an easy foot gun to cause issues with releases
- Proper sites should be enforcing the universally agreed upon naming standards.  And groups should be following them.

**Comment by sarakha63** [comment]
Hello @bakerboy448  you are right,

When usenet will get to yml definitions such options can be added at the indexer level (making a custom one if needed). And this will solve most of issues i have (which are usenet related)

Thanks
