### ISSUE TITLE
AvistaZ network [AvistaZ/PrivateHD etc] API overload/disabled 

### ISSUE THREAD

**Issue by karserasl** [Prowlarr/Prowlarr#1130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AvistaZ network disabled their API..

There is a banner in both Avistaz and PrivateHD:
![image](https://user-images.githubusercontent.com/14327196/192153882-647dd9a6-d114-4dfb-8a73-ea1b08053a10.png)

### Expected Behavior

No thing to be done.. API is down.

### Environment

```markdown
- OS: docker
- Prowlarr: develop
- Docker Install:
- Using Reverse Proxy: traefik
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

-

[AB#3825](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3825)

**Comment by bakerboy448** [comment]
Labeled as external for tracking

needless to say, you'll be experiencing errors in prowlarr accordingly and be told that cloudflare was detected / Flaresolverr is required.   Don't configure that per the sites' banner.

**Comment by karserasl** [comment]
True i have flaresolverr. Still, you cannot access their API endpoint atall.
