### ISSUE TITLE
Allow disabling apps

### ISSUE THREAD

**Issue by Visne** [Prowlarr/Prowlarr#1133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently it is not possible to disable an app, while it is possible to disable for example a download client.

### Describe the solution you'd like

Add an "Enabled" checkbox to apps similar to the one for download clients.

### Describe alternatives you've considered

Of course you can delete the app, but this is annoying when you want to enable it again.

### Anything else?

I'm not 100% sure if there is any harm in having an app that is not running enabled, but I imagine that it takes longer to sync while Prowlarr is waiting for a timeout for the app that is not running.

[AB#3837](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3837)

**Comment by bakerboy448** [comment]
Sync Level => Disabled, no?

**Comment by Visne** [comment]
Hmm, I currently don't have a Disabled sync level, I might have deleted it. If it is there by default, then I suppose this can be closed. Still, if there is ever some other feature added to apps, where just changing the sync level would not disable it, then it makes sense to add an Enabled button in my opinion.

**Comment by bakerboy448** [comment]
That's not possible. There's no profile.

Sync Level is within each app config and controls how prowlarr syncs to the app. 

What benefit does moving a drop-down entry to a checkbox provide?

**Comment by Visne** [comment]
> What other features? No plans for prowlarr to do anything besides sync indexers.

Sure, that makes sense.

> What benefit does moving a drop-down entry to a checkbox provide?

I think you are misunderstanding what I mean, but regarding the first point it is irrelevant anyways.

Thanks for your help, using the Disabled sync level makes sense.
