### ISSUE TITLE
Health check for apps

### ISSUE THREAD

**Issue by Visne** [Prowlarr/Prowlarr#1134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently there is no health check for apps. This means that it is not clear that Prowlarr can't connect to your app because of for example a configuration issue.

### Describe the solution you'd like

Ensure that an app that fails when you press "Test" in the Apps page, also generates a health warning.

### Describe alternatives you've considered

-

### Anything else?

-

[AB#3838](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3838)

**Comment by bakerboy448** [comment]
Already exists
https://github.com/Prowlarr/Prowlarr/blob/develop/src/NzbDrone.Core/HealthCheck/Checks/ApplicationStatusCheck.cs

**Comment by Visne** [comment]
This is a service that is currently not running, note how the test failed:

![image](https://user-images.githubusercontent.com/39844191/192416764-6cb946a7-fecb-4ae2-bd58-d36f73a3ff7e.png)

After running the Check Health task however there is no warning:

![image](https://user-images.githubusercontent.com/39844191/192416956-ffd673f1-b042-45c6-a3e1-378484527632.png)
![image](https://user-images.githubusercontent.com/39844191/192416967-ee8c71c6-0471-41cf-a7e2-10f4cdb5133f.png)

So then this must either be a bug or I am misunderstanding what is supposed to happen.

**Comment by bakerboy448** [comment]
You're editing an app. That does not throw any event nor should it. Otherwise everytime anyone tests the app when editing it the healthcheck would be running...that seems both annoying and unnecessary.

**Comment by Visne** [comment]
> Testing all apps from the settings page Would trigger it.

Well, it doesn't. And as I stated, running the Check Health app also doesn't trigger it.

**Comment by bakerboy448** [comment]
Known bug for test all

https://github.com/Prowlarr/Prowlarr/issues/507

**Comment by Qstick** [comment]
There was a bug where apps down longer than 6 hours don't throw a healthcheck. I've fixed that here e78b8d534652dc9dfdf6b0a9dfec59d0c74de648

Hopefully that is what you were seeing
