### ISSUE TITLE
Can't select Base URL - Fantastic Heaven

### ISSUE THREAD

**Issue by Orishas** [Prowlarr/Prowlarr#1138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding Indexer fantasticheaven Base URL dropdown doesn't work and is emtpy.
Can't save without it.

### Expected Behavior

Base URL is prefilled or selectable in dropdown

### Steps To Reproduce

Add Indexer
Search fantastic heaven and add it
Select Base Url

### Environment

```markdown
- OS: alpine linux
- Prowlarr: nightly-a7cb77c
- Docker Install: yes
- Using Reverse Proxy: No
- Browser: Chrome 105.0.5195.127
```

### What branch are you running?

Nightly

### Trace Logs?

[logs.txt](https://github.com/Prowlarr/Prowlarr/files/9672965/logs.txt)

[AB#3843](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3843)
[trace.txt](https://github.com/Prowlarr/Prowlarr/files/9673064/trace.txt)

**Comment by bakerboy448** [comment]
Info logs of just the error spew with no context are not valid for bug reports

please provide the required trace logs the bug report asks for

**Comment by Orishas** [comment]
I added the trace log, thanks for the advice.
Error is the same on the develop branch.
But maybe it is not a prowlarr bug, just an indexer config error

**Comment by Qstick** [comment]
This should be solved with the new indexer updating in dev
