### ISSUE TITLE
Unable to connect to QBittorrent

### ISSUE THREAD

**Issue by oliroe** [Prowlarr/Prowlarr#114]
Attempting to connect with QBittorrent but the test fails. The same details work using Lidarr/Sonarr/Radarr

Add details of QBittorrent and test connection
![image](https://user-images.githubusercontent.com/4500141/120936113-13bbce00-c6fe-11eb-9466-0b8e1d43620e.png)

**Expected behavior**
Successful connection
**Screenshots**

**Platform Information (please complete the following information):**
 - Synology NAS
 - Docker: 
 - Version 0.1.0.361 - Prowlarr Branch: <
 - nightly

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
https://pastebin.com/GTViFLN5

**Comment by Qstick** [comment]
The appears to be a setup issue. We've got quite a few people in testing connected to qBit without issues.

**Comment by oliroe** [comment]
Not sure whether the issue was specific to me but the solution was to uncheck the following 3 options in the Web UI tab of QBittorrent settings 
![image](https://user-images.githubusercontent.com/4500141/121005228-82913980-c787-11eb-911b-9a66f91219cb.png)
After the successful to connection I checked them again and now it connects without a problem
