### ISSUE TITLE
Pass proxy (HTTP or Socks) to Flaresolverr

### ISSUE THREAD

**Issue by almico** [Prowlarr/Prowlarr#1142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I added Flaresolverr and SOCKS5 proxies to Prowlarr configuration.
Then, for some indexers, I needed both of them applied at the same time (Flaresolverr + SOCKS5), so, I set up tags accordingly, expecting Prowlarr to include SOCKS5 parameters into the request passed onto Flaresolverr, but I read Prowlarr doesn't support this scenario.
Starting from version 2.0.0, Flaresolverr supports passing a proxy (without credentials), and, as far as I could read, Jackett is already supporting passing proxy info to Flaresolverr.

### Describe the solution you'd like

I would like Prowlarr to include SOCKS5 data into the request sent to Flaresolverr, if both Flaresolverr and SOCKS5 are tagged to be used with an indexer.

### Describe alternatives you've considered

- Add VPN at the router level, with custom routing
- Use Jackett instead of Prowlarr

### Anything else?

[This](https://github.com/FlareSolverr/FlareSolverr/issues/26) is the original issue at Flaresolverr that led to adding support for proxy (without authentication).

[AB#3847](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3847)

**Comment by Qstick** [comment]
This is a tad bit trick with per indexer proxies, but fairly doable with the global proxy. Let me put a bit of thought into this.
