### ISSUE TITLE
Issues with AlphaRatio & GreatPosterWall

### ISSUE THREAD

**Issue by tronyx** [Prowlarr/Prowlarr#1144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Prowlarr is unable to login to AlphaRatio: Unable to connect to indexer. Unexpected response header text/html from API request, expected application/json

### Expected Behavior

Prowlarr is able to login to AlphaRatio.

### Steps To Reproduce

Setup AlphaRatio as an Indexer and test it.

### Environment

```markdown
- OS: Docker
- Prowlarr: 0.4.7.1999
- Docker Install: 20.10.17, build 100c701
- Using Reverse Proxy: No
- Browser: Firefox 105.0.1, Chrome 106.0.5249.91
```

### What branch are you running?

Nightly

### Trace Logs?

https://0bin.net/paste/VUvfZTpe#gRvFCFZ9Z+nFMnGDqU4a3pBnydyxzoHFa0ZXSW1wGfK

[AB#3868](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3868)

**Comment by bakerboy448** [comment]
reported as working in v0.4.6.1969

**Comment by jpalenz77** [comment]
I still get the same error on 0.4.7.2000

**Comment by quorn23** [comment]
Seeing the same error as of 0.4.7.2000 with GreatPosterWall as well.

**Comment by Qstick** [comment]
Logs expired

**Comment by tronyx** [comment]
> Logs expired

Sorry about that. Fresh logs here: https://0bin.net/paste/1WbpGHnv#fKUIGt6XpGZVKvcj0pNkrgKI66bG+ndVIYPE5fd3pZe

**Comment by Qstick** [comment]
Which nightly build did this start on?

**Comment by tronyx** [comment]
> 

I noticed it on 0.4.7.1999, but I typically only update my containers once a week so I'm not sure if it started on an earlier version or not.
