### ISSUE TITLE
FileList trackers freeleech only toggle

### ISSUE THREAD

**Issue by PrivatePasta** [Prowlarr/Prowlarr#1147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

 I would love for Prowlarr to support freeleech with the FileList. I'm not sure if this is possible with their API (I couldn't find docs for it anywhere), so I understand if this is not possible until they do something on their end.

### Describe the solution you'd like

A simple "Search freeleech only" toggle like is common on other indexers.

### Describe alternatives you've considered

...

### Anything else?

...

[AB#3880](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3880)

**Comment by bakerboy448** [comment]
API docs are required or information as to what needs to be the query to return freeleech only

**Comment by Pircuremix** [comment]
This would be an awesome addition if possible!
