### ISSUE TITLE
DonTorrent and MejorTorrent

### ISSUE THREAD

**Issue by Urkov** [Prowlarr/Prowlarr#1151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

There is only one spanish public tracker for movies and tv shows, and it is not the best one (EliteTorrent).

### Describe the solution you'd like

I use Jackett with DonTorrent and MejorTorrent and I think they are the best ones, it will be great to add it to prowlarr.

### Describe alternatives you've considered

I do not know better public tracker for spaniards

### Anything else?

No

[AB#3890](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3890)

**Comment by bakerboy448** [comment]
Indexer Requests do not belong on GitHub.

**Comment by Urkov** [comment]
Sorry I thought it was a good place I will search the right place, maybe via web?
