### ISSUE TITLE
"Limit reached" error counts as connection failure; prevents adding indexer.

### ISSUE THREAD

**Issue by Extremity** [Prowlarr/Prowlarr#1152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding an indexer, if you've already reached your query limit for that day you are unable to add it. Testing fails, and as it tests when submitting you're stuck. It seems like instead of a blanket failure based on response type it may be worth specifically looking for failures that indicate you have connected and are just temporarily limited, whether that's simply a conditional looking for the text "request limit reached" or whatever else.

I actually waited a bit until a query fell off, and was able to successfully test. Unfortunately, I had forgotten that a test counts as a query and was right back in the same boat again. So, yeah. I apologize if this has been reported, I searched and found nothing.

### Expected Behavior

I would expect to be able to add an indexer I have a valid account/key for even if my queries are at their limit for the day.

### Steps To Reproduce

1. Max out your queries on an indexer. NZBFinder is an easy one, as it's open to everyone and a free account has a 25 query limit.
2. Attempt to add the indexer.
3. Watch on in horror as you cannot perform #2, yet are on #3, and have thus destroyed the space-time continuum.

### Environment

```markdown
- OS: Windows 10
- Prowlarr: 0.4.6.1969
- Docker Install: No
- Using Reverse Proxy: Yes/nginx
- Browser: Chrome 106.0.5249.103 (Not UI related)
```

### What branch are you running?

Develop

### Trace Logs?

I know logs are generally required for bug reports but this is so simple that I cannot imagine them being necessary. Here is a screenshot of it happening. 

![aKaugSdts9](https://user-images.githubusercontent.com/546451/195034836-5a1ee76d-1a71-4ab2-ae01-136e95ea7c7e.png)

[AB#3895](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3895)

**Comment by bakerboy448** [comment]
Should be able to force save by save twice

**Comment by Extremity** [comment]
You're right - I actually just found the "How can I add an indexer that is down or not functional?" area of WikiArr and came here to close this out. Sorry for this, I suppose I assumed that if you guys were aware of it it wouldn't be happening, I didn't consider that there was a way to bypass it (which is very nice to have, thank you) or that it would be referenced in the documentation.

This and (still) trying to figure out how to get custom indexer categories to populate the built-in search have been my only issues so far; for something in development that has so many variables and potential points of failure, I'd say this is one hell of a job for a relatively early work in progress. Thank you for the quick response, sorry for the waste of time. Keep up the good work!
