### ISSUE TITLE
Finelite indexer title missing

### ISSUE THREAD

**Issue by lepis0** [Prowlarr/Prowlarr#1153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Indexer Finelite doesn't have titles in releases.

### Expected Behavior

I think something is changed in tracker side because finelite.org worked before.

### Steps To Reproduce

Try search something from that indexer and there is no titles in releases

### Environment

```markdown
- OS: unraid
- Prowlarr: 0.4.7.2000
- Docker Install: yes (nightly-423e27a by hotio)
- Using Reverse Proxy: no
- Browser: chrome
```

### What branch are you running?

Nightly

### Trace Logs?

![image](https://user-images.githubusercontent.com/15526120/195091407-63a8f57b-ed51-4125-9226-6d12d9d1aeff.png)
Here is screenshot of search "aku ankka". Indexer finvip shows titles but finelite doesn't.

[AB#3896](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3896)

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13642 tracks changes to the indexer required after the site upgraded their browser engine. The Prowler team will import and amend as required for their app soon.
