### ISSUE TITLE
bj-share indexer: Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.

### ISSUE THREAD

**Issue by jaum20** [Prowlarr/Prowlarr#1155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Grabbing is working, but manual search is not working anymore. I have tryed to change the indexer category settings (movies 2000 and Filmes 100001) but neither is working. When I perform a manual search, the list of avaibable sources do not shows any sources from the index in question, but I can confirm that there are souces by doeing a search in the indexer website.

Testing the indexer in the Prowlarr interface does not give any errors. In Radarr, testing the indexer shows an error message: `Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.`

### Expected Behavior

Manual search should shows results from the indexer bj-share

### Steps To Reproduce

1. In Radarr, go to Settings > Indexers
2. Choose BJ-Share (Prowlarr) and click test
3. get error message "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings."

or

1. Go to a movie entry in Radarr
2. Click manual search
3. Get a health issue: Health Check Failure: Indexers are unavailable due to failures: BJ-Share

### Environment

```markdown
- OS: 20.04.5 LTS (Focal Fossa) arm7
- Prowlarr:0.4.6.1969
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Brave
```

### What branch are you running?

Master

### Trace Logs?

2022-10-13 13:58:45.1|Debug|IndexerFactory|Temporarily ignoring indexer Bj-Share till 10/13/2022 2:03:30 PM due to recent failures.
2022-10-13 13:58:45.1|Debug|ReleaseSearchService|All provided categories are unsupported by selected indexers: 2000, 100001

[AB#3899](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3899)

**Comment by bakerboy448** [comment]
- there is no master version of Prowlarr
- Info logs are not the required trace logs

> 2022-10-13 13:58:45.1|Debug|IndexerFactory|Temporarily ignoring indexer Bj-Share till 10/13/2022 2:03:30 PM due to recent failures.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

No results are expected for any searches if the indexer is disabled due to errors.

**Comment by bakerboy448** [comment]
- https://github.com/Jackett/Jackett/issues/13564 Had to add the User Agent to the request,  but that was for a different error  so we should probably do that, but not likely the cause.
- moving GHI the Indexer Repo


You'll need to contact the site and asked what and why they changed so that a perfectly valid search string is responded by them with a redirect

```
2022-10-13 18:41:24.7|Warn|Cardigann|https://bj-share.info/torrents.php?filter_cat[1]=1&searchstr=tt10954984&freetorrent=

[v0.4.6.1969] NzbDrone.Core.Indexers.Exceptions.IndexerException: Unexpected response status Redirect code from API request
   at NzbDrone.Core.Indexers.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannParser.cs:line 51
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 314
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 175
RequestUri: https://bj-share.info/torrents.php?filter_cat[1]=1&searchstr=tt10954984&freetorrent=;StatusCode: Redirect;ContentType: text/html; charset=utf-8
```
