### ISSUE TITLE
AvistaZ freeleech only toggle bug, waiting for new release with the fix

### ISSUE THREAD

**Issue by mynameisbogdan** [Prowlarr/Prowlarr#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current `Freeleech Only` setting for avistaz isn't available as a checkbox.

### Expected Behavior

The current `Freeleech Only` setting for avistaz to be available as a checkbox.

It was already been fixed [here](https://github.com/Prowlarr/Prowlarr/commit/4137193a606d212efe09c269e7d56f97af1aae0b).

When should be expected to land in a new release?

### Environment

```markdown
- OS: Unraid
- Prowlarr: 0.4.6.1969
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

-

[AB#3903](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3903)

**Comment by bakerboy448** [comment]
There is never an ETA on new releases.

GitHub is not for queries

**Comment by mynameisbogdan** [comment]
It was a nice way to remind tagging a new release, because currently there is a UI bug for 3 weeks.

My bad, `develop`. :)

And it's indeed a bug according to [you](https://github.com/Prowlarr/Prowlarr/issues/1108#issuecomment-1253367106).
