### ISSUE TITLE
SpeedApp indexer returns unrelevant results for the query.

### ISSUE THREAD

**Issue by batuhankrmn** [Prowlarr/Prowlarr#1163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

SpeedApp returns unrelevant results for the query. For instance, query: "the avengers 2012" 
results: 
"Captain.America.The.Winter.Soldier.2014.720p.BluRay.x264-xHD" 
"LEGO.MARVELs.Avengers-RELOADED"

### Expected Behavior

It should return only relevant results for the query like Jackett do. 
![image](https://user-images.githubusercontent.com/57859656/196870170-bd29c464-61cc-4501-b4fc-4bbf108b4356.png)

### Environment

```markdown
- OS: Windows 11 Pro
- Prowlarr: 0.4.7.2016
- Docker Install: na
- Using Reverse Proxy: na
- Browser: Chrome Version 106.0.5249.119
```

### What branch are you running?

Master

### Trace Logs?

50 results but only 5 of them are relevant for the query.

![image](https://user-images.githubusercontent.com/57859656/196870527-5971b5c3-461e-40e6-9767-0ddcd821476f.png)
![image](https://user-images.githubusercontent.com/57859656/196870931-1561408d-a800-4ca1-affe-be3a965cbde1.png)

[AB#3947](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3947)

**Comment by bakerboy448** [comment]
Jackett does additional filtering that prowlarr does not.

radarr would be doing an imdbid search more likely than not (unless tmdb did not have the imdbid for the movie) as Well. You can change the search type with the blue icon.

https://github.com/Prowlarr/Prowlarr/blob/e9e4248af49e21dd63046d050197c90fae99ad05/src/NzbDrone.Core/Indexers/Definitions/SpeedApp.cs#L38

**Comment by batuhankrmn** [comment]
Thanks @bakerboy448 but I don't use Radarr/Sonarr. I just use Prowlarr for manuel search (webUI) as Jackett replace. So Is there any workaround to eliminate these unrelevant results on webUI for SpeedApp? (I don't know If this is valid for any other trackers but seems like Jackett handles filtering in a different way.)

**Comment by bakerboy448** [comment]
You may not use them, but you can search better than just a text query search.

> So Is there any workaround to eliminate these unrelevant results on webUI for SpeedApp?

accordingly to the tracker those results match your search terms. If you believe that is wrong take it up with them.  We pass back what the tracker returns.
