### ISSUE TITLE
Manual search returns no results from RARBG.

### ISSUE THREAD

**Issue by batuhankrmn** [Prowlarr/Prowlarr#1164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When search made, there is no result from RARBG indexer even there is matching torrent in RARBG tracker.

![image](https://user-images.githubusercontent.com/57859656/196918975-d0130c40-f02a-49af-bc9e-313f69f2ddf8.png)

### Expected Behavior

Matching results should be returned when search made for RARBG indexer.
Results from RARBG:
![image](https://user-images.githubusercontent.com/57859656/196918859-c9e6826e-e571-45ba-985a-df7c51e3e6aa.png)

### Steps To Reproduce

1- Login Prowlarr webUI
2- Go to Search
3- Select RARBG indexer 
4- Query for "the last stand 2006"
5- Observe the results
6- Go to RARBG site itself and do same query on it.
7- Observe the results.

### Environment

```markdown
- OS: Windows 11 Pro
- Prowlarr: Version 0.4.7.2016
- Docker Install: NA
- Using Reverse Proxy: NA
- Browser: Chrome Version 106.0.5249.119 (Official Build) (64-bit)
```

### What branch are you running?

Develop

### Trace Logs?

[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/9828644/prowlarr.debug.txt)

[AB#3948](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3948)

**Comment by bakerboy448** [comment]
- not a bug
- `2022-10-20 12:58:32.1|Debug|Rarbg|Rarbg rate limit hit, retying request`
- Rarbg rate limits and thus no results are returned. Query them less and try again later
- debug != trace
