### ISSUE TITLE
TorrentAPI (Rarbg) new limits/changes

### ISSUE THREAD

**Issue by rarbg** [Prowlarr/Prowlarr#1169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

--

### Describe the solution you'd like

No clue who's responsible for Prowlarr right now but @bakerboy448 said to open an issue so here is it

To fix Prowlarr potential issues please implement the following in your torrentapi code :

1. Increase the sleep between requests x2
2. if the API returns 429 retry in 2 minutes , 429 returns a custom json with rate_limit 1 - ignore it
3. if the API returns 520 retry in 3 minutes
4. if the API returns 200 with a json that contains rate_limit 1 retry in 5 minutes

That will cover all cases. 

### Describe alternatives you've considered

--

### Anything else?

--

[AB#3969](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3969)

**Comment by Qstick** [comment]
Feel free to DM me on discord if you'd like to have a more in depth discussion on this. We can certainly change some things but it would be good to better understand things on your side.

**Comment by rarbg** [comment]
Please also change your app_id to rralworP to distinguish updated and non updated versions

**Comment by bakerboy448** [comment]
for posterity - context

> when rated limited cloudflare will return http code 429 with a json encoded string that includes rate limit 1
> when rated limited web returns http code 444 to cloudflare which returns 520 on cloudflare , there is no way to send 429 to cloudflare without it breaking the request properly and retrying it
> when rated limited code returns http code 200 with rate_limit 1
> 
> rate_limit : 1 is generally returned when you've exceeded the rate limit or when one of the many servers behind cloudflare is being overloaded - because cloudflare doesn't evenly redistribute requests equally its there so clients via api can see that they are rate limited , retry in lets say 5 seconds and they can get their request fullfilled on another backend ( cloudflare doesn't do stickiness ) in x time

https://github.com/Jackett/Jackett/issues/13663#issuecomment-1288190301

**Comment by Qstick** [comment]
> Please also change your app_id to rralworP to distinguish updated and non updated versions

Why ban the old app_id, there was rate limiting in them as well. Prowlarr is not the problem, 90% of any volume coming from Prowlarr is just proxied from another app (Sonarr, Radarr, Lidarr, Readarr, etc. ). If you guys want to come up with a reasonable way to reduce volume, the apps, which are the source of the requests, are the way to do it. Again I invite you to come have an actual conversation about this, the amount of handling and hack fixes we have in place now to support this is getting comical.

**Comment by ilike2burnthing** [comment]
I don't think it's being banned, just make monitoring easier. Jackett did the same 4 months ago per request - https://github.com/Jackett/Jackett/commit/e42c1499793627e5c0457842e78255885f01b24f

**Comment by Qstick** [comment]
All old versions with app_id Prowlarr are being reported as no longer working. Sounds kinda ban-ny to me.

I've been able to reproduce that `Prowlarr` doesn't work but even `prowlarr` does

**Comment by bakerboy448** [comment]
Confirmed `Prowlarr` is always 520'd by CF

```
2023-02-23 12:34:56.5|Trace|IndexerHttpClient|Res: [GET] https://torrentapi.org/pubapi_v2.php?mode=search&ranked=0&limit=100&token=(removed)&format=json_extended&app_id=Prowlarr_10.0.0.22465: 520.520 (7252 bytes)
```
vs.
```
2023-02-23 12:31:34.4|Trace|IndexerHttpClient|Res: [GET] https://torrentapi.org/pubapi_v2.php?mode=search&ranked=0&limit=100&token=(removed)&format=json_extended&app_id=rralworP_10.0.0.22465: 200.OK (77716 bytes) (1969 ms)
```

only diff was Prowlarr vs rralworP

**Comment by rarbg** [comment]
We are not doing this.

curl "https://torrentapi.org/pubapi_v2.php?mode=search&ranked=0&limit=100&token=(removed)&format=json_extended&app_id=Prowlarr" -vvv 2>&1|grep 520
< HTTP/2 520


curl "https://torrentapi.org/pubapi_v2.php?mode=search&ranked=0&limit=100&token=(removed)&format=json_extended&app_id=Prowlarr_version" -vvv 2>&1|grep 520
< HTTP/2 520

curl "https://torrentapi.org/pubapi_v2.php?mode=search&ranked=0&limit=100&token=(removed)&format=json_extended&app_id=rralworP_version" -vvv 2>&1|grep 520
< HTTP/2 520

**Comment by bakerboy448** [comment]
curl I found always returned a 520 error no matter the `app_id` FWIW

testing with the dev build indicates the case appears to be otherwise as per the logs i shared

**Comment by rarbg** [comment]
@bakerboy448 

curl "https://torrentapi.org/pubapi_v2.php?mode=search&ranked=0&limit=100&token=(removed)&format=json_extended&app_id=Prowlarr" -A notcrl -vvv 2>&1|grep 520
< HTTP/2 520

curl "https://torrentapi.org/pubapi_v2.php?mode=search&ranked=0&limit=100&token=(removed)&format=json_extended&app_id=Prowlarr_version" -A notcrl -vvv 2>&1|grep 520
< HTTP/2 520

curl "https://torrentapi.org/pubapi_v2.php?mode=search&ranked=0&limit=100&token=(removed)&format=json_extended&app_id=rralworP_version" -A notcrl -vvv 2>&1|grep 520
< HTTP/2 520

**Comment by rarbg** [comment]
Looks like its some weird CF caching bug
I flushed the cache completely
I don't see Prowlarr actually implementing any of the required timeouts from 3 months ago - WTF. Its literally shit ton of non compliant requests
Anyways i did some test after flushing and waiting for load to drop
30 second requests with app_id Prowlarr_123 , Prowlarr and rralworP_123 - 


`Thu Feb 23 19:53:44 CET 2023
< HTTP/2 200
Thu Feb 23 19:54:15 CET 2023
< HTTP/2 200
Thu Feb 23 19:54:45 CET 2023
< HTTP/2 200
Thu Feb 23 19:55:16 CET 2023
< HTTP/2 200
Thu Feb 23 19:55:47 CET 2023
< HTTP/2 200
Thu Feb 23 19:56:17 CET 2023
< HTTP/2 200
Thu Feb 23 19:56:48 CET 2023
< HTTP/2 200
Thu Feb 23 19:57:19 CET 2023
< HTTP/2 200
Thu Feb 23 19:57:49 CET 2023
< HTTP/2 200
Thu Feb 23 19:58:20 CET 2023
< HTTP/2 200
`

**Comment by bakerboy448** [comment]
yup cloudflare cache seems like it was the likely issue then

`app_id Prowlarr_123 , Prowlarr and rralworP_123` is not a valid Prowlarr ID nor one that would be sent....unless `123` is a generic placeholder?

Prowlarr respect's the responses; will edit momentarily with the code refs

**Comment by bakerboy448** [comment]
# initial call

https://github.com/Prowlarr/Prowlarr/blob/caab337379bac985cc8afc5e09ff79f14cff7622/src/NzbDrone.Core/Indexers/Definitions/Rarbg/Rarbg.cs#L115-L143

# http response check/logic

https://github.com/Prowlarr/Prowlarr/blob/develop/src/NzbDrone.Core/Indexers/Definitions/Rarbg/Rarbg.cs#L48-L63

# Response checking / error handling

https://github.com/Prowlarr/Prowlarr/blob/caab337379bac985cc8afc5e09ff79f14cff7622/src/NzbDrone.Core/Indexers/Definitions/Rarbg/RarbgParser.cs#L27-L63

**Comment by rarbg** [comment]
https://www.reddit.com/r/prowlarr/comments/11b7qa2/unable_to_connect_to_indexer_rarbg/j9wex6m/

Can you tell your mod to stop lying ?

**Comment by ilike2burnthing** [comment]
@PearsonFlyer update your comment, see above - https://github.com/Prowlarr/Prowlarr/issues/1169#issuecomment-1442258985.

**Comment by rarbg** [comment]
@PearsonFlyer 's edit

> EDIT: I've been asked to "stop lying" by the rarbg team. Rarbg is currently up and working with Prowlarr, at this moment.

**Comment by ftc2** [comment]
dear @rarbg,

thank you for your indexer!

however, in practice, it seems like i can only do about one request per minute now.

for the love of god, can you please, please have mercy on us and give us poor users a bit more to work with here? <3
