### ISSUE TITLE
Tipo: Torrents Rastreador: BJ-Share URL: https://bj-share.info/login.php Em Jackett ?: Sim

### ISSUE THREAD

**Issue by talesam** [Prowlarr/Prowlarr#1180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Unable to connect to indexer. We are being redirected to the login page. Most likely your session expired or was killed. Try testing the indexer in the settings."

### Expected Behavior

connect to bjshare, but it doesn't have a field for API and it doesn't have a field for username and password.

### Steps To Reproduce

1) Add new indexer
2) I choose BJ-Share
3) Choose the URL
4) Add cookie
5) I click on test and it gives an error, as there is no option to put my username and password.

### Environment

```markdown
- OS: Ubuntu ARM64
- Prowlarr: 0.4.7.2058
- Docker Install: Docker version 20.10.21
- Using Reverse Proxy: NPM
- Browser: Brave and Chrome
```

### What branch are you running?

Nightly

### Trace Logs?

https://pastebin.com/AukWLKRh

[AB#3998](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3998)

**Comment by bakerboy448** [comment]
- provided logs are not trace logs nor any prowlarr logs. They appear to be the journal which is not cleansed
- based on the error your cookie is not valid

**Comment by talesam** [comment]
LOG: https://pastebin.com/UZqAfm08

**Comment by bakerboy448** [comment]
Again, info logs are invalid for bug reports.
The bug report template links to the wiki for how to get and provide trace logs.

Again, Based on the error it seems likely the cookie you copied is either expired or incompletely copied.

Hash it out in support and discord

**Comment by talesam** [comment]
> Novamente, os logs de informações são inválidos para relatórios de erros - são necessários rastreios. O modelo de relatório de erros é vinculado ao wiki para obter e fornecer registros de rastreamento.
> 
> Novamente, com base no erro, parece provável que o cookie que você copiou tenha expirado ou tenha sido copiado de forma incompleta.
> 
> Esconda-o em suporte à discórdia

I got the log on the Prowler system. Cookies were not copied wrongly. I made a video showing. be yourself.

https://cloud.talesam.org/s/27enJzeexR6mJ9E
