### ISSUE TITLE
Synology Download Station search integration.

### ISSUE THREAD

**Issue by martijnw1986** [Prowlarr/Prowlarr#1182]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It is NOT related to a problem.

### Describe the solution you'd like

Synology Download Station has the ability to import .DLM files to add BT search engines. There are a few search engines available on GitHub that search a single torrent provider. However, I would love to be able to search my Prowlarr instance from within the Download Station GUI.

### Describe alternatives you've considered

I have searched Prowlarr manually from within the Web UI.

### Anything else?

https://www.synoboost.com/ holds a few DLM files for example.

[AB#4015](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4015)

**Comment by Qstick** [comment]
No plans for this, but would support anyone that wants to try this third party. Just hop on discord in our #integrations channel
