### ISSUE TITLE
Add options for title synonyms to AnimeBytes 

### ISSUE THREAD

**Issue by Kyle-B** [Prowlarr/Prowlarr#1191]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently [synonyms of AB results are added unconditionally ](https://github.com/Prowlarr/Prowlarr/blob/develop/src/NzbDrone.Core/Indexers/Definitions/AnimeBytes.cs#L231-L244). This leads to many duplicate entries in the results, often with no real benefit. In the [equivalent Jackett code](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/AnimeBytes.cs#L215-L220), these are filtered down with options for the Japanese/Romaji synonyms (not very useful), and Alternative Titles (generally helpful for matching).

### Describe the solution you'd like

Ideally extra options could be added for these three synonym categories, similar to how it works in Jackett.

### Describe alternatives you've considered

It may be worth unconditionally leaving the Alternative Titles in, since they can improve matching and I'd expect most users would want to have this option enabled.

### Anything else?

N/A

[AB#4051](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4051)

**Comment by DevYukine** [comment]
This is a fair suggestion, that said i would by default keep both for backward compatibility and just allow people to disable them if they want like you suggested, will see if i can implement this in the next few days, should be a quick change (if someone else is faster than me, i will review 👍)

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/b371f2d9136470db9a44be033567c9947645cac0
