### ISSUE TITLE
Prowlarr appears to be sending analytics even after opting out

### ISSUE THREAD

**Issue by zx8** [Prowlarr/Prowlarr#1193]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

My firewall sees traffic going out to `releases.server.com` every 15 minutes, even though I have opted out of analytics:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/8544900/201227764-15693640-67aa-45a7-8dbe-c40c7b24b50b.png">

This seems to trace back to https://github.com/Prowlarr/Prowlarr/blob/d5088cf4728e451ea628ec0fc7b7603bef5753c0/src/NzbDrone.Core/IndexerSearch/ReleaseAnalyticsService.cs

### Expected Behavior

No analytics should be sent when opted out.

### Steps To Reproduce

N/A

### Environment

```markdown
- OS: Synology
- Prowlarr: 0.4.8.2072
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Master

### Trace Logs?

If you need trace logs to debug this, let me know & I can obtain them, but I don't think they should be necessary.

[AB#4052](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4052)

**Comment by Qstick** [comment]
Thanks for reporting, looks to be a regression after debounce was added. Should be fixed in next release.
