### ISSUE TITLE
Nebulance API

### ISSUE THREAD

**Issue by ahopelesshadow** [Prowlarr/Prowlarr#1197]
Hello there, Kitty Admin @ NBL here, and I would just like to inform Prowlarr user's that nbl is in the process of implementing new rules regarding VPNs and IP Logins.  Since it looks like Prowlarr is still logging into NBL via a webscrape, this may cause issues for some users in the near future resulting in IP bans due to 2fa or vpn whitelisting issues.

I would like to request that Prowlarr devs take another look at changing the nbl indexer to login via api rather than a web scrape, and if there are any aspects of the api that are unclear or would make integration easier, we are more than willing to work with Prowlarr devs.  Jackett just completed this as well.

Thanks in advance,
-twizt3dkitty

        Still scraping for now, we'll tackle the API usage later

_Originally posted by @Qstick in https://github.com/Prowlarr/Prowlarr/issues/590#issuecomment-976963516_
      

[AB#4085](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4085)

**Comment by Qstick** [comment]
Hi, would be happy to knock this out, but I need an account to test with.

**Comment by ahopelesshadow** [comment]
> Hi, would be happy to knock this out, but I need an account to test with.

I believe I invited/reactivated your anthelion profile.  I have sent an invite to that same email address, please confirm for me :)

**Comment by Qstick** [comment]
Thanks

**Comment by Qstick** [comment]
@ahopelesshadow you guys might want to fix the response headers for the API, they show `text/html` for content type instead of `application/json`

![image](https://user-images.githubusercontent.com/376117/208326648-0e89b528-aaa8-4477-9c26-1e2a0cf58cf3.png)

**Comment by Qstick** [comment]
https://github.com/Prowlarr/Prowlarr/commit/b5aa85a5489cc86d3c9e2208029642710cab9666
