### ISSUE TITLE
Indexer specific categories and passing over tags to *arr apps

### ISSUE THREAD

**Issue by Benni0109** [Prowlarr/Prowlarr#1198]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I would like to have passed over indexer specific categories and *arr tags

### Describe the solution you'd like

Possibility to select indexer specific categories when adding / editing a indexer and the possibility to pass over *arr tags to a specified app

### Describe alternatives you've considered

Currently my alternative is setting all these setting manually but this is not really a solution 

## Example of Anime related Indexer specific Categories
![image](https://user-images.githubusercontent.com/47495914/201896413-242778e8-605f-49d8-9154-2e4cd4882512.png)
## Example of TV/Movie related Indexer specific Categories
![image](https://user-images.githubusercontent.com/47495914/201896470-9e3c8331-74de-4957-b74b-308d76ca3e35.png)

## Example Usage of pass over tags
Tagging anime indexers and movie indexers to separate them from each other in Radarr:
![image](https://user-images.githubusercontent.com/47495914/201896529-54e0fbd2-5aa2-4975-bed1-e887cd0452ee.png)

[AB#4087](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4087)

**Comment by bakerboy448** [comment]
Closed 

> indexer specific categories 

not needed. Categories are standardized to newznab.

> indexer specific categories 

multiple duplicates please actually search rather than simply checking the box.
