### ISSUE TITLE
Cleanse Logs (Cardigann) (alphanumeric)

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#12]
2021-2-27 21:50:22.5|Debug|Cardigann|.Config.oneurl got value "https://beyond-hd.me/one/99999999999999999999999999999999/9999999999999999999999999999999"
2021-2-27 21:50:22.5|Debug|Cardigann|Setting oneurl to https://beyond-hd.me/one/99999999999999999999999999999999/99999999999999999999999999999999

**Comment by Qstick** [comment]
@bakerboy448 this still a thing? if so can you update or PR a log cleanse?

**Comment by bakerboy448** [comment]
Moot for BHD given we now use the API... will need to see what else
