### ISSUE TITLE
Blutopia

### ISSUE THREAD

**Issue by vgambier** [Prowlarr/Prowlarr#1202]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Having added Blutopia to prowlarr, and checking the "Search freeleech only" option, prowlarr is able to download torrents that are NOT freeleech, and in fact merely "50% free". This happened with 2 separate torrents.

### Expected Behavior

When the "Search freeleech only" option is checked, 50% free torrents should not be fetched. This issue may apply to other torrent categories and other trackers, maybe? Blutopia also has 25% and 75% free torrents after all. To me this seems like a fairly big deal as it can lead to big unwanted downloads in private trackers where ratios are important.

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye) aarch64 
- Prowlarr: 0.4.6.1969-ls69 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: Yes (nginx/swag)
- Browser: N/A
```

### What branch are you running?

Master

### Trace Logs?

I had not enabled trace logs at the time and I do not wish to reproduce the issue, I hope you understand why. I'm obviously willing to work with you by providing any information you want though.

**Comment by bakerboy448** [comment]
Not a Prowlarr issue.

https://github.com/Prowlarr/Indexers/blob/052e3674c0554e65f4ac34e121c0808d8a28a8f6/definitions/v7/blutopia-api.yml#L74

Prowlarr simply passes the search freeleech flag to the site.  If the site considers 25%/50%/75% releases as `freeleech` then that is something you'll need to take up with them.

**Comment by vgambier** [comment]
Ok, thank you, I will try that.

**Comment by vgambier** [comment]
@bakerboy448 The Blutopia team told me the proper search parameter is `free[0]=100`, 0 being an index that is incremented when you have multiple freeleech filters active, but is not relevant here since the only filter we want is 100% Freeleech.

[A PR for Jackett](https://github.com/Jackett/Jackett/pull/13727) has been opened and accepted. As you can see, `}&free=1{` should be replaced with `}&free[]=100{`. I think this issue should be re-opened.

**Comment by ilike2burnthing** [comment]
When the next merge of Jackett indexers into Prowlarr occurs (probably in a few days), this latest change for Blutopia will be included.
