### ISSUE TITLE
Audiobook bay url not working

### ISSUE THREAD

**Issue by spijkey87** [Prowlarr/Prowlarr#1227]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Audiobook bay  needs more urls these are no longer working......use .nl please

### Expected Behavior

Won't work right now

### Environment

```markdown
- Prowlarr:
```

### What branch are you running?

Nightly

### Trace Logs?

None

[AB#4358](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4358)

**Comment by Qstick** [comment]
https://github.com/Prowlarr/Indexers/commit/7e494dab151a2544d89961b03b8776e5070986e9
