### ISSUE TITLE
Indexer-HDSpace

### ISSUE THREAD

**Issue by chiragkrishna** [Prowlarr/Prowlarr#1233]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Unable to connect to indexer, check the log for more details

### Expected Behavior

Successfully add indexer.

### Steps To Reproduce

1)Go to Add Indexer
2)Add HD-Space
3)Enter credentials
4)adding flaresolverr doesnt change the error
5)Test the indexer

### Environment

```markdown
- OS: Debian 11
- Prowlarr: 0.4.10.2111
- Docker Install: yes
- Using Reverse Proxy: doesn't matter, happens with/out using nginx as reverse proxy
- Browser: Chrome, Edge, Firefox
```

### What branch are you running?

Develop

### Trace Logs?

2022-12-12 11:52:56.1|Warn|HttpClient|HTTP Error - Res: [POST] http://10.11.12.13:8191/v1: 500.InternalServerError (820 bytes)
{"status":"error","message":"Error: Unable to process browser request. ProtocolError: Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5\nUnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1\nnavigate@chrome://remote/content/cdp/domains/parent/Page.jsm:103:13\nexecute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25\nexecute@chrome://remote/content/cdp/sessions/Session.jsm:64:25\nexecute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20\nonPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36\nonMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18\nhandleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14\n","startTimestamp":1670845953923,"endTimestamp":1670845976137,"version":"v2.2.10"}
2022-12-12 11:52:56.1|Warn|HDSpace|Unable to connect to indexer

[v0.4.10.2111] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://10.11.12.13:8191/v1]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 127
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 136
   at NzbDrone.Core.IndexerProxies.FlareSolverr.FlareSolverr.PostResponse(HttpResponse response) in D:\a\1\s\src\NzbDrone.Core\IndexerProxies\FlareSolverr\FlareSolverr.cs:line 51
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in D:\a\1\s\src\NzbDrone.Core\Indexers\IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.ExecuteAuth(HttpRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 412
   at NzbDrone.Core.Indexers.Definitions.HDSpace.DoLogin() in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\HDSpace.cs:line 94
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 374
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 308
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 503
{"status":"error","message":"Error: Unable to process browser request. ProtocolError: Protocol error (Page.navigate): frameId not supported RemoteAgentError@chrome://remote/content/cdp/Error.jsm:29:5\nUnsupportedError@chrome://remote/content/cdp/Error.jsm:106:1\nnavigate@chrome://remote/content/cdp/domains/parent/Page.jsm:103:13\nexecute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25\nexecute@chrome://remote/content/cdp/sessions/Session.jsm:64:25\nexecute@chrome://remote/content/cdp/sessions/TabSession.jsm:67:20\nonPacket@chrome://remote/content/cdp/CDPConnection.jsm:248:36\nonMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18\nhandleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14\n","startTimestamp":1670845953923,"endTimestamp":1670845976137,"version":"v2.2.10"}

[AB#4438](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4438)

**Comment by ilike2burnthing** [comment]
You can try the v3 beta - https://github.com/FlareSolverr/FlareSolverr/issues/522

**Comment by SmartPhoneLover** [comment]
> You can try the v3 beta - [FlareSolverr/FlareSolverr#522](https://github.com/FlareSolverr/FlareSolverr/issues/522)

I replied again to my own reply on this thread. (check the latest)
It keeps not working with latest beta3.

**Comment by chiragkrishna** [comment]
its working using this fork of flaresolverr

ghcr.io/aeonlucid/flaresolverr:v3.0.0

**Comment by Zeromark30** [comment]
I think this needs to be reopened flaresolverr is able to complete successfully but prowlarr is sending to many request to the indexer causing it to fail.

https://github.com/FlareSolverr/FlareSolverr/issues/522#issuecomment-1347694006

**Comment by bakerboy448** [comment]
What's the number of request per {timeframe} that HDSpace limits?  How long needs to be between requests?

**Comment by Zeromark30** [comment]
Im not sure but if we look at my two request and and responses its not login in correctly. Prowlarr assumes a login occurred but teh site still has taken the login data post.

FIRST REQUEST
> 2022-12-13 04:42:07 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://hd-space.org/index.php?page=login', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', 'proxy': {}}
> 2022-12-13 04:42:07 WARNING  Request parameter 'userAgent' was removed in FlareSolverr v2.
> 2022-12-13 04:42:12 INFO     Challenge not detected!
> 2022-12-13 04:42:12 INFO     Response in 5.045 s
> 2022-12-13 04:42:12 INFO     ** POST**/v1 200 OK

FIRST RESPONSE
> HTTP/1.1 200 OK
Content-Length: 10836
Content-Type: application/json
Date: Tue, 13 Dec 2022 04:42:07 GMT
Server: waitress

{"status": "ok", "message": "Challenge not detected!", "solution": {"url": "https://hd-space.org/index.php?page=login", "status": 200, "captcha_type": null, "cookies": [{"domain": "hd-space.org", "httpOnly": false, "name": "PHPSESSID", "path": "/", "secure": false, "value": "aunfkkchrsr0dbd207cu455os4"}, {"domain": ".hd-space.org", "expiry": 1702442529, "httpOnly": true, "name": "cf_clearance", "path": "/", "sameSite": "None", "secure": true, "value": "BIxVxh.LOW7VVmtggIMljkZ5qOIQ0gQb9N37HNU8kfw-1670906529-0-150"}], "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36", "headers": {}, "response": "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head>\n  <title>HD-Space - Sharing The Universe .::. Index-&gt;Login</title>\n      \n  <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n  <link rel=\"stylesheet\" href=\"https://hd-space.org/style/xbtit_default/main.css\" type=\"text/css\">\n  \n  <link rel=\"stylesheet\" type=\"text/css\"><link rel=\"stylesheet\" href=\"https://hd-space.org/style/xbtit_default/menu.css\" type=\"text/css\">\n  \n  \n  \n\n\n\t\n\t<script type=\"text/javascript\" src=\"https://hd-space.org/jscript/ajax.js\"></script>\n\n\t<script type=\"text/javascript\" src=\"https://hd-space.org/jscript/xbtit.js\"></script>\n    <script type=\"text/javascript\" src=\"https://hd-space.org/jscript/jquery-3.2.1.min.js\"></script>\n    <script type=\"text/javascript\" src=\"https://hd-space.org/jscript/freeInvitations.js\"></script>\n\t<script type=\"text/javascript\" src=\"https://hd-space.org/js/jquery.js\"></script>\n        <script type=\"text/javascript\" src=\"https://hd-space.org/js/menu.js\"></script>\n\n\n<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\n<script type=\"text/javascript\" src=\"js/menu.js\"></script>\n<script type=\"text/javascript\" src=\"./jscript/overlib.js\"></script>\n\n\n</head>\n<body><div id=\"overDiv\" style=\"position:absolute; visibility:hidden; z-index:1000;\"></div>\n\n\n  <div align=\"center\">\n<table width=\"100%\" cellspacing=\"0\" style=\"background: transperant; border: 3px;\">\n  <tbody><tr>\n    <td align=\"center\">\n<table width=\"900px\" cellspacing=\"2\" style=\"background: #212121; border: 3px solid #141414;\">\n  <tbody><tr>\n\n    <td align=\"center\">\n\n<table width=\"100%\" cellspacing=\"0\" style=\"background: transperant; border:none;\">\n  <tbody><tr>\n    <td align=\"center\">\n<table width=\"900px\" cellspacing=\"2\" style=\"background: #212121; border: 3px solid #141414;\">\n  <tbody><tr>\n\n    <td align=\"center\">\n\n<table class=\"new\" width=\"100%\" height=\"250px\" border=\"0\">\n<tbody><tr><td height=\"100\" colspan=\"2\">\n    <input type=\"image\" src=\"images/donatenew.png\" align=\"right\" border=\"0\" title=\"PayPal - The safer, easier way to pay online!\"><table width=\"100%\">\n\t<tbody><tr><td align=\"center\"><form action=\"index.php?page=donpage\" method=\"post\">\n\n</form></td></tr><tr></tr>\n\n\n\n</tbody></table>\n\n<br><br><br><br><br><br>\n\n        <table width=\"100%\" cellpadding=\"0\" cellspacing=\"6\" border=\"0\">\n        <tbody><tr>\n        <td valign=\"top\"><div><br>\n\n<table class=\"lista\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" align=\"center\">\n  <tbody><tr>\n    <td class=\"blockheader\" align=\"center\" height=\"20px\"><b></b></td>\n  </tr>\n  <tr>\n    <td width=\"100%\" align=\"justify\" valign=\"top\">\n        <form action=\"index.php?page=login\" name=\"login\" method=\"post\">\n    <table class=\"lista\" border=\"0\" width=\"100%\" cellpadding=\"4\" cellspacing=\"1\">\n    <tbody><tr>\n    <td class=\"lista\" align=\"left\">\n      <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n      <tbody><tr>\n      <td align=\"right\" class=\"lista\">User:</td>\n      <td class=\"lista\"><input type=\"text\" size=\"15\" name=\"uid\" id=\"want_username1\" value=\"\" maxlength=\"40\" style=\"font-size:10px\"></td>\n      <td align=\"right\" class=\"lista\">Password:</td>\n      <td class=\"lista\"><input type=\"password\" size=\"15\" name=\"pwd\" id=\"want_password1\" maxlength=\"40\" style=\"font-size:10px\"></td>\n      <td align=\"right\" class=\"lista\">Automatic log off after 15 minutes inactivity<input type=\"checkbox\" name=\"logout\" value=\"yes\"></td>\n      <td class=\"lista\" align=\"center\"><input type=\"submit\" value=\"Login\" style=\"font-size:10px\"></td>\n      </tr>\n      </tbody></table>\n    </td>\n    <td class=\"lista\" align=\"center\"><a href=\"index.php?page=signup\">Create account</a></td>\n    <td class=\"lista\" align=\"center\"><a href=\"index.php?page=recover\">Recover password</a></td>\n    </tr>\n    </tbody></table>\n    </form>\n<style type=\"text/css\">\n.mail {\n      -moz-box-shadow: 0px 10px 14px -7px #3e7327;\n\t-webkit-box-shadow: 0px 10px 14px -7px #3e7327;\n\tbox-shadow: 0px 10px 14px -7px #3e7327;\n\tbackground:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #77b55a), color-stop(1, #72b352));\n\tbackground:-moz-linear-gradient(top, #77b55a 5%, #72b352 100%);\n\tbackground:-webkit-linear-gradient(top, #77b55a 5%, #72b352 100%);\n\tbackground:-o-linear-gradient(top, #77b55a 5%, #72b352 100%);\n\tbackground:-ms-linear-gradient(top, #77b55a 5%, #72b352 100%);\n\tbackground:linear-gradient(to bottom, #77b55a 5%, #72b352 100%);\n\tfilter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#77b55a', endColorstr='#72b352',GradientType=0);\n\tbackground-color:#77b55a;\n\t-moz-border-radius:4px;\n\t-webkit-border-radius:4px;\n\tborder-radius:4px;\n\tborder:1px solid #4b8f29;\n\tdisplay:inline-block;\n\tcursor:pointer;\n\tcolor:#000000;\n\tfont-family:Arial;\n\tfont-size:14px;\n\tfont-weight:bold;\n\tpadding:5px 12px;\n\ttext-decoration:none;\n\ttext-shadow:0px 1px 0px #5b8a3c;\n}\n</style>\n\n    </td>\n  </tr>\n</tbody></table></div></td>\n\t\t\n        </tr>\n        \n\t\t          <tr><td class=\"lista\" width=\"100%\">\n    <script type=\"text/javascript\">\n    //Syntax: var uniquevar=new animatedcollapse(\"DIV_id\", animatetime_milisec, enablepersist(true/fase), [initialstate] )\n    var collapse2=new animatedcollapse(\"header\", 800, false, \"block\")\n    </script>\n    <div id=\"bodyarea\">  \n    <table border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n      <tbody><tr>\n        <td valign=\"top\" width=\"5\" rowspan=\"2\"></td>\n        <td valign=\"top\"><br>\n\n<table class=\"lista\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" align=\"center\">\n  <tbody><tr>\n    <td class=\"block\" align=\"center\" height=\"20px\"><b>Login</b></td>\n  </tr>\n  <tr>\n    <td width=\"100%\" align=\"center\" valign=\"top\">\n            <script type=\"text/javascript\" src=\"/jscript/animatedcollapse.js\"></script>\n<script type=\"text/javascript\">\nfunction form_control()\n  {\n    if (document.getElementById('want_username').value.length==0)\n      {\n      var want_username=document.createElement('span');\n      want_username.innerHTML='You must insert a username!';\n      alert(want_username.innerHTML);\n      document.getElementById('want_username').focus();\n      return false;\n      }\n\n    if (document.getElementById('want_password').value == \"\")\n      {\n      var want_password=document.createElement('span');\n      want_password.innerHTML='You must insert a password!';\n      alert(want_password.innerHTML);\n      document.getElementById('want_password').focus();\n      return false;\n      }\n\n   return true;\n  }\n</script>\n<form method=\"post\" onsubmit=\"return form_control()\" action=\"index.php?page=login&amp;returnto=index.php\">\n  <tag:count>\n  </tag:count></form></td></tr><tr><td colspan=\"2\" class=\"header\" align=\"center\">You have <span style=\"color:#FF6666\">10</span> remaining login attempts.</td></tr>  </tbody></table><table align=\"center\" class=\"lista\" border=\"0\" cellpadding=\"10\">\n    \n    \n\t    \n      \n    <tbody><tr>\n      <td align=\"right\" class=\"header\">User:</td>\n      <td class=\"lista\"><input type=\"text\" size=\"40\" name=\"uid\" id=\"want_username\" value=\"\" maxlength=\"40\"></td>\n    </tr>\n    <tr>\n      <td align=\"right\" class=\"header\">Password:</td>\n      <td class=\"lista\"><input type=\"password\" size=\"40\" name=\"pwd\" id=\"want_password\" maxlength=\"40\"></td>\n    </tr>        <tr>\n        <td align=\"right\" class=\"header\"></td>\n        <td class=\"lista\"><input type=\"checkbox\" name=\"logout\" value=\"yes\">Automatic log off after 15 minutes inactivity</td>\n    </tr>\n    <tr>\n      <td colspan=\"2\" class=\"header\" align=\"center\"><input type=\"submit\" class=\"btn\" value=\"Confirm\"></td>\n    </tr>\n    <tr>\n      <td colspan=\"2\" class=\"header\" align=\"center\">Note: You need cookies enabled to log in.</td>\n    </tr>\n  </tbody></table>\n\n<p align=\"center\">\n  <a href=\"index.php?page=signup\">Create account</a>&nbsp;&nbsp;&nbsp;<a href=\"index.php?page=recover\">Recover password</a>\n</p>\n\n    </td>\n  </tr>\n</tbody></table></div></td>\n        <td valign=\"top\" width=\"5\" rowspan=\"2\"></td>\n      </tr>\n    </tbody></table>\n      <br>\n      <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n        <tbody><tr>\n          <td valign=\"top\" width=\"5\" rowspan=\"2\"></td>\n          <td valign=\"top\"><br>\n</td>\n          <td valign=\"top\" width=\"5\" rowspan=\"2\"></td>\n        </tr>\n\t\t\t</tbody></table>\n    \n        \n\t\t          </td>\n      </tr>\n\t  \n\t  </tbody></table><table width=\"100%\" height=\"32\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tbody><tr>\n<td class=\"f_left\"></td>\n<td class=\"f_middle\" style=\"text-align:center;\">\n<span valign=\"bottom\" class=\"nav\"><br>If you find any information that is in violation to a privacy law please report to <u><a href=\"mailto:hd.space.org@gmail.com\">hd.space.org@gmail.com</a></u> ! </span></td>\n\n\t  \n </tr></tbody></table><table width=\"100%\" height=\"35\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tbody><tr>\n<td class=\"f_left\"></td>\n<td class=\"f_left\" style=\"text-align:center;\">\n<script type=\"text/javascript\">\n</script></td><td class=\"f_right\" align=\"right\">\n<font color=\"#6c6c6c\" size=\"2\" face=\"tahoma\"><i>Style: HD-Space v.2.5</i></font>       </td></tr></tbody></table>  </td>\n\n          </tr></tbody></table>  </td>\n\n\n    \n\n\n    </tr>\n  \n\n\n\n\n</tbody></table></td></tr></tbody></table></td></tr></tbody></table></div></body></html>"}, "startTimestamp": 1670906527281, "endTimestamp": 1670906532326, "version": "3.0.0"}

SECOND REQUEST

> 2022-12-13 04:42:12 INFO     Incoming request => POST /v1 body: {'headers': {'contentType': 'application/x-www-form-urlencoded'}, 'postData': 'uid=**&pwd=**', 'maxTimeout': 60000, 'cmd': 'request.post', 'url': 'https://hd-space.org/index.php?page=login', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36', 'proxy': {}}
> 2022-12-13 04:42:12 WARNING  Request parameter 'headers' was removed in FlareSolverr v2.
> 2022-12-13 04:42:12 WARNING  Request parameter 'userAgent' was removed in FlareSolverr v2.
> 2022-12-13 04:42:13 INFO     Challenge detected. Selector found: #challenge-spinner
> 2022-12-13 04:42:19 INFO     Challenge solved!
> 2022-12-13 04:42:19 INFO     Response in 7.291 s
> 2022-12-13 04:42:19 INFO     **POST **/v1 200 OK

SECOND RESPONSE

> HTTP/1.1 200 OK
Content-Length: 10830
Content-Type: application/json
Date: Tue, 13 Dec 2022 04:42:12 GMT
Server: waitress

{"status": "ok", "message": "Challenge solved!", "solution": {"url": "https://hd-space.org/index.php?page=login", "status": 200, "captcha_type": null, "cookies": [{"domain": "hd-space.org", "httpOnly": false, "name": "PHPSESSID", "path": "/", "secure": false, "value": "e0piar30rarrc5d5m66juv3972"}, {"domain": ".hd-space.org", "expiry": 1702442537, "httpOnly": true, "name": "cf_clearance", "path": "/", "sameSite": "None", "secure": true, "value": "ds2e_SoXoi35ln.i6zA.wr6anaiWCONFWbJOIdOu0XE-1670906537-0-150"}], "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36", "headers": {}, "response": "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head>\n  <title>HD-Space - Sharing The Universe .::. Index-&gt;Login</title>\n      \n  <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n  <link rel=\"stylesheet\" href=\"https://hd-space.org/style/xbtit_default/main.css\" type=\"text/css\">\n  \n  <link rel=\"stylesheet\" type=\"text/css\"><link rel=\"stylesheet\" href=\"https://hd-space.org/style/xbtit_default/menu.css\" type=\"text/css\">\n  \n  \n  \n\n\n\t\n\t<script type=\"text/javascript\" src=\"https://hd-space.org/jscript/ajax.js\"></script>\n\n\t<script type=\"text/javascript\" src=\"https://hd-space.org/jscript/xbtit.js\"></script>\n    <script type=\"text/javascript\" src=\"https://hd-space.org/jscript/jquery-3.2.1.min.js\"></script>\n    <script type=\"text/javascript\" src=\"https://hd-space.org/jscript/freeInvitations.js\"></script>\n\t<script type=\"text/javascript\" src=\"https://hd-space.org/js/jquery.js\"></script>\n        <script type=\"text/javascript\" src=\"https://hd-space.org/js/menu.js\"></script>\n\n\n<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\n<script type=\"text/javascript\" src=\"js/menu.js\"></script>\n<script type=\"text/javascript\" src=\"./jscript/overlib.js\"></script>\n\n\n</head>\n<body><div id=\"overDiv\" style=\"position:absolute; visibility:hidden; z-index:1000;\"></div>\n\n\n  <div align=\"center\">\n<table width=\"100%\" cellspacing=\"0\" style=\"background: transperant; border: 3px;\">\n  <tbody><tr>\n    <td align=\"center\">\n<table width=\"900px\" cellspacing=\"2\" style=\"background: #212121; border: 3px solid #141414;\">\n  <tbody><tr>\n\n    <td align=\"center\">\n\n<table width=\"100%\" cellspacing=\"0\" style=\"background: transperant; border:none;\">\n  <tbody><tr>\n    <td align=\"center\">\n<table width=\"900px\" cellspacing=\"2\" style=\"background: #212121; border: 3px solid #141414;\">\n  <tbody><tr>\n\n    <td align=\"center\">\n\n<table class=\"new\" width=\"100%\" height=\"250px\" border=\"0\">\n<tbody><tr><td height=\"100\" colspan=\"2\">\n    <input type=\"image\" src=\"images/donatenew.png\" align=\"right\" border=\"0\" title=\"PayPal - The safer, easier way to pay online!\"><table width=\"100%\">\n\t<tbody><tr><td align=\"center\"><form action=\"index.php?page=donpage\" method=\"post\">\n\n</form></td></tr><tr></tr>\n\n\n\n</tbody></table>\n\n<br><br><br><br><br><br>\n\n        <table width=\"100%\" cellpadding=\"0\" cellspacing=\"6\" border=\"0\">\n        <tbody><tr>\n        <td valign=\"top\"><div><br>\n\n<table class=\"lista\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" align=\"center\">\n  <tbody><tr>\n    <td class=\"blockheader\" align=\"center\" height=\"20px\"><b></b></td>\n  </tr>\n  <tr>\n    <td width=\"100%\" align=\"justify\" valign=\"top\">\n        <form action=\"index.php?page=login\" name=\"login\" method=\"post\">\n    <table class=\"lista\" border=\"0\" width=\"100%\" cellpadding=\"4\" cellspacing=\"1\">\n    <tbody><tr>\n    <td class=\"lista\" align=\"left\">\n      <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n      <tbody><tr>\n      <td align=\"right\" class=\"lista\">User:</td>\n      <td class=\"lista\"><input type=\"text\" size=\"15\" name=\"uid\" id=\"want_username1\" value=\"\" maxlength=\"40\" style=\"font-size:10px\"></td>\n      <td align=\"right\" class=\"lista\">Password:</td>\n      <td class=\"lista\"><input type=\"password\" size=\"15\" name=\"pwd\" id=\"want_password1\" maxlength=\"40\" style=\"font-size:10px\"></td>\n      <td align=\"right\" class=\"lista\">Automatic log off after 15 minutes inactivity<input type=\"checkbox\" name=\"logout\" value=\"yes\"></td>\n      <td class=\"lista\" align=\"center\"><input type=\"submit\" value=\"Login\" style=\"font-size:10px\"></td>\n      </tr>\n      </tbody></table>\n    </td>\n    <td class=\"lista\" align=\"center\"><a href=\"index.php?page=signup\">Create account</a></td>\n    <td class=\"lista\" align=\"center\"><a href=\"index.php?page=recover\">Recover password</a></td>\n    </tr>\n    </tbody></table>\n    </form>\n<style type=\"text/css\">\n.mail {\n      -moz-box-shadow: 0px 10px 14px -7px #3e7327;\n\t-webkit-box-shadow: 0px 10px 14px -7px #3e7327;\n\tbox-shadow: 0px 10px 14px -7px #3e7327;\n\tbackground:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #77b55a), color-stop(1, #72b352));\n\tbackground:-moz-linear-gradient(top, #77b55a 5%, #72b352 100%);\n\tbackground:-webkit-linear-gradient(top, #77b55a 5%, #72b352 100%);\n\tbackground:-o-linear-gradient(top, #77b55a 5%, #72b352 100%);\n\tbackground:-ms-linear-gradient(top, #77b55a 5%, #72b352 100%);\n\tbackground:linear-gradient(to bottom, #77b55a 5%, #72b352 100%);\n\tfilter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#77b55a', endColorstr='#72b352',GradientType=0);\n\tbackground-color:#77b55a;\n\t-moz-border-radius:4px;\n\t-webkit-border-radius:4px;\n\tborder-radius:4px;\n\tborder:1px solid #4b8f29;\n\tdisplay:inline-block;\n\tcursor:pointer;\n\tcolor:#000000;\n\tfont-family:Arial;\n\tfont-size:14px;\n\tfont-weight:bold;\n\tpadding:5px 12px;\n\ttext-decoration:none;\n\ttext-shadow:0px 1px 0px #5b8a3c;\n}\n</style>\n\n    </td>\n  </tr>\n</tbody></table></div></td>\n\t\t\n        </tr>\n        \n\t\t          <tr><td class=\"lista\" width=\"100%\">\n    <script type=\"text/javascript\">\n    //Syntax: var uniquevar=new animatedcollapse(\"DIV_id\", animatetime_milisec, enablepersist(true/fase), [initialstate] )\n    var collapse2=new animatedcollapse(\"header\", 800, false, \"block\")\n    </script>\n    <div id=\"bodyarea\">  \n    <table border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n      <tbody><tr>\n        <td valign=\"top\" width=\"5\" rowspan=\"2\"></td>\n        <td valign=\"top\"><br>\n\n<table class=\"lista\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" align=\"center\">\n  <tbody><tr>\n    <td class=\"block\" align=\"center\" height=\"20px\"><b>Login</b></td>\n  </tr>\n  <tr>\n    <td width=\"100%\" align=\"center\" valign=\"top\">\n            <script type=\"text/javascript\" src=\"/jscript/animatedcollapse.js\"></script>\n<script type=\"text/javascript\">\nfunction form_control()\n  {\n    if (document.getElementById('want_username').value.length==0)\n      {\n      var want_username=document.createElement('span');\n      want_username.innerHTML='You must insert a username!';\n      alert(want_username.innerHTML);\n      document.getElementById('want_username').focus();\n      return false;\n      }\n\n    if (document.getElementById('want_password').value == \"\")\n      {\n      var want_password=document.createElement('span');\n      want_password.innerHTML='You must insert a password!';\n      alert(want_password.innerHTML);\n      document.getElementById('want_password').focus();\n      return false;\n      }\n\n   return true;\n  }\n</script>\n<form method=\"post\" onsubmit=\"return form_control()\" action=\"index.php?page=login&amp;returnto=index.php\">\n  <tag:count>\n  </tag:count></form></td></tr><tr><td colspan=\"2\" class=\"header\" align=\"center\">You have <span style=\"color:#FF6666\">10</span> remaining login attempts.</td></tr>  </tbody></table><table align=\"center\" class=\"lista\" border=\"0\" cellpadding=\"10\">\n    \n    \n\t    \n      \n    <tbody><tr>\n      <td align=\"right\" class=\"header\">User:</td>\n      <td class=\"lista\"><input type=\"text\" size=\"40\" name=\"uid\" id=\"want_username\" value=\"\" maxlength=\"40\"></td>\n    </tr>\n    <tr>\n      <td align=\"right\" class=\"header\">Password:</td>\n      <td class=\"lista\"><input type=\"password\" size=\"40\" name=\"pwd\" id=\"want_password\" maxlength=\"40\"></td>\n    </tr>        <tr>\n        <td align=\"right\" class=\"header\"></td>\n        <td class=\"lista\"><input type=\"checkbox\" name=\"logout\" value=\"yes\">Automatic log off after 15 minutes inactivity</td>\n    </tr>\n    <tr>\n      <td colspan=\"2\" class=\"header\" align=\"center\"><input type=\"submit\" class=\"btn\" value=\"Confirm\"></td>\n    </tr>\n    <tr>\n      <td colspan=\"2\" class=\"header\" align=\"center\">Note: You need cookies enabled to log in.</td>\n    </tr>\n  </tbody></table>\n\n<p align=\"center\">\n  <a href=\"index.php?page=signup\">Create account</a>&nbsp;&nbsp;&nbsp;<a href=\"index.php?page=recover\">Recover password</a>\n</p>\n\n    </td>\n  </tr>\n</tbody></table></div></td>\n        <td valign=\"top\" width=\"5\" rowspan=\"2\"></td>\n      </tr>\n    </tbody></table>\n      <br>\n      <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n        <tbody><tr>\n          <td valign=\"top\" width=\"5\" rowspan=\"2\"></td>\n          <td valign=\"top\"><br>\n</td>\n          <td valign=\"top\" width=\"5\" rowspan=\"2\"></td>\n        </tr>\n\t\t\t</tbody></table>\n    \n        \n\t\t          </td>\n      </tr>\n\t  \n\t  </tbody></table><table width=\"100%\" height=\"32\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tbody><tr>\n<td class=\"f_left\"></td>\n<td class=\"f_middle\" style=\"text-align:center;\">\n<span valign=\"bottom\" class=\"nav\"><br>If you find any information that is in violation to a privacy law please report to <u><a href=\"mailto:hd.space.org@gmail.com\">hd.space.org@gmail.com</a></u> ! </span></td>\n\n\t  \n </tr></tbody></table><table width=\"100%\" height=\"35\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tbody><tr>\n<td class=\"f_left\"></td>\n<td class=\"f_left\" style=\"text-align:center;\">\n<script type=\"text/javascript\">\n</script></td><td class=\"f_right\" align=\"right\">\n<font color=\"#6c6c6c\" size=\"2\" face=\"tahoma\"><i>Style: HD-Space v.2.5</i></font>       </td></tr></tbody></table>  </td>\n\n          </tr></tbody></table>  </td>\n\n\n    \n\n\n    </tr>\n  \n\n\n\n\n</tbody></table></td></tr></tbody></table></td></tr></tbody></table></div></body></html>"}, "startTimestamp": 1670906532568, "endTimestamp": 1670906539859, "version": "3.0.0"}
