### ISSUE TITLE
[MoreThanTV] search criteria seems to outdated and broken

### ISSUE THREAD

**Issue by mynameisbogdan** [Prowlarr/Prowlarr#1235]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

1. when searching for `tv show name S19` it changes it to `tv show name S19*` which doesn't return any results.
2. when searching for `modern marvels` it replaces `marvels` with `marvel` resulting in `modern marvel` which doesn't return results (`modern marvels` works as intended)
3. when searching for a season in sonarr it doesn't use the season, just the tv show title thus returning results with all seasons.
4. clean up title function is old and useless, and it should be removed. example for original title `Movie.2008.720p.4K.Restoration.BluRay.DD5.1.x264-iFT` results in `Movie 2008 720p 2160p Restoration BluRay DD5 1 x264-iFT` having two resolutions and `DD5 1` instead of `DD5.1`.

### Expected Behavior

Some fixes would be to remove `GetSearchString` and `CleanUpTitle`, and add real support for season search when using `t=tvsearch&q=tv+show&season=19` for example, and even maybe support for single episode search.

### Environment

```markdown
- OS: Unraid
- Prowlarr: 0.4.10.2111
- Docker Install: Y
- Using Reverse Proxy: N
- Browser: -
```

### What branch are you running?

Develop

### Trace Logs?

N/A

[AB#4444](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4444)

**Comment by bakerboy448** [comment]
@DevYukine

**Comment by peelos** [comment]
API key is also now supported by MoreThanTV and Jackett - can that also be added, perhaps related to this issue.

**Comment by DevYukine** [comment]
MTV has a Torznab api now which is what should be used instead of this older scraping implementation, might be worth to move the indexer over to that instead or deprecate the current implementation in favor of torznab, either works here

**Comment by mynameisbogdan** [comment]
@DevYukine for the last days I tried their API as Generic Torznab and it seems unstable, not always seeing it in the *arr apps after create/edit, needing `Application Indexer Sync` to be manually run.

And while using the search within prowlarr I got this:

![Screenshot 2022-12-17 at 01 55 18](https://user-images.githubusercontent.com/707714/208209824-c172536b-c280-446f-8b6a-0e35872381ba.jpg)
![Screenshot 2022-12-17 at 01 55 23](https://user-images.githubusercontent.com/707714/208209830-1240f4b9-cea3-4206-a11e-ebcc1f07b2e9.jpg)

[Trace logs](https://privatebin.net/?69496e98b2d7902f#7z56epPhb21FP4DGfdZAUkHEUqEEAbcCNahwkeNP2RBB)

**Comment by Qstick** [comment]
If you can pinpoint some of the issues with the torznab implementation we can see about fixing those. 

As for the current, we could probably clean it up a bit in the meantime. The marvels to marvel replace is a bit odd, assume it was aiming to fix a specific case but it also breaks others. The wildcard can be tossed out if it doesn't work anymore. 

```
    private string GetSearchString(string input)
    {
        input = input.Replace("Marvels", "Marvel"); // strip 's for better results
        var regex = new Regex(@"(S\d{2})$", RegexOptions.Compiled);
        return regex.Replace(input, "$1*"); // If we're just seaching for a season (no episode) append an * to include all episodes of that season.
    }
```

**Comment by mynameisbogdan** [comment]
> If you can pinpoint some of the issues with the torznab implementation we can see about fixing those.

[Here's a trace log with a sample response](https://privatebin.net/?f85f547c0b9d9f38#9FWLfNp5KKYZD3ioipPdKeAFSKgdA28Yr6qnazTYYvhd).

> As for the current, we could probably clean it up a bit in the meantime. The marvels to marvel replace is a bit odd, assume it was aiming to fix a specific case but it also breaks others. The wildcard can be tossed out if it doesn't work anymore.

Maybe would be better to use their torznab API just like Jackett does?

**Comment by bakerboy448** [comment]
Agreed. We should obsolete the existing entry and users can move to the Torznab via Generic Torznab

**Comment by mynameisbogdan** [comment]
> Agreed. We should obsolete the existing entry and users can move to the Torznab via Generic Torznab

Well, [Jackett](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/Feeds/MoreThanTVAPI.cs) currently acts like a proxy to MTV API.

Also MTV must fix the search by `imdbid` without `tt`, they are aware of this and I'm waiting for the change.

**Comment by Qstick** [comment]
Can you provide response from `https://www.morethantv.me/api/torznab?t=caps&apikey={yourkey}`

We shouldn't need a separate implementation, but just a definition on our Torznab implementation for it. (this would function exactly like Generic Torznab, but have a dedicated option in UI). Our Torznab implementation is going the same thing as Jackett does, so if there are some issues with how Generic Torznab is handling this then we can get those sorted out.

**Comment by mynameisbogdan** [comment]
> Can you provide response from `https://www.morethantv.me/api/torznab?t=caps&apikey={yourkey}`

Sure, [here it is](https://privatebin.net/?7df6c8b5b76bb619#F2dyWK4F368tocsbyn6znTXvPDKSVyCmF1sDsSahG5eK).

**Comment by Qstick** [comment]
That should move all new setups to the API. You can keep your existing for now if you want until they fix imdb, but you should see a health warning until you change.

**Comment by mynameisbogdan** [comment]
> That should move all new setups to the API. You can keep your existing for now if you want until they fix imdb, but you should see a health warning until you change.

Well, I'm already using MTV via `Generic Torznab` since I wanted to test it for a couple of days to find any non-complainant stuff.

But the category shown in prowlarr would still be broken, no?

**Comment by Qstick** [comment]
> > That should move all new setups to the API. You can keep your existing for now if you want until they fix imdb, but you should see a health warning until you change.
> 
> Well, I'm already using MTV via `Generic Torznab` since I wanted to test it for a couple of days to find any non-complainant stuff.
> 
> But the category shown in prowlarr would still be broken, no?

Does it show that on all torrents? Or just a specific one?

**Comment by mynameisbogdan** [comment]
All, no matter what I'm searching. 

![Screenshot 2022-12-21 at 02 17 02](https://user-images.githubusercontent.com/707714/208791423-cb34b787-6dbd-4565-bc4d-59ba7ab3c92a.jpg)

The only weird thing that I noticed is that it seems to be always two `category` tags present in the XML output.

**Comment by Qstick** [comment]
Yea, the two category thing is newznab/torznab standard. Let me have a look at the category parsing I tweaked recently.

**Comment by Qstick** [comment]
Seems like they are providing an invalid feed, notice in AnimeTosho how the <category> items are the text categories and the caetgory attributes are the ids

```
      <item>
         <title>Bleach: Sennen Kessen-hen - 07 | Bleach - Thousand Year Blood War [English Dub][1080p]</title>
         <description><![CDATA[<strong>Source(s)</strong>: <a href="https://nyaa.si/view/1614446" title="Nyaa: Normal"><span style="color: #FBFBFB;">&#9679;</span>Nyaa</a><br/><strong>Total Size</strong>: 1.303 GB<br/><strong>Download Links</strong>: <a href="https://animetosho.org/storage/torrent/ba482d0fe846d37202d7874adbdf6cbd91378e9c/Bleach%20-%20Thousand-Year%20Blood%20War%20-%2007%20-%20Born%20in%20The%20Dark.torrent">Torrent</a>/<a href="magnet:?xt=urn:btih:XJEC2D7II3JXEAWXQ5FNXX3MXWITPDU4&amp;tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&amp;tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&amp;tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&amp;dn=Bleach%3A%20Sennen%20Kessen-hen%20-%2007%20%7C%20Bleach%20-%20Thousand%20Year%20Blood%20War%20%5BEnglish%20Dub%5D%5B1080p%5D">Magnet</a>, <a href="https://animetosho.org/storage/nzbs/00081e91/Bleach%20-%20Thousand-Year%20Blood%20War%20-%2007%20-%20Born%20in%20The%20Dark.nzb.gz">NZB</a> | <a href="https://clicknupload.to/z8z0woe2ioeb">ClickNUpload</a><br/>DownloadGG: <a href="https://download.gg/file-14541635_c2d3652ecf3c0a14">Part1</a>, <a href="https://download.gg/file-14541636_9a381ca5f8b90091">Part2</a><br/>KrakenFiles: <a href="https://krakenfiles.com/view/F9k0I3gLO7/file.html">Part1</a>, <a href="https://krakenfiles.com/view/nx69CPTQ1I/file.html">Part2</a><br/>MultiUp: <a href="https://multiup.org/download/081b1ee8a7f823f225cba6cfe13e85ff/Bleach%20-%20Thousand-Year%20Blood%20War%20-%2007%20-%20Born%20in%20The%20Dark.mkv.001">Part1</a>, <a href="https://multiup.org/download/2fa72ac26b07a5efb7ee3ed37329c08a/Bleach%20-%20Thousand-Year%20Blood%20War%20-%2007%20-%20Born%20in%20The%20Dark.mkv.002">Part2</a>, <a href="https://multiup.org/download/49b1ba5b57454ea836a440d7d6731f50/Bleach%20-%20Thousand-Year%20Blood%20War%20-%2007%20-%20Born%20in%20The%20Dark.mkv.003">Part3</a><br/>ZippyShare: <a href="https://www42.zippyshare.com/v/PzYO0jtd/file.html">Part1</a>, <a href="https://www42.zippyshare.com/v/BZaMp7HJ/file.html">Part2</a>, <a href="https://www42.zippyshare.com/v/6pIHd6GS/file.html">Part3</a>]]></description>
         <link>https://animetosho.org/view/bleach-sennen-kessen-hen-07-thousand-year-blood.n1614446</link>
         <comments>https://animetosho.org/view/bleach-sennen-kessen-hen-07-thousand-year-blood.n1614446</comments>
         <enclosure url="https://animetosho.org/storage/torrent/ba482d0fe846d37202d7874adbdf6cbd91378e9c/Bleach%20-%20Thousand-Year%20Blood%20War%20-%2007%20-%20Born%20in%20The%20Dark.torrent" type="application/x-bittorrent" length="0" />
         <enclosure url="https://animetosho.org/storage/nzbs/00081e91/Bleach%20-%20Thousand-Year%20Blood%20War%20-%2007%20-%20Born%20in%20The%20Dark.nzb" type="application/x-nzb" length="0" />
         <source url="https://nyaa.si/view/1614446">Nyaa</source>
         <pubDate>Sat, 17 Dec 2022 04:36:01 +0000</pubDate>
         <guid isPermaLink="true">https://animetosho.org/view/a532113</guid>
         <category>Anime</category>
         <newznab:attr name="category" value="5070" />
         <newznab:attr name="files" value="1" />
         <newznab:attr name="size" value="1398901737" />
         <torznab:attr name="tvdbid" value="74796" />
         <newznab:attr name="season" value="17" />
         <newznab:attr name="imdb" value="" />
         <newznab:attr name="year" value="2022" />
         <newznab:attr name="tvairdate" value="Tue, 22 Nov 2022 00:00:00 +0000" />
         <newznab:attr name="episode" value="7" />
         <torznab:attr name="category" value="5070" />
         <torznab:attr name="files" value="1" />
         <torznab:attr name="size" value="1398901737" />
         <torznab:attr name="infohash" value="ba482d0fe846d37202d7874adbdf6cbd91378e9c" />
         <torznab:attr name="magneturl" value="magnet:?xt=urn:btih:XJEC2D7II3JXEAWXQ5FNXX3MXWITPDU4&amp;tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&amp;tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&amp;tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&amp;tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&amp;dn=Bleach%3A%20Sennen%20Kessen-hen%20-%2007%20%7C%20Bleach%20-%20Thousand%20Year%20Blood%20War%20%5BEnglish%20Dub%5D%5B1080p%5D" />
         <torznab:attr name="seeders" value="50" />
         <torznab:attr name="leechers" value="2" />
         <torznab:attr name="peers" value="52" />
      </item>
```
Now let's look at the spec which calls out size and category are mandatory attributes 

![image](https://user-images.githubusercontent.com/376117/208793654-68ae3f16-4021-4bfc-b6b7-8647dd7317b6.png)

Keeping that in mind, lets look at a MTV item. They define `<category>` but never a category attribute per spec like this `<torznab:attr name="category" value="5070" />` which is what we look for (because it's spec :D)

```
  <item>
    <title>Out of the Past 1947 720p BluRay FLAC2.0 x264-CtrlHD.mkv</title>
    <guid isPermaLink="true">https://www.morethantv.me/torrents.php?id=(removed)&amp;torrentid=836164</guid>
    <link>https://www.morethantv.me/torrents.php?action=download&amp;id=(removed)&amp;authkey=(removed)&amp;torrent_pass=(removed)</link>
    <comments>https://www.morethantv.me/torrents.php?id=(removed)&amp;torrentid=836164</comments>
    <pubDate>Tue, 20 Dec 2022 21:32:17 +0000</pubDate>
    <size>5412993028</size>
    <files>1</files>
    <grabs>2</grabs>
    <category>2000</category>
    <category>2040</category>
    <description>A private eye escapes his past to run a gas station in a small town, but his past catches up with him. Now he must return to the big city world of danger, corruption, double crosses, and duplicitous dames.</description>
    <enclosure url="https://www.morethantv.me/torrents.php?action=download&amp;id=(removed)&amp;authkey=(removed)&amp;torrent_pass=(removed)" length="103641" type="application/x-bittorrent" />
    <torznab:attr name="size" value="5412993028" />
    <torznab:attr name="poster" value="anon" />
    <torznab:attr name="seeders" value="3" />
    <torznab:attr name="leechers" value="0" />
    <torznab:attr name="peers" value="3" />
    <torznab:attr name="infohash" value="(removed)" />
    <torznab:attr name="downloadvolumefactor" value="1" />
    <torznab:attr name="uploadvolumefactor" value="1" />
    <torznab:attr name="tag" value="anonymous" />
    <torznab:attr name="imdb" value="0039689" />
    <torznab:attr name="imdbid" value="tt0039689" />
  </item>
```

**Comment by mynameisbogdan** [comment]
I'm guessing that's the reason Jackett acts like an proxy.

**Comment by Qstick** [comment]
I can patch some code to clean this up, but you should submit another ticket with MTV to fix this as well.

**Comment by Qstick** [comment]
Let's try build 2155 once it's done

**Comment by mynameisbogdan** [comment]
Okay, good morning.

From your commit I'm seeing that MTV has a description but still shows `A Newznab-like api for torrents.`
![Screenshot 2022-12-21 at 12 43 14](https://user-images.githubusercontent.com/707714/208886840-e27595a7-b289-4fd1-8db3-c03b9605c947.jpg)

Their API path is `/api/torznab`, not simply `/api`. But I guess the user can change it if they know it, but it's hidden under `User > Security > Show API Tutorial`. I thought you should know this. 
![Screenshot 2022-12-21 at 12 47 08](https://user-images.githubusercontent.com/707714/208887379-1296a611-1527-4929-954d-48d8f5fcf2d9.jpg)

And the categories are showing now. 👍 
![Screenshot 2022-12-21 at 12 52 52](https://user-images.githubusercontent.com/707714/208888494-d6d1bfd9-99a7-44a8-9e1c-c95ed12042e4.jpg)

**Comment by mynameisbogdan** [comment]
@Qstick - would you like an invitation from MTV for future testing/use?
