### ISSUE TITLE
Tags not working

### ISSUE THREAD

**Issue by abb0r** [Prowlarr/Prowlarr#124]
**Describe the bug**
Adding tags with the mass editor are not added to indexers and give an error message under Settings --> Tags.

**To Reproduce**
1. Go to indexers and select mass editor
2. Add a tag and click apply
3. Tags don't show up in indexer list
4. Under Settings --> Tags I see the tags but when clicking on them I get the "There was an error loading this item" page. Clicking on "Details gives me this this: https://pastebin.com/c1pcmzPm

**Expected behavior**
Tags added correctly to indexers.

**Platform Information (please complete the following information):**
 - OS: unraid 6.9.2
 - Docker: Yes
 - .NET Version: 5.0.6
 - Browser and Version: Firefox 89.0
 - Prowlarr Version: 0.1.0.370
 - Prowlarr Branch: nightly-a5d637c by hotio

[AB#47](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/47)

**Comment by rycore** [comment]
Just to add, same issue on windows.

Docker: No
.NET Version: 5.0.6
Prowlarr Version: 0.1.0.390
Branch: nightly

**Comment by bakerboy448** [comment]
fixed https://github.com/Prowlarr/Prowlarr/commit/7480ebea85843c361052c2e649c336ff553b1e9d

**Comment by Mushin** [comment]
I'm now able to add tags to indexers. However, if I try to limit the indexers to be synced per app using the tags setting in the app settings ("Applies to indexers with at least one matching tag"), the tags are ignored and instead all indexers are synced to the app. 

Prowlar: Version 0.1.0.820, Package Version nightly-24f6efc by hotio.
Sonarr: Version 3.0.3.928, Package Version phantom-27f67f3-130 by hotio

Please let me know if you'd like a new issue to be opened for this.

**Comment by bakerboy448** [comment]
Correct that is expected.

tags for applications - as noted on the wiki - are not currently functional
