### ISSUE TITLE
[PHD] Category "Music" doesn't exist anymore 

### ISSUE THREAD

**Issue by mynameisbogdan** [Prowlarr/Prowlarr#1246]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

There is not category "Music" on PHD anymore, and it's making lidarr to spam it's events log.

Related lines:
https://github.com/Prowlarr/Prowlarr/blob/6bb8c09fcfbca2115b29147333aa78daab7ee69e/src/NzbDrone.Core/Indexers/Definitions/PrivateHD.cs#L44-L47
https://github.com/Prowlarr/Prowlarr/blob/6bb8c09fcfbca2115b29147333aa78daab7ee69e/src/NzbDrone.Core/Indexers/Definitions/PrivateHD.cs#L58

### Expected Behavior

N/A

### Environment

```markdown
- OS: Unraid
- Prowlarr: 0.4.11.2143
- Docker Install: y
- Using Reverse Proxy: n
- Browser: -
```

### What branch are you running?

Develop

### Trace Logs?

N/A

[AB#4512](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4512)

**Comment by Qstick** [comment]
Thanks!
