### ISSUE TITLE
[nebulance] Missing support for search by `tvmazeid`

### ISSUE THREAD

**Issue by mynameisbogdan** [Prowlarr/Prowlarr#1252]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

It seems like the tracker is built around tvmaze and somewhat lacks data to support search only by imdbid.

Related lines:
https://github.com/Prowlarr/Prowlarr/blob/7303cdf555de46e2cb31286b027dffb0a922048e/src/NzbDrone.Core/Indexers/Definitions/Nebulance.cs#L113-L121

### Expected Behavior

I think a solution would be to search only by `TvMazeId` if present, otherwise by `ImdbId` only if the former is empty since they are using the operator `AND` thus would fail if you'll search by both fields.

Something like this (`queryParams.Name` could be improved by checking if `queryParams.Tvmaze` or `queryParams.Imdb` is set):
```csharp
            if (searchCriteria.TvMazeId.HasValue && searchCriteria.TvMazeId > 0)
            {
                queryParams.Tvmaze = searchCriteria.TvMazeId;

                if (searchCriteria.EpisodeSearchString.IsNotNullOrWhiteSpace())
                {
                    queryParams.Name = "%" + searchCriteria.EpisodeSearchString + "%";
                }
            }
            else if (searchCriteria.ImdbId.IsNotNullOrWhiteSpace() && int.TryParse(searchCriteria.ImdbId, out var intImdb))
            {
                queryParams.Imdb = intImdb;

                if (searchCriteria.EpisodeSearchString.IsNotNullOrWhiteSpace())
                {
                    queryParams.Name = "%" + searchCriteria.EpisodeSearchString + "%";
                }
            }
```
And this since `t=tvsearch&q=Head&season=2` fails as well (`{"Age":">0","Name":"%Head S02%"}`):
```diff
            if (searchCriteria.SanitizedTvSearchString.IsNotNullOrWhiteSpace())
            {
-                queryParams.Name = "%" + searchCriteria.SanitizedTvSearchString + "%";
+                queryParams.Name = "%" + Regex.Replace(searchCriteria.SanitizedTvSearchString, @"[ -._]", "%").Trim() + "%";
            }

            if (searchCriteria.SanitizedSearchTerm.IsNotNullOrWhiteSpace())
            {
-                queryParams.Name = "%" + searchCriteria.SanitizedSearchTerm + "%";
+                queryParams.Name = "%" + Regex.Replace(searchCriteria.SanitizedSearchTerm, @"[ -._]", "%").Trim() + "%";
            }
```

### Steps To Reproduce

Searching from Sonarr would search first by `t=tvsearch&imdbid=8290362&season=2` and then `&t=tvsearch&q=Head+2020&season=2`, both failing to find anything since they don't have the year in the name. `&t=tvsearch&q=Head&season=2` fails too.

### Environment

```markdown
- OS: Unraid
- Prowlarr: 0.4.11.2143
- Docker Install: Y
- Using Reverse Proxy: -
- Browser: -
```

### What branch are you running?

Develop

### Trace Logs?

https://privatebin.net/?bb010d4b60e32029#2o1LNXbrhx291Bj8S7TJXHKhA4nt4tbrarsPKaNSCqBN

[AB#4526](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4526)

**Comment by Qstick** [comment]
Curious, Are they accepting `imdb` as just the int, or the full string with `tt` on front?

**Comment by Qstick** [comment]
Sure, qstick @ protonmail.com
