### ISSUE TITLE
0.4.11.2143 incorrectly labels AnimeTosho as Other/5999

### ISSUE THREAD

**Issue by datcactus** [Prowlarr/Prowlarr#1253]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After upgrading from 0.4.10.2111 to 0.4.11.2143, AnimeTosho Torznab no longer registers itself as TV/5070, but Other/5999. This prevents it from being used in something like Sonarr for anime category searches, and as such is a breaking change.

### Expected Behavior

AnimeTosho maintains its usual TV/5070 capabilities.

### Steps To Reproduce

1. Upgrade to Prowlarr 0.4.11.2143
2. Attempt to search on Sonarr for any anime that previously was searchable
3. Observe that no results are generated as the indexer no longer has 5070 as a capability
4. Observe that if you edit->save the AnimeTosho indexer in Prowlarr it changes the capability tag from TV/5070 to Other/5999

### Environment

```markdown
- OS: Ubuntu Server 22.04.1 LTS
- Prowlarr: 0.4.11.2143
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 108.0.1
```

### What branch are you running?

Develop

### Trace Logs?

https://gist.github.com/datcactus/35a623bca3ea1551980d441123bd757d

[AB#4527](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4527)

**Comment by Qstick** [comment]
Already fixed

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/6636cbc4aea7204613f915fb51645f2a03c1ce04
