### ISSUE TITLE
Show Ratio 

### ISSUE THREAD

**Issue by techguruz** [Prowlarr/Prowlarr#1257]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Would be nice if you could see your ratio and a few other stat maybe user group currently seeding/leeching.

### Describe the solution you'd like

It should be pretty easy to scrape at the very least your ratio but since most trackers use the same framework ratio leeching/seeding should be able to be pulled too maybe even more stuff. Once it has been scraped it could be saved to a database then displayed on the stats page to you can see your upload/download amount and ratio change since the last time you viewed or maybe weekly/monthly scrape so your not constantly hitting the trackers up for that info. 

### Describe alternatives you've considered

I have previously used pt-plugin-pro.

### Anything else?

https://github.com/pt-plugins/PT-Plugin-Plus

[AB#4547](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4547)

**Comment by Qstick** [comment]
Covered by #1203
