### ISSUE TITLE
Mobile UI bugs

### ISSUE THREAD

**Issue by d3mystified** [Prowlarr/Prowlarr#1267]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Mobile UI has a few bugs:

- Save and grab buttons don't do anything
- Sorting doesn't work
- Results should be clickable and take you to the indexer page. Doesn't.

### Expected Behavior

Those bugs shouldn't be there

### Environment

```markdown
- OS: Ubuntu
- Prowlarr: 1.0.0.2171
- Docker Install:1.0.0.2171-ls80
- Using Reverse Proxy:
- Browser: brave on Android
```

### What branch are you running?

Master

### Trace Logs?

Not relevant here.

[AB#4566](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4566)

**Comment by malventano** [comment]
Can confirm the same, but for amplifying info it only happens on mobile / with a desktop window small enough to shift the UI to the other mode. In the smaller mode, grab buttons and sort is broken (download buttons did work here). On desktop, resizing larger again resulted in sort/grab buttons once again working.

**Comment by tchirou** [comment]
For now, I have found a workaround. I do a search, i click on the sort setting I want, I randomly pick a filter, the list is now sorted, I just have to go back to the « all » filter

**Comment by bakerboy448** [comment]
- grabs fixed https://github.com/Prowlarr/Prowlarr/commit/6ce9e5ceb9763aeae6525a44b160f3cf9f09c4dd

**Comment by Qstick** [comment]
4175c2577ef78bd0afc52869358cada403f8ce7f
f386ddb80657d7d0f961f1d7ddf58e7379195aed
