### ISSUE TITLE
New Authentication Requirement Breaks Clean usage experience when paired with Authelia

### ISSUE THREAD

**Issue by deathbybandaid** [Prowlarr/Prowlarr#1269]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The consistancy of using Authelia for authentication in front of Prowlarr is now a broken experience. With the forced authentication from Prowlarr, I have 2 options

1) remove Authelia from the mixture and no longer have a nice SSO/2FA guarding prowlarr, and a seperate prowlarr password
2) Authenticate with both Authelia and prowlarr

Neither option is optimal.

### Expected Behavior

Using a reverse proxy (nginx) and setting Authelia as an authentication backend simplifies the authentication with most of my selfhosted apps including the *arrs. This allows me to use SSO and 2FA to access my services remotely.

Please don't force prowlarr credentials, or find a way to directly integrate services like Authelia, Keycloak, Authentik as authentication providers.

Alternatively allow advanced users to bypass this behavior with a config file setting that isn't available from the web interface.

### Environment

```markdown
- OS: Ubuntu
- Prowlarr: 1.0.0.2171
- Docker Install: no
- Using Reverse Proxy: yes
- Browser: firefox
```

### What branch are you running?

Develop

### Trace Logs?

N/A

[AB#4571](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4571)

**Comment by Roxedus** [comment]
https://wiki.servarr.com/prowlarr/faq#can-i-disable-forced-authentication

**Comment by bakerboy448** [comment]
> Alternatively allow advanced users to bypass this behavior with a config file setting that isn't available from the web interface.

See the FAQ.

Duplicate of https://github.com/Prowlarr/Prowlarr/issues/1265

> Report a new bug, if you are not 100% certain this is a bug **please go to our Reddit or Discord first**

**Comment by deathbybandaid** [comment]
thanks @Roxedus
