### ISSUE TITLE
Basic Auth Header missing on LAN if Host is used - Search result disappearing after a few seconds

### ISSUE THREAD

**Issue by danielb2** [Prowlarr/Prowlarr#1282]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I search for something, and after a few seconds the results disappears from the search result page saying no results found.

With help from bakerboy448 who noticed "Failure message: Authorization header missing" in my trace logs I tried a few things and found the issue.

- I had a hostname set in my `/etc/hosts` file to be an alias to the IP address. 
- Local authentication was disabled.
- Authentication method irrelevant

Changing the hostname to the actual IP address solved it.

IOW:

- http://192.168.0.9:9696/search  ✅
- http://host:9696/search ❌️

### Expected Behavior

search results should stay

### Steps To Reproduce

1. mod `/etc/hosts` to use an alias for IP
2. access a local client using the alias
3. do a search

### Environment

```markdown
- OS: linuxserver docker
- Prowlarr: 1.0.0.2171-ls80 by linuxserver.io
- Docker Install: Yes - https://hub.docker.com/r/linuxserver/prowlarr
- Using Reverse Proxy: Nein und nein!
- Browser: Brave of course
```

### What branch are you running?

Develop

### Trace Logs?

```
2023-01-03 13:13:11.7|Debug|Api|[GET] /api/v1/log/file: 200.OK (3 ms)
2023-01-03 13:13:14.0|Trace|Http|Req: 3763 [GET] /logfile/prowlarr.trace.txt (from 172.17.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
2023-01-03 13:13:14.0|Info|Prowlarr.Http.Authentication.BasicAuthenticationHandler|Basic was not authenticated. Failure message: Authorization header missing.
```

[AB#4622](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4622)

**Comment by brianturnersaturn** [comment]
has this been resolved? I am seeing the same issue.

**Comment by danielb2** [comment]
> Are you sure it's not related to the fact the offset is changed from 0 to 100, thus breaking pagination if your indexers doesn't support it?
> 
> Please check again and provide longer trace logs.

100% certain. And Bakerboy helped me triage this initially

**Comment by hypnosu** [comment]
I have this issue when trying to add to client. On second attempt it works, but after awhile breaks again.

**Comment by danielb2** [comment]
@mynameisbogdan  can you tell me what you did to reproduce?

**Comment by Dulanic** [comment]
Was wondering why I was seeing this so often. My connections to sonarr via http are across docker containers and thus dont use https. Not sure whats trying to access it, but the only culprits would be Caddy for my reverse proxy, Overseerr, or Unpackerr. However, none of those look to be having any errors....

**Comment by Dulanic** [comment]
It seems to be a arr thing? Maybe its just using the docker names? Im seeing it in prowlarr too.
```
[Info] Prowlarr.Http.Authentication.BasicAuthenticationHandler: Basic was not authenticated. Failure message: Authorization header missing.
[Info] Prowlarr.Http.Authentication.BasicAuthenticationHandler: Basic was not authenticated. Failure message: Authorization header missing.
```

**Comment by snickers2k** [comment]
same problem here... don't know whats causing it...
