### ISSUE TITLE
[Cardigann] "requestDelay" not supported? 

### ISSUE THREAD

**Issue by mynameisbogdan** [Prowlarr/Prowlarr#1287]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

[Wiki](https://wiki.servarr.com/prowlarr/cardigann-yml-definition#header) says that it supports `requestDelay`, but I didn't find anything in the code to back this affirmation up. 

This it's a little tricky because it's necessary with some trackers that rate limit you even on browsing/scraping, not necessary just on API use.

### Expected Behavior

`requestDelay` to be supported.

### Environment

```markdown
- OS: unraid
- Prowlarr: 1.0.1.2220
- Docker Install: Y
- Using Reverse Proxy: -
- Browser: -
```

### What branch are you running?

Develop

### Trace Logs?

N/A

[AB#4631](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4631)

**Comment by Qstick** [comment]
Good call on the tracking issue here, as honestly I'd forgotten about this. You are correct in that currently Cardigann just uses the default `HttpIndexerBase` RateLimit of 2 Sec for Indexer searches. One of those "we'll get it to it eventually" fixes when we first wrote our Cardigann implementation.
