### ISSUE TITLE
gay-torrents.org error

### ISSUE THREAD

**Issue by stitchemd** [Prowlarr/Prowlarr#1289]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Received Error "Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc." 

Confirmed accurate username and password and website address

### Expected Behavior

Expected to be able to add and login to tracker

### Steps To Reproduce

Go through steps to add tracker

### Environment

```markdown
- OS: Ubuntu 18.04
- Prowlarr:1.0.1.2220
- Docker Install:Yes
- Using Reverse Proxy:Yes
- Browser:Chrome
```

### What branch are you running?

Master

### Trace Logs?

02:44 | ProwlarrErrorPipeline | Invalid request Validation failed: -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc. |  

02:44 | ProwlarrErrorPipeline | FluentValidation.ValidationException: Validation failed: -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc.: Validation failed: -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc. |  

02:44 | Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware | An unhandled exception has occurred while executing the request.: Validation failed: -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc. |  

02:44 | Cardigann | Adding request: https://gay-torrents.org/torrents_beta.php?search=&active=0&options=0&order=data&by=desc

[AB#4645](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4645)

**Comment by bakerboy448** [comment]
> Trace Logs (https://wiki.servarr.com/prowlarr/troubleshooting#logging-and-log-files)
Generally speaking, all bug reports must have trace logs provided.

**Comment by justkorix** [comment]
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/10562793/prowlarr.trace.txt)
I'm having the same issue. Here are my trace logs

**Comment by bakerboy448** [comment]
> [prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/10562793/prowlarr.trace.txt)
> I'm having the same issue. Here are my trace logs

Doesn't seem to be a prowlarr issue

`<div class="error_header">Error:You're not authorized to view this Torrents!</div><div >Sorry...</div>`

Contact the tracker for support.

**Comment by justkorix** [comment]
Ah! Thank you for seeing that. I've contacted them, will come back and close with their reply

**Comment by bakerboy448** [comment]
closing; last updated indicated the tracker responded with not auth to view the torrents

can reopen if/when new information is available that indicates this is a prowlarr issue
