### ISSUE TITLE
Couldn't add report to download queue. <Torrent Name>: Invalid torrent file specified. 

### ISSUE THREAD

**Issue by JourneyOver** [Prowlarr/Prowlarr#129]
**Describe the bug**

Seems that prowlarr is returning 0 bytes for torrents from IPtorrents (not sure if this is the case for other trackers or not yet as I have only tested with IPtorrents so far)

**To Reproduce**

For sonarr to be able to pull the information correctly on a torrent so that it can be added to my download client.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS:  Windows 10 21H1
 - Docker:  NO
 - .NET Version (System -> Status):  5.0.6
 - Browser and Version (Only needed for UI issues): 
 - Prowlarr Version:  0.1.0.371
 - Prowlarr Branch:  nightly

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

Sonarr: https://paste.ee/p/UArer (error is near the bottom)
Prowlarr: https://paste.ee/p/sKsra

**Comment by Qstick** [comment]
Fixed in c61c3a9c456bec22dc57bd26956f3511541e5f96
