### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by jacovdyk** [Prowlarr/Prowlarr#1292]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Prowlarr won't start.

### Expected Behavior

Prowlarr should start.

### Steps To Reproduce

1. Raspberry Pi 3 Model B V1.2(Both on Raspberry Pi OS & DietPi).
2. With these steps:
https://wiki.servarr.com/prowlarr/installation#debian-ubuntu-hands-on-install
3. Device architecture: 
root@download:~# dpkg --print-architecture
arm64

Initially, no ICU package was installed, I installed:
 sudo apt-get install -y libicu-dev
 
 Prowlarr fails to start - new systemctl output attached.
[systemctl_output.txt](https://github.com/Prowlarr/Prowlarr/files/10355295/systemctl_output.txt)

### Environment

```markdown
- OS: DietPi_RPi-ARMv8-Bullseye & Raspberry Pi OS (64-bit) Lite
- Prowlarr: Prowlarr.master.1.0.1.2220.linux-core-arm64.tar.gz
- Docker Install: No
- Using Reverse Proxy: No
- Browser: n/a
```

### What branch are you running?

Master

### Trace Logs?

No log files to attach as application doesn't start.the 

[AB#4647](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4647)

**Comment by bakerboy448** [comment]
This has only been seen when required dotnet dependencies are missing.  Likely due to decisions made by dietpi.

https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian#dependencies

**Comment by MichaIng** [comment]
It is nearly assured to be this bug in .NET, solved with a downgrade to a specific v6 or upgrade to v7: https://github.com/dotnet/runtime/issues/79796

See also same problem with Jackett .NET variant: https://github.com/Jackett/Jackett/issues/13806

**Comment by MichaIng** [comment]
Right, SDK v6.0.403 / runtime v6.0.11 worked in the affected cases.

Ah, I have a new old SBC here, probably I am finally able to reproduce the issue and hence test fixes/binaries.

**Comment by Qstick** [comment]
Was it fixed in .13?

**Comment by MichaIng** [comment]
Indeed it seems to have been. This is the reason why I was not able to replicate it with .NET SDK/runtime alone, as I downloaded v6.0.13. I can replicate it with the `dotnet` executable of the SDK alone when using v6.0.404/6.0.12. Interestingly, with the runtme alone (without SDK), no segfault happens.

I'll do some more tests to narrow it down. If you do some v6.0.405/6.0.13 based Prowlarr build, I can test it ASAP.

**Comment by Qstick** [comment]
I'll trigger it in an hour

**Comment by Qstick** [comment]
560cda8ba0

**Comment by Qstick** [comment]
Lets try build 1.1.2.2419 on nightly.

**Comment by MichaIng** [comment]
There is not yet a build with this change available, or do I overlook something? Else, let me know where to download it from and I can test 🙂.

**Comment by Qstick** [comment]
It's been available on nightly, but is dependent on which branch you are on. It just went to develop branch tonight.

**Comment by MichaIng** [comment]
Prowlarr [1.1.2.2453](https://github.com/Prowlarr/Prowlarr/releases/tag/v1.1.2.2453) works fine 👍.
