### ISSUE TITLE
Can't Add Btschool

### ISSUE THREAD

**Issue by ibigbug** [Prowlarr/Prowlarr#1302]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

the recaptcha can't be displayed

<img width="495" alt="image" src="https://user-images.githubusercontent.com/543405/211197292-6ba6e35f-2b5a-45c1-a241-d9437b075dfe.png">

doesn't show the captcha image:

<img width="439" alt="image" src="https://user-images.githubusercontent.com/543405/211197360-f4a6aa04-7bdc-43d1-9590-67ebd33af108.png">

### Expected Behavior

the recaptcha image should be displayed

I have flare_resolver enabled with the tag `all` however in the log it doesn't really show flare_resolver is requested.

### Environment

```markdown
- OS: portainer
- Prowlarr: 1.0.1.2220
- Docker Install: Yes
```

### What branch are you running?

develop

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/10368473/prowlarr.trace.txt)

[AB#4662](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4662)

**Comment by bakerboy448** [comment]
Logs provided are some html, not the required trace logs

**Comment by ibigbug** [comment]
@bakerboy448 thank you i think i uploaded the wrong file.
