### ISSUE TITLE
Add Option to Specify LAN IPs for auth disable local address

### ISSUE THREAD

**Issue by shadofall** [Prowlarr/Prowlarr#1323]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Running Prowler on kubernetes means its using and detecting an internal network range that is different from my regular LAN range  so setting auth to ignore local addresses does not include my lan IP Range, 

### Describe the solution you'd like

I'd Like to see an option to Specify Trusted IP ranges that would be taken in to consideration when disable for local address is selected

### Describe alternatives you've considered

N/A

### Anything else?

N/A

[AB#4709](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4709)

**Comment by shadofall** [comment]
disregard for now. its now all of a sudden recognizing my LAN Despite the application being on a 172 address in the k8s clusters and my lan being a 192 range.

**Comment by bakerboy448** [comment]
> e so setting auth to ignore local addresses does not include my lan IP Range

the logic does not consider if its the same lan, just if it's a LAN/private address

```
if (_authenticationRequired == AuthenticationRequiredType.DisabledForLocalAddresses)
             {
                 if (context.Resource is HttpContext httpContext &&
                     IPAddress.TryParse(httpContext.GetRemoteIP(), out var ipAddress) &&
                     ipAddress.IsLocalAddress())
                 {
                     context.Succeed(requirement);
                 }
             }

             return Task.CompletedTask;
         }
         ```
https://github.com/Prowlarr/Prowlarr/commit/c7eb08a0f024cbed8531d46eaf1029b267d52837#diff-dcac3483b5f1b1b83fb74093df5ccbd4e14e9ea996421ec5f888c2d72c266ae7R31
https://github.com/Prowlarr/Prowlarr/commit/1c125733b2100bd841c1eb0cc3ca37618dad5ce0
