### ISSUE TITLE
Hawke-uno throws an error in Radarr when 'freeleech only' is enabled

### ISSUE THREAD

**Issue by BadJanitor** [Prowlarr/Prowlarr#1340]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I configured hawke-uno and enabled 'search freeleech only'.  Testing the indexer succeeds, however when it's sync'd to Radarr the indexer returns the following error:

`Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings.`

With freelech disabled on the indexer it works fine.  It also works in Sonarr.

### Expected Behavior

Indexer tests successfully with Freelech enabled

### Steps To Reproduce

1. Configure hawke-uno indexer in Prowlarr and select 'search freelech only'
2. Save and sync the indexer to Radarr
3. In Radarr, edit the settings of the indexer and click Test

### Environment

```markdown
- OS:Unraid 6.11.5
- Prowlarr: 1.1.0.2322
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 108.0.2
```

### What branch are you running?

Develop

### Trace Logs?

[radarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/10447355/radarr.trace.txt)
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/10447356/prowlarr.trace.txt)
![image](https://user-images.githubusercontent.com/22528339/213198721-a8072f3c-2c3b-436b-baee-98037262c8e0.png)

[AB#4756](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4756)

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/radarr/troubleshooting#query-successful-no-results-returned
