### ISSUE TITLE
Indexer - SDBits - Unable to Add - Redirected to Domain

### ISSUE THREAD

**Issue by HamilcarH** [Prowlarr/Prowlarr#135]
**Describe the bug**

SDBits indexer can't be added.

**To Reproduce**

Add SDBits as an indexer. Enter the relevant information, press the test button.

**Expected behavior**

After entering the relevant information, the indexer should pass the test.

**Platform Information (please complete the following information):**
 
- OS: Unraid 6.9.2
 - Docker: Yes, 20.10.5
 - .NET Version (System -> Status): 5.0.6
 - Prowlarr Version: 0.1.0.361
 - Prowlarr Branch: develop

log: https://pastebin.com/X5kNGF07

**Comment by Qstick** [comment]
Let's try 413

**Comment by BEisem** [comment]
Fixed for me in 413.

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/9ac435bc41b6ead3874f8d17148f9971444288b9
