### ISSUE TITLE
Indexer - Orpheus - Add 2FA / APIKey support

### ISSUE THREAD

**Issue by kccorl1993** [Prowlarr/Prowlarr#137]
**Describe the bug**
Adding Orpheus, when 2FA is enabled, fails with `Unable to connect to indexer. Unexpected response status Redirect code from API request`

**To Reproduce**
1. Go to `Add Indexer`
2. Search `Orpheus`
3. Select Orpheus
4. Fill out Username and Password
5. Click `Test`
6. Receive error `Unable to connect to indexer. Unexpected response status Redirect code from API request`

**Expected behavior**
Orpheus is added to the indexer list

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker: No
 - .NET Version (System -> Status): 5.0.6
 - Prowlarr Version: 0.1.0.361
 - Prowlarr Branch: nightly

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
https://pastebin.com/XYd2VzP6

**Note**
I did log in with the credentials used on Orpheus itself, so the HTML returned is definitely due to my 2FA as referenced.

[AB#49](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/49)

**Comment by bakerboy448** [comment]
I'm assuming still an issue on the 6XX builds?

**Comment by kccorl1993** [comment]
@bakerboy448 just updated to latest (0.1.0.640) and still the same error message.

**Comment by toconquer** [comment]
I'm receiving this error also on both Orpheus and Redacted, both of them have 2FA enabled.

**Comment by crafty35a** [comment]
> I'm receiving this error also on both Orpheus and Redacted, both of them have 2FA enabled.

Prowlarr does not currently support the Orpheus API key method, so you will not be able to use it yet with 2FA enabled. Redacted API key support was just added to nightly.

**Comment by micah** [comment]
I have 2FA disabled, and I get the error.

I tried with password, as well as the API key.

**Comment by kccorl1993** [comment]
Is this, by chance, on the radar for prowlarr?  It's not preventing me from using it, but would be nice to have.

Thanks!

**Comment by bakerboy448** [comment]
> Is this, by chance, on the radar for prowlarr? It's not preventing me from using it, but would be nice to have.
> 
> Thanks!

It is open and not closed; so yes

**Comment by micah** [comment]
On 2021-08-14 18:35:47, bakerboy448 wrote:
> It is open and not closed; so yes

thanks!

**Comment by bakerboy448** [comment]
Seems we have several 6/5 commits Jackett made that we may need to pull?

among them: adding APIKey support
https://github.com/Jackett/Jackett/commits/c5283113c577c4880fdc7d1ef272c1b7d31273c6/src/Jackett.Common/Indexers/Orpheus.cs

**Comment by fana13** [comment]
Hi,

Could you add the API key support please like jackett ?
Thanks a lot !

**Comment by kccorl1993** [comment]
> 
> 
> Hi,
> 
> Could you add the API key support please like jackett ?
> Thanks a lot !

Not a developer for this project, but I am one in general.  They have stated they know the issue and this is on their radar.  In most cases, badgering like this will not get it done any quicker, and in some cases (not suggesting they'd do this), it in fact reduces their motivation to do so.  Be patient and understand this is still beta (maybe alpha?) software that has a lot of bugs to work through and has daily releases, so not every bug can be done as soon as it is discovered.

**Comment by Qstick** [comment]
@bakerboy448 this still broken?

**Comment by bakerboy448** [comment]
> @bakerboy448 this still broken?
> 
> 

Can't test, but I'd assume so?
Vaugely recall it recently mentioned in discord?

**Comment by klepp0906** [comment]
@Qstick yes, i just got in there and excitedly added it to prowlarr only to have my dreams crushed :P

**Comment by chansearrington** [comment]
+1 would really like this supported.

**Comment by kccorl1993** [comment]
> +1 would really like this supported.

Fingers crossed it can be addressed. I have been patiently waiting and it's more of an inconvenience than anything, but it would still be nice.

**Comment by fana13** [comment]
> > +1 would really like this supported.
> 
> Fingers crossed it can be addressed. I have been patiently waiting and it's more of an inconvenience than anything, but it would still be nice.

it's not considering like badgering in this case for you ? ...
Anyway it would be really great if API was supported

**Comment by kccorl1993** [comment]
> > > +1 would really like this supported.
> > 
> > 
> > Fingers crossed it can be addressed. I have been patiently waiting and it's more of an inconvenience than anything, but it would still be nice.
> 
> it's not considering like badgering in this case for you ? ... Anyway it would be really great if API was supported

Saw it as more of mentioning the issue is getting more eyes, whereas your comment was a redundant request based on what a dev already suggested within a month of their comment. This one came a year after that and wasn't necessarily a call to action.

**Comment by kccorl1993** [comment]
Validated on Nightly, and appears to connect. Thank you guys so much for your time and effort :)
