### ISSUE TITLE
(Indexer) - Torrent - mma-tracker.net

### ISSUE THREAD

**Issue by rreveley** [Prowlarr/Prowlarr#138]
**Type:** Torrents
**Tracker:** mma-tracker.net
**URL:** mma-tracker.net
**In Jackett?:** No

**Comment by bakerboy448** [comment]
can you please fill out the template you nuked....and fix the title you also nuked

`(Indexer) mma-tracker.net`

```
<!-- Check the pinned Jackett parity issue prior to submitting a request. Duplicated requests or requests covered in existing GitHub Issues will be closed without warning. Please search GitHub prior to requesting.->
**Type:** <Usenet|Torrents>
**Tracker:** <Indexer/Tracker Name>
**URL:** <Indexer/Tracker URL>
**In Jackett?:** <Yes|No>

**Additional context**
<!-- Add any other context or screenshots about the request here. -->
```

**Comment by bakerboy448** [comment]
Fixed up, thanks for pointing it out! :)

the html code is to ensure additional information users should know is front and center

**Comment by rreveley** [comment]
I can send an invite. What email address should I send it to?

**Comment by bakerboy448** [comment]
https://requests.prowlarr.com/b/feedback/p/torrent-mma-tracker-net
