### ISSUE TITLE
Servarr update API reports wrong branch name after develop->master switch

### ISSUE THREAD

**Issue by frebib** [Prowlarr/Prowlarr#1397]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

https://prowlarr.servarr.com/v1/update/develop?version=0.0&os=linux&runtime=netcore&arch=x64

Reports `branch: develop` even though the download URL has branch as master

### Expected Behavior

Branch is reported as `master` to match the download URL

### Environment

```markdown
N/A
```

### What branch are you running?

Master

### Trace Logs?

N/A

[AB#4861](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4861)

**Comment by Qstick** [comment]
This is intentional. Every `master` release creates a release in both the `master` and `develop` release channels. The `branch: develop` in that response is the release channel, however the file name is based on the github branch. Just like you see `develop` in the file names for `nightly` release channel releases.

**Comment by frebib** [comment]
We're using the `branch` to template the branch name in the release URL. For example
https://github.com/Prowlarr/Prowlarr/releases/tag/v1.1.3.2521 is commit 1a339b9ab22729e409618595271275ab449b52ac which is on the branch `develop` even though all of the download URLs use `master`: https://github.com/Prowlarr/Prowlarr/releases/download/v1.1.3.2521/Prowlarr.master.1.1.3.2521.linux-musl-core-x64.tar.gz

Is it an incorrect assumption to want to template the URL like this? Perhaps `branch` is a misleading term in this context.
