### ISSUE TITLE
Add Indexer - Torrent - RevolutionTT

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#14]
**Type:** Torrent
**Tracker:** RevolutionTT
**URL:** <https://revolutiontt.me/>
**In Jackett:** Yes

[Reference](https://discord.com/channels/767843854736949299/815273658774978591/815310734056620073)

**Comment by Qstick** [comment]
https://github.com/Prowlarr/Prowlarr/commit/696489731b6176316e8832f41fac63844505c9b4
