### ISSUE TITLE
LostFilm.tv (Indexer) 

### ISSUE THREAD

**Issue by beastlordalex** [Prowlarr/Prowlarr#141]
**Type:** Torrents
**Tracker:** LostFilm.tv
**URL:** https://www.lostfilm.tv/
**In Jackett?:** Yes

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/issues/29

> Request an indexer for Prowlarr. **Check the pinned Jackett parity issue prior to submitting a request.** Duplicated requests will be closed without warning. Please search GitHub prior to requesting.
