### ISSUE TITLE
Reading size and freeleech attributes for torrent-explosiv tracker not working

### ISSUE THREAD

**Issue by ShaggaSonOfDolf** [Prowlarr/Prowlarr#1414]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Prowlarr seems to be unable to extract torrent size and freeleect attributes for the Torrent-Explosiv tracker

### Expected Behavior

Prowlarr should be able extract torrent size and freeleect attributes for the Torrent-Explosiv tracker

### Steps To Reproduce

Add Torrent-Explosiv as a tracker and search for a torrent

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: 1.1.3.2521
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome 108.0.5359.124
```

### What branch are you running?

Master

### Trace Logs?

![image](https://user-images.githubusercontent.com/85927901/217795325-61670bd3-bcb8-439c-a5f1-d751fa157ed2.png)

[AB#4888](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4888)

**Comment by bakerboy448** [comment]
A screenshot of the results is not the trace logs that are required for bug reports. 

Given this is also an issue with parsing, when providing the trace logs the indexer response will also be needed.

Please see the wiki the bug report template linked for details and provide the required information

**Comment by bakerboy448** [comment]
![image](https://user-images.githubusercontent.com/55419169/217865721-a2149dc7-9f99-4140-970f-9c1c5a3c53f4.png)

**Comment by bakerboy448** [comment]
@ilike2burnthing FYI; response above

**Comment by ilike2burnthing** [comment]
Size is an easy enough fix, `_ag` has changed to `_ad`.

However, I can't find any freeleech/onlyup torrents to check if the selector is correct. @ShaggaSonOfDolf please provide an example. Or if you have to purchase freeleech/onlyup using bonus points, please provide an HTML dump for the search results page for a torrent on which you have freeleech/onlyup.

**Comment by ShaggaSonOfDolf** [comment]
Hi,

I did some research. As far I can see it right now the tracker offers no torrent specific freeleech tag in the search results list. Only after having a look on the torrent page itself a 'onlyup' tag indicates that this torrent is actually a freeleech torrent. But right now all torrents are freeleech, I think the 'onlyup' banner above the results is signaling that. So I guess a freelech flag in prowlarr is not possible for this page?

Just for my interest: Where do you make those changes? Could I myself add support for trackers I find to be missing?

Thanks

**Comment by ilike2burnthing** [comment]
If there's a global freeleech without an indicator on torrent results, then as it's a YAML indexer there's no way to way to show this in Jackett or Prowlarr.

I've added the fix to indexer for the size selector (see link above). It will be available in Jackett in ~18hrs and in Prowlarr after the next Cardigann definitions merge (they happen every few days to a week).

If you wish to contribute, YAML indexers would be submitted to https://github.com/Prowlarr/Indexers or Jackett, whereas C# ones would be submitted here.

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/364eefc9cfbbbb9a1dc962bbedd00335ad7a5753
