### ISSUE TITLE
PornoLab.net (Indexer) 

### ISSUE THREAD

**Issue by beastlordalex** [Prowlarr/Prowlarr#142]
**Type:** Torrents
**Tracker:** http://pornolab.net/forum/tracker.php
**URL:** http://pornolab.net/forum/index.php
**In Jackett?:** Yes

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/issues/29

> Request an indexer for Prowlarr. **Check the pinned Jackett parity issue prior to submitting a request.** Duplicated requests will be closed without warning. Please search GitHub prior to requesting.
