### ISSUE TITLE
Categories - major categories aren't selected by default in Sonarr/Radarr

### ISSUE THREAD

**Issue by Beersteddy** [Prowlarr/Prowlarr#1421]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Categories like "TV Packs" aren't selected by default in Sonarr

The same goes for movies X265 etc  in Radarr

### Expected Behavior

All Movie related categories selected by default for Radarr, TV for Sonarr

### Steps To Reproduce

1. Add to Prowlarr a well-known tracker with many categories.
2. Check in Sonarr / Radarr which categories selected
3. Many TV categories will not be chosen by default

![image](https://user-images.githubusercontent.com/91010735/218269482-0a88307f-1ee4-4aa4-b7e6-9fffd20fbaac.png)

### Environment

```markdown
- OS: Unraid
- Prowlarr: latest
- Docker Install: linuxserver io
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

...

[AB#4896](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4896)

**Comment by bakerboy448** [comment]
- latest is not a prowlarr version
- Prowlarr syncs the categories the user tells it to and has normal defaults https://github.com/Prowlarr/Prowlarr/blob/b5e43e7a1a89ab950c4faed978b021ec2264cdad/src/NzbDrone.Core/Applications/Sonarr/SonarrSettings.cs#L25
- Indexer custom categories like the one indicate will need to have that standardized category selected if the user wants it to be synced
