### ISSUE TITLE
Generated Torznab invalid XML due to unescaped ampersands "&"

### ISSUE THREAD

**Issue by ghoto** [Prowlarr/Prowlarr#1425]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The generated torznab which has an XML format doesn't comply with RSS standards. The character & which appears on URLs has to be escaped as `&amp;` in order to be a valid XML. 

### Expected Behavior

The torznab generated by Prowlarr has to be a valid XML document. This means it should not contain unescaped characters like ampersand.

### Steps To Reproduce

All Torznab contain links to Prowlarr that have ampersand.

### Environment

```markdown
- OS: Linux
- Prowlarr: 1.1.2.2394
- Docker Install: Yes
- Using Reverse Proxy: N/A
- Browser: N/A
```

### What branch are you running?

Master

### Trace Logs?

This is a sample Torznab produced by Prowlarr. It is not valid XML.
```
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed" version="1.0">
<channel>
<atom:link rel="self" type="application/rss+xml"/>
<title>Prowlarr</title>
<item>
<title>[Yameii] Shin Shinka no Mi - Shiranai Uchi ni Kachigumi Jinsei - 01 | The Fruit of Evolution 2 - Before I Knew It, My Life Had It Made [English Dub] [CR WEB-DL 1080p] [06235E97]</title>
<description/>
<guid>https://nyaa.si/download/1630242.torrent</guid>
<prowlarrindexer id="8">Nyaa.si</prowlarrindexer>
<comments>https://nyaa.si/view/1630242</comments>
<pubDate>Fri, 27 Jan 2023 22:45:00 +0000</pubDate>
<size>1395864320</size>
<link>http://localhost:9696/prowlarr/8/download?apikey=REDACTED&link=Yldkcmh4anIrWjhlWml5VDNBelZWbEdIUGdsVkV0RVE2VC9rcDREYkw3bnQ1Tk5pbUpwNkJDckQ0QzYyNGR5TDcxZXJDT2VlMUd2b3FuUEl1emFWZXc9PQ&file=%5BYameii%5D+Shin+Shinka+no+Mi+-+Shiranai+Uchi+ni+Kachigumi+Jinsei+-+01+%7C+The+Fruit+of+Evolution+2+-+Before+I+Knew+It%2C+My+Life+Had+It+Made+%5BEnglish+Dub%5D+%5BCR+WEB-DL+1080p%5D+%5B06235E97%5D</link>
<category>5070</category>
<category>127720</category>
<category>2020</category>
<enclosure url="http://localhost:9696/prowlarr/8/download?apikey=REDACTED&link=Yldkcmh4anIrWjhlWml5VDNBelZWbEdIUGdsVkV0RVE2VC9rcDREYkw3bnQ1Tk5pbUpwNkJDckQ0QzYyNGR5TDcxZXJDT2VlMUd2b3FuUEl1emFWZXc9PQ&file=%5BYameii%5D+Shin+Shinka+no+Mi+-+Shiranai+Uchi+ni+Kachigumi+Jinsei+-+01+%7C+The+Fruit+of+Evolution+2+-+Before+I+Knew+It%2C+My+Life+Had+It+Made+%5BEnglish+Dub%5D+%5BCR+WEB-DL+1080p%5D+%5B06235E97%5D" length="1395864320" type="application/x-bittorrent"/>
<torznab:attr name="category" value="5070"/>
<torznab:attr name="category" value="127720"/>
<torznab:attr name="category" value="2020"/>
<torznab:attr name="tag" value="freeleech"/>
<torznab:attr name="seeders" value="1"/>
<torznab:attr name="grabs" value="0"/>
<torznab:attr name="peers" value="4"/>
<torznab:attr name="infohash" value="ad512df55d635ba3a3f6fb1d4676fc9c5f43396e"/>
<torznab:attr name="downloadvolumefactor" value="0"/>
<torznab:attr name="uploadvolumefactor" value="1"/>
</item>
</channel>
</rss>
```

**Comment by bakerboy448** [comment]
it's just `link` that is invalid, correct?

looks like encoding the `&` here https://github.com/Prowlarr/Prowlarr/blob/4fb5d3432bcc77eea3b36bf7b51323effddb8082/src/NzbDrone.Core/Download/DownloadMappingService.cs#L40  is likely the quick fix

cc @mynameisbogdan

**Comment by KyleSanderson** [comment]
Hotio and LinuxServer have 1.1.2.2394 as valid tags, no idea what they're running.

**Comment by KyleSanderson** [comment]
> > Hotio and LinuxServer have 1.1.2.2394 as valid tags, no idea what they're running.
> 
> Yeah, that's nigthly from 3 weeks ago. Not that old. The issue is that his output is already parsed.
> 
> Prowlarr returns "application/rss+xml", while Jackett returns "application/xml". Might be related to how his library is parsing the content type?

Probably a dumb question but do (modern) browsers know what that is? if their browser parses it as HTML maybe it's showing as that...

The library we're using that he's having trouble with is https://github.com/mmcdole/gofeed (shouldn't have an issue with that?). I have no idea what nyaa is, in the initial report they also say that the names aren't fully handled or parsed. I don't know if that's related, but if there's not a lot of sanitization wrapping these in CDATA blocks would avoid that atleast.

Anyway...

**Comment by ghoto** [comment]
@mynameisbogdan I queried prowlarr using `curl` and I see the escaped XML. I assume the problem is the browser not displaying the original.
