### ISSUE TITLE
Nyaa.si Search results age is incorrect when source does not specify timezone.

### ISSUE THREAD

**Issue by ArabCoders** [Prowlarr/Prowlarr#144]
**Describe the bug**
When searching via GUI using torrents indexers, if the source index does not specific time zone i.e. (nyaa.si/TPB), the time calculation is using the systemwide timezone instead. 

**To Reproduce**
set your docker time zone to lets say UTC+3, add nyaa.si as torrent indexer. just click search without specifying anything. then sort by age.
if there is new torrents <3hrs it will show age in negative numbers.
 
**Expected behavior**
I think the indexer definitions should include a timezone for each tracker or use UTC as global one. using local system timezone most often will be incorrect. 

**Screenshots**
![example](https://user-images.githubusercontent.com/1621552/121044730-45946980-c7be-11eb-9e3e-77f21ca49456.png)

**Platform Information (please complete the following information):**
Version
0.1.0.382
Package Version
0.1.0.382-ls5 by linuxserver.io
.NET
Yes (5.0.6)
Docker
Yes
DB Migration
7
AppData directory
/config
Startup directory
/app/prowlarr/bin
Mode
Console
Uptime

[AB#51](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/51)

**Comment by bakerboy448** [comment]
it looks like their response has the epoch? we should use that and then convert
`<td class="text-center" data-timestamp="1626148018">2021-07-13 03:46</td>`

**Comment by bakerboy448** [comment]
pretty sure there's no logic for sonarr to not see negative ages

#753 has no relevance as nyaa is yml/cardigann and torrentleech at that time was csharp.

```yml
    date:
      selector: td:nth-child(5)
      filters:
        - name: append
          args: " -00:00" # GMT
        - name: dateparse
          args: "2006-01-02 15:04 -07:00"
```

nyaa's response is GMT, but it looks like it may now be -06:00

![image](https://user-images.githubusercontent.com/55419169/207961206-929a2516-8a8f-4f0c-8ee0-122a0157b633.png)

Servertime is UTC-6.  

@garfield69 - didn't look like nyaa get caught in the latest TZ updates?  should -06:00 be being appended instead of GMT?

**Comment by garfield69** [comment]
> should -06:00 be being appended instead of GMT?

the jackett nyaasi indexer is showing the correct publishing datetime for me.
@ilike2burnthing if you compare the web site with the indexer what do you see?

**Comment by bakerboy448** [comment]
Prowlarr date Cardigann
https://github.com/Prowlarr/Prowlarr/blob/develop/src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs#L519-L522

jackett date Cardigann
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/CardigannIndexer.cs#L2017-L2021

same logic. So the only variable would be app system timezone.

**Comment by ilike2burnthing** [comment]
No issues here:

![nyaa](https://user-images.githubusercontent.com/59480337/207973579-95a50172-27d3-4e5a-a2ad-438d99aabae3.png)

**Comment by bakerboy448** [comment]
What's your system timezones?

**Comment by ilike2burnthing** [comment]
GMT

**Comment by bakerboy448** [comment]
> GMT

that'd be why it works then.  can you test again with a non-GMT timezone?

**Comment by garfield69** [comment]
I've tested with  +13:00 and it still works fine for me.

**Comment by ilike2burnthing** [comment]
Changed TZ on my NAS to CST (-6:00), restarted container, Nyaa still shows correct times. Did notice though that the logs still show GMT time, but if I run the `date` command it shows it's using CST, so I'm not really sure what's going on there.
