### ISSUE TITLE
Indexer - xtremewrestlingtorrents - Unable to Add - No Results

### ISSUE THREAD

**Issue by abendel** [Prowlarr/Prowlarr#145]
**Describe the bug**
Trying to add XWT as a tracker it wont let me.

**To Reproduce**
I go to "add indexer,---> XWT, Un and PW, error.

Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.
**Expected behavior**
It adds the indexer

**Screenshots**

**Platform Information (please complete the following information):**
 - OS:  **Windows 10 0.1.0.388**
 - Docker: 
 - .NET Version (System -> Status): 
 - Browser and Version (Only needed for UI issues): 
 - Prowlarr Version: 
 - Prowlarr Branch: 
Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

https://pastebin.com/mBsMfMGe

**Comment by bakerboy448** [comment]
version please

**Comment by abendel** [comment]
0.1.0.388

**Comment by Qstick** [comment]
Paste expired, can we also try on build 413
