### ISSUE TITLE
Can't add indexer

### ISSUE THREAD

**Issue by M3th0s** [Prowlarr/Prowlarr#146]
**Describe the bug**
Issue adding indexers that rely on username/password combo auth

**To Reproduce**
Go to indexers
Add indexer
Indexer fails to add with error: "Unable to connect to indexer, check the log for more details"
This is currently giving me issues on the following indexers: Portugas, TorrentDb, TVChaosUk

**Expected behavior**
Indexer gets added

**Screenshots**
![image](https://user-images.githubusercontent.com/42418409/121051489-6904e780-c7b1-11eb-8a06-f000934c4fd1.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker: Yes
 - Prowlarr Version: 0.1.0.388
 - Prowlarr Branch: nightly

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6610432/prowlarr.trace.txt)

**Comment by bakerboy448** [comment]
TorrentDB does work.

Please don't submit blank issues that ignore the template (many 3rd party apps do this)

Please edit your post to fill out the bug template

https://github.com/Prowlarr/Prowlarr/issues/new?assignees=&labels=Type%3A+Bug&template=bug_report.md&title=

**Comment by M3th0s** [comment]
Updated

**Comment by bakerboy448** [comment]
TorrentDB seems more likely to be invalid credentials

can you get (separate please so they're easy to read)  logs of the others

You're also extremely out of date `0.1.0.390` is out already; update before digging further please

**Comment by M3th0s** [comment]
I wouldn't say extremely out of date as my version is 0.1.0.388 dated 07/06 (today) and there's only 1 version upwards from mine (0.1.0.390) however hotio/prowlarr:nightly still hasn't got that version so will have to wait and get back to you once that's been released.

**Comment by M3th0s** [comment]
Spoke too soon, it's been published a few mins ago :)

**Comment by M3th0s** [comment]
I've just tested TorrentDB.
I tried logging on the site with my credentials, no issues.
If I try and add the indexer via prowlarr, it fails and i get an email from TorrentDB with a warning for wrong credentials. I have typed these credentials and checked and triple checked they are the correct ones.
[prowlarr.trace_torrentdb.txt](https://github.com/Prowlarr/Prowlarr/files/6610579/prowlarr.trace_torrentdb.txt)

**Comment by M3th0s** [comment]
Further trace logs provided below for portugas and tvc:
[prowlarr.trace_portugas.txt](https://github.com/Prowlarr/Prowlarr/files/6610593/prowlarr.trace_portugas.txt)
[prowlarr.trace_tvc.txt](https://github.com/Prowlarr/Prowlarr/files/6610594/prowlarr.trace_tvc.txt)

**Comment by bakerboy448** [comment]
- TVChaosUk needs to get swapped to the API #78 
- Portugas needs to get swapped to the API #78
- TorrentDB also needs to get swapped to the API #78 

Going to close in lieu of the fact that changing to the API is needed.

@Qstick @RobinDadswell FYI; reopen if we want to debug further.
