### ISSUE TITLE
Indexer - BakaBT - Add Support for Movies

### ISSUE THREAD

**Issue by ArabCoders** [Prowlarr/Prowlarr#147]
Right now if use BakaBT indexer, and search for movie, it will be categorized as TV/Anime, and i think movies should be listed as Movies. from the discussion i had with animetosho admin, he said there is no specific Movies/Anime category in nzb spec. 

The Parser already recognize audio/books, it should recognize the movie tag as well. 

[AB#53](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/53)

**Comment by bakerboy448** [comment]
Currently the Indexer does not support movies period.
https://github.com/Prowlarr/Prowlarr/blob/0ddc530dd4b374980436eed15ed4fb0ac88b80ea/src/NzbDrone.Core/Indexers/Definitions/BakaBT.cs#L107

This would require adding movie support + the cats....tho does the indexer even actually support movies? or just anime movies?

**Comment by ArabCoders** [comment]
@bakerboy448 Hi, indeed they do have a movie /browse.php?cat=5 and this is how they are named mostly.

```text
Sangokushi Dai Ichi Bu Eiyuu-tachi no Yoake | Sangokushi: Dawn of the Heroes [Orphan] (1080p)
Hashire! Shiroi Ookami | Run! White Wolf (VHS) [Orphan]
Konohakaseki no Natsu | Summer of Fossil Leaves (H264, 720p) [COOL] 
Youjuu Toshi | Wicked City (BD 1080p) [Iznjie Biznjie] 
Yubi no Sukima-chan | The devil between my fingers (WEB 720p) [TardS] 
```

And they are classified as movies. I think  "/browse.php?cat=2" (OVA) can be considered anime tv specials or tv movies

**Comment by Qstick** [comment]
Currently we have this defined as TVAnime, but I'd agree it likely makes more sense mapping to a movie cat

```
caps.Categories.AddCategoryMapping(5, NewznabStandardCategory.TVAnime, "Anime Movie");
```

The question is what makes most sense? Movie top level `2000`? or something like MovieOther `2020`?

**Comment by ArabCoders** [comment]
i assume it would be 2000 as this category in BakaBT includes everything from 480p to 4k

**Comment by ArabCoders** [comment]
> Currently we have this defined as TVAnime, but I'd agree it likely makes more sense mapping to a movie cat
> 
> 
> 
> ```
> 
> caps.Categories.AddCategoryMapping(5, NewznabStandardCategory.TVAnime, "Anime Movie");
> 
> ```
> 
> 
> 
> The question is what makes most sense? Movie top level `2000`? or something like MovieOther `2020`?

i assume it would be 2000 as this category in BakaBT includes everything from 480p to 4k
