### ISSUE TITLE
Make search case insensitive

### ISSUE THREAD

**Issue by jeff47** [Prowlarr/Prowlarr#1472]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Not really a problem, but capitalization in torrents & NZBs is not consistent.  Having the search be case insensitive might be more logical.

### Describe the solution you'd like

Have the search be case insensitive

### Describe alternatives you've considered

n/a

### Anything else?

n/a

**Comment by bakerboy448** [comment]
Got a screenshot of the exact same search with the only difference being something is different case?

I just did `test` and `Test` against all my sites and got the exact same results

**Comment by jeff47** [comment]
Oops, I really described this badly.  It's not the search that's the issue, it's the sorting of the results.  Sort by title is case sensitive.
