### ISSUE TITLE
Team CT Game - captcha not working

### ISSUE THREAD

**Issue by jsmdy** [Prowlarr/Prowlarr#1494]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The tracker need a captcha validation, I can't see any on prowlarr, just the entry form

### Expected Behavior

Show a captcha 

### Environment

```markdown
- OS: Ubuntu (seedbox seedit4me)
- Prowlarr: 1.3.1.2796
- Docker Install: No
- Using Reverse Proxy: don't know
- Browser: Firefox and Chrome tested
```

### What branch are you running?

Master

### Trace Logs?
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/10851810/prowlarr.trace.txt)

**Comment by jsmdy** [comment]
maybe this trouble is linked to #1474

**Comment by bakerboy448** [comment]
- please provide the required trace logs the bug report template asks and requires
- a single line validationfailure saying to check the logs around the validation failure is invalid for bug reports
- Provided small log snippet says the login selectors do not exist and has nothing relating to a captcha

**Comment by bakerboy448** [comment]
```
Nous en venons à croire que vous essayez de tromper notre système, nous avons donc banni votre adresse IP !
```
=>
```
We come to believe that you are trying to trick our system, so we have banned your IP address!
```

The site has IP banned you - talk to them for support.

**Comment by jsmdy** [comment]
ok, sry for this lost of time :s, it's bad that nothing appears on my  tracker account
