### ISSUE TITLE
Add Indexer - Torrent - PrivateHD

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#15]
**Type:** Torrent
**Tracker:** PrivateHD
**URL:** <https://privatehd.to/>
**In Jackett:** Yes

[Reference](https://discord.com/channels/767843854736949299/815273658774978591/815312005753602068)

**Comment by TheCatLady** [comment]
Seems like PrivateHD has been added, but AvistaZ is missing?

**Comment by Qstick** [comment]
> Seems like PrivateHD has been added, but AvistaZ is missing?

Just added the entire network on history branch (had some kinks to workout with PHD before adding the others). Have you been testing? if so, I can bring you into the private discord...

**Comment by TheCatLady** [comment]
> Just added the entire network on history branch (had some kinks to workout with PHD before adding the others). Have you been testing? if so, I can bring you into the private discord...

I haven't been, but decided to check out what you guys had so far today!  Would be happy to join the Discord and help test 😸
