### ISSUE TITLE
Available URLs for AudioBookBay do not include current TLD .nl

### ISSUE THREAD

**Issue by bradkeller** [Prowlarr/Prowlarr#1500]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The base URLs available for theaudiobookbay currently include TLDs .se and .li. However the current tld for the site is .NL.

### Expected Behavior

Able to select TLD from dropdown that is .NL or allow custom base URL since the domain hops so often.

### Steps To Reproduce

Open Prowlarr indexer menu and attempt to confirm for Torrent -> AudioBookBay.

### Environment

```markdown
- OS: Debian Stretch
- Prowlarr: Latest
- Docker Install: Y
- Using Reverse Proxy: N
- Browser: Chromium
```

### What branch are you running?

Master

### Trace Logs?

n/a

**Comment by ilike2burnthing** [comment]
*.nl redirects to *.li for me.
