### ISSUE TITLE
Indexer - TorrentDownload - Search Error

### ISSUE THREAD

**Issue by michpas** [Prowlarr/Prowlarr#151]
No search results when indexer: Torrentdownload is used.

**To Reproduce**
Enabling TorrentDownload as indexer and I put in my cookie key:  PHPSESSID=8fxxxxxxx; __utma=xxxxx etc
When manually search for the word 'gesproken'  will result in a 'There was an error loading this page'

**Expected behavior**
not to error out

**Screenshots**

Latest nightly hotio

**Comment by bakerboy448** [comment]
Please fill out the entire bug template you butchered, and include logs.

also `latest nightly` is not a version.
