### ISSUE TITLE
Unable to access 1337x.to, blocked by CloudFlare Protection

### ISSUE THREAD

**Issue by adstep** [Prowlarr/Prowlarr#1518]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Testing/adding indexer 1337x is blocked by CloudFlare protection despite having Flaresolverr configured.

Fails with error:
```
Unable to access 1337x.to, blocked by CloudFlare Protection
```

From the logs + code I can see:
1. Request by Prowlarr that gets blocked by Cloudflare protection
2. Request by Prowlarr to Flaresolverr. Flaresolver returns 200 'Challenge not detected' w/ full expected response.
3. Prowler retries the request using the cookies from 2., which gets blocked again by Cloudflare protection

### Expected Behavior

Indexer should bypass Cloudflare protection when Flaresolverr is configured.

### Steps To Reproduce

Consistently repros on my server, but haven't been able to repro locally. Don't have a consistent repro to share not familiar with debugging from a container on my server. 

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: 1.2.2.2699
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: N/A
- Flaresolver: 3.0.4
```

### What branch are you running?

Master

### Trace Logs?

See trace logs containing repro [prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/10928730/prowlarr.trace.txt).

**Comment by adstep** [comment]
Containers are on same machine & same network with IPv6 disabled.

**Comment by bakerboy448** [comment]
is your server a shared IP - seems more like something specific to your setup / server / bad luck.
Is it an issue with all of 1337x's mirrors?
Is it an issue with the newest FS version 3.1.2?

As far as the response retry - The theory is to have FS get the valid cookie to bypass CF and then be able to do other requests normally
