### ISSUE TITLE
PassThePopcorn (PTP) not being added to sonarr

### ISSUE THREAD

**Issue by Astonish3750** [Prowlarr/Prowlarr#1526]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Currently when PassThePopcorn (PTP) is added as an indexer in prowlarr and sonarr is added as an app with full sync, PTP is not being added to sonarr as an indexer. It is being added correctly to radarr.

I've tried manually adding it to sonarr via the torznab indexer but get this error message "No rss feed query available. This may be an issue with the indexer or your indexer category settings.". I also tried adding "Movies" as a sync category to sonarr, and that didn't work. I added both sonarr and PTP to the same tag and that also didn't seem to do anything.

Another user on PTP's forums has also commented that they are having this issue. 

### Expected Behavior

I would expect that prowlarr adds PTP to sonarr as an indexer just like it does for radarr. PTP might seem dedicated to movies but they also have a good selection of mini series that are only available on sonarr.

### Steps To Reproduce

1. Install prowlarr normally
2. Add prowlarr as an indexer
3. Add sonarr as an app
4. Set sonarr to full sync
5. Observe that PTP is not added to sonarr

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- Prowlarr: 1.2.2.2699
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Microsoft Edge Version 110.0.1587.69 (Official build) (64-bit)
```

### What branch are you running?

Master

### Trace Logs?

```
2023-03-13 11:39:07.8|Warn|HttpClient|HTTP Error - Res: [POST] http://172.19.0.31:8989/api/v3/indexer: 400.BadRequest (208 bytes)
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "No rss feed query available. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2023-03-13 11:39:07.8|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://172.19.0.31:8989/api/v3/indexer]
```

**Comment by Roxedus** [comment]
PTP does not expose TV series as a category, as it is mainly a movie indexer

**Comment by Astonish3750** [comment]
It is still displayed as such in prowlarr, not that it makes any difference.
![image](https://user-images.githubusercontent.com/127745528/224694239-d817259b-520e-4e79-9bc1-cc4d0190dca9.png)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

Prowlarr syncs apps that have the categories you configure apply to the app.
