### ISSUE TITLE
BJ-Share

### ISSUE THREAD

**Issue by aserighelli** [Prowlarr/Prowlarr#153]
Type: Torrents
Tracker: BJ-Share
URL: https://bj-share.info/login.php
In Jackett?: Yes

**Comment by aserighelli** [comment]
Type: Torrents
Tracker: BJ-Share
URL: https://bj-share.info/login.php
In Jackett?: Yes

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/issues/29

>Request an indexer for Prowlarr. ### Check the pinned Jackett parity issue prior to submitting a request. Duplicated requests will be closed without warning. Please search GitHub prior to requesting.

**Comment by aserighelli** [comment]
Sorry, I didn't understand.

Having BJShare on the list means it will eventually be added to Prowlarr?

**Comment by Qstick** [comment]
> Sorry @bakerboy448 , I didn't understand.w
> 
> Having BJShare on the list means it will eventually be added to Prowlarr?

Yes
