### ISSUE TITLE
Suppress known/expected HTTP Errors

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#1532]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently we log at WARN any HTTP error.  This is annoying and spammy for sites that use error codes for expected responses that are not errors.

~~RarBG - 429 and 520~~
Cinemaz, PrivateHD, avistaz - 404 is no results

### Describe the solution you'd like

Fix and implement SuppressHttpErrorStatusCodes or perhaps create a new `LogHttpError` to not warn on known codes for various sites

### Describe alternatives you've considered

keep existing spammy unnecessary logging

### Anything else?

https://github.com/Prowlarr/Prowlarr/issues/1531

**Comment by jonatino** [comment]
Will this finally fix the `Indexers unavailable due to failures: Rarbg (Prowlarr)` issue? Rarbg barely functions with prowlarr

**Comment by bakerboy448** [comment]
No. those errors are valid. Rarbg has significantly increased their rate limit and their servers are also perpetually overloaded so you get rate limited there as well.

It is disabled for the time rarbg staff specified based on the error code returned and that disable time is visible in prowlarr, returned to starr, and visible in starr and prowlarr logs.

**Comment by corilde** [comment]
Hi! I've the same issue with HDOlimpo. Any ideas to fix it?

**Comment by bakerboy448** [comment]
> Hi! I've the same issue with HDOlimpo. Any ideas to fix it?

Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.
