### ISSUE TITLE
Update existing indexer

### ISSUE THREAD

**Issue by xiongster** [Prowlarr/Prowlarr#1534]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Request to add 'Bwtorrents.cc' as additional base url as its only one accessible in my location

### Describe the solution you'd like

Add 'Bwtorrents.cc' url

### Describe alternatives you've considered

none

### Anything else?

no

**Comment by bakerboy448** [comment]
cc @ilike2burnthing

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/45484006d2bf22a85ff304cd35e35e30a2c47fc1

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/134ae12c642f7a08e800b6c753f6bd8164347932
