### ISSUE TITLE
All applications are unavailable due to failures

### ISSUE THREAD

**Issue by rycore** [Prowlarr/Prowlarr#154]
**Describe the bug**
Applications wont sync

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Apps'
3. Click on 'Sync App Indexers'

**Expected behavior**
When clicking _Sync App Indexers_, all indexers should update within each application.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Windows Server 2012r2
 - Docker: No
 - .NET Version: 5.0.6
 - Prowlarr Version: 0.1.0.397
 - Prowlarr Branch: nightly

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6612599/prowlarr.trace.txt)

**Comment by bakerboy448** [comment]
Trace Logs?

>Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
`<!-- Trace logs are named Prowlarr.trace.txt or Prowlarr.trace.#.txt and will contain "trace" in them-->`

but possibly a support / local networking issue

**Comment by rycore** [comment]
Sorry, I've updated the post with the trace log. It was working fine until I updated to 0.1.0.397, I also just updated to 0.1.0.398 and still the same issue.

**Comment by rycore** [comment]
With the latest **0.1.0.40** update, prowlarr seems to be working again.
