### ISSUE TITLE
Apply indexer seed options to manually grabbed torrent

### ISSUE THREAD

**Issue by timotheeandres** [Prowlarr/Prowlarr#1544]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When I grab something using the "Search" option of Prowlarr, the seeding options set up for the content's indexer (seed ratio, seed time) do not get applied to the items in qBittorrent.

Indexer options:
![image](https://user-images.githubusercontent.com/25198539/225851288-80592379-48e0-4d0d-97e5-16f2b83ccc20.png)

Seed options in qBittorrent:
![image](https://user-images.githubusercontent.com/25198539/225851375-d1b16286-4327-49d4-8cd2-c3d30f95d721.png)

### Describe the solution you'd like

I would like that when I grab something through Prowlarr, items added to qBittorrent have their seeding options corresponding to those I set up in their respective indexers, i.e. after grabbing content through an indexer that has "seed time" and "pack seed time" set to 10000, I would like to see this automatically done in qBittorrent:
![image](https://user-images.githubusercontent.com/25198539/225851567-05a30138-9cfc-42bd-aabe-4da25d3be072.png)

### Describe alternatives you've considered

For now, I manually set up the ratio, and I don't really see any other alternative

### Anything else?

Thank you!

**Comment by bakerboy448** [comment]
How can Prowlarr know if it is a Discography or a season pack?
Likely would just apply the default seed time for the tracker if this is implemented.

**Comment by timotheeandres** [comment]
> How can Prowlarr know if it is a Discography or a season pack? Likely would just apply the default seed time for the tracker if this is implemented.

Yes, I think the default option should be applied. IMO, it is better than not applying anything
