### ISSUE TITLE
Query Limit per hour

### ISSUE THREAD

**Issue by berot3** [Prowlarr/Prowlarr#1545]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This is what it says on filelist forum: "Every user is limited to 150 API calls per hour;"

But in the settings, I can only set a limit for 24 hours.

### Describe the solution you'd like

allow an option or toggle to select 24hours or 1 hour

### Describe alternatives you've considered

none come to my mind

### Anything else?

no, nothing. Thanks!

**Comment by bakerboy448** [comment]
BTN and Filelist are the only two that have hourly query limits - the workaround for BTN was to bump the ratelimit to 5s between requests which helps mitigate slightly.

Given the niche use - likely doesn't make sense to implement this hourly.

there's also no regular use case that would justify more than 150 queries per hour on a continual basis.

the rate limiting functionality should also handle this without issue as the Arrs will get a 429 with a 1 hour retry time or the time the site provides prowlarr if it does
