### ISSUE TITLE
Unknown error message, please report.

### ISSUE THREAD

**Issue by klepp0906** [Prowlarr/Prowlarr#1567]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Upon trying to add/test/enable the HD-Space indexer alongside cloudflare, I get the following in prowlarr.
![image](https://user-images.githubusercontent.com/10392920/229853917-6b7ad0b2-81d9-459a-a32e-c72b1b7d1ba7.png)

Meanwhile, flaresolverr shows as receiving and solving the requests.
![image](https://user-images.githubusercontent.com/10392920/229855947-98cf9211-f034-4715-8447-5db32b3ff452.png)

They are both running on the same local machine. 

### Expected Behavior

The indexer should be added/enabled/functional as it is tagged with flaresolverr and flaresolverr is running.

### Steps To Reproduce

1. On windows 11
2. Running FlareSolverr 3.1.2 alongside Prowlarr 1.3.3.2992/nightly
3. Attempt to add HD-Space indexer to Prowlarr using username and password and appropriately tagged with flaresolverr
4. Experience the error shown above.

### Environment

```markdown
- OS: Windows 11
- Prowlarr: 1.3.3.2992
- Docker Install: n/a
- Using Reverse Proxy: n/a
- Browser: n/a
```

### What branch are you running?

Nightly

### Trace Logs?

https://0bin.net/paste/nCoMkdgC#D+Q47y4iBh6u2o5lLBBfkXUDM62bUEL9J68+uLA3Szi

**Comment by bakerboy448** [comment]
logs expired or never existed

**Comment by klepp0906** [comment]
> logs expired or never existed

sorry, musta left it on 1 day expiration.  heres a new one from after trying to test HD-Space with flaresolverr running.

https://0bin.net/paste/S3z4GVuP#fC5KEElHJXAbDkNfQwSsM4EzZoA8CdUkOfpWHfIJsTs

**Comment by bakerboy448** [comment]
logs expired, again

**Comment by klepp0906** [comment]
oop, completely forgot about this.  it automagically solved itself at some point.  as slow as hd-space is, likely an hd-space issue.  will re-open with fresh logs if it ever crops back up to be sure.
