### ISSUE TITLE
Apostrphe in gui instantly returns no results (haven't tested api)

### ISSUE THREAD

**Issue by ArchemedIan** [Prowlarr/Prowlarr#1575]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

if using an apostrophe in the search on gui, such as `It's Always Sunny in Philadelphia` it will immediately tell you there's no results.

### Expected Behavior

to return results

### Steps To Reproduce

open web gui
enter a search term with an apostrophe (sometimes it eventually works, and sometimes it works first try???)

### Environment

```markdown
- OS: proxmox, ubuntu 22.04 container (Linux Ubuntu-Arr 5.15.102-1-pve #1 SMP PVE 5.15.102-1 (2023-03-14T13:48Z) x86_64 x86_64 x86_64 GNU/Linux)
- Prowlarr: 1.3.3.3005 (dotnet 6.0.13)
- Docker Install: no
- Using Reverse Proxy: yes (nginx)
- Browser: firefox 111.0.1
```

### What branch are you running?

Master

### Trace Logs?

![prowlarr](https://user-images.githubusercontent.com/105951210/230163122-4a11ab6a-280b-48cd-aa62-2e9e47d82b1c.gif)

[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/11161690/prowlarr.txt)

**Comment by bakerboy448** [comment]
Can't reproduce this on 1.3.3.3005

**Comment by bakerboy448** [comment]
> the logs are under the gif as prowlarr.txt

info logs are not what the template asks for nor are valid for bug reports
