### ISSUE TITLE
Indexer - Danish Bytes - Unable to Connect - Unexpected Response Status Redirect

### ISSUE THREAD

**Issue by hauge1990** [Prowlarr/Prowlarr#158]
Describe the bug
Trying to add Danishbytes will give a error message saying "Unable to connect to indexer. Unexpected response status Redirect code from API request"

To Reproduce

   1. Go to Add Indexer
   2. Add DANISH BYTES
   3. Enter credentials
   4. Test the indexer
   5. See error --> Unable to connect to indexer. Unexpected response status Redirect code from API request

Expected behavior
That it would verify correctly

Screenshots

Not needed

Platform Information (please complete the following information):

    OS: Docker
    Docker: Yes
    .NET Version (System -> Status): .NET 5.0.6
    Browser and Version (Only needed for UI issues):
    Prowlarr Version: 0.1.0.398
    Prowlarr Branch: nightly

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!

https://pastebin.com/zpFBtgQQ

[AB#57](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/57)

**Comment by Qstick** [comment]
Try on 413

**Comment by hauge1990** [comment]
> 
> 
> Try on 413

what do you mean?

**Comment by hauge1990** [comment]
> 
> 
> Try on 413

Getting this error on 413 "Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings."

https://ghostbin.com/paste/kxxEH

**Comment by and992** [comment]
do it help to get one more?

https://ghostbin.com/paste/OiWtK

**Comment by strunov** [comment]
Jackett has a simular issue. Maybe you could collaborate to solve this issue?

https://github.com/Jackett/Jackett/issues/11857

**Comment by bakerboy448** [comment]
https://github.com/Jackett/Jackett/pull/11929

PR to convert indexer to C# in jackett @austinwbest @Qstick  FYI
