### ISSUE TITLE
Reduce memory usage in history API

### ISSUE THREAD

**Issue by telyn** [Prowlarr/Prowlarr#1581]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I recently had an issue where my Prowlarr instance was repeatedly restarting inside its container due to an Out-Of-Memory condition. Recently I noticed that exportarr's Prowlarr support had graduated to the master branch, which I felt was stable enough to deploy to my system. exportarr functions by requesting statistics from prowlarr's APIs, including the history API.

Sometime after this deployment I noticed the issue described above and started looking into it - I could see that prowlarr's memory usage was rising to the maximum, prowlarr was getting killed by the OOM killer, and was being restarted by the supervisor inside the container.

Knowing that Prowlarr is a .Net app I looked into ways to limit the memory usage and found the DOTNET/ComPlus (I just used both sets as I wasn't sure what version of .Net was in use) `_GCHighMemPercent`, and `_GCHeapHardLimitPercent` environment variables, which limit the amount of memory the runtime will allow to be allocated.

Restarting Prowlarr with those env vars set caused it to output System.OutOfMemoryExceptions, along with backtraces, into the log instead of getting OOM-killed.

All the backtraces for this implicated the history API, so I enabled trace logging and restarted - I saw that Prowlarr was performing a `SELECT` query over the history table with no `LIMIT` clause.

At this point I discovered that I had an unnecessarily large history retention (365 days) in prowlarr, lowered it, cleared the old history, and (maybe) restarted Prowlarr. This completely solved my issue.

I only took cliff-notes instead of a complete trace log, (this happened a couple of weeks ago so those logs are long gone) but here's what I noticed:

* The query trace showed a SELECT "History".*  with no LIMIT, selecting all history entries between the year 1 and now.
* in the Api.V1.Indexers.IndexerStatsController

### Describe the solution you'd like

A LIMIT is somehow placed on the SELECT query in the history API.

I understand that's easier said than done - the Repository structure you have is not something I am used to working with, and I would worry about causing breakages elsewhere with any alterations I made.

### Describe alternatives you've considered

Document the situation and suggest maximum history sizes for certain memory sizes. For what its worth, all I know is that 1 year of 4 downstream applications with ~10 indexers is too much for 256mb of RAM to serve from the history API at present.

### Anything else?

As I said above, the issue is completely solved for me at this point just by my limiting the history to a week, and mine is not a multiuser system so I'm not too concerned about not having the history.

For those reasons I wouldn't say I feel this is high-priority, and I mainly just wanted to get this behaviour written down in a searchable place on the internet for anyone else running prowlarr with memory constraints and adding exportarr to the mix :-)

Thanks for making such a useful bit of software!

**Comment by Qstick** [comment]
The IndexerStatsController API endpoint does accept parameters for start and end date. Not knowing the full intentions of the app, it may be beneficial for exportarr to use these?

**Comment by bakerboy448** [comment]
Closing pending OPs response
