### ISSUE TITLE
Indexer - Nordic+ - Unable to Connect - Unexpected Response Status Redirect

### ISSUE THREAD

**Issue by hauge1990** [Prowlarr/Prowlarr#159]
Describe the bug
Trying to add Nordic+ will give a error message saying "Unable to connect to indexer. Unexpected response status Redirect code from API request"

To Reproduce

   1. Go to Add Indexer
   2. Add Nordic+
   3. Enter credentials
   4. Test the indexer
   5. See error --> Unable to connect to indexer. Unexpected response status Redirect code from API request

Expected behavior
That it would verify correctly

Screenshots

Not needed

Platform Information (please complete the following information):

    OS: Docker
    Docker: Yes
    .NET Version (System -> Status): .NET 5.0.6
    Browser and Version (Only needed for UI issues):
    Prowlarr Version: 0.1.0.398
    Prowlarr Branch: nightly

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!

https://pastebin.com/JH3fRmYa

**Comment by Qstick** [comment]
Try on 413

**Comment by hauge1990** [comment]
> 
> 
> Try on 413

Working on 413

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/9ac435bc41b6ead3874f8d17148f9971444288b9
