### ISSUE TITLE
Database password is still not masked

### ISSUE THREAD

**Issue by rootwyrm** [Prowlarr/Prowlarr#1612]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Technically a duplicate of #632 

Still not masking correctly in 1.3.2.3006.

```
[Info] Bootstrap: Starting Prowlarr - /opt/Prowlarr/Prowlarr - Version 1.3.2.3006 
[Info] AppFolderInfo: Data directory is being overridden to [/talecaster/config] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/talecaster/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/talecaster/config] 
[Warn] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {c89bc010-8b4c-4f1f-9dfc-0aee2f8f7a6a} may be persisted to storage in unencrypted form. 
[Info] MigrationController: *** Migrating Database=prowlarr;Host=10.X.X.X;Username=prowlarr;Password=t3stc4s3;Port=5432;Enlist=False *** 
[Info] MigrationController: *** Migrating Database=prowlarr_log;Host=10.X.X.X;Username=prowlarr;Password=t3stc4s3;Port=5432;Enlist=False ***
```

### Describe the solution you'd like

Prowlarr (and any other *arrs using PostgreSQL) should mask the password

### Describe alternatives you've considered

N/A; already accepted as bug, and fix already attempted

### Anything else?

As mentioned, this was addressed in #632 but appears to still not be working as intended.

**Comment by rootwyrm** [comment]
Console logger should be sanitized as well for sure, just to keep it consistent.

Use case here is that the console output is shipped unfiltered as logs, and in VPS/VPC scenarios with console access, could be exposed. Probably best to just mask it globally in the absence of a more explicit debug request IMO.

**Comment by Qstick** [comment]
Agree, console not being cleansed is intentional behavior
