### ISSUE TITLE
Indexer - HDME - Unable to Add

### ISSUE THREAD

**Issue by esran** [Prowlarr/Prowlarr#164]
The test when setting up HDME tracker fails.

1. Add indexer
2. Select HDME
3. Populate fields as appropriate
4. Hit the Test button
5. Test fails

**Expected behavior**
Test should succeed!

**Screenshots**
![image](https://user-images.githubusercontent.com/5937837/121170187-c437e800-c84c-11eb-84a4-c850ff1de5e6.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker: Yes
 - .NET Version (System -> Status): 5.0.6
 - Browser and Version (Only needed for UI issues): Firefox 89.0 on Windows 10
 - Prowlarr Version: 0.1.0.361
 - Prowlarr Branch: develop

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6615778/prowlarr.trace.txt)

**Comment by esran** [comment]
I gave this another try with version **0.1.0.410**. Different error this time.

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6618320/prowlarr.trace.txt)

**Comment by Qstick** [comment]
Please give 413 a go @esran

**Comment by esran** [comment]
It adds now, but I'm not sure its working. A manual search gives a page load error with `TypeError: e.categories is undefined`. Searching on other indexers works correctly.

[details.txt](https://github.com/Prowlarr/Prowlarr/files/6622314/details.txt)
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6622315/prowlarr.trace.txt)

**Comment by Qstick** [comment]
Thanks, this is similar issue to some others. I'll try and fix this weekend if someone doesn't beat me to it

**Comment by Qstick** [comment]
9675171af hopefully fixes this
