### ISSUE TITLE
Add Host/DNS Name Support to Application section (Truecharts / TrueNAS Scale)

### ISSUE THREAD

**Issue by joubertclementst** [Prowlarr/Prowlarr#1646]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When using TrueCharts version on TrueNAS scale, the Download client supports DNS Name or IP and a separate line for port. This works great since it is on a VPN and I can link directly to it and if the IP changes on a reboot / reinstall it automatically reconnects. The applications section only allows you to enter an IP address and port number. I cannot use the DNS Name. So if the IP changes for any reason I have to manually update the IP address and resync.

### Describe the solution you'd like

Add Host name support on application connections so the DNS name can be used instead of a changing IP address.

### Describe alternatives you've considered

Since I am not too familiar with Linux I am not sure of another way this could be accomplished.

### Anything else?

See the attached screen shots where you can see the difference. The download client host can use DNS name. The app linking only allows IP addresses.
![App Server IP Address](https://user-images.githubusercontent.com/5096697/236586830-796755bb-b998-4ecc-a4d0-1b48c4237060.png)
![download client host name](https://user-images.githubusercontent.com/5096697/236586831-7f0831b6-1359-4c54-a6a0-1e63a9eb1c83.png)

**Comment by bakerboy448** [comment]
There's no requirement it's an IP address only a valid URL as the UI indicates.
