### ISSUE TITLE
PTR lookup to in-addr.arpa

### ISSUE THREAD

**Issue by fede843** [Prowlarr/Prowlarr#1664]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Everytime a search is made (manual or by a service), an extra PTR DNS query is made.

### Expected Behavior

Want to know why this happens. Is it needed? Can I disable this somehow?

### Steps To Reproduce

- While using a network tool to record traffic, (wireshark, tcpdump, etc) make a manual query.
- You will see a nslookup to the IP of the host browser making that request. In my case my machine IP is 192.168.254.64, then I get a PTR DNS query to 64.254.168.192.in-addr.arpa 

Also:

- If a servarr service is using it internally via docker network, then a PTR DNS query is made to the docker network gateway. In my case I get a hit 1.0.20.172.in-addr.arpa for each indexer configured.

### Environment

```markdown
- OS: Linux raspberrypi 6.1.21-v8+ #1642 64 bits
- Prowlarr: 1.5.0.3300
- Docker Install: YES
- Using Reverse Proxy: NO
- Browser: Chrome 112.0.5615.49 64 bits

Containers are using a docker bridge network.
```

### What branch are you running?

Master

### Trace Logs?

DNS log:
May 16 08:10:20: query[PTR] 64.254.168.192.in-addr.arpa from 172.20.0.140
...
May 16 08:11:10: query[PTR] 1.0.20.172.in-addr.arpa from 172.20.0.140

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.  What issue(s) is this causing?  Can reopen later if a bug is identified.

For App Stats - Prowlarr attempts to get the HostName that make the requests.
![image](https://github.com/Prowlarr/Prowlarr/assets/55419169/e700434d-424c-4dab-8e71-3e9cecc1ac79)

https://github.com/Prowlarr/Prowlarr/blob/4c4ebdf17c595eeb0cbe686c3d343ffe4e818fcf/src/Prowlarr.Http/Extensions/RequestExtensions.cs#L140-L155

**Comment by fede843** [comment]
Hi @bakerboy448 thanks for the quick reply. Yes, I have asked before in Discord, but I could not get this technical answer on why this was happening. Now it is crystal clear. Than you.

> also - if the containers are hitting your dns server and not docker's dns - that'd be why you're seeing the container requests....which would be an issue with your setup.

I am using docker DNS, but the resolution is self hosted, that is why I can follow the traffic.

Related to that, I am using a plain simple bridged network for Servarr, not quite sure yet why are not the other apps (Radarr, Sonarr, etc) are not reaching there (at least at that bit of the code) by their IPs, rather the 172.20.0.1, which is the GW. Is it something wrong in my configuration probably?
