### ISSUE TITLE
Addition of a new tracker: iAnon

### ISSUE THREAD

**Issue by IHateIssues** [Prowlarr/Prowlarr#1665]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Would love to have this new tracker added into prowlarr, as a replacement for now decaying and stolen BrokenStones by the rogue dev.

### Describe the solution you'd like

Described above

### Describe alternatives you've considered

Described above

### Anything else?

No

**Comment by bakerboy448** [comment]
Site Requests are handled in the #indexer-requests channel on discord.
