### ISSUE TITLE
(Indexer) omgwtfnzbs.me

### ISSUE THREAD

**Issue by jsclayton** [Prowlarr/Prowlarr#167]
**Type:** Usenet

**Tracker:** omgwtfnzbs

**URL:** https://omgwtfnzbs.me/

**In Hydra?:** Yes

**Comment by bakerboy448** [comment]
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/160

please search prior to creating a GHI

**Comment by jsclayton** [comment]
🤦🏼 sorry, filtered by the `Indexer Request` tag, missed that it was only showing open issues.
