### ISSUE TITLE
Ability to multi select and download results

### ISSUE THREAD

**Issue by JonzaUK** [Prowlarr/Prowlarr#171]
**Is your feature request related to a problem? Please describe.**
No, but would make things a lot easier when manually searching for things using prowlarr

**Describe the solution you'd like**
Tick boxes on each result from a manual search allowing you to tick multiple results with then a download button at the top allowing you to add all ticked results to your client

**Describe alternatives you've considered**
None,

[AB#50](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/50)

**Comment by kyoumei** [comment]
Just want to add on, if it is possible to add a bulk select by "shift clicking" on a search item to select from first item to last item, "ctrl click" to bulk add individual items and having an option to "select all" would be amazing.
