### ISSUE TITLE
Automatic updates do not reflect in Add/Remove Programs

### ISSUE THREAD

**Issue by benwa** [Prowlarr/Prowlarr#1715]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

With Prowlarr's (and the other *arr's) update system, the Add/Remove Programs (ARP) entry does not reflect the actually installed version. This can cause problems with things like winget or other system monitoring tools.

### Describe the solution you'd like

My preference is that the `DisplayName` is simply "Prowlarr" and the `DisplayVersion` is the correct, currently installed, version.

### Describe alternatives you've considered

The `DisplayName` could just be "Prowlarr" and the `DisplayVersion` can be the major version only.

### Anything else?

Related to https://github.com/Sonarr/Sonarr/issues/5710

**Comment by bakerboy448** [comment]
Same as Sonarr. The installer is not used for updates and no plans to do so.

looks like we use majorVersion.BuildNumber as the windows version. PR'd accordingly to just use majorVersion like was done for Sonarr

**Comment by ilike2burnthing** [comment]
Similar issue for Jackett from the start of the year - https://github.com/Jackett/Jackett/issues/12826

The suggested solution (although I'm only remembering about it now and never looked into it) was to get the updater to also update the uninstall registry entry.
