### ISSUE TITLE
Missing omgwtfnzbs

### ISSUE THREAD

**Issue by mmaghometech** [Prowlarr/Prowlarr#174]
Please add support for NZBGet indexer https://omgwtfnzbs.me/login

**Comment by Qstick** [comment]
Use "Generic Newznab", assuming you don't get banned for breaking their rules

**Comment by flippedcracker** [comment]
> Use "Generic Newznab", assuming you don't get banned for breaking their rules

Just so we can know, is there a certain rule that it would be breaking?

**Comment by bakerboy448** [comment]
Users of trackers/indexers are responsible for being aware and abiding of the applicable rules on their given tracker/indexer.

As an example, some sites have rules along the lines of:
> · Do NOT advertise this site and/or its content in public (All places are considered public, unless they are invite only).

**Comment by flippedcracker** [comment]
So it was an in general statement then. I thought there was a specific rule that prevented using something like Prowlarr.
