### ISSUE TITLE
Enable/Disable RSS or search per Application

### ISSUE THREAD

**Issue by gotson** [Prowlarr/Prowlarr#1741]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I use the same indexers in Sonarr and Radarr, but the accuracy of the automatic searches is much better for tv shows than it is for movies.

As such, i would like to disable the RSS for my indexers, for Radarr only, but leave it enabled for Sonarr.

### Describe the solution you'd like

A way to enable/disable RSS/auto search/interactive search for indexers at the application level, but still have the indexers sync in full sync.

### Describe alternatives you've considered

Sync with 'Add and remove only' and manage in Radarr directly.

### Anything else?

nope

**Comment by bakerboy448** [comment]
This is already done with sync profiles + duplicating the indexers + using tags.

closing for future consideration one day

**Comment by gotson** [comment]
I saw sync profiles could do that, but I didn't think about duplicating the indexers. Seems like a lot of hassle though.
