### ISSUE TITLE
Release Group mis-recognized as email address

### ISSUE THREAD

**Issue by ylorn** [Prowlarr/Prowlarr#1751]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Take following title as example:

```plaintext
Avatar The Way of Water 2022 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-Group@PTSite
```

The `Group@PTSite` gets mis-recognized as an email address, so it appears in the search result as:

```plaintext
Avatar The Way of Water 2022 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1 [email protected]
```

This makes the customized filter of `Group` not work (shows zero results) because the keyword gets redacted.

### Expected Behavior

The title should stay intact.

Honestly I am not sure why the title needs to be redacted, I highly doubt if people add their email address to their release title.

Or at lease, we should use a more precise regex to match the potential email address.

### Environment

```markdown
- OS: archlinu
- Prowlarr: 1.6.3.3608
- Docker Install: Yes
- Using Reverse Proxy: Yes (Caddy)
- Browser: Safari
```

### What branch are you running?

Master

### Trace Logs?
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/11902640/prowlarr.txt)

<img width="849" alt="Screenshot 2023-06-29 at 2 16 26 AM" src="https://github.com/Prowlarr/Prowlarr/assets/1502810/80104f7e-4450-4e68-b9a5-f05141b82fa0">

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by ylorn** [comment]
here is the reproduction of the search issue:
![Screenshot 2023-06-29 at 6 58 08 PM](https://github.com/Prowlarr/Prowlarr/assets/1502810/46821bf1-fd09-4b18-80d4-001c5f228e38)

and this is the trace log generated for above issue:
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/11911062/prowlarr.trace.txt)

**Comment by bakerboy448** [comment]
@mynameisbogdan do you have access or do we need trace w/ indexer response enabled?

**Comment by bakerboy448** [comment]
@ylorn see the wiki for dets, but can you redo with indexer response logging enabled.

**Comment by ylorn** [comment]
@bakerboy448 yeah sure. here it is

[prowlarr.trace-2.txt](https://github.com/Prowlarr/Prowlarr/files/11911142/prowlarr.trace-2.txt)

**Comment by bakerboy448** [comment]
Yup it's how the site has the page designed / using cloudflare to protect the emails.

Bogdan feel free to reopen but I don't see anything to be done here

```
<b>Avatar The Way of Water 2022 V2 ULTRAHD BluRay 2160p HEVC Atmos <span class="__cf_email__" data-cfemail="6f3b1d1a0a272b58415e421c28010d2f2c272b2d061b1c">[email&#160;protected]</span></b>
```
