### ISSUE TITLE
Digital Core provider RSS feed repeats downloads infinitely 

### ISSUE THREAD

**Issue by SnippetSpace** [Prowlarr/Prowlarr#1769]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Indexer digitalcore seems to download the same torrent over and over. This leads to bad stats showing 1372 grabs when in reality I grabbed maybe 20 torrents in the last weeks.
![dc stats](https://github.com/Prowlarr/Prowlarr/assets/917744/e5539b7f-2037-48f1-96ac-c3eae51591e3)

When torrent X gets grabbed and I manually delete it from qBittorent the same torrent gets added back that same day, indicating that the RSS feed refresh shows older items and prowlarr does not eliminate these. This leads to the same torrent that is already in the queue being added over and over, hammers the indexer, breaks stats, and makes manual torrent management very difficult as sometimes I want to manually kill a download.

### Expected Behavior

When using RSS refresh, do not take entries into account that were in the previous RSS sync.

### Steps To Reproduce

1. add digitalcore indexer
2. wait
3. check stats

For trace logs I cleared logs, ran RSS sync for sonarr and radarr twice. I can confirm a torrent I previously had deleted has been re-added.

### Environment

```markdown
- OS: Synology DSM (linux)
- Prowlarr: 1.6.3.3608
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: MS Edge (Chromium)
```

### What branch are you running?

Master

### Trace Logs?

https://logs.notifiarr.com/?69b69225e36bb317#GR3GgXnAa14DouTrYzcn1Q9DFoU1ZN1gEKstSuZwA5cq

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
So to confirm you're saying 'https://digitalcore.club/api/v1/torrents?categories[]=10&categories[]=11&categories[]=8&categories[]=9&categories[]=13&categories[]=14&categories[]=12&dead=true&extendedDead=true&extendedSearch=false&freeleech=true&index=0&limit=100&order=desc&page=search&section=all&sort=d&stereoscopic=false&watchview=false' is giving the same results over a period of time?  

Prowlarr has no control with the results the site returns nor if there is nothing new.

If qbit is failing to keep track of what it's grabbed that's something you'll need to take up with the qbit team and doesn't involve prowlarr at all.

**Comment by SnippetSpace** [comment]
ok will make a report there. thanks
