### ISSUE TITLE
Counting issue with number of indexers

### ISSUE THREAD

**Issue by DarrenPIngram** [Prowlarr/Prowlarr#177]
(I have been directed from the Reddit forum to file this bug report).

With my newly-installed app and one tracker installed (more to follow) when I've done a search at the bottom of the screen it invites me to search two trackers (!). Despite only one tracker being present.

Under the Usenet tab to the left it shows a master group called Usenet and then the individual tracker(s). Again in my case only one tracker. Does whatever is doing the counting need a little attention?

Image: https://ibb.co/DpFgbSq

[AB#56](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/56)

**Comment by Qstick** [comment]
Need a new screenshot... just post it in GH this time

**Comment by bakerboy448** [comment]
Here ya go Q
![image](https://user-images.githubusercontent.com/55419169/128092520-fabfe2aa-2466-41e6-b33a-9b611015cbff.png)

**Comment by Qstick** [comment]
This issue was something else if I recall @bakerboy448

**Comment by bakerboy448** [comment]
> This issue was something else if I recall @bakerboy448

similar 
https://www.reddit.com/r/prowlarr/comments/nv2mbk/search_two_trackers/

I vaguely recall it being something along this then
![image](https://user-images.githubusercontent.com/55419169/129462214-88826a94-db2a-407c-b355-9ddc3d908e30.png)

**Comment by DarrenPIngram** [comment]
Yes, looking at it again it shows two indexers, but in the box marked "indexers" it has "Usenet" and "Torrent" entered and "two indexers" to the right-hand-side. So I guess it may be correct, but possibly confusing, since people may interpret "indexers" to mean specific services, e.g. OMG or DOG.
