### ISSUE TITLE
Show RSS link in UI for indexers and searches

### ISSUE THREAD

**Issue by DarrenPIngram** [Prowlarr/Prowlarr#182]
Is there a plan, or can there be, to add a RSS search function to a made search term? 

This exists in NZBHydra and I use it to keep a track on some keywords rather than "episode/show" titles. 

I can then review them in my RSS reader and decide whether to download or not. E.g. show all items (in the last poll) with "London" in the title. Similar use could be made by download clients if desired, such as the RSS searching and downloading feature within SABNZBD

I see in history there is a mention of a RSS search made per category, but that is not the same.

[AB#55](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/55)

**Comment by Qstick** [comment]
What exactly are you talking about here? Screenshots of functionality in hydra would be helpful

**Comment by arifer612** [comment]
I believe it would be something like what Jackett provides, an option to export the cached results of the tracker as an RSS feed where we could put in our search terms as
http://HOST:JACKETT_PORT/api/v2.0/indexers/INDEXER_NAME/results/torznab/api?apikey=API_KEY&t=search&cat=SEARCH_CATEGORY&q=SEARCH_PARAMS

We can then use this RSS feed in our RSS reader to parse the information however so we want it to. Jackett makes this feed URL easy accessed through a single button next to the indexer:
![Screenshot from 2021-08-01 10-39-21](https://user-images.githubusercontent.com/46054733/127757324-3b7c8428-3e38-4045-973d-c6bc1d08528d.png)

**Comment by DarrenPIngram** [comment]
Sorry for the delay in responding. Hopefully this can give some information: https://github.com/theotherp/nzbhydra2/wiki/External-API,-RSS-and-cached-queries and https://newznab.readthedocs.io/en/latest/misc/api/#search (search for RSS).

**Comment by Qstick** [comment]
Our standard Nab response should work fine in an RSS reader…. Which is essentially what that hydra link says

**Comment by DarrenPIngram** [comment]
Thanks for the update. Am I being dense, but if I do (for example) a search for "Mike Oldfield" I don't get a specific URL returned that presumably could be pasted into a RSS reader. I get just the http://192.168.0.90:9696/search page remaining with the results displayed. May I trouble you for a bit of enlightenment?

**Comment by Qstick** [comment]
`http://192.168.1.100:9696/{indexerid}/api?t=search&apikey={yourkey}`
`http://192.168.1.100:9696/{indexerid}/api?t=search&q=mike&apikey={yourkey}`

These result in rss compatible feeds.

**Comment by DarrenPIngram** [comment]
Thanks. I will give it a go.
Would it be possible to consider adding a feature within the application to "make a RSS link from this search" to present a link that can be cut and pasted?

**Comment by Qstick** [comment]
> Thanks. I will give it a go.
> Would it be possible to consider adding a feature within the application to "make a RSS link from this search" to present a link that can be cut and pasted?

Sure, could likely do that

**Comment by DarrenPIngram** [comment]
That would be appreciated by at least one user:) Thank you!
‌

**Comment by gotson** [comment]
Sorry to jump in, but is it possible to search by category using the above mentioned RSS-compatible URL ? I tried adding `&categories=2000` but that doesn't seem to work.

**Comment by bakerboy448** [comment]
> Sorry to jump in, but is it possible to search by category using the above mentioned RSS-compatible URL ? I tried adding `&categories=2000` but that doesn't seem to work.

works fine `https://domain.tld/prowlarr/api/v1/search?query=black%20hawk%20down&indexerIds=-1&categories=2000`

**Comment by gotson** [comment]
> /api/v1/search?query=black%20hawk%20down&indexerIds=-1&categories=2000

This is the normal JSON API endpoint, we were talking about the [RSS compatible endpoint](https://github.com/Prowlarr/Prowlarr/issues/182#issuecomment-899920833).

**Comment by bakerboy448** [comment]
> > /api/v1/search?query=black%20hawk%20down&indexerIds=-1&categories=2000
> 
> This is the normal JSON API endpoint, we were talking about the [RSS compatible endpoint](https://github.com/Prowlarr/Prowlarr/issues/182#issuecomment-899920833).

ah my b

try 
`http://192.168.1.100:9696/{indexerid}/api?t=search&q=mike&apikey={yourkey}&cats={comma separated list}`

**Comment by gotson** [comment]
> > > /api/v1/search?query=black%20hawk%20down&indexerIds=-1&categories=2000
> > 
> > 
> > This is the normal JSON API endpoint, we were talking about the [RSS compatible endpoint](https://github.com/Prowlarr/Prowlarr/issues/182#issuecomment-899920833).
> 
> ah my b
> 
> try
> `http://192.168.1.100:9696/{indexerid}/api?t=search&q=mike&apikey={yourkey}&cats={comma separated list}`
> 
> or
> pass `X-Api-Key` with the key as a header
> `http://192.168.1.100:9696/{indexerid}/api?t=search&q=mike&cats={comma separated list}`

It seems the `cats` parameter is ignored.

I tried `{server}/7/api?t=search&apikey={key}&cats=7000` to search for books, but it returns all sort of results.

Logs confirm that the category filter is not applied:
`[Info] NzbSearchService: Searching indexers: [FileList] for {Term: , Offset: 0, Limit: 0, Categories: []}

**Comment by bakerboy448** [comment]
sigh...

`cat`, not `cats`

**Comment by gotson** [comment]
> sigh...
> 
> `cat`, not `cats`
> 
> also added: https://wiki.servarr.com/en/prowlarr/search#api-endpoints

I tried that before, and it works only for some indexers. For example on FileList it's working, but for YggTorrent it's not propagating to the actual indexer search:

```
[Info] NzbSearchService: Searching indexers: [YGGtorrent] for {Term: , Offset: 0, Limit: 0, Categories: [7000]} 
[Info] Cardigann: Adding request: https://www3.yggtorrent.nz/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date 
[Info] Cardigann: Adding request: https://www3.yggtorrent.nz/engine/search?category=all&name=&page=50&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date 
```

**Comment by bakerboy448** [comment]
Any chance all the busted ones are Cardigann? or is there any pattern for those problematic ones?

If they're all cardigann, do their [YML definitions indicate ](https://github.com/Prowlarr/indexers)they support that category?

**Comment by gotson** [comment]
> Any chance all the busted ones are Cardigann? or is there any pattern for those problematic ones?
> 
> If they're all cardigann, do their [YML definitions indicate ](https://github.com/Prowlarr/indexers)they support that category?

It seems there is a Prowlarr category (like 7000 for books, 7030 for books/comics), and an [indexer category](https://github.com/Prowlarr/Indexers/blob/c7ce0a4e4138317520062259a7d5bfeca2793b4a/definitions/v1/yggtorrent.yml#L80-L86).

However i couldn't find any mapping between the prowlarr category and the indexer category in that yml definition.

**Comment by Milor123** [comment]
How works it in 2023?
