### ISSUE TITLE
Some of the "Go to link" buttons on the Indexer page actually go to the API URL instead of indexer's home page.

### ISSUE THREAD

**Issue by BEisem** [Prowlarr/Prowlarr#183]
**Describe the bug**
Clicking on the link of some of the indexers on my list incorrectly links to the API URL, instead of the indexer's home page. It happens with some, but not all of the indexers I belong to.

BTN
DogNZB
DrunkenSlug
Nzb.su
NZBGeek
NZBPlanet
OMG
OZNzb

This is probably an incomplete list, but these are the ones I'm personally seeing in my list of indexers.

**To Reproduce**
Click the link on the Indexers page to go to an indexer.

**Expected behavior**
It should go to the indexer's home page, not the API page.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: 
 - Docker: 
 - .NET Version (System -> Status): 
 - Browser and Version (Only needed for UI issues): 
 - Prowlarr Version: 
 - Prowlarr Branch: 

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/7ce0343752a6171c138c3b5c271d90b39188db46
