### ISSUE TITLE
Filter freeleech on HD-Space

### ISSUE THREAD

**Issue by bbtufty** [Prowlarr/Prowlarr#1830]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

HD-Space has support for freeleech torrents (and an interactive search flags them as such on prowlarr), but there isn't a flag when adding the indexer like other private trackers

### Describe the solution you'd like

Add checkboxes for filtering freeleech/internal etc., in parity with other private indexers

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by bbtufty** [comment]
Maybe I misunderstood how this works, the search flags things as freeleech but the indexer itself needs to send a search that only returns freeleech torrents for that switch to be useful?

**Comment by bbtufty** [comment]
As far as I can tell their search doesn't do that. Closing the issue

**Comment by ilike2burnthing** [comment]
There's no freeleech search, but Jackett does have an option to filter by freeleech - https://github.com/Jackett/Jackett/blob/cc6dfe52998fc230e60381e6aa1672ac3d6382c5/src/Jackett.Common/Indexers/HDSpace.cs#L47

**Comment by ilike2burnthing** [comment]
Signup is open until the 22nd - https://hd-space.org/index.php?page=signup
