### ISSUE TITLE
Button to open all indexers in a new window or tabs

### ISSUE THREAD

**Issue by onedr0p** [Prowlarr/Prowlarr#1837]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Indexers require you to log in once in awhile to keep your accounts active.

### Describe the solution you'd like

I would like a way to open all indexers in a new browser window or tab

### Describe alternatives you've considered

I am currently using a Chrome bookmarklet

```js
javascript: (function openLinksInNewTab() {
    new Set(
      Array.prototype.filter
        .call(document.querySelectorAll('a[title="Website"][class*="IndexerIndexRow-externalLink"]'), function (a) {
          return a.tagName.toLowerCase() !== "link" && a.href[0] !== "#";
        })
        .map(function (a) {
          return a.href;
        })
    ).forEach(function (a) {
      window.open(a, "_blank");
    });
})();
```

### Anything else?

The button could be placed near here

<img width="355" alt="image" src="https://github.com/Prowlarr/Prowlarr/assets/213795/34d2301e-d0b5-4825-a18d-42dba113b21a">

**Comment by Qstick** [comment]
Is this really something we want?

**Comment by Qstick** [comment]
Doesn't a query keep them active?

**Comment by onedr0p** [comment]
For those that use only the API, I don't think so. For those that use session/cookie auth, maybe?

**Comment by onedr0p** [comment]
Going to close this issue, it's probably not that important
