### ISSUE TITLE
Auto-test indexers on a regular basis

### ISSUE THREAD

**Issue by leodoi3** [Prowlarr/Prowlarr#1858]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have found that when Prowlarr is unable to connect to an indexer it marks it as such but does not appear to 'try again' later. Over a long enough, this results in all my indexers being marked as unconnected and so Sonarr/Radarr has no ability to access them. If I then click on "test all indexers" then Prowlarr discovers it can reconnect to them and so then Sonarr/Radarr can operate as normal. But if I do not do this manual operation then the system grinds to a halt. 

### Describe the solution you'd like

A setting or flag that can make Prowlarr attempt to 'reconnect' to indexers automatically every 12 hours or something?

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by bakerboy448** [comment]
- back off logic and 429s in prowlarr already handle this
- Back off logic in and 429 responses to Starr already handle this

Fix your connection issues, if prowlarr is disabling them for significant amounts of time then they have not been available and had continual issues
