### ISSUE TITLE
(Indexer) - Torrent - Ilcorsaroverde

### ISSUE THREAD

**Issue by bonny1992** [Prowlarr/Prowlarr#186]
**Type:** Torrents

**Tracker:** Il Corsaro Verde

**URL:** http://www.icv-crew.com/forum/index.php?action=forum

**In Jackett?:** No

**Additional Context:**
It's a tracker based on SMF, where the search is limited at one search each 60 seconds (IIRC), and one will need to click on a "Thank you" link in order to get the magnet url.
It will be hard for sure. But, for italians, this is probably the biggest "semi-private" tracker available, after TNTVillage that closed.

**Comment by bakerboy448** [comment]
https://requests.prowlarr.com/b/feedback/p/torrent-ilcorsaroverde
