### ISSUE TITLE
Seed time and ratio

### ISSUE THREAD

**Issue by 2fst4u** [Prowlarr/Prowlarr#188]
**Is your feature request related to a problem? Please describe.**
Currently Prowlarr doesn't have options for seed time and seed ratio. When indexers get imported to apps, they are missing these settings.

**Describe the solution you'd like**
Prowlarr just needs these options included in indexer setup. 

**Describe alternatives you've considered**
Nil

**Additional context**
Nil

**Comment by bakerboy448** [comment]
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/106

**Comment by 2fst4u** [comment]
Whoops I tried searching but didn't find that one with these terms. My bad
team.
