### ISSUE TITLE
TorrentWhiz has the wrong URL.

### ISSUE THREAD

**Issue by prevail90** [Prowlarr/Prowlarr#1886]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Torrentwhiz is set to torrentwhiz61.com and it is currently at torrentwhiz62.com which makes prowlarr mark is as unable to be used.

### Expected Behavior

prowlarr use torrentwhiz to get the korean torrent files.

### Environment

```markdown
- OS: ubuntu 
- Prowlarr: 1.8.4.3884
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: mozilla
```

### What branch are you running?

Master

### Trace Logs?

I dont have any

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Refresh your definitions from system tasks
https://github.com/Prowlarr/Indexers/commit/d9a99901d81537a71c09ef2a0e3e6f0110b5c38c
