### ISSUE TITLE
Make it possible to manually set a "Base Url" when adding a specific indexer

### ISSUE THREAD

**Issue by jaja360** [Prowlarr/Prowlarr#1892]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes, indexers change URLs but it takes a long time before prowlarr updates to the new url.
For example, DICMusic changed its url from dicmusic.club to dicmusic.com more than one month ago, and prowlarr still has no way to use the new URL.

### Describe the solution you'd like

When adding a specific indexer, the "Base Url" field should allow to input manually an URL, so that we don't have to wait for a prowlarr update.

### Describe alternatives you've considered

None.

### Anything else?

None.

**Comment by bakerboy448** [comment]
- no plans
- Cardigann definitions can use custom definitions
- Csharp definitions which dicmusic need to be updated in the code base. This has not been done as no one ever opened a GHI nor reported the url change on discord
