### ISSUE TITLE
AudioBookBay 503 Error when trying to Add

### ISSUE THREAD

**Issue by Uggers** [Prowlarr/Prowlarr#191]
When trying to add AudioBookBay, it times out stating there is an error;
**Unable to connect to indexer, check the log for more details**

**To Reproduce**

1. Go to 'Indexers'
2. Click on 'Add Indexer.'
3. Click on 'Save or Test.'

[prowlarr.txt.txt](https://github.com/Prowlarr/Prowlarr/files/6630742/prowlarr.txt.txt)
**Platform Information (please complete the following information):**
Version    0.1.0.421
Package Version    0.1.0.421-ls16 by linuxserver.io 
.NET    Yes (5.0.6)
Docker    Yes
Running on UNRAID

Log attached
[prowlarr.txt.txt](https://github.com/Prowlarr/Prowlarr/files/6630746/prowlarr.txt.txt)
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6631447/prowlarr.trace.txt)

**Comment by bakerboy448** [comment]
Please fill out the bug template and complete the information you removed from the template.

also trace log as per the template as well

**Comment by Uggers** [comment]
> Edit disregard, see the issue, you removed the –> which causes the text to hide. Edited/fixed

Thanks that was my fault but I hadn't figured out what I did, but I could see it when I hit edit so I thought maybe it was just my end.

Let me know if you need anymore info.

**Comment by Uggers** [comment]
trace attached

**Comment by Qstick** [comment]
Site was likely down or is not available for you. Either way this is either resolved (works here) or needs alternative links (a different issue is already open)

**Comment by Fma965** [comment]
This still doesn't appear to be working

**Comment by bakerboy448** [comment]
> This still doesn't appear to be working

Unfortunately our crystal balls are out of magic unicorn blood.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) and we can troubleshoot.

**Comment by Fma965** [comment]
I don't have the time to troubleshoot currently, just wanted to inform you that it's still not working, although when you visit the website you do need to be logged in to download, so maybe that is why? Jackett also doesn't work for this site any more.

**Comment by bakerboy448** [comment]
> Jackett also doesn't work for this site any more.

no one has reported this to Jackett is appears.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

so it seems they perhaps changed their URL and the current one is no longer supported by the indexer as Qstick mentioned.

No action to be taken without additional information on the sites new url(s).

**Comment by Uggers** [comment]
Sorry, can you clarify what you need regarding "new url(s)" ?

http://audiobookbay.ch  seems to be the latest one

**Comment by Fma965** [comment]
From my perspective, the IP's used by PIA are blocked, no idea why a torrent site would block a VPN but thats the issue here. so therefore there is no issue with the existing URL's as far as i know

However I can't use https://audiobookbay.unblockit.ch as it's a proxy which uses Cloudflare and doesn't seem to work despite working on the same public IP (on another VM)

**Comment by Uggers** [comment]
ah ok, that makes sense I guess

I'm using Mullvad as my VPN so I'm guessing it's blocking those IP's too.

**Comment by Fma965** [comment]
By settings up a separate PIA VPN docker using a different country VPN https://github.com/qdm12/gluetun and routing prowlarr via it via http proxy i have managed to work around this issue.
