### ISSUE TITLE
Indexer errors with AvistaZ indexers on ID based searches

### ISSUE THREAD

**Issue by esran** [Prowlarr/Prowlarr#192]
**Description**
When searching by ID, for example searching for a specific title from radarr, prowlarr logs indexer failures and notifies these. No errors are reported back to radarr though.

**Steps**
Configure one or more of the AvistaZ family of indexers (AvistaZ, PrivateHD, Cinemaz, ExoticaZ).
From radarr or sonarr perform a search for a specific item (movie, season or episode).
Results may be found, but prowlarr will log an error for the indexers and send a notification (if configured).
From the logs it looks like term based searches are fine but ID based searches (it looks like it uses IMDB for these sites) give a 404 error.

**Expected behavior**
Hopefully the API/URL used can be tweaked to make ID based searches work with AvistaZ sites.

**Screenshots**
![image](https://user-images.githubusercontent.com/5937837/121548877-4965fd00-ca05-11eb-861d-1b9b2a4c11de.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker: Yes
 - .NET Version (System -> Status): 5.0.6
 - Browser and Version (Only needed for UI issues): Firefox 89.0 Windows 10
 - Prowlarr Version: 0.1.0.421
 - Prowlarr Branch: nightly

**Trace Log**
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6632456/prowlarr.trace.txt)

**Comment by esran** [comment]
Still seeing errors for AvistaZ and CinemaZ (but PrivateHD looks to be okay now).

![image](https://user-images.githubusercontent.com/5937837/121777303-3da34380-cb89-11eb-8cf1-1071d9413f19.png)

**Comment by Qstick** [comment]
> Still seeing errors for AvistaZ and CinemaZ (but PrivateHD looks to be okay now).
> 
> ![image](https://user-images.githubusercontent.com/5937837/121777303-3da34380-cb89-11eb-8cf1-1071d9413f19.png)
> 

What is the same request to AvistaZ from Jackett that is working? (from Jackett logs)

**Comment by esran** [comment]
Jackett testing. I performed two manual searches in radarr. The first was for a movie not on AvistaZ and the second is for on that is on AvistaZ.

[avistaz-jackett-missing.txt](https://github.com/Prowlarr/Prowlarr/files/6642574/avistaz-jackett-missing.txt)
[avistaz-jackett-hit.txt](https://github.com/Prowlarr/Prowlarr/files/6642575/avistaz-jackett-hit.txt)

Also of note, the results of the second search included a LOT of results from my other indexers in Prowlarr for the wrong film. The search took a long time. There doesn't seem to be any connection betweem the results as far as I can tell. Also worth noting that I had AvistaZ enabled for Prowlarr still and that gave zero results.

**Comment by Qstick** [comment]
Jackett is making the same request now that we are, so no issues there. I assume the problem you are calling out is just that it errors instead handling a 0 result gracefully

`https://avistaz.to/api/v1/jackett/torrents?in=1&type=1&imdb=tt2797106`

**Comment by esran** [comment]
I've been seeing health check notifications when doing title based searches. It looks like results are returned successfully though.

**Comment by Qstick** [comment]
Seems we throw on error in HttpIndexerBase instead of letting the Indexer parser handle error codes, should be a fairly straightforward fix to allow status codes to be handled by the specific parser for those codes that can mean different things ( like 404). We'll dial back HttpBase to only thrown on known common codes like 429 and 401
