### ISSUE TITLE
i2p: Trying to add socks5 gets stuck at validation.

### ISSUE THREAD

**Issue by IngwiePhoenix** [Prowlarr/Prowlarr#1921]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Since QBittorrent supports I2P traffic now since 4.6.0 and since I already run i2pd on my system, I made sure that my containers could reach it - with success.

However, when trying to add i2pd as a socks5 proxy, it gets stuck while saving, then fails with a health check issue, and dumps a stacktrace to the logs with no URL to indicate *how* the check was done, to possibly replicate it.

```
prowlarr  | [Error] Socks5: Proxy Health Check failed
prowlarr  |
prowlarr  | [v1.9.4.4039] System.Net.WebException: Http request timed out
prowlarr  |    at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 162
prowlarr  |    at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Prowlarr.Common/Http/HttpClient.cs:line 171
prowlarr  |    at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 70
prowlarr  |    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
prowlarr  |    at NzbDrone.Core.IndexerProxies.HttpIndexerProxyBase`1.Test() in ./Prowlarr.Core/IndexerProxies/HttpIndexerProxyBase.cs:line 39
prowlarr  |
prowlarr  |
prowlarr  | [Warn] ProwlarrErrorPipeline: Invalid request Validation failed:
prowlarr  |  -- Host: Failed to test proxy: Http request timed out
```

And the error in the dialog just references that:
> Failed to test proxy: Http request timed out

### Expected Behavior

I expected Prowlarr to *just* save the proxy. It is configured with an outproxy through Tor, but this is more of a failsafe than anything - so technically, it should resolve everything just fine. However, it seems that Tor can take it's absolute sweetest time in resolving and connecting to the clearnet... And hence, whilst trying to replicate this behaviour using `icanhazip.com`, I too got stuck o.o

```
# curl -x socks5h://192.168.2.1:4447 -Lv icanhazip.com
*   Trying 192.168.2.1:4447...
* Connected to 192.168.2.1 (192.168.2.1) port 4447
* SOCKS5 connect to icanhazip.com:80 (remotely resolved)
<-- stuck. ctrl-c'd -->
```

So, I would also expect either the option to just forego the healthcheck and immediately save - or at the very least, configure a timeout for the check itself. And, to know which URL is used for health checking.

### Steps To Reproduce

1. Setup Gluetun Docker container
2. Setup Prowlarr (linuxserver image) Docker container
3. Add a firewall rule to Gluetun to enable local network access.
4. In Prowlarr, try to add a new Socks5 proxy.
5. Enter the IP and Port of your i2p/i2pd instance.
6. Click Save.

### Environment

```markdown
- OS: OpenWrt 22.03
- Prowlarr: 1.9.4.4039-ls39 by linuxserver.io
- Docker Install: Compose
- Using Reverse Proxy: Caddy
- Browser: OperaGX
```

### What branch are you running?

Master

### Trace Logs?

Added the trace above, nothing else showed up.

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- Console logs are not trace logs 
- Please don't check the box indicating you followed the wiki on how to provide logs it was clearly not followed. Reports can and will be closed as invalid.
- More than likely this is a support issue, but let's see the proper logs
