### ISSUE TITLE
[1337x] 503.ServiceUnavailable

### ISSUE THREAD

**Issue by she11sh0cked** [Prowlarr/Prowlarr#193]
**Describe the bug**
I get a 503.ServiceUnavailable response when trying to connect to 1337x (see logs)

**To Reproduce**
1. Go to 'Indexers'
2. Click on 'Add Indexer'
3. Click on '1337x'
4. Click on 'Test'
5. See error

**Platform Information:**
 - OS: Ubuntu 21.04
 - Docker: Yes
 - .NET Version: Yes (5.0.6)
 - Prowlarr Version: 0.1.0.421
 - Prowlarr Branch: nightly
 
 **Possibly Related**
 #191
 
 **Logs**
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/6632737/prowlarr.txt)
[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/6632738/prowlarr.debug.txt)
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6632739/prowlarr.trace.txt)

**Comment by jellis413** [comment]
Also happening here with Windows Server 2019

**Comment by Qstick** [comment]
Works fine for me here. They were likely down for a tad
