### ISSUE TITLE
Add "Instance Name"

### ISSUE THREAD

**Issue by anuradhaedirisuriya** [Prowlarr/Prowlarr#1935]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, there is no field to add a custom "Instance Name" like Radarr and Sonarr

### Describe the solution you'd like

I'd like to request the ability to change/add a custom Instance Name field

### Describe alternatives you've considered

Radarr and Sonarr both have this feature

![image](https://github.com/Prowlarr/Prowlarr/assets/7523370/99f889ef-fbd2-4eed-92c6-b22c8ea9b9e6)

### Anything else?

No

**Comment by Roxedus** [comment]
Prowlarr also has this feature.

**Comment by anuradhaedirisuriya** [comment]
> Prowlarr also has this feature.

How do you do this?

**Comment by Roxedus** [comment]
Its under advanced, as it is for radarr and sonarr
