### ISSUE TITLE
[Feature Request] EasyNews Web/RSS as data source?

### ISSUE THREAD

**Issue by GrabbenD** [Prowlarr/Prowlarr#1936]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

EasyNews is a Usenet newsgroup which also offers direct downloads through their Web/RSS interface. Downloading through their website makes it possible to stream contents of a file without having to decrypt & reassemble it first (unlike regular NZB route thus eliminating the need to use a Usenet indexer).

### Describe the solution you'd like

Support for EasyNews Web/RSS as a datasource for Sonarr/Radarr

### Describe alternatives you've considered

Using EasyNews as a regular Usenet provider is possible but with this route the files have to be downloaded first to access their contents.

### Anything else?

Implementing this is outside my expertise which is why I opted to make a request in hopes of finding someone who might have interest in taking a look at this 🙂

**Comment by bakerboy448** [comment]
- No plans for DDL (i.e. non-usenet, non-torrent, direct download) providers
