### ISSUE TITLE
NzbDrone.Core.Applications.ApplicationService HTTP request failed

### ISSUE THREAD

**Issue by smidley** [Prowlarr/Prowlarr#194]
As soon as I add any indexers, I start seeing this in the logs:

`HTTP Error - Res: [POST] http://192.168.86.20:8989/api/v3/indexer: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Unable to connect to indexer, check the log for more details",
    "severity": "error"
  }
]`

`NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://192.168.86.20:8989/api/v3/indexer]`

**Expected behavior**
I would expect the indexers to be updated on the applications linked to Prowlarr.  None of the applications get any of the indexers added.

 - OS: Unraid 6.9
 - Docker: Yes
 - Prowlarr Branch: nightly

Trace logs: https://pastebin.com/RPFM7xNJ

**Comment by bakerboy448** [comment]
- Logs appear to be not from prowlarr and contain nothing related to an attempted add
- Please fill out the remainder of the template you appear to have butchered out
- This behavior is expected if the indexer fails *Arr validation.

**Comment by Qstick** [comment]
This is bad Prowlarr address in app setup
