### ISSUE TITLE
TorrentGalaxy failing periodically

### ISSUE THREAD

**Issue by kingp0dd** [Prowlarr/Prowlarr#1940]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Error:

Indexers unavailable due to failures for more than 6 hours: TorrentGalaxy 

Is there a recommended query limit to avoid failure?

### Expected Behavior

No error

### Environment

```markdown
- OS: Debian
- Prowlarr: 1.9.4.4039
- Docker Install: Yes
- Using Reverse Proxy: N
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

Indexers unavailable due to failures for more than 6 hours: TorrentGalaxy 

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Invalid bug report
