### ISSUE TITLE
YGG : No form found on https://www3.yggtorrent.wtf/ using form selector #user-login

### ISSUE THREAD

**Issue by gjobin** [Prowlarr/Prowlarr#1941]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

user-login form nor found on YGG page, so indexer fails.

Kindly requested help on Discord, no one is willing to help.

### Expected Behavior

Form is found and indexer can proceed to search/grab.

### Steps To Reproduce

1. Configure Latest FlareSolverr (3.3.10)
2. Configure YGG Indexer, and add proper tag from FS.
3. Test/Save

-------

1. Run FlareSolverr on Desktop (headless=false)
2. Configure new FS with proper IP address
3. Configure YGG Indexer, and add proper tag from FS on Desktop
3. Test/Save
4. We can see the challenge being resolved and page loading. (See video)

### Environment

```markdown
- OS: TrueNAS-SCALE-22.12.4
- Prowlarr: 1.10.5.4116
- Docker Install: TrueNAS Apps
- Using Reverse Proxy: NO
- Browser: Version 119.0.6045.160 (Official Build) (64-bit)
```

### What branch are you running?

Master

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/13501737/prowlarr.trace.txt)

https://github.com/Prowlarr/Prowlarr/assets/9118970/db867dd5-5958-4e9a-bd7f-4b68f3928095

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
>  I have searched the existing open and closed issues

Why lie?

Duplicate of https://github.com/Prowlarr/Prowlarr/issues/1919
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/1392

> Kindly requested help on Discord, no one is willing to help.

**GITHUB IS NOT AND IS NEVER FOR SUPPORT**

**Comment by gjobin** [comment]
> > I have searched the existing open and closed issues
> 
> Why lie?
> 
> Duplicate of #1919 Duplicate of #1392

Wanted to comment about this, but as I was gathering the information, I forgot to come back on this. Sorry. They all have been closed as support requests, and use Discord. I'm confident I am experiencing a bug on the form identification process, as proven by logs and video.

> > Kindly requested help on Discord, no one is willing to help.
> 
> **GITHUB IS NOT AND IS NEVER FOR SUPPORT**

This was to show help on discord was requested before digging deeper and recording video. showing evidence FS is not the issue. Please kindly reconsider at least investigating this issue.

**Comment by bakerboy448** [comment]
- Please use [Discord](https://prowlarr.com/discord) for support/questions.
- Not a bug, YGG is anti-automation and continually makes efforts to break prowlarr.
