### ISSUE TITLE
hide disabled indexers

### ISSUE THREAD

**Issue by snickers2k** [Prowlarr/Prowlarr#1946]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

would be great to hide disabled indexers (for less cluttering)

### Describe the solution you'd like

hide disabled indexers - on/off button under view-options 

### Describe alternatives you've considered

using tagging for "active" / "inactive" and only show "active" but it's too much work^^

### Anything else?

-

**Comment by bakerboy448** [comment]
- what specific problems does this solve / what's the usecase?
- Generally anything more than a dozen or so indexers is unnecessary and provides no benefit
  - public trackers all scrape each other and are redundant

**Comment by snickers2k** [comment]
i have some indexers i have disabled but don't want to delete, because maybe  i'll use them in the future again.

**Comment by bakerboy448** [comment]
So Prowlarr's indexer enable/disable flag not like disabled temporarily?

This can already be done with custom filters for enabled = true and enabled = false respectively
