### ISSUE TITLE
Orionoid Indexer

### ISSUE THREAD

**Issue by maxexcloo** [Prowlarr/Prowlarr#1955]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

I would like to be able to use the Orionoid (https://orionoid.com/) indexer to search for torrents.

### Describe alternatives you've considered

Using other indexers - this is working for now but I've had great experiences with Orionoid.

### Anything else?

Awesome project <3

**Comment by bakerboy448** [comment]
Indexer requests in the indexer request channel on discord :)

Please use [Discord](https://prowlarr.com/discord)
