### ISSUE TITLE
Add AutoBRR as supported client

### ISSUE THREAD

**Issue by ThaDaVos** [Prowlarr/Prowlarr#1966]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently one has to add each indexer in Prowlarr to AutoBRR manually - same as one used to do for the *Arr stack - which is really cumbersome

### Describe the solution you'd like

This: https://autobrr.com/configuration/feeds#torznab--newznab
But automated from Prowlarrs side, same as with the *Arr's

### Describe alternatives you've considered

Manually doing this:
https://autobrr.com/configuration/feeds#torznab--newznab

### Anything else?

Not really

**Comment by bakerboy448** [comment]
- no plans
- Only needed for a handful of sites in autobrr that need to be feed not irc. Nothing to sync other than a 1 time add

**Comment by ThaDaVos** [comment]
Sorry, but doesn't the same go for the other *Arr services? The idea is to ease setting it up - and prevent repeating steps in the future if a new indexer gets added...

**Comment by bakerboy448** [comment]
Most trackers in autobrr are going to be IRC not feed.

**Comment by ThaDaVos** [comment]
The idea was for syncing the ones through the feed option - so these doesn't have to be entered manually, retrieving their id etc
