### ISSUE TITLE
Blutopa URL

### ISSUE THREAD

**Issue by mduijm** [Prowlarr/Prowlarr#1967]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The Indexer details for Blutopia refer to the URL:  https://blutopia.xyz/, however the URL should be: https://blutopia.cc/

### Expected Behavior

See above, the URL needs an update to: https://blutopia.cc/

### Environment

```markdown
Version
1.11.2.4160
Package Version
1.11.2.4160-ls140 by linuxserver.io
.NET
Yes (6.0.25)
Docker
Yes
DB Migration
38
Database
Sqlite 3.41.2
AppData directory
/config
Startup directory
/app/prowlarr/bin
Mode
Console
Uptime
```

### What branch are you running?

Master

### Trace Logs?

afail: No log needed 

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Non-issue. https://github.com/Prowlarr/Indexers/blob/8f639a4205670956207228a280489cfda3fe8b4f/definitions/v9/blutopia-api.yml#L9C22-L9C22
