### ISSUE TITLE
Don’t add `(Prowlarr)` to Indexer name when syncing

### ISSUE THREAD

**Issue by tillkruss** [Prowlarr/Prowlarr#1978]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Having `(Prowlarr)` included in every Indexer name makes list sometimes look funny and long on small screens.

### Describe the solution you'd like

Is there (or could there be) an option to not append `(Prowlarr)` to synchronized indexer names in Radarr/Sonarr?

### Describe alternatives you've considered

Turning off full sync and manually changing the names of dozens of indexers in Sonarr/Radarr. 

### Anything else?

No

**Comment by Qstick** [comment]
Dupe #544
