### ISSUE TITLE
Toggle for Cross-Seed on torznab entries

### ISSUE THREAD

**Issue by dsrtusr88** [Prowlarr/Prowlarr#1987]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Cross-Seed uses prowlarr to search for potential torrents to xseed.  If the `Use Freeleach Token` is marked `true`, cross-seed will burn a FL token on a xseed that you already have.

### Describe the solution you'd like

Would like a toggle on Torrent Trackers that you intend to use cross-seed with this tracker.  If the Cross-Seed API calls Prowlarr (which Prowlarr seems to know how to track based on the Stats view), then `Use Freeleach Token` is not invoked.

### Describe alternatives you've considered

Would have to make cloned tracker entries in prowlarr.

### Anything else?

Nothing additional.

**Comment by zakkarry** [comment]
Why can't you just duplicate the indexer and not use FL Tokens?

**Comment by zakkarry** [comment]
If this is strictly for cross-seed, I think this is engineering a solution for a use-case that is easily solved with a few clicks already.
