### ISSUE TITLE
Prowlarr changes case of UrlBase

### ISSUE THREAD

**Issue by OdinVex** [Prowlarr/Prowlarr#1988]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I've attempted to setup a Prowlarr instance and I've noticed that Prowlarr doesn't respect the case of UrlBase, unlike Radarr/Sonarr. It is also ignoring the ReverseProxy HTTPS and uses links to HTTP, unlike Radarr/Sonarr.

### Expected Behavior

Respect the case of UrlBase. /Prowlarr /Whatever instead of /prowlarr /whatever.

### Steps To Reproduce

1. Set UrlBase to any string of URI with uppercase character(s).
2. Launch instance, access panel. You'll get your login form but all requests as per Prowlarr will be UrlBase->Lowercase.

### Environment

```markdown
- OS: Linux
- Prowlarr: Hotio:latest (release-1.12.2.4211)
- Docker Install: Yes
- Using Reverse Proxy: Yes* Properly configured, same config as Radarr/Sonarr but named Prowlarr.
- Browser: LibreWolf
```

### What branch are you running?

Master

### Trace Logs?

Executing usermod...
usermod: no changes
Applying permissions to /config
s6-rc: info: service init-setup successfully started
s6-rc: info: service service-prowlarr: starting
s6-rc: info: service service-prowlarr successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[Info] Bootstrap: Starting Prowlarr - /app/bin/Prowlarr - Version 1.12.2.4211 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] MigrationController: *** Migrating data source=/config/prowlarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 *** 
[Debug] MigrationController: Took: 00:00:01.0366865 
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3;busytimeout=100 *** 
[Info] Microsoft.Hosting.Lifetime: Now listening on: http://localhost:9696 
[Info] CommandExecutor: Starting 3 threads for tasks. 
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. 
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production 
[Info] Microsoft.Hosting.Lifetime: Content root path: /run/s6-rc:s6-rc-init:FhCHgB/servicedirs/service-prowlarr
[Info] Auth: Auth-Success ip <removed> username '<removed>' 

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Please do not erroneously check the box saying logs were provided and the wiki was followed when no such thing occurred.

**Comment by bakerboy448** [comment]
For future reference: If the wiki was followed then the provided docker container output would not be provided and instead there would be log output from the app log file. In fact, it is impossible if the 6 steps are followed - ignoring trace - for the resulting logs found to be container logs as provided.

**Comment by bakerboy448** [comment]
- Baseurl will be fixed with - https://github.com/Prowlarr/Prowlarr/pull/1989
- HTTPS/HTTP issue is a support issue / reverse proxy misconfiguration
