### ISSUE TITLE
HDTorrents.it only shows four results every query

### ISSUE THREAD

**Issue by andreacoradi** [Prowlarr/Prowlarr#199]
Every query against this tracker shows only four results that are named after film qualities like "() [BDRip 1080p - ITA]"

**To Reproduce**
1. Go to 'Search'
2. Choose a random query, like "test"
3. Click on 'Indexers'
4. Scroll down to 'HDTorrents.it'
5. See error

**Expected behavior**
It should display results related to the query

**Screenshots**
![see](https://user-images.githubusercontent.com/10401120/121774338-59571b80-cb82-11eb-8196-160963370cfa.png)

**Platform Information (please complete the following information):**
 - OS: Debian 10
 - Docker: No
 - .NET Version 5.0.6
 - Prowlarr Version: 0.1.0.436
 - Prowlarr Branch: nightly

**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
[Trace logs](https://pastebin.com/u1Z1hR1d)

**Comment by bakerboy448** [comment]
trace logs, not debug logs please

**Comment by andreacoradi** [comment]
My bad, updated

**Comment by Qstick** [comment]
We're probably going to need an invite to fix this

**Comment by andreacoradi** [comment]
I can provide only 1 invite at the moment, let me know how and to whom I can share it

**Comment by Qstick** [comment]
Seems they are down, or lost the domain.. HDTorrents.it

closing this for now, let me know if something changes with the site
