### ISSUE TITLE
Provide more options for seeding limits

### ISSUE THREAD

**Issue by Dukobpa3** [Prowlarr/Prowlarr#1990]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I can't set seed limits except more than 0

### Describe the solution you'd like

I can make it manually in download client

### Describe alternatives you've considered

Would be great to have options in indexers configuration to set seeding limits 0 and -1 also.
Fore example qBittorrent have both of this numbers as legal option.
* -1 – for infinite
* 0 – for not seeding (useful for public trackers)

But in Prowlarr I should make it only more than 0 and only positive

As a workaround I've made in qbit default -1
Then in Prowlarr for semi-public trackers I set `1.5-2-5-x` limits
For private `nothing` – and there will be infinite (-1 default from qBit)
For public I can set something like 0.1 but **why not provide the legal 0 option for it.**

So my suggestion is to provide more agile settings in torrents seeding limits direct in Prowlarr

### Anything else?

nothing

**Comment by bakerboy448** [comment]
- 0 is allowed, you must force save
- only assholes don't seed and set goals of 0

unlimited - just set no seed limit.

**Comment by Dukobpa3** [comment]
> * 0 is allowed, you must force save by doing a double click on the save button. orange text it's a warning, not an error.
> * please consider setting goals higher than 0, if no one seeds then torrents can't exist. if you can't or won't seed - pay for seedbox or switch to usenet.
> 
> unlimited - just set no seed limit in Starr and in qbit

Agree but I just want to get the similar setting as my loading tool

If my tool supports -1/0/0+ – I want to see it in the prowlarr settings

thats all.
