### ISSUE TITLE
Indexer - NZBPlanet - Unable to manually search (sonarr)

### ISSUE THREAD

**Issue by neuman1812** [Prowlarr/Prowlarr#201]
added nzbplanet to Prowlarr, which connected and added to sonarr fine. I even included the urlbase (http://localhost:8989/sonarr). I did notice when prowlarr added the indexer it does not include the prowlarr url base (http://localhost:9696/3/). I tried manually adding it, same result.

A test from prowlarr works, a test from sonarr works.

But manual searching produces no result. A trace log on prowlarr does not see any attempt to connect during a manual search. Trace logs on sonarr produce this:

https://hastebin.com/urupoqopol.yaml

--I did try this search on nzbplanet using the NON-prowlarr version, it does return a result. I also tested on more recent shows and episodes. same result.

**Comment by holl595** [comment]
This is clearly a bug, unless you are going to close all the bugs and declare them feature requests? 🤣

**Comment by bakerboy448** [comment]
well you also never bothered to fill out a bug report template nor provide trace logs 😂 

plus plenty of others, myself included, have planet working fine.  Thus more than likely a user configuration issue assuming both sonarr and prowlarr are up to date.

**Comment by jonathan-bloodworth** [comment]
Hi,

I appear to have the same issue so not sure why the bug has been closed? I'll provide some logs in a few minutes but I have had to add planet manually as an indexer. The prowlarr version is synced and tested correctly but no results are returned (they do for the manually added indexer).

**Comment by jonathan-bloodworth** [comment]
Looking at the debug logs it looks like the planet rss feed is not even hit, all my other indexers are, here's an example of what I mean for nzbgeek:

>2021-06-24 08:54:02.4|Debug|Newznab|Downloading Feed http://192.168.0.217:9696/2/api?t=tvsearch&cat=5000,5020,5030,5040,5045,5050,5070&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=378165&season=1&ep=1

If I manually go to the rss feed for the planet indexer I get a list of expected results.

Hopefully this helps anyone trying to debug this on prowlarr's side.

**Comment by neuman1812** [comment]
I posted this question in the subreddit a week ago.  Personflyer mentioned several people had issue with it, and suggested I open a github issue.

https://www.reddit.com/r/prowlarr/comments/ny4y9y/trouble_getting_nzb_indexer_to_work

I've included the trace logs.   But if you want I can try again there for support.

**Comment by bakerboy448** [comment]
@Qstick 

I reproduced this on my Prod... seems the caps call Sonarr makes is returning nothing
```2021-06-24 09:32:38.0|Trace|HttpClient|Res: [GET] http://localhost:9696/prowlarr/6/api?t=caps&apikey=(removed) 200.OK (215 ms)
2021-06-24 09:32:38.0|Debug|NewznabRequestGenerator|Indexer capabilities lacking season & ep query parameters, no Standard series search possible.```
![image](https://user-images.githubusercontent.com/55419169/123282736-648a3f80-d4d0-11eb-8469-0d95c877efa2.png)


Indexer 6 is planet

**Comment by bakerboy448** [comment]
and final answer/ following up on those sonarr logs; this appears to be a planet problem with their caps

https://api.nzbplanet.net/api?t=caps&apikey={key}
```
<searching>
<search available="yes"/>
<tv-search available="yes"/>
<movie-search available="yes"/>
<audio-search available="yes"/>
</searching>
```
https://api.nzbgeek.info/api?t=caps&apikey={key}
vs geek

```
<searching>
<search available="yes" supportedParams="q,group"/>
<tv-search available="yes" supportedParams="q,rid,tvdbid,season,ep"/>
<movie-search available="yes" supportedParams="q,imdbid,genre"/>
<audio-search available="no" supportedParams="q,album,artist,label,year,genre"/>
</searching>
```

**Comment by jonathan-bloodworth** [comment]
Sorry to comment again but why does this work when adding the indexer directly to radarr/sonarr?

**Comment by neuman1812** [comment]
> and final answer/ following up on those sonarr logs; this appears to be a planet problem with their caps
> 
> [https://api.nzbplanet.net/api?t=caps&apikey={key}](https://api.nzbplanet.net/api?t=caps&apikey=%7Bkey%7D)
> 
> ```
> <searching>
> <search available="yes"/>
> <tv-search available="yes"/>
> <movie-search available="yes"/>
> <audio-search available="yes"/>
> </searching>
> ```
> 
> [https://api.nzbgeek.info/api?t=caps&apikey={key}](https://api.nzbgeek.info/api?t=caps&apikey=%7Bkey%7D)
> vs geek
> 
> ```
> <searching>
> <search available="yes" supportedParams="q,group"/>
> <tv-search available="yes" supportedParams="q,rid,tvdbid,season,ep"/>
> <movie-search available="yes" supportedParams="q,imdbid,genre"/>
> <audio-search available="no" supportedParams="q,album,artist,label,year,genre"/>
> </searching>
> ```

Does that mean it's an issue with nzbplanet and not prowler?   Would nzbplanet need to be contacted for assistance?
