### ISSUE TITLE
Cannot update prowlarr to the latest version

### ISSUE THREAD

**Issue by darlopvil** [Prowlarr/Prowlarr#2032]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Can't update Prowlarr

### Expected Behavior

To be able to update the program

### Steps To Reproduce

Noticed prowlarr hasn't had any updates in a long time
Go to the updates tab
Several updates waiting.
Press update
Got this "Failed" little menssage in the left down corner of the screen
Go to "events".
CommandExecutor is having problems. Seems to be the cause of the problem

![imagen](https://github.com/Prowlarr/Prowlarr/assets/60988792/ea852c10-2477-4ade-bb8f-3a04723eca5d)

### Environment

```markdown
- OS: Windows 10 x64
- Prowlarr: 1.13.1.4223
- Docker Install: No
- Using Reverse Proxy: No, i think what is even this
- Browser: LibreWolf 121.0-1
```

### What branch are you running?

Master

### Trace Logs?

https://privatebin.net/?ee93a3e4787b7074#GhgHqCSJgxbdPMP5qxgkR7GQkxgMhvj9yQwWe9UVfTjA

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Already fixed https://github.com/Prowlarr/Prowlarr/commit/cd7d1571db373de08e219a2171d36011d71ba441

update manually / in place reinstall over existing
