### ISSUE TITLE
consistency

### ISSUE THREAD

**Issue by Tom-Neverwinter** [Prowlarr/Prowlarr#2037]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

https://github.com/Radarr/Radarr/releases/tag/v5.3.6.8612
https://github.com/Prowlarr/Prowlarr/releases/tag/v1.14.0.4286
https://github.com/Lidarr/Lidarr/releases/tag/v2.2.0.4045
https://github.com/Readarr/Readarr/releases/tag/v0.3.19.2437
sonarr is also doing the same thing. 

develop for one then master for another. 

can we have some consistency in the community?

### Describe the solution you'd like

standardize! 

### Describe alternatives you've considered

making a bot do this so that they pull from my own build branch and are standardized

### Anything else?

simple is best

**Comment by bakerboy448** [comment]
Servarr all do nightly => develop => master
Sonarr does develop=> main

refer to the App's FAQs for branch details
Please use [Discord](https://prowlarr.com/discord) for support/questions.
