### ISSUE TITLE
[DigitalCore] Unrelated results on search for Korean movie

### ISSUE THREAD

**Issue by esran** [Prowlarr/Prowlarr#205]
**Describe the bug**
Incorrect results being returned for Korean title search. This affects a number of indexers but was specifically tested for this issue using digitalcore. 

**To Reproduce**
1. Add the Korean title 'Way Back Home' (2013) to radarr.
2. Perform a manual search.
3. The search takes much longer than expected.
4. A large number of unrelated titles are returned.

**Expected behavior**
Expect just matches for the movie in question.

**Screenshots**
![image](https://user-images.githubusercontent.com/5937837/121784250-d6968680-cbaa-11eb-8831-3c42a4140f08.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker: Yes
 - .NET Version (System -> Status): 5.0.6
 - Browser and Version (Only needed for UI issues): Firefox 89.0 Windows 10
 - Prowlarr Version: 0.1.0.436
 - Prowlarr Branch: nightly

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

[prowlarr-digitalcore.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6642615/prowlarr-digitalcore.trace.txt)

[AB#7](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/7)

**Comment by Qstick** [comment]
Searching `집으로 가는 길 2013` on DC site gives same spew of results... This isn't something we can fix

**Comment by bakerboy448** [comment]
labels updated;  will likely close this

issue seems to be the site cannot handle korean characters being searched; this can be mitigated if the site ever properly supports an id based searched
