### ISSUE TITLE
need https://lillesky.org added to indexers

### ISSUE THREAD

**Issue by goffy59** [Prowlarr/Prowlarr#2050]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No problem, just need https://lillesky.org added somehow.

### Describe the solution you'd like

Please add https://lillesky.org to the indexer list

### Describe alternatives you've considered

RSS feeds from the site, but I prefer to add https://lillesky.org like I do all the other indexers I use.

### Anything else?

I would have loved to have an invite available for a developer to test but I do not. If anyone does please provide one to the prowlarr devs.

**Comment by bakerboy448** [comment]
GitHub is not for indexer requests
