### ISSUE TITLE
Add support for custom indexers

### ISSUE THREAD

**Issue by MrDrMcCoy** [Prowlarr/Prowlarr#2055]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

At the moment, there is no way to add custom indexers.

### Describe the solution you'd like

It would be nice to be able to add custom indexers. This would cover less popular/new indexers that haven't been added yet, as well as self-hosted options like Bitmagnet, Spotweb, NNTmux, etc. 

### Describe alternatives you've considered

One can of course add these manually to the other *arr apps, but having all indexers centrally managed is very nice.

### Anything else?

Nope.

**Comment by bakerboy448** [comment]
No plans beyond the existing:

- any Torznab via generic Torznab 
- Any newznab via generic newznab 
- Custom Cardigann YML
