### ISSUE TITLE
[FEATURE REQ] Sync download clients to *arr apps

### ISSUE THREAD

**Issue by appiekap653** [Prowlarr/Prowlarr#2064]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It would be nice to have Prowlarr as one single place to manage all indexers for all *arr apps.

You can set all indexer seeding and max grab settings already, but not the download client settings.

A lot of people have 2 download clients setup in the *arr apps.
1 for public trackers and 1 for private trackers.
Both with different pre- and post-category settings. 

At this moment you can't use Prowlarr in sync mode, because it will set all download clients back to 'any' in the *arr apps with every sync.
But if you want some seeding settings changed,  or category changes, or whatever, you have to do it in all apps again, not just in Prowlarr.

It is often requested but every time it is being answered with not needed to implement because it is a 1x configuration. but as I have detailed, it is not. It defeats the whole sync functionality. 

### Describe the solution you'd like

have the download clients and their settings also synced from Prowlarr. 

### Describe alternatives you've considered

none, manually going over every indexer in all different apps to make some changes. 

### Anything else?

none

**Comment by bakerboy448** [comment]
Duplicate of:
- https://github.com/Prowlarr/Prowlarr/issues/2022
- https://github.com/Prowlarr/Prowlarr/issues/1229
- https://github.com/Prowlarr/Prowlarr/issues/1190
- https://github.com/Prowlarr/Prowlarr/issues/583
- https://github.com/Prowlarr/Prowlarr/issues/509
- https://github.com/Prowlarr/Prowlarr/issues/323
