### ISSUE TITLE
Instance of Radarr not syncing

### ISSUE THREAD

**Issue by HStep20** [Prowlarr/Prowlarr#208]
**Describe the bug**
Prowlarr is not syncing between applications. The logs indicate that it is getting a Bad Request with the error message "'Name' Should be unique. My current 4K instance of Radarr has 0 indexers, and is the main one causing issues, so there should be no names to conflict with.
It has been occurring on previous branches as well.

I have readded my apps a couple times, and it persists through deletion/addition of the application

**To Reproduce**
Attempt to sync apps on the Settings/Apps page. No specific error pops up, but the logs indicate the error

**Expected behavior**
I expected all of my indexers to sync to my apps

**Platform Information (please complete the following information):**
 - OS: Unraid
 - Docker: Yes
 - .NET Version (System -> Status): 5.0.6
 - Prowlarr Version: 0.1.0.450
 - Prowlarr Branch: Nightly

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
Trace Logs: https://pastebin.com/0tFggwf9

**Comment by bakerboy448** [comment]
What's the indexers table for the 4k Radarr and 4k Sonarr instances look like?

**Comment by Qstick** [comment]
This generally means the apikey for Prowlarr was changed or is different than the Indexers that are setup in Sonarr/Radarr.

**Comment by HStep20** [comment]
It shows no indexers added. I can connect when I test the apps and the error/warning goes away, but when I go to sync them, it has problems.

**Comment by Qstick** [comment]
```
2021-06-13 10:50:04.5|Trace|HttpClient|Res: [POST] http://10.0.0.101:7879/api/v3/indexer: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Unable to connect to indexer, check the log for more details",
    "severity": "error"
  }
] (13 ms)
```

This typically indicates the `ProwlarrURL` you have setup in app settings is wrong, in other words Arr cannot connect back to Prowlarr using that url. It could mean you are missing urlbase or just have the wrong address. Can you check that?

**Comment by HStep20** [comment]
It seems that the problem was I had used localhost instead of the local ip in the prowlarr server box on a few apps. Interestingly though, I didn't get the same error with one instance of sonarr that had it set to localhost:port, whereas I had the error with another instance of sonarr and one of radarr. 

Solved
