### ISSUE TITLE
Query column empty for history

### ISSUE THREAD

**Issue by iamwoz** [Prowlarr/Prowlarr#210]
Query column shows no content. Have tried removing, re-adding, restarting. Occurs for Sonarr, Radarr, Lidarr (all my clients).

Version: 0.1.0.450 - nightly
Package Version: 0.1.0.450-ls25 by linuxserver.io
.NET: Yes (5.0.6)
Docker: Yes
DB Migration: 7
AppData directory: /config
Startup directory: /app/prowlarr/bin
Mode: Console
Uptime: 03:09:00

![image](https://user-images.githubusercontent.com/85816876/121820711-6ee65580-cce8-11eb-9d85-cf6fe1dfeb09.png)

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6644563/prowlarr.trace.txt)

**Comment by bakerboy448** [comment]
RSS queries do not have a query, so this is to be expected.

perhaps we can fill in a placeholder of "RSS Query" ?

**Comment by iamwoz** [comment]
Thanks, yes just tested and interactive queries have content. Placeholder == good idea
