### ISSUE TITLE
Indexer - Usenet - Tabula Rasa Can't be added (Cloudflare/403)

### ISSUE THREAD

**Issue by hr1232** [Prowlarr/Prowlarr#212]
**Description**
Tabula Rasa cannot be added ("Unable to connect to indexer, check the log for more details"). Must be a Prowlarr bug, as connection through NZBHydra2 is working just fine.

**To Reproduce**
Just add normally. As Tabula Rasa has V1 and V2 API, I tried the following API paths, all with the same result:
- /api/v1
- /api/v1/
- /api/v2
- /api/v2/
- /api/v1/api
- /api/v1/api/
- /api/v2/api
- /api/v2/api/

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/24797275/121928631-9f59de00-cd40-11eb-80cb-a90b11897dc0.PNG)

**Platform Information (please complete the following information):**
 - OS: Debian
 - Docker: Yes (linuxserver/prowlarr:develop)
 - .NET Version (System -> Status): .NET 5.0.6
 - Browser and Version (Only needed for UI issues): Firefox 89.0
 - Prowlarr Version: 0.1.0.447
 - Prowlarr Branch: Develop

**Logs**
Logs for V1 API
[v1_api-prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/6649948/v1_api-prowlarr.debug.txt)
[v1_api-prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6649949/v1_api-prowlarr.trace.txt)
[v1_api-prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/6649950/v1_api-prowlarr.txt)

Logs for V2 API
[v2_api-prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/6649954/v2_api-prowlarr.debug.txt)
[v2_api-prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6649955/v2_api-prowlarr.trace.txt)
[v2_api-prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/6649956/v2_api-prowlarr.txt)

**Comment by bakerboy448** [comment]
Logs indicate a 403 and a Cloudflare block.

If the indexer chooses to put cloudflare in front of their services...well that'll always cause issues

**Comment by hr1232** [comment]
Cloudflare chooses to leave me alone on any other site. Might of course be, that Cloudflare doesn't like Prowlarr User-Agent. However, NZBHydra2 is working fine. I'll try to contact the Indexer's maintainer and inform him of this bug report, so he/she can try to solve the Cloudflare issue (maybe by adding Prowlarr UA to a whitelist).

**Comment by bakerboy448** [comment]
Known issue:
>  btw, tabula rasa's down for a couple of days, if anyone says anything about it not working. It's not us, it's them.

**Comment by jpalenz77** [comment]
It is up again but still cannot be added, it works in Hydra tho.

**Comment by hr1232** [comment]
It's been up the entire time. And it's been working in NZBHydra the entire time.

BTW, quoting some Reddit threat with general, non-specific information is not the way to go about fixing this.

If Cloudflare allows my NZBHydra through but bans my Prowlarr (same ip address, same machine), it has to be a User Agent issue. Probably the site admin has some kind of whitelist of User Agents that may access the API. Either he/she adds Prowlarr to that whitelist (already contacted, but no answer yet), or Prowlarr devs should think about an option that NZBHydra has had for quite some time: Custom User Agents. Probably not the only Indexer that's hiding behind Cloudflare, so such a feature should come in handy regularly...

**Comment by bakerboy448** [comment]
> Prowlarr devs should think about an option that NZBHydra has had for quite some time: Custom User Agents
Covered under https://github.com/Prowlarr/Prowlarr/issues/27

Generally issues with cloudflare are a handful of Trackers that need Flaresolver; no plans to deal with those.
or, presumably for Tabula Rasa, need the Indexer Admin to add Prowlarr to the allow list.

**Comment by DariusIII** [comment]
Hello everyone. There are no *arr blocks in last 24 hours on cloudflare. I have re-enabled rules that were active before the site went down. If you encounter any issues with Tabula Rasa please send me an email through site, on forum or reddit.

**Comment by jpalenz77** [comment]
It works now! thanks!
