### ISSUE TITLE
Check private torrent (tracker) for amount of seeders and keep seeding until X amount of seeders are back.

### ISSUE THREAD

**Issue by Prankish8407** [Prowlarr/Prowlarr#2122]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Feature request, not an issue.

### Describe the solution you'd like

Would love to see a implementation to check how many seeders the torrent has before stopping it.

I use the function seed until ratio 3 for private trackers, but i'm unable to set an option for keep torrent alive until X amount of seeders + ratio is reached.

so for example: i download a torrent that has 1 seeder, then i upload it for 3 times but since there not X amount of seeders active i want it to stay alive in stead of stopping / removing the torrent.

### Describe alternatives you've considered

I haven't found a solution for it yet, therefore i request it as a feature.

### Anything else?

Yes, thanks for all the work and the awesomeness of prowlarr!

**Comment by bakerboy448** [comment]
Prowlarr has nothing to do with items in your download client, no plans for anything other than sending.

Qbit Manage can do this with share limits function and its minimum seeders attribute
