### ISSUE TITLE
Indexer - Usenet - abNZB Can't be added (429 too many requests)

### ISSUE THREAD

**Issue by hr1232** [Prowlarr/Prowlarr#213]
**Description**
abNZB cannot be added ("Unable to connect to indexer, check the log for more details"). Must be a Prowlarr bug, as connection through NZBHydra2 is working just fine.

**To Reproduce**
Just add normally.

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/24797275/121929927-104dc580-cd42-11eb-85d1-86dfb140838e.PNG)

**Platform Information (please complete the following information):**
 - OS: Debian
 - Docker: Yes (linuxserver/prowlarr:develop)
 - .NET Version (System -> Status): .NET 5.0.6
 - Browser and Version (Only needed for UI issues): Firefox 89.0
 - Prowlarr Version: 0.1.0.447
 - Prowlarr Branch: Develop

**Logs**
[abnzb_prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/6649982/abnzb_prowlarr.debug.txt)
[abnzb_prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6649983/abnzb_prowlarr.trace.txt)
[abnzb_prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/6649984/abnzb_prowlarr.txt)

[AB#6](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/6)

**Comment by bakerboy448** [comment]
```
2021-06-14 18:53:04.0|Trace|HttpClient|Res: [GET] https://abnzb.com/api?t=search&extended=1&apikey=(removed)&: 429.TooManyRequests
<?xml version="1.0" encoding="UTF-8"?>
<error code="500" description="Request limit reached. Retry in 0 minutes."/>
 (121 ms)
2021-06-14 18:53:04.0|Warn|Newznab|HTTP Error - Res: [GET] https://abnzb.com/api?t=search&extended=1&apikey=(removed)&: 429.TooManyRequests
<?xml version="1.0" encoding="UTF-8"?>
<error code="500" description="Request limit reached. Retry in 0 minutes."/>

2021-06-14 18:53:04.1|Warn|Newznab|Unable to connect to indexer

[v0.1.0.447] NzbDrone.Common.Http.TooManyRequestsException: HTTP request failed
```

could be a bug; could also be user inflicted due to trying too frequently or running out of API hits

**Comment by hr1232** [comment]
According to the profile page it is not a problem of me running out of API requests. However, I'll try to contact the Indexer's maintainer and direct him/her to this thread.
![abnzb](https://user-images.githubusercontent.com/24797275/121932837-a0d9d500-cd45-11eb-9207-adb9f06a96cc.PNG)

**Comment by bakerboy448** [comment]
Closing; can reopen if needed; added without issue on `0.1.0.639`
