### ISSUE TITLE
YGGtorrent new website and domain name

### ISSUE THREAD

**Issue by screamjojo** [Prowlarr/Prowlarr#2134]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

New domain name : ygg.re
and now YGGTorrent become a full private tracker,
Jackett need an update : https://github.com/Jackett/Jackett/issues/15314

### Expected Behavior

Login succefull

### Environment

```markdown
- OS: 
- Prowlarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannConfigException: Login failed: No form found on https://www3.yggtorrent.cool/ using form selector #user-login

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/issues/448
