### ISSUE TITLE
Cannot connect with HellasHut  

### ISSUE THREAD

**Issue by pagratios** [Prowlarr/Prowlarr#2139]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Trying to connect to indexer Hellashut and after setting Username Password and CAPTCHA I got this error

Unable to connect to indexer, check the log above the ValidationFailure for more details. Found captcha during automatic login, aborting. I tried to connect to same indexer using Jackett and it succeed.

### Expected Behavior

Connect to Hellashut indexer successfully 

### Steps To Reproduce

1.  Click on Add Indexer
2.  Search for Hellashu
3.  Set Username, Password, Search freeleech only and CAPTCA
4.  Click Save
5. I got this error : Unable to connect to indexer, check the log above the ValidationFailure for more details. Found captcha during automatic login, aborting

### Environment

```markdown
- OS: Debian 12
- Prowlarr: 1.17.2.4511
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Firefox 126
```

### What branch are you running?

Master

### Trace Logs?

debug: https://privatebin.net/?f1b077fbb93e2788#DSNrw6Fn9VHK3K7uNa3TZkTvPYi4DnkLDFSxciV1RWtC
trace: https://privatebin.net/?0c0f90cd02512c95#YnWTw8kxB78XfWcxdsRMGJEdgTDFfyETjveo9R5MmWX

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by pagratios** [comment]
I just pressed  Save not  test button. The strange thing with specific indexer is that the captcha is needed only once, after that they generate a passkey  that is used to all api calls

**Comment by iveney** [comment]
I have a same issue with other sites (tested hdfans, azusa). "Found captcha during automatic login, aborting".

I pulled an earlier version 1.15.0.4361 and the issue went away.
