### ISSUE TITLE
(Indexer) Remove non-existent/closed-down indexers

### ISSUE THREAD

**Issue by hr1232** [Prowlarr/Prowlarr#214]
The following Indexers are closed down and should be removed. Evidence is provided in form of screenshots.

**Name:** NZBs2Go
**Type:** Usenet
**URL:** https://nzbs2go.com/
**In Jackett?:** Don't know and don't care
**Reason:** Closed down according to maintainer statement
**Screenshot:**
![nzbs2go](https://user-images.githubusercontent.com/24797275/121930577-d204d600-cd42-11eb-9223-c2effc80c8f9.PNG)
 
**Name:** OZnzb
**Type:** Usenet
**URL:** https://www.oznzb.com/
**In Jackett?:** Don't know and don't care
**Reason:** Has been gone for months (if not years). All that's left is an unmanaged, outdated WordPress version
**Screenshot:**
![oznzb](https://user-images.githubusercontent.com/24797275/121931484-f7461400-cd43-11eb-879b-c03c83bf2a7c.PNG)

**Comment by bakerboy448** [comment]
appears OZ is not dead?
https://www.reddit.com/r/usenet/comments/n92ojz/cant_connect_to_oznzb/gze5zwk/

**Comment by TRaSH-** [comment]
it isn't i can just access it
