### ISSUE TITLE
"Search Freelech Only" on HD-Olimpo indexer doesn't work

### ISSUE THREAD

**Issue by Crosus97** [Prowlarr/Prowlarr#2142]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

when the freelech only option of hd-olimpo indexter is marked, this indexer doesnt receive any result

![image](https://github.com/Prowlarr/Prowlarr/assets/46854222/6fca6d8d-8454-4e63-a1ea-5fc73625e9de)

i dont know if this work with the indexer flags
This are the indexer flags
![image](https://github.com/Prowlarr/Prowlarr/assets/46854222/d3cc27c2-fca2-43a7-91e0-78cec8595904)

maybe can help

### Expected Behavior

when the options is marked must appear the Only Freeleech result with the indexer flag Freeleech

### Steps To Reproduce

1. usea any enviorment and any S.O 
2. add and hd-olimpo with a correct api key
3. mark the 
![image](https://github.com/Prowlarr/Prowlarr/assets/46854222/1406ad7a-95d9-4218-a340-7b333d5b395d)

4. the query must only search a freeleech option

### Environment

```markdown
- OS: 22.04
- Prowlarr: 1.17.2.4511
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome 125.0.6422.114
```

### What branch are you running?

Master

### Trace Logs?

2024-05-31 18:29:53.3|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc.
2024-05-31 18:30:01.9|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc.
2024-05-31 18:30:18.4|Info|Prowlarr.Http.Authentication.BasicAuthenticationHandler|Basic was not authenticated. Failure message: Authorization header missing.

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
> Reports may be closed if the required logs are not provided.

**Comment by Crosus97** [comment]
Logs replication the error

**Comment by bakerboy448** [comment]
prowlarr's messaging is accurate. the site failed to return any results, you'd need to ask them why

```
2024-05-31 19:27:37.2|Trace|Cardigann|No releases found. Response: {
    "data": [],
    "links": {
        "first": "https://hd-olimpo.club/api/torrents/filter?page=1",
        "last": "https://hd-olimpo.club/api/torrents/filter?page=1",
        "prev": null,
        "next": null,
        "self": "https://hd-olimpo.club/api/torrents"
    },
    "meta": {
        "current_page": 1,
        "from": null,
        "last_page": 1,
        "links": [
            {
                "url": null,
                "label": "&laquo; Anterior",
                "active": false
            },
            {
                "url": "https://hd-olimpo.club/api/torrents/filter?page=1",
                "label": "1",
                "active": true
            },
            {
                "url": null,
                "label": "Siguiente &raquo;",
                "active": false
            }
        ],
        "path": "https://hd-olimpo.club/api/torrents/filter",
        "per_page": "100",
        "to": null,
        "total": 0
    }
}
```

**Comment by Crosus97** [comment]
Let's see if I can try to clarify something.

This error occurs when I select said box. Who is responsible for that Button? hd-olympus or prowlarr? because I added it from the prowlarr repository

If I don't check that button, the indexer searches everything.

Who is in charge of the prowlarr repository? Because it seems like a problem that comes from there

**Comment by bakerboy448** [comment]
The issue is the site fails to return any results and a freeleech only search is done. That is a site issue.

**Comment by ilike2burnthing** [comment]
Conversation was had before, a bunch of variations were tried, but nothing seemed to work:
- https://github.com/Prowlarr/Indexers/issues/407
- https://github.com/Jackett/Jackett/commit/4bdef1b3902e286a644b365e5b718102f5a911d9

In terms of other similar trackers, there's not a whole lot of variation:
- https://github.com/search?q=repo%3AProwlarr%2FIndexers+%22json+UNIT3D+6%22+%22.Config.freeleech%22&type=code

Unless a member can get an answer from the admins, this can't be fixed. I suspect they might have disabled freeleech searching in the API.

@Crosus97 if you're not able to get an answer in a few days, I think it would be better to remove the setting from the indexer.

**Comment by ilike2burnthing** [comment]
Removed.

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/30144bc0f6d4201bef2ace58d281d6a5e851ae0a
