### ISSUE TITLE
[torrentgalaxy] (testing) Exception (torrentgalaxy): Relogin failed: Parse error

### ISSUE THREAD

**Issue by Yumega** [Prowlarr/Prowlarr#2148]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

torrentgalaxy failed 

### Expected Behavior

don't work

### Environment

```markdown
- OS: openwrt
- Prowlarr:
- Docker Install:yes
- Using Reverse Proxy:no
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

https://github.com/Jackett/Jackett/issues/15358

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Invalid bug report
