### ISSUE TITLE
Bitmagnet Indexer

### ISSUE THREAD

**Issue by Junktroep** [Prowlarr/Prowlarr#2149]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Base url is an dropdown with http://localhost:3333 this cannot be modified to another url.
This limits running of bitmagnet on the same box as prowlarr.

### Expected Behavior

Freedom of specifying custom url.

### Steps To Reproduce

1. add indexer
2. select BitMagnet (Local DHT)
3. Base URL is a non customizable localhost entry

### Environment

```markdown
- OS: Debian 12
- Prowlarr:1.18.0.4543
- Docker Install:yes
- Using Reverse Proxy:yes
- Browser:Edge (latest)
```

### What branch are you running?

Master

### Trace Logs?

NA

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [ ] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Write a custom definition
