### ISSUE TITLE
Checks for Messages and notifications on the tracker

### ISSUE THREAD

**Issue by christianmerges** [Prowlarr/Prowlarr#2152]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have to login to all the trackers periodically to check for messages and notifications. Because most of them don't send e-mail notifications.

### Describe the solution you'd like

It would be nice to make prowlarr chowing an unread Message/Notifications counter in the table of trackers. So i need to only login, if there is something.

**Comment by bakerboy448** [comment]
No plans
