### ISSUE TITLE
Video search show video resolution

### ISSUE THREAD

**Issue by RuneMason1** [Prowlarr/Prowlarr#2153]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'm working on curating a 4k movie library with a focus on ultra wide compatible (no black bars above/below) and I'd love to see the resolution displayed when searching (or at least have the option). 

### Describe the solution you'd like

Option to display the resolution of searched media as a column 

### Describe alternatives you've considered

Clicking each release to view the info manually one at a time. 

### Anything else?

Nothing else

**Comment by bakerboy448** [comment]
No plans to try to scrape and display the media info or a nfo for additional release info.

All releases that are not 16:9 will always have black bars.  Target imax / imax-e releases or releases made specifically for TV viewing/ 16:9 format.

Quality which is source+resolution is typically already available in the release names.

**Comment by RuneMason1** [comment]
That's not true though. I even went through releases to specifically find one that wasn't 16:9 earlier. Most releases were 4000 by 2000 (can't remember the exact numbers) but this one was 4000 by like 1600. Black bars aren't always hard coded, and there really isn't a big reason why they should be, tbh. The playback device should be left to display the video where it fits.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RuneMason1** [comment]
I can provide screenshots illustrating what I mean if that's helpful

**Comment by bakerboy448** [comment]
they won't be as it doesn't change the premise of the denial nor the denial
