### ISSUE TITLE
[Add and Remove only] removing a tag does not delete indexer from App

### ISSUE THREAD

**Issue by galeksandrp** [Prowlarr/Prowlarr#2155]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

1. When I have App in [Add and Remove only] mode, adding a indexer with tag any other than in app will do nothing for that app (will skip adding that indexer). This is expected behaviour, all good and dandy.

2. But if we other way around, removing Prowlarr tag from indexer that already exist in App does not delete indexer from App.

3. Despite that, removing indexer with any set of tags from Prowlarr entirely will remove it from App.

This looks like sophisticately deliberate decision to acknowlege tags on indexer adding, but ignore tags on indexer removal.

### Describe the solution you'd like

[Add and Remove only] mode need to add/delete indexer to App like in [Full Sync] mode.

### Describe alternatives you've considered

[Full Sync]. I am actually using [Full Sync] for all Apps, except one where I need [Add and Remove only].

### Anything else?

I am not experienced *arr stack user, there may be like popular case for [Add and Remove only] users when autoadd/autodelete indexers on retagging will break everything in the world.

What do you think?

**Comment by bakerboy448** [comment]
Trace logs of a sync after removing a tag?

**Comment by galeksandrp** [comment]
Okay, please clarify.

As far as I am aware, in [Add and Remove only] mode the will not be any Sync after removing a tag.
In [Add and Remove only] any Sync is started only when indexer is added or removed in Prowlarr itself.

So which `sync` `trace logs` are you requesting? There will not be any `sync` `trace logs` in this mode after removing a tag.
