### ISSUE TITLE
Provide a knob to attempt IPv6 first, then fallback on IPv4 (instead of the opposite)

### ISSUE THREAD

**Issue by RomLecat** [Prowlarr/Prowlarr#2156]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Prowlarr checks the existence of IPv4 and disables IPv6 if IPv4 is working (https://github.com/Prowlarr/Prowlarr/blob/9f075c09a2c12cedb7e58c9478a7faf4eac8c664/src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs#L332).

I use a Kubernetes dual-stack environment with proper IPv4+IPv6, and I'm not willing to disable IPv6, due to security issue of using sysctl in pods, and we're in 2024, IPv6 should not be disabled. The pod running Prowlarr and FlareSolverr both have Affinity rules that cause them to run on a same node, and share the same IPv4 and IPv6 (NAT by the CNI on the node itself).

The issue is that indexers that uses FlareSolverr to bypass CloudFlare are broken, because FlareSolverr works in IPv6, and therefore generates a CloudFlare cookie only valid for IPv6 address. Once IPv6 is disabled in Prowlarr, the IP is not the same (because Prowlarr is doing IPv4) and the cookie is invalided, causing requests to fail.

If we're doing an indexer check right after Prowlarr starts, it works because Prowlarr has not disabled IPv4 yet, therefore all requests come from proper IP.

### Describe the solution you'd like

A knob to cancel the current behaviour, and still run IPv6 even if IPv4 is available. Or a knob to prefer IPv6 over IPv4 when IPv6 is available.

### Describe alternatives you've considered

Disabling IPv6 in the pod, but this is really inconvenient on Kubernetes, and a potential security issue (https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#setting-sysctls-for-a-pod).

### Anything else?

I know that IPv6 is not super popular, and I'm aware of the recommendations of disabling it in both FlareSolverr and Prowlarr. But in this case, everything would work properly without the IPv4 forced fallback. 

I'm also aware of https://github.com/dotnet/runtime/issues/26177, but it only applies if IPv6 is broken.
If IPv6 is working properly (as it should anyway), we should be able to disable IPv4-only if we're confident IPv6 is working properly (even if it's not the default).

Thanks for your work!

**Comment by bakerboy448** [comment]
This is what already occurs. Read the comment on the line above the code you link 

https://github.com/Prowlarr/Prowlarr/commit/a25e79031f263764c2402370588b4f16a5b64109

**Comment by RomLecat** [comment]
The comment says "// Do not retry IPv6 if a routable IPv4 address is available, otherwise continue to attempt IPv6 connections."
The code says that when IPv4 is working, IPv6 is disabled. IPv6 is left enabled only if IPv4 is not present.

This issue is about keeping IPv6 enabled if it is working, even if IPv4 is also working (dual-stack).

**Comment by RomLecat** [comment]
The title was likely a bit misleading, I edited it.

Could you please re-open @bakerboy448 ?

**Comment by RomLecat** [comment]
Huuuh, after re-reading, I understand it slightly better. You do some sort of happy-eyeballs yourself (https://github.com/Prowlarr/Prowlarr/blob/9f075c09a2c12cedb7e58c9478a7faf4eac8c664/src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs#L318).

I think it's triggering wrongly in my environment (perhaps because IPv6 latency is a bit higher in my environment than IPv4, although if I understand correctly, the timeout is 2000ms, which I'm definitely not hitting due to IPv6 over IPv4).
However it keeps IPv6 disabled for the lifetime of the container, which is not good.

Is there some debug I can enable to see why this is triggering ?

**Comment by bakerboy448** [comment]
That code is only hit after ipv6 fails.

Please use [Discord](https://prowlarr.com/discord) for support/questions.
