### ISSUE TITLE
Dognzb

### ISSUE THREAD

**Issue by KlausStortebeker** [Prowlarr/Prowlarr#2165]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Dognzb is pointing to https://www.dognzb.cr

### Expected Behavior

Dognzb has their api at https://api.dognzb.cr

### Environment

```markdown
- OS: Debian 11
- Prowlarr: 1.20.0.4570
- Docker Install: no
- Using Reverse Proxy: nginx 
- Browser: Not important
```

### What branch are you running?

Master

### Trace Logs?

Is not important again because I have multiple indexers but because of the wrong link the dognzb would stop working properly.

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
invalid bug report
https://github.com/Prowlarr/Prowlarr/blob/a1d19852dc38914a715b26bad2e2abe5a9fe124c/src/NzbDrone.Core/Indexers/Definitions/Newznab/Newznab.cs#L97

**Comment by bakerboy448** [comment]
Please use [Discord](https://prowlarr.com/discord) for support/questions.

**Comment by KlausStortebeker** [comment]
Oh nevermind I should have done this on discord but I don't use it.
