### ISSUE TITLE
Add a buffer amount setting

### ISSUE THREAD

**Issue by arthurmelton** [Prowlarr/Prowlarr#2167]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

For me at least, I keep freeleech only all the time for trackers with harsh economies. I don't want to risk the chance that prowlarr will grab a big torrent or an *arr wants to fill a request and eats up more than my buffer can withstand for a tracker.

### Describe the solution you'd like

I don't know if this would be the best solution but maybe there could be a settings to set how much buffer you are allowing a tracker to use. Say I put in 100gb, and it grabs a torrent for 75gb, it would automatically assume that I have downloaded the whole thing and set my buffer setting to 25gb. Say it tries to search for another torrent, and a result is 50gb, it would not show up on the list because it is bigger than the buffer that is currently set.

### Describe alternatives you've considered

I have thought about using the grab limits, but I would prefer to not have to constantly baby it and watch to see if my buffer is getting too low and to disable it. It also does not see any difference between a 100mb torrent and 100gb torrent.

I though about prowlarr potentially automatically grabbing the buffer size for each tracker, but I though that maybe some people would want to maintain a specific ratio so that would not be viable.

### Anything else?

The biggest problem I see with the solution is that the user would have to go into prowlarr every once in a while and update there buffer for each provider. If your buffer is quite low, then you might have to come in every few days, but I think once you get a more healthy buffer you could just come in once a month and just update the numbers.

**Comment by bakerboy448** [comment]
- No plans to support tracker ratio/buffers
- Prowlarr does not and will never grab anything by itself. You or another app that you configured tells Prowlarr exactly what to grab.

**Comment by arthurmelton** [comment]
> Prowlarr does not and will never grab anything by itself.

I know that, but I mean to not show it in query results. It would be just like the freeleech only toggle.
