### ISSUE TITLE
Unable to add CinemaZ

### ISSUE THREAD

**Issue by sadstan** [Prowlarr/Prowlarr#219]
Unable to add CinemaZ indexer.

**To Reproduce**
1. Go to Indexers
2. Click on 'Add Indexers'
3. Search for 'CinemaZ'
4. Click on 'CinemaZ'
5. Enter username and password. Click on 'Test'
6. Notice the error 'Unable to connect to indexer, check the log for more details'

**Expected behavior**
The indexer test passes, and shows a green tick on the 'Test' button

**Screenshots**
N/A

**Platform Information (please complete the following information):**
 - OS: Windows 10 v21H1 (OS Build 19043.1052); Ubuntu Ubuntu 20.04.2 LTS (WSL2)
 - Docker: Yes (Docker version 20.10.7, build f0df350; docker-compose version 1.29.2, build 5becea4c)
 - .NET Version (System -> Status): Yes (5.0.6)
 - Browser and Version (Only needed for UI issues): Not a UI issue
 - Prowlarr Version:     0.1.0.458
 - Prowlarr Branch:      nightly-4c93f51 by hotio 

Trace logs: https://0bin.net/paste/1cG4am7f#yyZSQKqcfuKENLr898vw+lvKgjgTWCgy5HFMg7b-5bM

Ref:
https://discord.com/channels/767843854736949299/767843854824374281/854338987534712838

**Comment by Qstick** [comment]
Are you entering PID?

**Comment by sadstan** [comment]
The issue was with CinemaZ on their end. It was resolved. Prowlarr works fine now. Thanks :)

**Comment by jeliastam** [comment]
@sadstan having this problem currently, how did you resolve it?

**Comment by jeliastam** [comment]
@sadstan nevermind... I just joined and I think im not high enough rank yet to use the API, apologies, thanks
