### ISSUE TITLE
Add additional URL to BitMagnet indexer definition to allow connections within docker-compose stack

### ISSUE THREAD

**Issue by tyrells** [Prowlarr/Prowlarr#2196]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently the only Base URL defined for the BitMagnet (Local DHT) indexer is `http://127.0.0.1:3333/`. When using Prowlarr and BitMagnet as part of a single docker-compose stack file (i.e. [Servarr wiki Docker guide](https://wiki.servarr.com/docker-guide)), you cannot connect to a different container in the same stack using the localhost IP address, but must rather use the `container_name` specified for the particular container you are trying to connect to.

### Describe the solution you'd like

Add a second Base URL in the BitMagnet indexer definition file as follows `http://bitmagnet:3333/`. This is the `container_name` used in the [official bitmagnet installation instructions](https://bitmagnet.io/setup/installation.html).

### Describe alternatives you've considered

Add additional common container names too, although I don't think this should be considered, as it has already been rejected in this issue: https://github.com/Prowlarr/Prowlarr/issues/2149

### Anything else?

N/A

**Comment by tyrells** [comment]
Moving to Indexers repo

**Comment by bakerboy448** [comment]
PR upstream to https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/bitmagnet.yml
and it'll get pulled to Indexers next sync
