### ISSUE TITLE
Convert Desitorrents.tv to support Gazelle

### ISSUE THREAD

**Issue by theworldhealer1** [Prowlarr/Prowlarr#220]
Desitorrents.tv indexer does not work. It was recently fixed in Jackett [here](https://github.com/Jackett/Jackett/issues/11904).

[AB#9](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/9)

**Comment by bakerboy448** [comment]
close when this is resolved https://requests.prowlarr.com/b/feedback/p/torrent-desi-torrents
