### ISSUE TITLE
"Ignored Addresses" routing through proxy & not being ignored

### ISSUE THREAD

**Issue by Permanently** [Prowlarr/Prowlarr#2203]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm routing Prowlarr to Radarr through `172.21.0.1`, and I've added it to the ignored addresses section on the proxy section. Despite this, whenever proxy is enabled, it tries to route this through SOCKS5.

Current setting for Ignored Addresses: `100.64.0.0/10, 192.168.0.0/16, 172.21.0.1, 172.16.0.0/12, 127.0.0.1, localhost`
(by the way, I know I put both the CIDR and the IP. I put the IP after being convinced CIDRs didn't work)

**With proxy enabled**

![chrome_xZ5hzJgGOc](https://github.com/user-attachments/assets/a711d8cb-9a44-44cb-8d8c-b2d5ac34a274)
![chrome_N6Dp1G4xlE](https://github.com/user-attachments/assets/4e674d1b-0e03-45d8-b2f4-d0294cc25eaa)

**Without proxy enabled**
![chrome_x0ATKZbSVQ](https://github.com/user-attachments/assets/52bfb63a-e4ca-4a95-998d-697eb706c4d1)
![chrome_GQzZ2xUkZ5](https://github.com/user-attachments/assets/ed998ec9-e198-4829-98fe-5bdb22360a96)

### Expected Behavior

I expected the IP I specified to not be routed through proxy.

### Steps To Reproduce

1. Run Prowlarr on Docker: ghcr.io/linuxserver/prowlarr:develop (1.21.2.4649-ls187)
2. Set the SOCKS5 proxy in Settings > General
3. Add Ignored Addresses
4. Try to access Radarr/Sonarr through IP that is on Ignored Addresses
5. Observe

### Environment

```markdown
- OS: Ubuntu 24.04
- Prowlarr: 1.21.2.4649
- Docker Install: Yes, 1.21.2.4649-ls187 by linuxserver.io
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Master

### Trace Logs?

https://gist.github.com/Permanently/31da979e7dfa2ea4f4605b4b4454bae8

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Permanently** [comment]
Apologies - was looking in Docker logs instead, have updated with [GitHub Gist link](https://gist.github.com/Permanently/31da979e7dfa2ea4f4605b4b4454bae8) to the trace logs

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/blob/99f9a0b4e6f354d2406a95605b113a7d3912c5ba/src/NzbDrone.Core/Http/HttpProxySettingsProvider.cs#L53C29-L53C37

**Comment by bakerboy448** [comment]
remove the spaces. the list is comma separated, not comma space separated

`100.64.0.0/10,192.168.0.0/16,172.16.0.0/12` works

**Comment by Permanently** [comment]
This is still an issue, even when removing spaces.
https://gist.github.com/Permanently/cfb33dddacdd4adae4375f4f127dc1c9

![chrome_btUZwRL6t5](https://github.com/user-attachments/assets/89951874-50d5-47d6-b4f6-6f8da33aabb1)

![chrome_VeDlJ3o5cB](https://github.com/user-attachments/assets/07b7a758-ee8e-4638-8025-d1c8d9fc94e6)

**Comment by bakerboy448** [comment]
```csharp
        private HttpProxySettings GetProxySettings()
        {
            return new HttpProxySettings(ProxyType.Socks5, "localhost", 8080, "100.64.0.0/10,192.168.0.0/16,172.21.0.1,172.16.0.0/12", true, null, null);
        }

        [Test]
        public void should_bypass_proxy()
        {
            var settings = GetProxySettings();

            // Subject.ShouldProxyBeBypassed(settings, new HttpUri("http://eu.httpbin.org/get")).Should().BeTrue();
            // Subject.ShouldProxyBeBypassed(settings, new HttpUri("http://google.com/get")).Should().BeTrue();
            Subject.ShouldProxyBeBypassed(settings, new HttpUri("http://localhost:8654/get")).Should().BeTrue();
            Subject.ShouldProxyBeBypassed(settings, new HttpUri("http://172.21.0.1:8989/api/v3/indexer/schema")).Should().BeTrue();
        }
```

tests pass

```csharp
        private HttpProxySettings GetProxySettings()
        {
            return new HttpProxySettings(ProxyType.Socks5, "localhost", 8080, "100.64.0.0/10,192.168.0.0/16,172.16.0.0/12", true, null, null);
        }

        [Test]
        public void should_bypass_proxy()
        {
            var settings = GetProxySettings();

            // Subject.ShouldProxyBeBypassed(settings, new HttpUri("http://eu.httpbin.org/get")).Should().BeTrue();
            // Subject.ShouldProxyBeBypassed(settings, new HttpUri("http://google.com/get")).Should().BeTrue();
            Subject.ShouldProxyBeBypassed(settings, new HttpUri("http://localhost:8654/get")).Should().BeTrue();
            Subject.ShouldProxyBeBypassed(settings, new HttpUri("http://172.21.0.1:8989/api/v3/indexer/schema")).Should().BeTrue();
        }
```

tests fail.

@mynameisbogdan  seems its CIDR possibly?

**Comment by Permanently** [comment]
> It should fail since `172.16.0.0/12` doesn't contain `172.21.0.1`.

Yes it does? Goes from 172.16.0.1 to 172.31.255.254
