### ISSUE TITLE
AlphaRatio indexer is not working when option "Use freeleech tokens when available" is enabled

### ISSUE THREAD

**Issue by Smexhy** [Prowlarr/Prowlarr#2206]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I tick option in AlphaRatio indexer to "Use freeleech tokens when available", I get this error:

```
Invalid request Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc.
```

I am unable to save the changes with this option enabled and indexer gets disabled because of this error. Last time I was able to use this option without issue was around 5 months ago.

### Expected Behavior

After ticking the option to use FL tokens, I am expecting Prolwarr to automatically use the token on any non-freeleech torrents when grabbing them.

### Environment

```markdown
- OS: Ubuntu 24.04.1
- Prowlarr: 1.21.2.4649
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Safari 17.6
```

### What branch are you running?

Develop

### Trace Logs?

```
2024-09-01 13:39:29.1|Debug|AlphaRatio|Downloading Feed https://alpharatio.cc/ajax.php?action=browse&order_by=time&order_way=desc
2024-09-01 13:39:29.8|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc.
2024-09-01 13:39:29.8|Debug|Api|[PUT] /api/v1/indexer/57: 400.BadRequest (307 ms)
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Please do not check the trace log / following wiki box when the instructions were not followed.
