### ISSUE TITLE
DivTeam tracker cannot be added

### ISSUE THREAD

**Issue by jpalenz77** [Prowlarr/Prowlarr#221]
**Describe the bug**

When trying to add DivTeam with the very same cookie I use in Jackett or with a new one FWIW it doesnt pass the test.

**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
https://pastebin.com/qrpFUaKw

**Comment by bakerboy448** [comment]
those are not trace logs.

and please fully fill out the bug report form.

**Comment by jpalenz77** [comment]
Sorry, here you go: https://pastebin.com/kD4YwSs1

prowlarrs version: 0.1.0.447
hotios docker
ubunto 20.04

thanks

**Comment by Qstick** [comment]
Wanna try on 464 with bbea256

**Comment by jpalenz77** [comment]
working on .468
