### ISSUE TITLE
Indexer "Bitsearch" doesn't sync to the Apps even though it's enabled

### ISSUE THREAD

**Issue by lpapadakos** [Prowlarr/Prowlarr#2210]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

During Indexer Sync in the Prowlarr UI there is nothing out of the ordinary, however in the indexer settings of Sonarr and Radarr the index is not being added. I think this is because Prowlarr expects the indexer to return some categories that its not returning?

The fact that the indexer is inside the list when adding a new one, indicates that it's supported and it at least used to work at some point.

### Expected Behavior

Sync finishes and the Bitsearch indexer is visible in Sonarr and radarr Indexer settings.

### Steps To Reproduce

1. Add Bitsearch indexer and enable it
2. Click "Sync App Indexers" and wait for it to finish
3. Go to Sonarr/Radarr Indexer Section. Bitsearch is not there.

### Environment

```markdown
- OS: Arch Linux x86_64
- Prowlarr: 1.23.1.4708
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox 131
```

### What branch are you running?

Master

### Trace Logs?

[prowlarr.trace.txt](https://github.com/user-attachments/files/16873652/prowlarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by lpapadakos** [comment]
@mynameisbogdan Ok I didn't know such a buried place inside the modal could have a message, thansk for the answer

The message itself doesn't really help users regarding what to do next. I added it manually though Torznab on Sonarr but from what I can see, I went into Settings > Apps and on the categories for Soanrr and Radarr, added the Other (8000) Category as a valid sync category, and now it syncs correctly. I think the message should mention that this can be done in Prowlarr's settings.

And the location of the message should be on the top of the modal

**Comment by lpapadakos** [comment]
Honestly I might that's a good idea. At least the text.

**Comment by colemar** [comment]
I had the same issue. Solved adding category 8000 in  Prowlarr/Settings/Apps/Radarr/Sync Categories (must enable advanced settings). BitSearch synched immediately.
**TorrentsCSV still does not appear in Radarr**, despite it having (only) category 8000.
