### ISSUE TITLE
Not enough meaningful description of the app function in README

### ISSUE THREAD

**Issue by slrslr** [Prowlarr/Prowlarr#2214]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This repository:

> About
> No description or website provided. 

README:

> Prowlarr is an indexer manager/proxy ... supports management of ... Torrent Trackers

It seems like I am not the only one who does not understand that description: https://news.ycombinator.com/item?id=36380303

I am currently using [Jackett](https://internetlifeforum.com/showthread.php?28331-How-to-search-many-torrent-trackers-thanks-to-Jackett-with-qBittorrent-client) as my search engine and also [integrated using plugin into my bittorrent client qBittorrent](https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin). Into Jackett I have added easily tens of torrent trackers and i can search all these in one search.

What Prowlarr can do beside indexing trackers? I think that this is not described on prominent place on this repo homepage.

### Describe the solution you'd like

Update the description/s to be like: Prowalarr allows/can be useful for 1)... 2)... 3)....

### Describe alternatives you've considered

-

### Anything else?

-

**Comment by bakerboy448** [comment]
This is covered on the readme and in the wiki.

**Comment by slrslr** [comment]
I am not using Discord and this issue is related to this repository.

> This is covered

In the readme it is not covered the way I have described, hard to find (not on a prominent place), hard to understand:
> Manual searching of Trackers & Indexers at a category level
> Support for pushing multiple releases at once directly to your download clients from Prowlarr

In the wiki? Are you joking?! When people are linked/come to this official repository/page they expect to find on an easy to spot place what this software will allow them doing. You have failed in this.

**Comment by bakerboy448** [comment]
> In the readme it is not covered the way I have described, hard to find (not on a prominent place), hard to understand:

if you're unable to read the readme that clearly lists the features then there is no where this information can be placed.

Perhaps you should PR what specifically you want as no one agrees with / understands your interpretation.

it appears many of questions are related to basic torrent / Usenet terms and the readme is not intended to explain these concepts.

**Comment by thezak48** [comment]
I don't see how this is hard to understand

> Prowlarr is an indexer manager/proxy built on the popular *arr .net/reactjs base stack to integrate with your various PVR apps. Prowlarr supports management of both Torrent Trackers and Usenet Indexers. It integrates seamlessly with Lidarr, Mylar3, Radarr, Readarr, and Sonarr offering complete management of your indexers with no per app Indexer setup required (we do it all).

**Comment by slrslr** [comment]
>  should PR what specifically you want

I can not since I do not know what the app can do.

@thezak48 yours quoted text makes no or too little sense to someone who does not use any *arr apps (though may be interested in them) and does not make them understand what the software is doing. "Complete management" does not tell much. I can do a complete management in a notepad... When you first mention an "indexer" in that paragraph, it should be described what it is, ideally without the need to continue reading and find the answer in the next sentences, where you mention "Usenet indexer", no link to explanation what is that. My main complaint is that it is not easy to find what is that "management".

If you argument that it is explained somewhere in https://github.com/Prowlarr/Prowlarr#major-features-include

maybe:
`- Manual searching of Trackers & Indexers at a category level
- Support for pushing multiple releases at once directly to your download clients from Prowlarr`

then why it is "hidden" below hard to understand features like:
"Support for custom YML definitions via Cardigann"

The software description should list key features in a prominent place in first couple sentences, not hidden like that. End of rant, sorry.

**Comment by bakerboy448** [comment]
> I can not since I do not know what the app can do.

It's important to note that Prowlarr and other *arr apps are part of an ecosystem tailored for users familiar with concepts like torrent trackers and Usenet indexers. Typically, someone wouldn't stumble upon Prowlarr unless they were already exploring this space, where understanding these terms is fundamental. Prowlarr's key functionality is to manage and sync these indexers across the mentioned apps like Sonarr and Radarr, streamlining the process significantly. It automates what would otherwise be a manual and repetitive setup task, making it an invaluable tool for those in this ecosystem.
