### ISSUE TITLE
The Horror Channel tracker cannot be added

### ISSUE THREAD

**Issue by jpalenz77** [Prowlarr/Prowlarr#222]
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
https://pastebin.com/aJQPAWcA

**Comment by bakerboy448** [comment]
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/122

Please search prior to posting

**Comment by jpalenz77** [comment]
ups, sorry
