### ISSUE TITLE
ZonaQ tracker cannot be added

### ISSUE THREAD

**Issue by jpalenz77** [Prowlarr/Prowlarr#224]
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
https://pastebin.com/gTdZinhN

**Comment by bakerboy448** [comment]
those are not trace logs.

and please fully fill out the bug report form.

**Comment by jpalenz77** [comment]
sorry here you are https://pastebin.com/Qpe1cu08

prowlarrs version: 0.1.0.447
Hotios docker
ubuntu 20.04

**Comment by jpalenz77** [comment]
working on .468
