### ISSUE TITLE
Cannot Disable Indexer that is Down

### ISSUE THREAD

**Issue by DrSeussFreak** [Prowlarr/Prowlarr#226]
**Describe the bug**
I have an indexer that has been offline for a week or so.  I am trying to disable it, but if I uncheck "Enabled" I cannot click save, as it validates the indexer, which fails, due to being offline.

**To Reproduce**
1. Uncheck Enable on an indexer
2. Click Save

**Expected behavior**
I would hope that having  "Enabled" unchecked, it would skip validation, it does not

**Screenshots**
![Screen Shot 2021-06-15 at 11 14 54 AM](https://user-images.githubusercontent.com/175500/122088043-02905280-cdcb-11eb-8c40-cd6c46e03ab1.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - .NET Version (System -> Status): Yes (5.0.6)
 - Browser and Version (Only needed for UI issues): Chrome 91.0.4472.106
 - Prowlarr Version: 0.1.0.458
 - Prowlarr Branch: nightly

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6657443/prowlarr.trace.txt)

Edit: new trace log uploaded

**Comment by bakerboy448** [comment]
those are not logs; they are an HTML dump?

**Comment by DrSeussFreak** [comment]
No idea what happened, just edited my OP and provided the logs.

FYI, download in the UI for the logs seems to download the page I previously uploaded, not the log itself.

**Comment by bakerboy448** [comment]
Download Link on the Logs tab works fine; based on the file that was there, it appears to be a misconfiguration with `Authelia` on your end.

**Comment by DrSeussFreak** [comment]
ahh, ok, I will have to look at that then, thanks

**Comment by bakerboy448** [comment]
Possible Interim Workaround - Hit Save Twice

**Comment by DrSeussFreak** [comment]
that is not working for me, I just hit save repeatedly (maybe 10 times in a row) and it won't save

**Comment by bakerboy448** [comment]
Could not reproduce this on `0.1.0.471`

Added RarBG -> Blocked RarBG's site at the host -> Test and failed as expected -> Uncheck `Enabled` -> Save, no issue

**Comment by DrSeussFreak** [comment]
I just tested it on `0.1.0.481` and it worked for simplynzbs but not for oznzb (both are listed as down right now)
