### ISSUE TITLE
Faster saving after editing indexer

### ISSUE THREAD

**Issue by GeoffreyCoulaud** [Prowlarr/Prowlarr#2279]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When saving an indexer after renaming it (or changing something else unrelated to connectivity) a connectivity test seems to be performed, wasting time.

### Describe the solution you'd like

Saving after changing fields unrelated to indexer connectivity shouldn't trigger a test.

### Describe alternatives you've considered

- Dealing with it, and lose a couple of seconds when saving (which is... fine)
- Avoid editing tracker metadata (not realistic)
- Using the API to edit metadata (unpractical)

### Anything else?

Thanks for the software, I know how time consuming that is.

**Comment by bakerboy448** [comment]
@mynameisbogdan  feasibility of tracking which fields change and maintain and inclusionary or exclusionary list of connectivity critical values?

seems like heavy lift, low reward.   a double save (i.e. force save) seems like the easy option?

**Comment by GeoffreyCoulaud** [comment]
I didn't even know that there is a double save, you're right that would be a great solution !
