### ISSUE TITLE
Torrentleech "Search freeleech only" setting doesn't work

### ISSUE THREAD

**Issue by cameronrbrown** [Prowlarr/Prowlarr#2283]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I tick the box for "Search freeleech only" under settings for Torrentleech, Prowlarr still grabs non-freeleech torrents.

### Expected Behavior

I expect torrents not tagged as "freeleech" to not be fetched

### Environment

```markdown
- OS: Windows 11
- Prowlarr: 1.25.4.4818
```

### What branch are you running?

Master

### Trace Logs?

no

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Invalid bug report. Incomplete report. Logs required and refused; closing
