### ISSUE TITLE
Redacted URL Change

### ISSUE THREAD

**Issue by undaunt** [Prowlarr/Prowlarr#2287]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Redacted has updated its website domain from redacted.ch to redacted.sh when they came back from recent downtime.

### Expected Behavior

Add or replace the existing base URL option of redacted.ch with redacted.sh.

### Environment

```markdown
- OS: Ubuntu 24.04 LTS
- Prowlarr: 1.26.1.4844
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

```
Invalid request Validation failed: -- : Unable to connect to indexer, please check your DNS settings and ensure IPv6 is working or disabled. Name does not resolve (redacted.ch:443)
Unable to connect to indexer: Name does not resolve (redacted.ch:443)
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Already done in nightly https://github.com/Prowlarr/Prowlarr/commit/b447db5d08f9fa0127570375efdee4478bbaee97

**Comment by bakerboy448** [comment]
Same as https://github.com/Prowlarr/Indexers/issues/499
