### ISSUE TITLE
(Indexer) Torrents | Norbits 

### ISSUE THREAD

**Issue by Sebbis1981** [Prowlarr/Prowlarr#229]
Type: Torrents
Tracker: Norbits
URL: https://norbits.net
In Jackett?: Yes

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/issues/29

> Request an indexer for Prowlarr. Check the pinned Jackett parity issue prior to submitting a request. Duplicated requests will be closed without warning. Please search GitHub prior to requesting.
