### ISSUE TITLE
Torrent Blackhole overwrites files with identical names

### ISSUE THREAD

**Issue by phoenixtetra** [Prowlarr/Prowlarr#2295]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When using Torrent Blackhole as the download client, if multiple torrents with the same name are downloaded, the later torrents overwrite the earlier ones. At the end, only the last torrent file remains.

### Expected Behavior

If a torrent file with the same name already exists, a number in parentheses is appended to the new file. Ideally, it would be even better to prefix every torrent file with the tracker's name: `[Tracker]Title.torrent`.

### Steps To Reproduce

Bulk download two or more torrents with identical names.

### Environment

```markdown
- OS: Windows 11 24H2
- Prowlarr: Prowlarr 1.27.0.4852
- Docker Install: No
- Using Reverse Proxy: No
- Browser: -
```

### What branch are you running?

Master

### Trace Logs?

https://katb.in/prowlarr.trace

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
@markus101 upstream nzb and torrent blackhole naming conflict thoughts?

**Comment by markus101** [comment]
Don't use blackhole?

Honestly it seems like such an edge case and putting more effort into a "client" that we recommend no one really use doesn't make a lot of sense to me.

If you try to add a duplicate torrent to a client it will fail most of the time as well.

**Comment by bakerboy448** [comment]
No plans for this at this time.

Torrent clients would error in the same situation.
