### ISSUE TITLE
Load balance/Round Robin or Script To Rotate Priority

### ISSUE THREAD

**Issue by blakeusblade** [Prowlarr/Prowlarr#2298]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Having multiple indexers and priority is equal. Results in the first indexer added into the interface ALWAYS being used and doesnt load balance or round robin between the indexers.

Please see my request on sonarr 
https://github.com/Sonarr/Sonarr/issues/7472

### Describe the solution you'd like

Can you please add a way to load balance / round robin when priorities are equal?
or
Can you provide an example API call that I can use to script rotation of the priority every 15 mins between 1, 2 or however many indexers I have setup?

### Describe alternatives you've considered

This possible feature request to grant load balancing/round robining between indexers with equal priority
or
A script I can run to change priority on schedule

### Anything else?

Please see my request on sonarr 
https://github.com/Sonarr/Sonarr/issues/7472

**Comment by bakerboy448** [comment]
> Can you please add a way to load balance / round robin when priorities are equal?

- Prowlarr has nothing to do with how applications that interact with its api process or rank downloads
- Indexer priority is nothing more than a tiebreaker and no plans for any round robin functionality.

> Can you provide an example API call that I can use to script rotation of the priority every 15 mins between 1, 2 or however many indexers I have setup?

the api docs are public and UI is lipstick on the api. You can see the network calls the UI makes from your browser's development tools
