### ISSUE TITLE
(Indexer) Torrents | bj-share.info

### ISSUE THREAD

**Issue by beriom** [Prowlarr/Prowlarr#230]
**Type:**  Torrents

**Tracker:** BJ-Share

**URL:** bj-share.info

**In Jackett?:**  Yes

**Additional Context:**

**Comment by bakerboy448** [comment]
> Request an indexer for Prowlarr. Check the [Jackett GHI](https://github.com/Prowlarr/Prowlarr/issues/29) & search GitHub prior to submitting a request. Duplicate requests will be closed.
