### ISSUE TITLE
Indexer - Rarbg - G_Freeleech flag not applied in Radarr

### ISSUE THREAD

**Issue by KnifeFed** [Prowlarr/Prowlarr#234]
**Describe the bug**
Rarbg doesn't have the `G_Freeleech` indexer flag applied in Radarr as Jackett does.

I don't think any other info is needed, otherwise please let me know and I'll add it.

**Comment by bakerboy448** [comment]
wanna fill out the remainder of the template you decided to nuke?

**Comment by Qstick** [comment]
Radarr needs updates to support how Prowlarr does flags.

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/issues/6268 to be percise

**Comment by KnifeFed** [comment]
> Radarr needs updates to support how Prowlarr does flags.

I see. So how come e.g. 1337x, LimeTorrents, and ETTV from Prowlarr have the `G_Freeleech` flag?
