### ISSUE TITLE
[Feature Request] Add application support to sync indexers with Mylar3

### ISSUE THREAD

**Issue by kingfenix** [Prowlarr/Prowlarr#237]
**Is your feature request related to a problem? Please describe.**
Would like indexers to sync with mylar in the same way as Sonarr/Readarr/Radarr so that I can use prowlarr without having to add/remove/edit indexers manually

**Describe the solution you'd like**
Mylar has created some API endpoints specifically for this usage. Using these API endpoints in mylar3, prowlarr should be able to add mylar as a built in application to choose from for syncing indexers. Also the indexers would use category 7030.
listProviders - https://github.com/mylar3/mylar3/wiki/listProviders
addProvider - https://github.com/mylar3/mylar3/wiki/addProvider
delProvider - https://github.com/mylar3/mylar3/wiki/delProvider
changeProvider - https://github.com/mylar3/mylar3/wiki/changeProvider

**Comment by Roxedus** [comment]
#86 is still open.

**Comment by kingfenix** [comment]
yes, but I wanted to provide this new information and links to the API

**Comment by bakerboy448** [comment]
Duplicate of #86

**Comment by bakerboy448** [comment]
Landed https://github.com/Prowlarr/Prowlarr/commit/77892a3885a0675e9cc53a48a6fe9b28011cb7a6
