### ISSUE TITLE
[feature request] sub-search within query results

### ISSUE THREAD

**Issue by sirloinofbeef** [Prowlarr/Prowlarr#243]
Both Jackett & NZBHydra have the ability to search with manual query results without re-polling the indexers. It would be great to have this feature in Prowlarr.

[AB#18](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/18)

**Comment by bakerboy448** [comment]
Covered under #27 I believe

>  12. Ad-hoc filter and sort results by title, indexer, category, size, number of hits, age
