### ISSUE TITLE
Allow season packs and other parameters in search results

### ISSUE THREAD

**Issue by BEisem** [Prowlarr/Prowlarr#247]
**Describe the solution you'd like**
Similar to Sonarr, it would be great to be able to search only for season packs (or alternatively, to disregard season packs) when searching for TV shows. You could even expand on this, and allow search results to be filtered by resolution, Quality, etc...

**Additional context**
With a large number of indexers, Sonarr sometimes fails when doing an interactive search. In these cases, it would be helpful to be able to search from within Prowlarr with as many of the same search features and parameters that are available in Sonarr, since the search in Prowlarr seems to be much faster and more efficient.

[AB#17](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/17)

**Comment by bakerboy448** [comment]
> With a large number of indexers, Sonarr sometimes fails when doing an interactive search. 

Sonarr does not fail with long interactive searches. Your reverse proxy would be timing out.

> it would be great to be able to search only for season packs

this is already possible. All Sonarr does for a season pack search is searches the season parameter only without any episode specified.  this would be evident in the logs for requests from sonarr. Simply do a tv search and specify the season parameter + series name or ID

https://wiki.servarr.com/prowlarr/search#performing-a-search
