### ISSUE TITLE
Support for Torrent RSS Feeds

### ISSUE THREAD

**Issue by Sahasrahla** [Prowlarr/Prowlarr#248]
**Is your feature request related to a problem? Please describe.**
I have Torrent RSS Feeds in Sonarr/Radarr, but I cannot add them to Prowlarr.

**Describe the solution you'd like**
An Indexer Type in Prowlarr matching the functionality of Torrent RSS Feeds from Sonarr/Radarr

**Describe alternatives you've considered**
My current alternative is leaving the Torrent RSS Feed configured manually in each *arr app.

**Additional context**
I have one Indexer that wishes to remain REALLY anonymous. The forum software does not use TorzNab format, but it does allow for RSS feeds. Before Prowlarr, I have configured this site into *arr apps as a Torrent RSS Feed and it works wonderfully. I would like to add it to Prowlarr simply so it can sync across all my apps with all my other Indexers.

**Comment by TRaSH-** [comment]
New and only place for a indexer request => https://requests.prowlarr.com/
