### ISSUE TITLE
TorrentParadise - 400.BadRequest

### ISSUE THREAD

**Issue by costaht** [Prowlarr/Prowlarr#251]
**Describe the bug**
When adding TorrentParadise to the list of enabled indexers, an exception occurs and Prowlarr can't finish the process. 
The exception happens right after the message `[v0.1.0.497] System.Exception: Got redirected to another domain`.

**To Reproduce**
1. Go to Indexer
2. Click on Add indexer
3. Find "TorrentParadise" on the list
4. Try to add it and the error will occur.

**Expected behavior**
The addition of the new indexer

**Screenshots**

![Screenshot from 2021-06-20 19-57-28](https://user-images.githubusercontent.com/50637431/122692228-ccefcd00-d201-11eb-9c06-837864053ad2.png)

**Platform Information (please complete the following information):**
 - OS: CentOS 8 Stream 
 - Docker: No 
 - .NET Version (System -> Status): 5.0.6 
 - Browser and Version (Only needed for UI issues): 
 - Prowlarr Version: 0.1.0.497
 - Prowlarr Branch: nightly

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

https://paste.centos.org/view/099119be

**Comment by Qstick** [comment]
This crashes out because of a redirect to another domain, this will be solved by alternate link support

**Comment by Qstick** [comment]
This should be fixed in latest indexer push https://github.com/Prowlarr/Indexers/commit/fbe0206124eaafe02fa80656dd74ac9304b2aea2
