### ISSUE TITLE
[Feature Request] Add Join test server as an option for notifications

### ISSUE THREAD

**Issue by ChronoStriker1** [Prowlarr/Prowlarr#254]
In connections add a dropdown, checkbox, or seperate entry to use the Join test server instead of the normal one.  
This is usefull to people currently using the Join Destop App due to using firefox or other non compatible browsers instead of google chrome.

Normal APIAddress:  https://joaomgcd.appspot.com
Test API Address:  https://testsjoaomgcd.appspot.com

**Comment by Qstick** [comment]
Not sure I quite understand the use case for this. Can you explain a bit more why one would use the test server?

**Comment by ChronoStriker1** [comment]
Users who can't use the Join Google Chrome extension, because they are using Firefox or an incompatible chromium build (i.e. brave, ungoogled chromium, etc.) Currently can use a desktop app instead that uses the test address for its api currently. So devices on the test address can't talk to devices/apps on the normal one. 

Jun 21, 2021 9:46:48 PM Qstick ***@***.***>:

**Comment by Qstick** [comment]
> Users who can't use the Join Google Chrome extension, because they are using Firefox or an incompatible chromium build (i.e. brave, ungoogled chromium, etc.) Currently can use a desktop app instead that uses the test address for its api currently. So devices on the test address can't talk to devices/apps on the normal one. Jun 21, 2021 9:46:48 PM Qstick ***@***.***>:
> […](#)

Got it

**Comment by bakerboy448** [comment]
Closing per https://www.reddit.com/r/JoinApp/comments/o69c7k/dev_join_30_works_in_firefox_and_edge_local/
