### ISSUE TITLE
Indexer - P2PElite - Unable to Add

### ISSUE THREAD

**Issue by afraazali** [Prowlarr/Prowlarr#262]
**Describe the bug**
Unable to connect P2PElite tracker

**To Reproduce**

1. Go to Indexer
2. Click on 'Add Indexer'
3. Scroll down to 'P2PElite'
4. Add credentials
5. Click Test button

**Expected behavior**

It should connect successfully

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Ubuntu 
 - Docker: Yes 
 - .NET Version (System -> Status): 5.0.1 
 - Browser and Version (Only needed for UI issues): N/A 
 - Prowlarr Version: 0.1.0.515 
 - Prowlarr Branch: nightly 

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

https://0bin.net/paste/aEkzzyhM#vDXk3ohzguChQ3Exw65gp6nth5HXkc+yRDU7w9ckZWS

[AB#24](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/24)

**Comment by skuizy** [comment]
Sign ups are open : https://p2pelite.com/signup.php
