### ISSUE TITLE
Indexer - Usenet - Gingadaddy - Fails Test

### ISSUE THREAD

**Issue by veritas2884** [Prowlarr/Prowlarr#265]
I just set up Prowlarr and 3 of my 4 NZB trackers work perfectly. 
Gingadaddy fails testing and will not save. However, it will work directly in SONARR and RADARR.
I've tried using both the Prowlarr suggested URL: https://www.gingadaddy.com and the SONARR suggested one : https://www.gingadaddy.com/api.php

Thank you for creating this awesome program and for any help.

**Comment by bakerboy448** [comment]
please edit and fill out the bug template
https://github.com/Prowlarr/Prowlarr/issues/new?assignees=&labels=Type%3A+Bug&template=bug_report.md&title=

**Comment by Qstick** [comment]
Ginga has a netoriously bad API, but the following should work

![image](https://user-images.githubusercontent.com/376117/123188471-16daec00-d46a-11eb-9c48-5887f702e354.png)

Closing this until we get a log or more info from the template
