### ISSUE TITLE
[BroadcastheNet] Punctuation in Title Returns 0 Results

### ISSUE THREAD

**Issue by Ayfteyd7Od** [Prowlarr/Prowlarr#266]
**Describe the bug**

When searching BTN for titles that include punctuation like _Ms Fisher's Modern Murder Mysteries_ or _Superman & Lois_, Prowlarr returns 0 results. The same search works with the native BroadcastheNet indexer in Sonarr. It appears Prowlarr is changing or removing the punctuation. 

For example, 
_Ms Fisher's Modern Murder Mysteries_ is changed to _Ms Fishers Modern Murder Mysteries_
_Superman & Lois_ is changed to _Superman and Lois_

**To Reproduce**

1. In Sonarr, add both Prowlarr BTN indexer & native BTN indexer.
2. Search for title that includes punctuation.
3. Only the native Sonarr BTN indexer returns results.
4. Check search history in Prowlarr and confirm no results for BTN searches. Punctuation appears to be stripped or altered from the search.

**Expected behavior**

Prowlarr search results should be same as native indexer search results.

**Screenshots**

N/A

**Platform Information (please complete the following information):**
 - OS:  N/A
 - Docker:  Yes
 - .NET Version (System -> Status):  .NET 5.0.6
 - Browser and Version (Only needed for UI issues):  N/A
 - Prowlarr Version:  0.1.0.447
 - Prowlarr Branch:  develop

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

https://privatebin.net/?6238e1600b139f49#ECt4o8zY7RcR6QWdgydp3Wtj7tdkuQC3sWjkC2dgzHmU

**Comment by Qstick** [comment]
I'm fairly certain this is an issue with how arr handles torznab queries. Your log shows that if a search with punctuation is presented to Prowlarr then it returns results without issue. 

```
2021-06-23 13:31:52.5|Debug|NzbSearchService|Total of 21 reports were found for {Term: Ms Fisher's Modern Murder Mysteries, Offset: 0, Limit: 0, Categories: []} from 1 indexers
2021-06-23 13:31:52.5|Trace|Http|Res: 15243 [GET] /api/v1/search?query=Ms%20Fisher%27s%20Modern%20Murder%20Mysteries&indexerIds=15: 200.OK (694 ms)
```

Sonarr is cleaning the search before sending it to Prowlarr. Prowlarr cannot add back punctuation it knows nothing about unfortunately.

**Comment by bakerboy448** [comment]
https://github.com/Sonarr/Sonarr/issues/1225

Yup it's an *arr issue

**Comment by bakerboy448** [comment]
at least partly unintentionally fixed in https://github.com/Prowlarr/Prowlarr/commit/d5b34e8c038f140627b807a40552e76d5d17d9a1

BTN in Prowlarr was missing reporting that it supports ID based searches

**Comment by markus101** [comment]
Sonarr will not strip punctuation if `capabilities.TextSearchEngine` is set to "raw" for Torznab/Newznab, if it's unset or set to any other value this will be removed.
