### ISSUE TITLE
Error when running ./build

### ISSUE THREAD

**Issue by mattias197711** [Prowlarr/Prowlarr#267]
\# build.sh
Row: 200
"
    cp -r $outputFolder/$framework-windows/$runtime/publish/* $folder
"
\# spits out this:

yarn run v1.22.5
$ esprint check

Done in 7.71s.
Finish 'ESLint'
Start 'Stylelint'
yarn run v1.22.5
$ stylelint $(find frontend -name '*.css') --config frontend/.stylelintrc
Done in 2.52s.
Finish 'Stylelint'
Start 'Creating Windows Package for net5.0'
Adding LICENSE
cp: cannot stat '_output/net5.0-windows/win-x64/publish/*': No such file or directory

\# To Solve it: edit build.sh and remove *-windows from #Quote

\# 
My box info
ubuntu 20.04 with alot of ppa stuff dev,stable,nightly and so on..
\#
ii  dotnet-apphost-pack-5.0                                     5.0.7-1                                                        amd64        Microsoft.NETCore.App.Host 5.0.7
ii  dotnet-host                                                 5.0.7-1                                                        amd64        Microsoft .NET Host - 5.0.7
ii  dotnet-hostfxr-5.0                                          5.0.7-1                                                        amd64        Microsoft .NET Host FX Resolver - 5.0.7 5.0.7
ii  dotnet-runtime-5.0                                          5.0.7-1                                                        amd64        Microsoft .NET Runtime - 5.0.7 Microsoft.NETCore.App 5.0.7
ii  dotnet-runtime-deps-5.0                                     5.0.7-1                                                        amd64        dotnet-runtime-deps-5.0 5.0.7
ii  dotnet-sdk-5.0                                              5.0.301-1                                                      amd64        Microsoft .NET SDK 5.0.301
ii  dotnet-targeting-pack-5.0                                   5.0.0-1                                                        amd64        Microsoft.NETCore.App.Ref 5.0.0

yarn@1.22.5
npm@7.18.1
Mono JIT compiler version 6.13.0
NuGet Version: 5.6.0.6489

\# just playing around.. cant get it to build on my system :) its good sometimes to have ADHD/ADD

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.  It builds fine.

**Comment by mattias197711** [comment]
ok.

sorry.
