### ISSUE TITLE
Implement Indexer Specific Flags to Provide Users with More Info

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#273]
As another note, with our new flag system in prowlarr we can define indexer specific flags. This would allow us to call these out as limited-freeleech to give the user more information if we think it's worthwhile

_Originally posted by @Qstick in https://github.com/Prowlarr/Prowlarr/issues/270#issuecomment-867212540_

... For future discussion and thinking. Not any time in the immediate future.

[AB#28](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/28)

**Comment by Qstick** [comment]
This should be specific to an indexer, this is already done for a few of them

**Comment by Qstick** [comment]
Closing this as it's super generic and the functionality is there in general.. open an issue if we need to add a flag to a particular indexer
