### ISSUE TITLE
Mass Editor Delete Failing - 415 Unsupported Media Type

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#275]
**Describe the bug**

Deleting Indexers via Mass Editor fails with 415 Unsupported Media Type

**To Reproduce**

1. Mass Editor
2. Select Indexer(s)
3. Hit Delete
4. Hit Yes

**Expected behavior**

Indexer(s) are deleted

**Screenshots**

**Platform Information (please complete the following information):**
 - OS:  agnostic
 - Docker: agnostic
 - .NET Version (System -> Status): agnostic
 - Browser and Version (Only needed for UI issues): agnostic
 - Prowlarr Version:  0.1.0.525
 - Prowlarr Branch:  nightly

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

```
2021-06-23 23:56:57.9|Debug|Api|[POST] /api/v1/command: 201.Created (89 ms)
2021-06-23 23:56:59.0|Trace|Http|Req: 64 [GET] /favicon.ico?h=Nrb6aZ5ZHAbcTkj/ZJxsSg (from ::1)
2021-06-23 23:56:59.0|Trace|Http|Res: 64 [GET] /favicon.ico?h=Nrb6aZ5ZHAbcTkj/ZJxsSg: 200.OK (3 ms)
2021-06-23 23:57:02.6|Trace|Http|Req: 65 [DELETE] /api/v1/indexer/editor (from ::1)
2021-06-23 23:57:04.8|Trace|Http|Res: 65 [DELETE] /api/v1/indexer/editor: 415.UnsupportedMediaType (2137 ms)
2021-06-23 23:57:04.8|Debug|Api|[DELETE] /api/v1/indexer/editor: 415.UnsupportedMediaType (2137 ms)
```

***Additional Notes***

**Request Headers:**

```
DELETE /api/v1/indexer/editor HTTP/1.1
Host: localhost:9696
Connection: keep-alive
Content-Length: 18
Pragma: no-cache
Cache-Control: no-cache
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"
DNT: 1
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
X-Api-Key: {removed}
Origin: http://localhost:9696
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:9696/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,it;q=0.6

```
**Form Data**
`{"indexerIds":[1]}`

**Response**
```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
  "title": "Unsupported Media Type",
  "status": 415,
  "traceId": "00-63d644e3f0a7a846b9b924517ccc2e29-0452e3f1dc624843-00"
}
```

[AB#26](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/26)

**Comment by johnsturgeon** [comment]
Is there any other way to delete indexers?

**Comment by bakerboy448** [comment]
@johnsturgeon  Indexers -> Edit Indexer (Wrench Icon) -> Delete
