### ISSUE TITLE
Per-Indexer option to use a proxy

### ISSUE THREAD

**Issue by ArthurMitchell42** [Prowlarr/Prowlarr#281]
**Is your feature request related to a problem? Please describe.**
In some countries some indexers are blocked and need a tor proxy to access them

**Describe the solution you'd like**
Being able to route all access to specific indexers through a proxy would allow access to them and not overload/not block all indexers on failure

**Describe alternatives you've considered**
Route all traffic through proxy? but this would cause a bandwidth/data rate restriction and if the proxy docker container goes down or looses connection you'd loose all indexers rather than just the proxied ones
My current setup is hydra with 2 instances of jackett, one of which routes through torprivoxy. It would be nice to simplify this.

**Additional context**
TorPrivoxy is my prefered server for this

[AB#29](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/29)

**Comment by ArthurMitchell42** [comment]
You are a gentleman and a scholar, thank you!

**Comment by icf20** [comment]
any alternative for TorPrivoxy looks abandoned

**Comment by bakerboy448** [comment]
> any alternative for TorPrivoxy looks abandoned

Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.
