### ISSUE TITLE
Add ability to select downloader tag/category when manually searching

### ISSUE THREAD

**Issue by misleadingrhino** [Prowlarr/Prowlarr#304]
**Is your feature request related to a problem? Please describe.**
No. It's a current feature of NZBHydra.

**Describe the solution you'd like**
When doing a manual search and downloading, add a pop-up to select the downloader category to use(books, movies, etc...) instead of a blanket one for all Prowlarr downloads. 

[AB#1158](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1158)

**Comment by bakerboy448** [comment]
Please review the pinned issue / search prior to posting

https://github.com/Prowlarr/Prowlarr/issues/27

downloader # 6

**Comment by misleadingrhino** [comment]
Thanks, guess I didn't understand what that meant.
