### ISSUE TITLE
Manual Search not respecting Category selections

### ISSUE THREAD

**Issue by misleadingrhino** [Prowlarr/Prowlarr#305]
When doing a manual search and selecting individual categories, all categories are being returned. Looking at the log, it appears this is happening with torrents but not with usenet. The category appears to be sent when querying usenet indexers but not torrent indexers. 

**To Reproduce**
1. Go to search. 
2. Select categories (I've noticed this with comics and books/comics). 
3. Search for something. 
4. Results come back from all categories. 

**Expected behavior**
1. Results come back only from the selected categories.

**Screenshots**
![Screenshot 2021-07-01 at 08-59-57 Prowlarr](https://user-images.githubusercontent.com/14330129/124129107-72e5d780-da4b-11eb-82fc-87f86c2d68b9.png)

**Platform Information (please complete the following information):**
Version    0.1.0.568
Package Version   nightly-aa70086 by hotio 
.NET   Yes (5.0.6)
Docker    Yes
DB Migration   7
Mode    Console

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
[Prowlarr-2021-07-01.txt](https://github.com/Prowlarr/Prowlarr/files/6748395/Prowlarr-2021-07-01.txt)

[AB#1159](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1159)

**Comment by bakerboy448** [comment]
Reproduced with TorrentDB 

> 2021-07-01 08:15:36.2|Trace|HttpClient|Res: [GET] https://torrentdb.net/filter/torrents?categories[]=1&freeleech=1&search=21&tags=&sorting=created_at&direction=desc&qty=100: 200.OK (623 ms)

Also reproduced with BeyondHD

seems we're dropping the cats somewhere

> 2021-07-01 08:18:47.7|Trace|Http|Req: 927 [GET] /prowlarr/api/v1/search?query=21&indexerIds=14&categories=2000 (from 67.*.*.254)
2021-07-01 08:18:47.7|Info|NzbSearchService|Searching indexers: [BeyondHD] for {Term: 21, Offset: 0, Limit: 0, Categories: [2000]}
2021-07-01 08:18:47.7|Debug|BeyondHD|Downloading Feed https://beyond-hd.me/api/torrents/ff7c4786301ae900690fabcac5c4540e
2021-07-01 08:18:47.7|Trace|HttpClient|Req: [POST] https://beyond-hd.me/api/torrents/{removed will PR}
2021-07-01 08:18:47.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-07-01 08:18:48.3|Trace|HttpClient|Res: [POST] https://beyond-hd.me/api/torrents/{removed - will PR}: 200.OK (646 ms)

**Comment by bakerboy448** [comment]
Reproduced with TorrentDB 

> 2021-07-01 08:15:36.2|Trace|HttpClient|Res: [GET] https://torrentdb.net/filter/torrents?categories[]=1&freeleech=1&search=21&tags=&sorting=created_at&direction=desc&qty=100: 200.OK (623 ms)

Also reproduced with BeyondHD

seems we're dropping the cats somewhere

> 2021-07-01 08:18:47.7|Trace|Http|Req: 927 [GET] /prowlarr/api/v1/search?query=21&indexerIds=14&categories=2000 (from 67.*.*.254)
2021-07-01 08:18:47.7|Info|NzbSearchService|Searching indexers: [BeyondHD] for {Term: 21, Offset: 0, Limit: 0, Categories: [2000]}
2021-07-01 08:18:47.7|Debug|BeyondHD|Downloading Feed https://beyond-hd.me/api/torrents/{removed will PR}
2021-07-01 08:18:47.7|Trace|HttpClient|Req: [POST] https://beyond-hd.me/api/torrents/{removed will PR}
2021-07-01 08:18:47.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-07-01 08:18:48.3|Trace|HttpClient|Res: [POST] https://beyond-hd.me/api/torrents/{removed - will PR}: 200.OK (646 ms)

**Comment by Junkbite** [comment]
i dont have TorrentDB but was unable to reproduce with AinimeBytes. Are there any other trackers this is happening with or only TorrentDB?

**Comment by bakerboy448** [comment]
@Junkbite 

I can reproduce with TorrentDB and BHD (don't have many more trackers otherwise)

![image](https://user-images.githubusercontent.com/55419169/124168687-15fa1980-da6b-11eb-8303-ec8b3bad8600.png)
![image](https://user-images.githubusercontent.com/55419169/124169049-5f4a6900-da6b-11eb-9a3a-eebaa170dab7.png)


AnimeByes is a C#
TorrentDB is cardigann
BHD is C# and uses BHD's API

**Comment by Junkbite** [comment]
Id say this is a backend thing since the category query string param is being sent to the api but the api is still returning all results. can be filtered out on the frontend as well though

**Comment by PearsonFlyer** [comment]
I've confirmed this is a problem on my torrent searches as well (IPTorrents, ImmortalSeed, 1337x, and HD-Torrents). This appears to be an issue with ALL torrent searches, but not any usenet searches.

**Comment by PearsonFlyer** [comment]
A couple of these have now been fixed. Some others are more difficult (like 1337x, for example).

**Comment by Qstick** [comment]
A blanket fix is not in place, but we should also fix definitions as they come up.
