### ISSUE TITLE
[request] Ability to filter indexers when adding

### ISSUE THREAD

**Issue by Marthisdil** [Prowlarr/Prowlarr#306]
Would be great to have some filters dynamically available in the add indexer list.

Things like:
nzb/torrent
public/private
languages

Thanks for everything!

[AB#1160](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1160)

**Comment by Lagicrus** [comment]
Is this what you are looking for? https://github.com/Prowlarr/Prowlarr/pull/178

**Comment by bakerboy448** [comment]
please search prior to posting

Duplicate of https://github.com/Prowlarr/Prowlarr/issues/94
