### ISSUE TITLE
Feature toggle: Disable id-search and fallback to word-search on a per tracker basis

### ISSUE THREAD

**Issue by giddorah** [Prowlarr/Prowlarr#321]
**Discussion about prowlarr returning a huge amount of search results on interactive search**
https://www.reddit.com/r/prowlarr/comments/oewngt/interactive_search_feedback/

Short version: Prowlarr has support for id-searching tv-episodes. If the tracker isn't setup correctly this means there will be a huge amount of results rendering prowlarr basically useless, which is very unfortunate considering how awesome it is on everything else.

**A feature toggle can solve this**
So how about a feature toggle on every tracker you add which allows the user to disable the id-search and fallback to a word search. This would give the search results a user expects and also not mess up the current trackers.

[AB#1222](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1222)

**Comment by ta264** [comment]
I think this should really be fixed in the indexer definition so it just works, rather than requiring the user to change settings to make it work properly

**Comment by giddorah** [comment]
Just wondering why this was closed?

**Comment by ta264** [comment]
See my comment above
