### ISSUE TITLE
Support indexer advanced settings

### ISSUE THREAD

**Issue by etomm** [Prowlarr/Prowlarr#322]
When you add an indexer in Radarr (or sibling project) you are able to access some advanced settings like *Multi Languages*, *Additional parameters*, *seed time*, *seed ratio* etc.

It would be good to be able to synchronize them too, or through the indexer properties or the profile properties.

[AB#1225](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1225)

**Comment by bakerboy448** [comment]
Duplicate of #106
