### ISSUE TITLE
Distribute download clients too

### ISSUE THREAD

**Issue by etomm** [Prowlarr/Prowlarr#323]
Seen that indexer and download clients are strictly related it would be good that Prowlarr would distribute the download clients too.

[AB#1226](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1226)

**Comment by bakerboy448** [comment]
Closing and tabling for maybe one day

no plans at this time to sync download clients
