### ISSUE TITLE
Add SelectOptionsString to FieldDefinition

### ISSUE THREAD

**Issue by AthAshino** [Prowlarr/Prowlarr#330]
**Is your feature request related to a problem? Please describe.**
I'm trying to add an Indexer to Prowlarr (which need c#). But when I need to add a string selector there is no option to do it actually.
In my example :
I want to add "MULTI REPLACEMENT" setting, which will return "FRENCH", "TRUEFRENCH" or "MULTI.FRENCH". But to do it, I need to add a fielddefinition that get an enum as SelectOptions. The problem is that the enum will give a number, not the string wanted (normal, it's an enum).

**Describe the solution you'd like**
The solution would be to add a SelectOptionsString that take a dictionnary to return the string value

**Describe alternatives you've considered**
Actually I changed the get function of the setting so it return a string based on the enum

[AB#1245](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1245)

**Comment by Qstick** [comment]
Don't mind the number, the string is shown in the select box.. But hop on discord to discuss. Further if you want to hide the num values as well, it's doable (and we do it in Radarr in cases)

Example

```
    public enum FileListCategories
    {
        [FieldOption]
        Movie_SD = 1,
        [FieldOption]
        Movie_DVD = 2,
        [FieldOption]
        Movie_DVDRO = 3,
        [FieldOption]
        Movie_HD = 4,
        [FieldOption]
        Movie_HDRO = 19,
        [FieldOption]
        Movie_BluRay = 20,
        [FieldOption]
        Movie_BluRay4K = 26,
        [FieldOption]
        Movie_3D = 25,
        [FieldOption]
        Movie_4K = 6,
        [FieldOption]
        Xxx = 7
    }
```    

![image](https://user-images.githubusercontent.com/376117/125217808-93a1fe80-e28f-11eb-92b2-315b56c8ab29.png)
