### ISSUE TITLE
Wiki Script Issues

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#331]
https://github.com/Prowlarr/Prowlarr/blob/wiki-indexer-script/Convert-ProwlarrSupportedIndexersToMarkdownTable.ps1

- [x] Lines 94 and 95 need slightly less r and n;  output fails markdownlint

- [x] output file is a binary file

[AB#1247](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1247)

**Comment by bakerboy448** [comment]
Using this script now; running manually
https://gist.github.com/bakerboy448/2ea70252d88df74477229dc9df9cb59c

**Comment by RobinDadswell** [comment]
@bakerboy448  this is fixed now right?
