### ISSUE TITLE
Better support for RARBG indexer

### ISSUE THREAD

**Issue by agneevX** [Prowlarr/Prowlarr#333]
**Is your feature request related to a problem? Please describe.**

- RARBG consistently returns no results for random periods of time. 
- There’s no retries currently, which should be done due to a very problematic API
- During arr RSS Sync, if there's zero results returned, it is **not** marked as a failure, when it should be
- IMDb/~~TVDB/TMDB~~ search doesn't work

Jackett, in comparison returns results somewhat better.

**Describe the solution you'd like**

- Support site links (pre-determined list of proxies/user-defined), retries like Jackett:

<img src="https://user-images.githubusercontent.com/19761269/125171371-845c7b80-e1d1-11eb-8edf-5ab5d51bd8ca.jpeg" width="270">

- Mark indexer as a failure if RSS Sync returns zero results and API returns `200`.
- Support IMDb ~~/TVDB/TMDB~~ search by auto detection. API docs:

![81C1EFA8-12AF-42A3-A705-CDC010B8227A](https://user-images.githubusercontent.com/19761269/125235532-3d20d880-e300-11eb-8762-f85ea9988e08.jpeg)

**Describe alternatives you've considered**

**Additional context**

[AB#1248](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1248)

**Comment by Qstick** [comment]
> * There’s no retries currently, which should be done due to a very problematic API

 Typically this just makes the issue worse as more people will be bombarding the API with retries and additional requests, given their API is trash and seem to be not just overloaded I'd be willing to hardcode this to 2.

> Jackett, in comparison returns results somewhat better.

Define better? we do the same search

> * Support site links (pre-determined list of proxies/user-defined), retries like Jackett:

We do support them, but I'll need a list to add alternate URLs for Rarbg

> Mark indexer as a failure if RSS Sync returns zero results and API returns 200.

This is problematic and we likely won't do it. It would result in too many notifications due to the state of their API

> * Support IMDb ~/TVDB/TMDB~ search by auto detection. API docs:

IMDB is supported, TVDB is not currently. But will be within the hour.

**Comment by agneevX** [comment]
> but I'll need a list to add alternate URLs for Rarbg

There's so many, but here's a list:

```url
https://rarbg.to
https://rarbgprx.org
https://proxyrarbg.org
https://rarbgget.org
https://rarbgproxied.org
```

> IMDB is supported

Not really. It still uses `search_string` instead of `search_imdb`:

```
2021-08-04 11:14:44.1|Trace|HttpClient|Req: [GET] https://torrentapi.org/pubapi_v2.php?mode=search&search_string=tt3480822&ranked=0&limit=100&token=(removed)&format=json_extended&app_id=Prowlarr
2021-08-04 11:14:44.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-08-04 11:14:45.1|Trace|HttpClient|Res: [GET] https://torrentapi.org/pubapi_v2.php?mode=search&search_string=tt3480822&ranked=0&limit=100&token=(removed)&format=json_extended&app_id=Prowlarr: 200.OK (1006 ms)
2021-08-04 11:14:45.1|Trace|Rarbg|{"error":"No results found","error_code":20}
```

It has to automatically detect the preceding `tt` and parse it accordingly. 

In Sonarr, for episode searches, I'm not seeing any IMDb searches for RARBG

<img width="518" alt="image" src="https://user-images.githubusercontent.com/19761269/128129149-874635d0-b6f4-4bbf-8e20-0ed830a66ebf.png">

For TVDB, I'm not sure how it'll be used for manual search, since there isn't a known prefix. Besides, Sonarr only searches in IMDb besides string?

**Comment by bakerboy448** [comment]
Series IMDB => #392

**Comment by agneevX** [comment]
Thought it'd be better to create a separate issue.
