### ISSUE TITLE
Pull Sonarr Commit: Log Real IP on Authentication failure in case of a reverse proxy

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#35]
fix up https://github.com/Prowlarr/Prowlarr/blob/develop/src/Prowlarr.Http/Authentication/AuthenticationService.cs

https://github.com/Sonarr/Sonarr/commit/686a14cdff63fcffe4fceee1f9a06d0b2dc3e813

**Comment by RobinDadswell** [comment]
Already I'm so not needed
