### ISSUE TITLE
Indexer - Swarmazon - Unable to connect to indexer

### ISSUE THREAD

**Issue by DevYukine** [Prowlarr/Prowlarr#356]
**Describe the bug**

**To Reproduce**

1. Go to Add Indexer
2. Select Swarmazon
3. Enter credentials and Captcha
4. Test or add it
5. see error

**Expected behavior**
Adding the indexer

**Screenshots**

**Platform Information (please complete the following information):**

 - OS: Linuxserver docker Image, probably alpine? (not exactly sure)
 - Docker: Yes
 - .NET Version (System -> Status): 5.0.6
 - Browser and Version: not needed
 - Prowlarr Version: 0.1.0.686
 - Prowlarr Branch: develop

Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

https://gist.github.com/DevYukine/3bce9dbb22bcddc24645db87896c4c08

[AB#1271](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1271)

**Comment by bakerboy448** [comment]
Make a local copy of the yml and change https to http; see if that does it

(note you'll also wanna make the indexer name unique as well

**Comment by Qstick** [comment]
Looks like they are redirecting https to http based on the log, which is giving cardigann fits

**Comment by bakerboy448** [comment]
Pretty sure Jackett works around those already; perhaps just http not https in the YML?

**Comment by garfield69** [comment]
possibly related to https://github.com/Jackett/Jackett/issues/12217

**Comment by bakerboy448** [comment]
> possibly related to [Jackett/Jackett#12217](https://github.com/Jackett/Jackett/issues/12217)

https://github.com/Prowlarr/Indexers/pull/36

**Comment by bakerboy448** [comment]
Reopening per Yukine on discord; still persists

**Comment by DevYukine** [comment]
Still seems to be broken for me, tested on latest Jackett and after i removed it and readded it (i assume some cookie issue) it works now there, on prowlarr i still get the same error

Trace Logs: https://gist.github.com/DevYukine/1a86d953f33f83dcc04fb1920b67cce9

**Comment by Qstick** [comment]
Need an invite

**Comment by garfield69** [comment]
can do. email?

**Comment by Qstick** [comment]
> can do. email?

qstick @ protonmail.com

Thanks!

**Comment by garfield69** [comment]
done.

**Comment by Qstick** [comment]
Thanks, given Swarmazon API implementation works fine, is there a reason to keep the U/P version around?

**Comment by Qstick** [comment]
Actually U/P is working fine in latest Prowlarr as well. I'm closing this up.
