### ISSUE TITLE
[FEAT]: Support FlareSolverr Indexer

### ISSUE THREAD

**Issue by xiNeRoar** [Prowlarr/Prowlarr#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Support FlareSolverr Indexer

### Describe the solution you'd like

Support FlareSolverr Indexer

### Describe alternatives you've considered

Support FlareSolverr Indexer

### Anything else?

Support FlareSolverr Indexer

[AB#1275](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1275)

**Comment by bakerboy448** [comment]
Anyone feel like testing Flaresolverr or SOCKS proxy support on a new branch?
Branch indexer-proxy for non-docker, and hotio/prowlarr:pr-indexer-proxy for docker.

PR #380  adds Flaresolverr support
