### ISSUE TITLE
[FEAT]: Global minimum seeders

### ISSUE THREAD

**Issue by redairforce** [Prowlarr/Prowlarr#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When the torrent indexers are added to Sonarr/Radarr, they are all added with a minimum seeder requirement of 1.

### Describe the solution you'd like

I would like a global method to update this number. If I could just change this up to 10 and then have it synced back to the *arr, that would be fantastic. 

### Describe alternatives you've considered

I would rather not manually have to go through each indexer in each app and update. 

### Anything else?

I got nothin. 

[AB#1280](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1280)

**Comment by Mushin** [comment]
This would save time instead of manually needing to update all indexer settings in each app. An alternative could be to add minimum seeders to the indexer settings in Prowlarr, so different thresholds can be set for each one.

**Comment by bakerboy448** [comment]
Related to https://github.com/Prowlarr/Prowlarr/issues/106

but would have a global level / or easy of applying en mass

**Comment by razuos** [comment]
Can i help on this?

**Comment by oenu** [comment]
Id be interested in seeing this addition

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/e90a796b27dc5e9d0dfe0335a7f873428d16e22a
