### ISSUE TITLE
[BUG]: HDBits returning Unknown Category

### ISSUE THREAD

**Issue by stevezau** [Prowlarr/Prowlarr#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When searching via HDBits it is showing Unknown category for all releases.

### Expected Behavior

Expect to see the Category.

### Steps To Reproduce

1. Add HDBits
2. Search
3. Unknown shows for all results

### Environment

```markdown
- OS: Docker 
- Prowlarr: 0.1.0.608-ls9 by linuxserver.io
- Using Reverse Proxy: No
- Browser: Chrome Latest Ver
```

### What branch are you running?

Develop

### Anything else?

I enabled trace logging but not much useful info shows to try debug.

```2021-07-24 11:32:02.3|Info|NzbSearchService|Searching indexers: [HDBits] for {Term: , Offset: 0, Limit: 0, Categories: []}
2021-07-24 11:32:02.3|Debug|HDBits|Downloading Feed https://hdbits.org/api/torrents
2021-07-24 11:32:02.3|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-07-24 11:32:02.3|Trace|HttpClient|Req: [POST] https://hdbits.org/api/torrents
2021-07-24 11:32:02.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-07-24 11:32:03.3|Trace|HttpClient|Res: [POST] https://hdbits.org/api/torrents: 200.OK (1020 ms)
2021-07-24 11:32:03.3|Trace|EventAggregator|Publishing IndexerQueryEvent
2021-07-24 11:32:03.3|Trace|EventAggregator|IndexerQueryEvent -> HistoryService
2021-07-24 11:32:03.3|Trace|EventAggregator|IndexerQueryEvent <- HistoryService
2021-07-24 11:32:03.3|Debug|NzbSearchService|Total of 50 reports were found for {Term: , Offset: 0, Limit: 0, Categories: []} from 1 indexers
```

[AB#1285](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1285)

**Comment by stevezau** [comment]
If someone can point me to where the HDBits API code is i can try take a look at this and open a PR?

**Comment by stevezau** [comment]
If someone can point me to where the HDBits API code is i can try take a look at this and open a PR?

@Qstick or @bakerboy448 ?

**Comment by Qstick** [comment]
https://github.com/Prowlarr/Prowlarr/blob/e26081acfff6f6a5261dac1da88ac4f73506b859/src/NzbDrone.Core/Indexers/Definitions/HDBits/HDBits.cs#L50

**Comment by stevezau** [comment]
Should i be looking here https://github.com/Prowlarr/Indexers/blob/master/definitions/v1/hdbits.yml ?

**Comment by Qstick** [comment]
No, read the comment above

**Comment by stevezau** [comment]
thanks, i'm more a python/node dev but ill take a look.

**Comment by Qstick** [comment]
It likely just needs some category updates from the Jackett yml to our instance

**Comment by stevezau** [comment]
hmm, i had a look but as i'm so unfamiliar with the code base and language i'm a little lost.

**Comment by Qstick** [comment]
For us to action this, we'd need to know what specific search/results are showing unknown and what they show as category on the site. Otherwise there isn't anything we can do unless you are still planning to handle this one @stevezau

**Comment by bakerboy448** [comment]
> It likely just needs some category updates from the Jackett yml to our instance

Our categories match both Jackett's YML and Jackett's C# (API) implementation.

regardless, would need more specific info as Q mentioned.

**Comment by stevezau** [comment]
@Qstick @bakerboy448, trying to troubleshoot. I manually hit the API.. I've stripped out the title and hash. Below is the API response.

You'll notice the type_category is an integer, not a string. However, looking at this block it seems correct to me. This is assuming the fn `AddCategoryMapping(` first param is to map the API into the Category Name.

https://github.com/Prowlarr/Prowlarr/blob/e26081acfff6f6a5261dac1da88ac4f73506b859/src/NzbDrone.Core/Indexers/Definitions/HDBits/HDBits.cs#L50-L58.

I wanted to check if it was checking against the correct field name but I'm getting lost in the code as I'm not familiar with .net. If you can point m in the right direction or advice on how I can t-shoot this deeper.

Thanks!

```
{
  "status": 0,
  "data": [
    {
      "id": 577308,
      "hash": "[REMOVED]",
      "leechers": 3,
      "seeders": 1,
      "name": "[REMOVED]",
      "times_completed": 1,
      "size": 14957182721,
      "utadded": 1627861241,
      "added": "2021-08-01T23:40:41+0000",
      "comments": 0,
      "numfiles": 76,
      "filename": "[REMOVED].torrent",
      "freeleech": "no",
      "type_category": 1,
      "type_codec": 1,
      "type_medium": 1,
      "type_origin": 0,
      "torrent_status": "",
      "bookmarked": 0,
      "wishlisted": 0,
      "tags": [
        ""
      ],
      "username": "Anonymous",
      "owner": 0
    },
    ....
```

**Comment by stevezau** [comment]
Shouldn't there be a mapping to category here https://github.com/Prowlarr/Prowlarr/blob/e26081acfff6f6a5261dac1da88ac4f73506b859/src/NzbDrone.Core/Indexers/Definitions/HDBits/HDBitsParser.cs#L63-L82 ??

**Comment by stevezau** [comment]
@Qstick @bakerboy448 looking at jacket i suspect Prowlarr is missing this 

https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/HDBitsApi.cs#L146

**Comment by stevezau** [comment]
@bakerboy448 @Qstick any more info you need from me?

**Comment by Qstick** [comment]
@stevezau Nice work sir!

**Comment by stevezau** [comment]
tested and can confirm fix works.

**Comment by stevezau** [comment]
Hey @Qstick  or @bakerboy448  , I went onto discord and posted the below but there is a lot of activity in there so i'm posting here in case it gets lsot.


i've been testing https://github.com/Prowlarr/Prowlarr/issues/365. It seems the category now returns as expected.. but the results do not seem correct. Especially when it is a search that might not exist, it seems to return random results. I am trying to troubleshoot but enabling trace does not show the exact calls to the tor site making it hard to t-shoot before opening an issue. Any advice?

**Comment by stevezau** [comment]
nevermind logged bug here https://github.com/Prowlarr/Prowlarr/issues/437
