### ISSUE TITLE
[FEAT]: Search screen user login

### ISSUE THREAD

**Issue by RemoteMedia** [Prowlarr/Prowlarr#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not related to a problem.

### Describe the solution you'd like

I am blown away by how easily this works with the other amazing *arr products. 
I was wondering if there is any scope towards having a single access page for searching I can provide user logins to for my consumers?
I currently use Ombi for music and Overseer for movie and show requests but none have the ability to add books.
My consumers read quite a lot of books and request a lot on discord I have to then go and find..
The ability for them to be able to search one program (like this) to get what they are after would be huge.
I'm not overly concerned re granular controls for permissions of adding content as the media server will show eahc person their own libraries. 
But if this would be something others would find helpful, I would appreciate support.
OR, down the road(map) a request app because every other single *aar app just performs flawlessly. I never have issues with these apps, only others hooking in to them.

### Describe alternatives you've considered

Ombi (music, shows, movies)
Overseer (shows, movies)
Calibre (books)

### Anything else?

Nil

[AB#1286](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1286)

**Comment by austinwbest** [comment]
> I was wondering if there is any scope towards having a single access page for searching I can provide user logins to for my consumers?

Negative. No intentions of adding a user system so people can sell/share their indexers and libraries. The alternatives would be your option(s) in this case.
