### ISSUE TITLE
[FEAT]: Add custom label on "Add to download client"

### ISSUE THREAD

**Issue by Eds1989** [Prowlarr/Prowlarr#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not a Prowlarr problem, but the way Proawlarr currently handles labels means other apps (Sonarr/Radarr) do not detect downloads added to download client without manual intervention.

### Describe the solution you'd like

I'd like the ability to specify a label to add to any torrent added directly to the download client via Prowlarr.

So when searching and clicking "Add to download client" in Prowlarr, I'd like to have the option to specify the label to add rather than using the global one defined in Prowlarr settings.

### Describe alternatives you've considered

None.
Current manual intervention required to adjust label in the download client to match the download type (Film/TV/Music etc).

### Anything else?

None

[AB#1304](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1304)

**Comment by Qstick** [comment]
Dupe #170
