### ISSUE TITLE
[BUG]: Validation failed - Gingadaddy

### ISSUE THREAD

**Issue by drizzt09** [Prowlarr/Prowlarr#382]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

see https://github.com/Prowlarr/Prowlarr/issues/265 thats closed

Test fails authentication for gingadaddy even though it works in sonarr

see logs below

### Expected Behavior

successful connection to gingadaddy since Sonarr works fine

### Steps To Reproduce

add gingadaddy URL and api key
switch to advanced and change path to /api.php (also doesnt work with /api)
run test

### Environment

```markdown
- OS: Win 10 64
- Prowlarr: 0.1.0.608
- Docker Install: no
- Using Reverse Proxy:no
- Browser:MS Edge(chrome)
```

### What branch are you running?

Develop

### Anything else?

https://hastebin.com/wivoxigigo.yaml
![image](https://user-images.githubusercontent.com/6366965/127757811-b9df2c9a-6e53-4b29-bd11-89805e6114da.png)

[AB#1309](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1309)

**Comment by bakerboy448** [comment]
Judging by the error indicating the response is bad combined with the Indexer not having any categories in its cap's call;  this seems to be more likely an indexer failing to follow newzab standards issue than a Prowlarr issue.

```
<caps>
<!--  server information  -->
<server version="1.0" title="GingaDADDY" strapline="The DADDY of NZB indexers" email="support@gingadaddy.com" url="https://www.gingadaddy.com/" image="https://www.gingadaddy.com/themes/ICGstation/images/newlogo2.png"/>
<!--  limit parameter range  -->
<limits max="100" default="50"/>
<retention days="9001"/>
<registration available="no" open="no"/>
<searching>
<search available="yes"/>
<tv-search available="yes"/>
<movie-search available="yes"/>
</searching>
<categories> </categories>
</caps>
```

Ref: https://github.com/Radarr/Radarr/issues/6256#issuecomment-892189805

**Comment by drizzt09** [comment]
You referenced my other ticket on Radaar #6256 which you mentioned same stuff about non-conventional categories.
However with Sonaar I can add the custom Gingadaddy categories.
In Radaar I can not add the custom categories but still do not get this authentication error.
Prowlarr is the only one that gets auth error.

**Comment by bakerboy448** [comment]
> Anyway, some additional food for thought from checking out GingaDaddy's forums it seems they are no longer even giving out VIP to users once the users have paid in 2020 and 2021. Staff is also - as you noted - gone.

> I'm not sure of the benefits for making code changes to support a site that - by all appearances frankly - is scamming its users at this point; doesn't abide by any standards; has no devs/ownership to be found; and technically isn't able to be used by any new users.

For Posterity; my comment from the Radarr issue.

**Comment by austinwbest** [comment]
As i mentioned in radarr, i dont see a need in making changes for a site that has no devs and doesn't follow a standard caps call.
