### ISSUE TITLE
Upstream Pull: New: ISO 8601 Date format in log files

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#39]
https://github.com/Prowlarr/Prowlarr/blob/3bf8bfd9a69060c01c0bc0298c2a0164c8ef80d9/src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs#L15

`yyyy-MM-dd`

**Comment by austinwbest** [comment]
Closing. Next time dont blow out the template.

Will review when it is done properly
