### ISSUE TITLE
[FEAT]: Support for RARBG show search by IMDb ID

### ISSUE THREAD

**Issue by agneevX** [Prowlarr/Prowlarr#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Search by IMDb ID for the RARBG indexer is currently not supported. As a result, episode searches, particularly season searches turn up a lot of duplicates.

### Describe the solution you'd like

The torrentapi.org API supports searches by both `search_string` and `search_imdb` URL parameters.

This query, for example, will allow episode searches by IMDb ID:

`curl "https://torrentapi.org/pubapi_v2.php?app_id=app1&token=xxx&mode=search&search_imdb=tt10986410&search_string=S02E01"`

[AB#1383](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1383)

**Comment by agneevX** [comment]
> https://github.com/Prowlarr/Prowlarr/blob/50cae0719f9c03fb1b06913a1eb9270db644b40b/src/NzbDrone.Core/Indexers/Definitions/Rarbg/RarbgRequestGenerator.cs#L39

That's only for queries containing a single IMDb query and nothing else and is largely useful for Radarr only. 

What I'm asking for is a IMDb ID and text along side it, e.g. not `tt10986410` but `S02 tt10986410 E01 DV` or similar, in which case, the IMDb ID will be inside the `search_imdb` param (`search_imdb=tt10986410`) and the remaining text will be inside the `search_string` param, e.g. `&search_string=S02%20E01`. 

The `caps` request should also return IMDb for shows, so that Sonarr can search in that manner, which it currently does not. 

Thanks!

**Comment by agneevX** [comment]
Well I specifically mentioned "show" which isn't really supported, because, again, it's not supported per the caps request.

**Comment by Qstick** [comment]
> Well I specifically mentioned "show" which isn't really supported, because, again, it's not supported per the caps request.

Touché
