### ISSUE TITLE
[FEAT]: Add (App Sync) Support for Indexers who only have no category / assumed category 8000 (i.e. Other)

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Certain indexers - such as BTDigg - do not support categories and default to `8000`

We should add support for these types of indexers syncing to the apps and also need to add a method to guess/assume a category for the results returned.  Possibly via regexing the release name

### Describe the solution you'd like

Discussed above

### Describe alternatives you've considered

Not supporting these indexers in apps at all

### Anything else?

N/A

[AB#1385](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1385)

**Comment by toxic0berliner** [comment]
as you can see in the many linked issues, not all default to 8000 categories. Some will need keywordless searches and will return some non-standard category like Torrent9 which says this : 
````
Torrent9 only returns category Movies in its Keywordless search results page.
To pass your apps' indexer TEST you will need to include the 131681(Movies) category.
````
So this feature request should also hopefully provide some way to add 131681 or something else when setting up an app for this indexer so it adds these categories.

**Comment by Qstick** [comment]
This can already be done by adjusting sync categories under advanced settings for your apps to include `Other`. 

For the case of torrent9, their `Movies` gets mapped to Torznab Movies (2000). Thus when selecting that it should ensure that Torrent9 is brought in based on the yml mapping.

**Comment by toxic0berliner** [comment]
Thanks for the tip but I fear this didn't work.
I added Others in sonarr's settings in prowlarr but I still get this:
````
	8:27am	ApplicationService	NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://sonarr:8989/api/v3/indexer]	
8:27am	HttpClient	HTTP Error - Res: [POST] http://sonarr:8989/api/v3/indexer: 400.BadRequest [ { "isWarning": false, "propertyName": "", "errorMessage": "Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.", "severity": "error" } ]	
8:27am	Cardigann	Adding request: https://www.torrent9.pw/top	
````
Other indexers get added to sonarr without issues but it seems this one doesn't pass the sonarr test.
Any help will be very much appreciated.
Thanks in advance.

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/34a09af01e1e13cb65e37179b29d4916726facd2
