### ISSUE TITLE
[BUG]: DOGnzb url isn't working

### ISSUE THREAD

**Issue by kantjer** [Prowlarr/Prowlarr#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The DOGnzb url on the indexers page isn't pinting to the correct URL.
https://dognzb.cr/ should be https://dognzb.cr/login.

### Expected Behavior

RL should go to DOGnzb login page

### Steps To Reproduce

Indexers page
DOGnzb website link
=> "This dognzb.cr page can’t be found"

### Environment

```markdown
- OS: Syno DSM7
- Prowlarr: 0.1.0.749
- Docker Install: Yes, Hotio
- Using Reverse Proxy: Yes, SWAG
- Browser: Chrome
```

### What branch are you running?

Nightly

### Anything else?

Nothing to add

[AB#1387](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1387)

**Comment by bakerboy448** [comment]
Bug reports need logs :)

**Comment by bakerboy448** [comment]
if it's this link
![image](https://user-images.githubusercontent.com/55419169/128393249-aabc316a-f91e-4e79-924d-9ceccaf154e1.png)

then that comes based on the indexer's URL https://github.com/Prowlarr/Prowlarr/blob/38c09277d9c5215c41b31939ada22f627983c57d/frontend/src/Indexer/Index/Table/IndexerIndexRow.js#L251

Which means this arguably is not a Prowlarr bug given DogNZB should redirect the main page to the login as/if needed.

**Comment by kantjer** [comment]
In that case let's close the issue
