### ISSUE TITLE
[FEAT]: Add a unified search url across all indexers

### ISSUE THREAD

**Issue by ytzelf** [Prowlarr/Prowlarr#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I'd like to set up my mobile applications with a single URL for search that Prowlarr would provide.

### Describe the solution you'd like

Similar to what NZBHydra does, provide a single URL to search across all indexers. Simplifies setting up mobile appos (Lunasea / NZB360) a lot).

### Describe alternatives you've considered

Going back to NZBHydra :(

### Anything else?

n.a.

[AB#1404](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1404)

**Comment by ta264** [comment]
We have made the decision not to support this.  In our view it's more trouble than it's worth.

**Comment by ta264** [comment]
PS the lunasea / nzb360 devs are pretty helpful, I think it would make more sense to talk to them about using the prowlarr API to automatically add all indexers to nzb360 / lunasea
