### ISSUE TITLE
[BUG]: Internet Archive: cannot save - Value cannot be null. (Parameter 'infoHash') - Sourced from btih

### ISSUE THREAD

**Issue by danshilm** [Prowlarr/Prowlarr#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Testing the Internet Archive indexer that was recently added fails.

### Expected Behavior

I expect to be able to add the indexer to my instance without issues.

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: 0.1.0.761
- Docker Install: yes - nightly-632f276 by hotio
- Using Reverse Proxy: no
- Browser: not related
```

### What branch are you running?

Nightly

### Anything else?
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/6945247/prowlarr.trace.txt)

[AB#1405](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1405)

**Comment by bakerboy448** [comment]
@Nyuels  seems there is no infoHash in their response?

also ref: https://archive.org/help/json.php

**Comment by bakerboy448** [comment]
Should be fixed on the next build;  ~20min for native ~1hr for docker
