### ISSUE TITLE
Bulk indexer add/indexer selection similar to the one in jackett

### ISSUE THREAD

**Issue by aniel300** [Prowlarr/Prowlarr#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

the ability to to filter and bulk & batch add indexers (torrents) by open, semi-private, lenguage, etc similar to how it is on jackett

### Describe alternatives you've considered

jackett but the all url doesnt work in radarr

### Anything else?

thank you

[AB#1419](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1419)

**Comment by bakerboy448** [comment]
What specifically are you looking for?

- an aggregate endpoint ala Jackett's `/all`?
 
 No plans to ever put that in Prowlarr; additionally every one - include Jackett's devs - advice it shouldn't be used and has significant downsides

- adding every public indexer at once?

No plans to add this either and it doesn't make sense give most public trackers scrape each other; in additional a large number of search results causes issues on the *arr / automation end.

- a way to bulk add indexers?

watch what the API does in the UI via the network calls  and then write a script that does what you need

- ? Something I'm missing?

**Comment by aniel300** [comment]
1) no aggregation endpoint ala Jackett's /all but the ability to choose which ones you wants in the indexer pick menu again similar to how you can do it in jackett

**Comment by bakerboy448** [comment]
So to be able to bull select multiple public indexers and only public indexers on the indexers add screen and add multiple indexers at once, correct?

**Comment by aniel300** [comment]
yes

**Comment by aniel300** [comment]
> So to be able to bull select multiple public indexers and only public indexers on the indexers add screen and add multiple indexers at once, correct?

any update on this ?

**Comment by aniel300** [comment]
any eta on when this will be available ?

**Comment by ThaDaVos** [comment]
Instead of a multi-select like in Jackett, what would really help is that if the search for indexer popup stays open after adding one, so you can easily select another indexer - instead of re-opening the popup, re-entering the filter, scrolling to the correct indexer and clicking it - and repeat...

**Comment by Qstick** [comment]
> Instead of a multi-select like in Jackett, what would really help is that if the search for indexer popup stays open after adding one, so you can easily select another indexer - instead of re-opening the popup, re-entering the filter, scrolling to the correct indexer and clicking it - and repeat...

Not a terrible idea, I'll see what I can do

**Comment by aniel300** [comment]
@ThaDaVos that could work as well

**Comment by aniel300** [comment]
@Qstick did u close the request ?
