### ISSUE TITLE
[BUG]: data path location not respected

### ISSUE THREAD

**Issue by hunter-nl** [Prowlarr/Prowlarr#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When prowlarr is started with -data=<path>, then this is not used by .aspnet data protection keys.

2021-08-10 13:17:11.5|Info|AppFolderInfo|Data directory is being overridden to [/opt/data/Prowlarr]
2021-08-10 13:17:11.5|Error|Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider|An error occurred while reading the key ring.

[v0.1.0.768] System.UnauthorizedAccessException: Access to the path '/home/prowlarr/.aspnet/DataProtection-Keys/key-<keyvalue-made-hidden>.xml' is denied

### Expected Behavior

All data should being written to overridden data directory.

### Steps To Reproduce

Start prowlarr with -data=<path> parameter.

### Environment

```markdown
- OS: Rocky Linux (CentOS) 8.4
- Prowlarr: 0.1.0.768
- Docker Install: Not used
- Using Reverse Proxy: nginx
- Browser: Not related to issue
```

### What branch are you running?

Develop

### Anything else?

2021-08-10 13:17:11.5|Info|AppFolderInfo|Data directory is being overridden to [/opt/data/Prowlarr]
2021-08-10 13:17:11.5|Error|Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider|An error occurred while reading the key ring.

[v0.1.0.768] System.UnauthorizedAccessException: Access to the path '/home/prowlarr/.aspnet/DataProtection-Keys/key-<keyvalue-made-hidden>.xml' is denied

[AB#1425](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1425)

**Comment by ta264** [comment]
You might be able to work around it by setting the XDG environment variables correctly

**Comment by bakerboy448** [comment]
Don't think this was ever reproduced

```
KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
ng overridden to [/data/media/.config/Prowlarr]
KeyManagement.XmlKeyManager: No XML encryptor configured. Key {adc231fe-1edd-4960-aadc-b36007caaa90} may be persisted to storage in unencrypted form.
```

is what the logs show; no attempt to use /home/prowlarr... (which doesn't exist is made)

**Comment by ta264** [comment]
That commit I mentioned needs pulling here and will fix it
