### ISSUE TITLE
[BUG]: Yggtorrent base Url change

### ISSUE THREAD

**Issue by bentux** [Prowlarr/Prowlarr#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The base Url is not up to date

### Expected Behavior

The new one is : https://www3.yggtorrent.nz/

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr:0.1.0.768
- Docker Install:Yes
- Using Reverse Proxy: Yes
```

### What branch are you running?

Develop

### Anything else?

https://www3.yggtorrent.nz

[AB#1426](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1426)

**Comment by bakerboy448** [comment]
No need for an issue everytime :)

YGG is YML and we'll PR the updates to the indexer server when Jackett makes the updates then merge those in on roughly a weekly basis
