### ISSUE TITLE
[FEAT]: Database support (non sqlite or without WAL mode)

### ISSUE THREAD

**Issue by samip5** [Prowlarr/Prowlarr#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

NFS with sqlite doesn't work great due to WAL

### Describe the solution you'd like

I would ask if it could be done to support another database like Postgres.

### Describe alternatives you've considered

There is none when you're forced to use NFS

### Anything else?

Kubernetes deployment, using the unofficial Helm chart at k8s-at-home.

[AB#1431](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1431)

**Comment by bakerboy448** [comment]
Like the other *arrs.
No plans for this.
