### ISSUE TITLE
[BUG]: [PR Build] [PR indexer-proxy] Socks5 Proxy not working without authentication in Indexer proxies

### ISSUE THREAD

**Issue by darkknight6722** [Prowlarr/Prowlarr#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In Indexer proxies, Socks5 is not working without username and password even if it is not needed. It shows `ProxyCheckFailedToTestMessage`. If user/pass is enabled in the proxy, and added to prowlarr settings, it works fine. 

If the same proxy is added to General setting without user/pass, it works.

### Expected Behavior

If user/pass is not needed, Proxy should work without user/pass.

### Steps To Reproduce

Add a Socks5 proxy in Indexer proxies without password and Test it.

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: 0.1.0.746 (pr-4165c60 by hotio)
- Docker Install: Yes
- Using Reverse Proxy: Traefik
- Browser: N/A
```

### What branch are you running?

`indexer-proxy`

### Anything else?

https://0bin.net/paste/u7gsiXCk#TOnSN45grfZ2lel-GOHqMbOXbEFcsYzUnen7W6X5smG (changed to never expire)

If anything missed https://discord.com/channels/767843854736949299/767843854824374281/874849579189809162

[AB#1433](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1433)

**Comment by bakerboy448** [comment]
Found in PR #380

**Comment by Qstick** [comment]
Try build 773
