### ISSUE TITLE
[BUG]: Torrentdb not returning single episode results

### ISSUE THREAD

**Issue by Davo1624** [Prowlarr/Prowlarr#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When searching for an individual episode Prowlarr is sending imdb show queries to torrentdb.com, not individual episode queries. This only happens when the request comes from Sonarr, direct search in Prowlarr will send text search to torrentdb.com which returns the correct results.

The end result is only season packs are returned via Sonarr/Prowlarr requests, not individual episodes

### Expected Behavior

Prowlarr to send individual episode queries to torrentdb.com when receiving a search request from Sonarr

### Steps To Reproduce

OS:
Prowlarr: 0.1.0.771 nightly
Docker Install: Yes
Using Reverse Proxy: No
Browser:

Search for any television episode in Sonarr and review the relevant query logs in Prowlarr

### Environment

```markdown
- OS: 
- Prowlarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Nightly

### Anything else?

Line from Prowlarr log, search was generated in Sonarr for RIck & Morty S05E07:

today at 2:33:36 PM [Info] Cardigann: Adding request: https://torrentdb.net/filter/torrents?categories[]=2&search=2861424&tags=&sorting=created_at&direction=desc&qty=100

2861424 is the imdb category for the show Rick & Morty, when the above search is performed only season packs were returned not episodes as requested

[AB#1440](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1440)

**Comment by bakerboy448** [comment]
X-Ref https://github.com/Jackett/Jackett/issues/12156

**Comment by bakerboy448** [comment]
waiting for info as we'll see what jackett folks say given they are more familiar with the site and yml def

**Comment by bakerboy448** [comment]
Will be Fixed with https://github.com/Prowlarr/Indexers/pull/22

This removes support for id based searches for series for TorrentDB per jackett's bandaid fix.
