### ISSUE TITLE
Pull Jackett Commit Category Update for DanishBytes

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#417]
Pull https://github.com/Jackett/Jackett/commit/1c2a99116741aaa7034ab9fee3f49430806bde06

Updates:
https://github.com/Prowlarr/Prowlarr/blob/d5b34e8c038f140627b807a40552e76d5d17d9a1/src/NzbDrone.Core/Indexers/Definitions/DanishBytes.cs#L73

[AB#1441](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1441)

**Comment by Qstick** [comment]
Dupe #384 don't make another issue to catch-up the same indexer
