### ISSUE TITLE
[BUG]: Mylar adding "Torznab Host" without colon between address and port

### ISSUE THREAD

**Issue by kingfenix** [Prowlarr/Prowlarr#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Mylar support adding "Torznab Host" without colon between address and port

### Expected Behavior

Torznab host should contain colon between address and port

### Steps To Reproduce

Sync indexers to Mylar, then view providers in mylar

### Environment

```markdown
- OS: Unraid
- Prowlarr: latest
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox
```

### What branch are you running?

Nightly

**Comment by bakerboy448** [comment]
Trace Logs of the Sync & screenshot (minus the API key) of your configuration for Mylar in Prowlarr?

**Comment by kingfenix** [comment]
![Screen Shot 2021-08-15 at 4 39 38 PM](https://user-images.githubusercontent.com/1764199/129492711-027ccef3-d0dd-4d29-9ca2-356959870dc7.png)

**Comment by bakerboy448** [comment]
Of Mylar's Configuration in Prowlarr

**Comment by kingfenix** [comment]
how do I get the trace logs your referring to? screenshot is attached now

**Comment by bakerboy448** [comment]
Trace Logs link is noted on the template 

> Anything else?
Trace Logs (https://wiki.servarr.com/prowlarr/troubleshooting#logging-and-log-files)
Links? References? Anything that will give us more context about the issue you are encountering!

> Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

**Comment by kingfenix** [comment]
![Screen Shot 2021-08-15 at 5 00 49 PM](https://user-images.githubusercontent.com/1764199/129492794-8d82daa4-0ff8-46ec-96d2-0009c01cf392.png)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

not a bug; prowlarr is syncing exactly what was input, as designed and expected

**Comment by kingfenix** [comment]
well damn now I see the problem, I shot myself in the foot, please close and sorry to bother you
