### ISSUE TITLE
[FEAT]: Trigger manual search through query param

### ISSUE THREAD

**Issue by the-lazy-fox** [Prowlarr/Prowlarr#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have some automation on my own and I'm using this great feature from Jackett and HydraNZB.
Just inject search=My.Search (or q=) in the URL and it will directly trigger a manual search on all indexers for all categories.

### Describe the solution you'd like

Just inject search=My.Search (or q=) in the URL and it will directly trigger a manual search on all indexers for all categories.
If wished, you can also refine like search=My.Search&tracker=tracker1,tracker2&category=2000&filter=all.
It will be a great addition to fully use Prowlarr 👍🏼 

### Describe alternatives you've considered

/

### Anything else?

Thanks for the great job!

[AB#1451](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1451)

**Comment by bakerboy448** [comment]
Why not just use the torznab endpoint that exists for each indexer?

**Comment by the-lazy-fox** [comment]
It will requires to do it for each indexers (torrent + usenet), being able to use from the full power of Prowlarr would be amazing.

**Comment by Qstick** [comment]
Your options are the nab endpoints for each as @bakerboy448 mentioned, or the /search api endpoint which has the ability to search multiple, but with less parameter support. We don’t plan to add a consolidated nab compatible endpoint

**Comment by the-lazy-fox** [comment]
Hello @Qstick 
Could you please provide a list of authorized parameters for the /search page?
Thanks a lot!

**Comment by bakerboy448** [comment]
`domain.tld/prowlarr/api/v1/search?query=blackjack&indexerIds=24&indexerIds=5&categories=2010&categories=2020`

`query` - Search String
`indexerIds` - Indexer ID (leave off for all)
 - `-2` is all torrents
 - `-1` is all usenet
`categories` - categories to use (leave off for all)

You can just watch the network calls as I did

**Comment by Qstick** [comment]
query
indexerIds
categories

Use chrome network tab to see the UI request if you have issues
