### ISSUE TITLE
[BUG]: Flaresolverr not working (docker)

### ISSUE THREAD

**Issue by Merrick28** [Prowlarr/Prowlarr#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I try to make prowlarr work with flaresolverr.

Images : hotio/prowlarr:nightly and flaresolverr/flaresolverr:latest

I add flaresolverr as shown and the test is ok
![image](https://user-images.githubusercontent.com/3830148/129710847-8f72be97-0bc4-4e56-b105-10d5469ae007.png)

After I save, flaresolverr is always disabled
![image](https://user-images.githubusercontent.com/3830148/129710930-34c10250-084d-4b1a-a99e-931017ddd150.png)

On health I have the message "All proxies are unavailable due to failures"

Prowlarr logs : 
```
[Error] IndexerProxyCheck: Proxy Health Check failed 

[v0.1.0.820] System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at NzbDrone.Core.HealthCheck.Checks.IndexerProxyCheck.IsProxyWorking(IIndexerProxy indexerProxy) in D:\a\1\s\src\NzbDrone.Core\HealthCheck\Checks\IndexerProxyCheck.cs:line 72

```

Tests : 
```
docker exec -it prowlarr bash
root@56db9e3a110f:/# curl http://flaresolverr:8191/
{"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1629196480068,"endTimestamp":1629196480068,"version":"v1.2.9"}root@56db9e3a110f:/# 
```

### Expected Behavior

Falresolverr should be active, and working as the hostname is resolved in the container

### Environment

```markdown
- OS: 
- Prowlarr: 
- Docker Install: hotio/prowlarr:nightly 
- Using Reverse Proxy: traefik
- Browser:

Version 0.1.0.820
Package Version nightly-24f6efc by hotio
.NET Yes (5.0.9)
Docker Yes
DB Migration 11
AppData directory /config
Startup directory /app/bin
Mode Console

```

### What branch are you running?

Nightly

### Anything else?

```
docker exec -it prowlarr bash
root@56db9e3a110f:/# curl http://flaresolverr:8191/
{"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1629196480068,"endTimestamp":1629196480068,"version":"v1.2.9"}root@56db9e3a110f:/# 
```

[AB#1455](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1455)

**Comment by PearsonFlyer** [comment]
For the URL, it looks like the error message is telling you that it wants an address only. You should remove the http:// part of the hostname and see if that goes away.

The disabled part is because you did not apply a tag, and then apply that tag to the indexer(s) you want to use flaresolverr with. Once you do that, it will no longer be disabled (disabled here means it's not being actively used with any indexers).

**Comment by Qstick** [comment]
I've fixed the healthcheck in 4a957b6, @PearsonFlyer is correct on the tags/disabled parts

**Comment by Merrick28** [comment]
Thanks. I will test asap.

**Comment by Merrick28** [comment]
Hello, yes it works for me since the fix of the healthcheck
