### ISSUE TITLE
[FEAT]: BHD - Add "BHDStudio Quality Seal" indexer flag

### ISSUE THREAD

**Issue by KnifeFed** [Prowlarr/Prowlarr#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

The internal BHDStudio releases get a "BHDStudio Quality Seal" flag, e.g. [this one](https://beyond-hd.me/torrents/batman-the-long-halloween-part-one-2021-bluray-1080p-dd51-x264-bhdstudio.129231). It would be nice if it could be added to Prowlarr.

### Describe alternatives you've considered

None.

### Anything else?

No.

[AB#1460](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1460)

**Comment by Qstick** [comment]
Need to see an API response and how this is identified

**Comment by bakerboy448** [comment]
Closing; Not possible, this is not in BHD's API Response.  Please ask them to add a flag field indicating such seals to their API.

https://beyond-hd.me/forums/topic/torrents-api-overview-beyondhd.3721

```json
{
  "status_code": 1,
  "page": 1,
  "results": [ 
    {
      "id": 129231,
      "name": "Batman: The Long Halloween Part One 2021 BluRay 1080p DD5.1 x264-BHDStudio",
      "folder_name": "\/",
      "info_hash": "{removed}",
      "size": 5404942508,
      "uploaded_by": "KeyserSoze",
      "category": "Movies",
      "type": "1080p",
      "seeders": 38,
      "leechers": 0,
      "times_completed": 56,
      "imdb_id": "tt14324650",
      "tmdb_id": "movie\/736073",
      "bhd_rating": 0,
      "tmdb_rating": 0,
      "imdb_rating": 7.4,
      "tv_pack": 0,
      "promo25": 0,
      "promo50": 0,
      "promo75": 0,
      "freeleech": 0,
      "rewind": 0,
      "refund": 0,
      "limited": 0,
      "rescue": 0,
      "bumped_at": "2021-07-04 11:39:46",
      "created_at": "2021-07-04 11:39:46",
      "url": "{removed}",
      "download_url": "{removed}"
    },```
