### ISSUE TITLE
[FEAT]: HTTP "keep alive" feature

### ISSUE THREAD

**Issue by DarrenPIngram** [Prowlarr/Prowlarr#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not related to a problem per se (with the existing application).

### Describe the solution you'd like

Would you consider the following feature?

Situation: Many trackers require a login and keep an account only valid for a certain time IF no logins are made. The use of the application can mean that one often doesn't log into all trackers installed, especially if they are viewed as "secondary" venues.

Proposal: A button (to fire off) and/or automatic option set on a preference (every X days) that would OPEN in a browser (new tabs) all of the stored trackers, using credentials provided (if ordinarily it does not log in with the same web credentials then offer a place to save the credentials).

Benefit: Trackers remain enabled, even if one was forgetful or even sick.

### Describe alternatives you've considered

The alternative solution is relying on the brain... itself a more risky proposition.

### Anything else?

-

[AB#1469](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1469)

**Comment by ta264** [comment]
I don't think this is ever going to happen.  What if prowlarr is running on a headless box with no browser?

**Comment by DarrenPIngram** [comment]
Well I envisaged it being a "turn on or off" feature, so anyone using a headless installation wouldn't turn it on.
