### ISSUE TITLE
[BUG]: Rarbg dropdown doesn't do anything

### ISSUE THREAD

**Issue by manubell** [Prowlarr/Prowlarr#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `Base Url` dropdown does completely nothing when clicking it. 
![image](https://user-images.githubusercontent.com/17701567/130152137-57de8791-0beb-4265-a0d5-dffd65dde634.png)

No errors in browser console when clicking it. 

### Expected Behavior

A dropdown with a URL. 

### Steps To Reproduce

1. Indexers
2. Add indexer
3. Filter for Rarbg (do have browser console errors while filtering, but unrelated to this)
4. Click Rarbg
5. Click dropdown

### Environment

```markdown
- OS: Synology/Linux
- Prowlarr: 0.1.0.768
- Docker Install: Yes (testing-a98760b by hotio)
- Using Reverse Proxy: No
- Browser: Firefox 91.0.1 (64-bit) + Safari on Iphone
```

### What branch are you running?

Develop

### Anything else?

Extra information from @bakerboy448:

1. `http://localhost:9696/api/v1/indexer/action/getUrls` returns nothing for rarbg
2. ![image](https://user-images.githubusercontent.com/17701567/130152923-ec103998-1ee3-4e2a-be0a-72dc8b297de2.png) request body has the data

[AB#1472](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1472)

**Comment by bakerboy448** [comment]
confirmed on 0.1.0.829 as well
