### ISSUE TITLE
[BUG]: Mylar3 UA parsed incorrectly for stats

### ISSUE THREAD

**Issue by Qstick** [Prowlarr/Prowlarr#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot_20210821-210450](https://user-images.githubusercontent.com/376117/130339076-784b5f81-aa1f-4ee6-bb2d-7e732d64e001.png)

### Expected Behavior

Parse as `Mylar3`

### Environment

```markdown
- OS: 
- Prowlarr: 842
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Nightly

### Anything else?

Negative

[AB#1490](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1490)

**Comment by bakerboy448** [comment]
to do this right would need example UA calls for all apps.

But I think I may have it
