### ISSUE TITLE
[FEAT]: Add 'VIP Expiration' as an optional column with sort

### ISSUE THREAD

**Issue by Fringe09** [Prowlarr/Prowlarr#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

There is no easy way to tell the expiration of Indexers. Only method to check is by editing each Indexer one by one.

### Describe the solution you'd like

Add 'VIP Expiration' as an optional column with ability to sort.

### Describe alternatives you've considered

I can't think of another alternative.

### Anything else?

No

[AB#1495](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1495)

**Comment by bakerboy448** [comment]
related to https://github.com/Prowlarr/Prowlarr/issues/797
