### ISSUE TITLE
Indexer - Internet Archive - Jackett Pull - No Magnet (Torrent file Only) Option

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#457]
feature add - https://github.com/Jackett/Jackett/commit/a00cac6ad320734ed7d6b86d3491ccfe378f38e8
lint - https://github.com/Jackett/Jackett/commit/da65e0ed10808454ed564d3031b479c04b3a8c10

[AB#1496](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1496)

**Comment by Nyuels** [comment]
I haven't seen anything like it, but we do not automatically generate a magnet link from an available InfoHash - like Jackett does?

**Comment by Qstick** [comment]
We do

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/4347e1cf7aec78d7fc244befd8525cdde58e820c
