### ISSUE TITLE
[FEAT]: Allow force save of disabled indexers

### ISSUE THREAD

**Issue by famewolf** [Prowlarr/Prowlarr#461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I wish to add several indexers I know to be valid but are currently in a "disabled" state because I have exceeded their daily api and/or download limits.     Ideally I'd like to be able to have it save the indexer info for later followup so it can get the api/download maximum's from the indexer in automated fashion.  nzbhydra does this and I know there are a couple of api calls that can be made to return the api limits.

### Describe the solution you'd like

Mirror nzbhydra functionality possibly with a "I know what I'm doing" checkbox when clicking save.

### Describe alternatives you've considered

Waiting possibly days to get all the indexer's added.   Not a good solution.

### Anything else?

![2021-08-26_12-02](https://user-images.githubusercontent.com/4558832/130996687-ccc7d2d6-2e16-41da-bec1-2dc3fb754583.png)

[AB#1502](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1502)

**Comment by homerjsim** [comment]
I would also like this feature but at the moment I found a workaround. When you add the indexer (in my case it is a usenet indexer) enter everything and untick "enabled". Then you can save it. Maybe you need to click on "save" twice. After that it is saved and in your list. 
Then edit the indexer again and enable it. Then click save (maybe twice) and is saved and active. 
I hope this helps.
