### ISSUE TITLE
[FEAT]: RSS feed search in all indexers

### ISSUE THREAD

**Issue by lightglitch** [Prowlarr/Prowlarr#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The rss feeds apis now support the following:

`http://192.168.1.1:9696/{indexer}/api?t=search&q=movie&apikey={apikey}`
`http://192.168.1.1:9696/api/v1/indexer/{indexer}/newznab?t=search&q=movie&apikey={apikey}`

But there isn't any possible to search in all them and return in the rss format like the normal search:

`http://192.168.1.1:9696/api/v1/search?query=movie&apikey={apikey}`

does for json.

### Describe the solution you'd like

We should add a new API in the NewznabController that matches:

`http://192.168.1.1:9696/all/api?t=search&q=movie&apikey={apikey}`
`http://192.168.1.1:9696/api/v1/indexer/all/newznab?t=search&q=movie&apikey={apikey}`

and searches in all the indexers like:

`http://192.168.1.1:9696/api/v1/search?query=movie&apikey={apikey}`

does for json.

### Describe alternatives you've considered

None.

### Anything else?

No.

[AB#1509](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1509)

**Comment by Qstick** [comment]
No plans to do this, we don't want to promote this type of use.
