### ISSUE TITLE
[BUG]: Since fex days OxTorrent and Torrent9 doesn't match with Prowlarr

### ISSUE THREAD

**Issue by narol69** [Prowlarr/Prowlarr#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Prownlarr couldn't connect to OxTorrent and Torrent9 anymore since few days

### Expected Behavior

I try to delete these indexers and recreate them, but no issue

### Environment

```markdown
- OS: Synology DS908+
- Prowlarr: 0.1.1.875
- Docker Install: ghcr.io/linuxserver/prowlarr:develop
- Using Reverse Proxy: no
- Browser: Chrome 92.0.4515.159
```

### What branch are you running?

Develop

### Anything else?

[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/7072866/prowlarr.txt)

[AB#1515](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1515)

**Comment by bakerboy448** [comment]
- Those are not trace logs; please see the wik link included in the template
> Trace Logs (https://wiki.servarr.com/prowlarr/troubleshooting#logging-and-log-files)
Links? References? Anything that will give us more context about the issue you are encountering!
Generally speaking, all bug reports must have trace logs provided.

- Logs indicate only issues with Xthor hitting the rate limit, PR made to bump that to a few hundred ms longer

**Comment by bakerboy448** [comment]
OxTorrent had their definition updated tonight in Prowlarr; run the definition sync and the new url should fix that hopefully

would need logs for Torrent9, but seems jackett would likely have the same issue as well

**Comment by bakerboy448** [comment]
Closing pending addition information from OP
