### ISSUE TITLE
[FEAT]: Encrypted Client Hello (ECH) Formerly named ESNI

### ISSUE THREAD

**Issue by unai-ndz** [Prowlarr/Prowlarr#489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Supporting this would fix all indexers (supporting ECH themselves) blocked by ISP using packet inspection.

I tested this with 1337x.to, blocked by my ISP.
By enabling ECH on firefox (the only browser supporting it for now) I'm able to access it without problem.

Web pages using cloudflare support it already, so 1337x.to works with this.

### Describe the solution you'd like

ECH being supported by prowlarr.

### Describe alternatives you've considered

Setting up a local https forward proxy for prowlarr that forces ECH.
No forward proxy supports it for now AFAIK.
The usual external proxy or vpn will also work ofc but it has to be external.

### Anything else?

ECH it's still in drafts so only firefox and cloudflare (boringssl) afaik support it right now. Tho work is being done in several others it's gonna be a while until it gains wide support but looks pretty promising.

Looks like the heavy lifting is done by the ssl/https library used but I don't know how it works for C#.
Which ssl/https library prowlarr uses?

[For testing it with firefox.](https://blog.mozilla.org/security/2021/01/07/encrypted-client-hello-the-future-of-esni-in-firefox/)
[More info from cloudflare.](https://blog.cloudflare.com/encrypted-client-hello/) 

[AB#1560](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1560)

**Comment by timcoop3r** [comment]
Also interested in this being added. Seems like a brilliant feature to be using considering the use case of Prowlarr and more and more governments pushing regimes reducing privacy. 

Worth noting that Chrome and Edge have provisional support for ECH for some time as well now

**Comment by Qstick** [comment]
https://github.com/dotnet/runtime/issues/43912
