### ISSUE TITLE
[BUG]: Title display in the mobile version is really short

### ISSUE THREAD

**Issue by tchirou** [Prowlarr/Prowlarr#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi
When using a mobile (safari for iOS 14.7.1 on iPhone 11 pro for me) for a search, the title are cut really short, so it's not usable at all
Thanks

### Expected Behavior

Seeing the whole title of the search queries

### Environment

```markdown
- OS: DSM 6.2.4-25556
- Prowlarr: 0.1.1.875-ls17 by linuxserver.io
- Docker Install: 0.1.1.875-ls17 by linuxserver.io
- Using Reverse Proxy:
- Browser: mobile safari
```

### What branch are you running?

Develop

### Anything else?

No

[AB#1561](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1561)

**Comment by stenwt** [comment]
![msg116096463-65929](https://user-images.githubusercontent.com/149782/148142892-60ae639d-1986-43cd-90e0-93647b2380c1.jpg)
submitted as an example. the title bar can't be resized, and it's only this good after I turned off "protocol" and "age" which are to the left of the title by default.

**Comment by tchirou** [comment]
Hi
It's nice, we can view everything at a glance but sorting doesn't seem to work (Safari and chrome on iOS 16.2) at all, nothing happens
Thanks a lot
