### ISSUE TITLE
[FEAT]: Disable instead of removing unavailable trackers

### ISSUE THREAD

**Issue by costaht** [Prowlarr/Prowlarr#494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Prowlarr doesn't offer the option to set up ratio and seed-time goals for trackers, for that reason, those have to be manually added to Sonarr and Radarr.
Today, when a tracker gets individually unavailable or your internet goes down, Prowlarr will remove all these unavailable trackers from the ARRs, which is not a problem at all, since the goal is to avoid timeouts when searching for a new title.
The problem is when the trackers are added back to the ARRs. Since Prowlarr doesn't know what seed-time/ratio are, these configurations are discarded by Sonarr/Radarr.

### Describe the solution you'd like

The implementation of seedtime and ratio goals on Prowlarr have already been requested through the FRs #106 and #188.
I´d like to request a temporary solution while the more complex features are developed which is **disabling** unavailable trackers instead of removing them from the ARRs.

### Describe alternatives you've considered

The feature request itself is a temporary solution to the root problem.

### Anything else?

https://discordapp.com/channels/767843854736949299/767843855109718067/884786138261385216

[AB#1566](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1566)

**Comment by bakerboy448** [comment]
Seems like it'd be reasonable to hold off on removal/de-syncing until the indexer is down for X time given that failed indexers already get disabled.

@Qstick @RobinDadswell you guys have been around the sync logic, this feasible?

**Comment by Qstick** [comment]
> Seems like it'd be reasonable to hold off on removal/de-syncing until the indexer is down for X time given that failed indexers already get disabled.
> 
> @Qstick @RobinDadswell you guys have been around the sync logic, this feasible?

You just closed another issue for the exact same behavior (removed all indexers because they failed) and why I left it open 😉. I would agree it's not ideal behavior.

**Comment by bakerboy448** [comment]
> You just closed another issue for the exact same behavior (removed all indexers because they failed)

https://github.com/Prowlarr/Prowlarr/issues/435  ?

I'm not seeing `(removed all indexers because they failed)`  I'm seeing the indexers were in *arr, but somehow not in Prowlarr at all and then Prowlarr removed them from *arr.

Was that because they were down and Prowlarr pretends down indexers do not exist in its DB - thus removes them from the app?

**Comment by Qstick** [comment]
Correct, looks like user had an event the resulted in all indexers failing (likely network or something). There's a current logic in sync that filters blocked indexers when pulling indexer list during sync, that filtered list is also used as the Prowlarr list for the delete from remote app logic. 

Somewhat easy to fix, just needs done.
