### ISSUE TITLE
Indexer - TPB - Jackett Pull Alt URLS

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#495]
https://github.com/Jackett/Jackett/commit/8fa49fe33781ba4756d0844aa65cc9994a800a40

[AB#1568](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1568)

**Comment by bakerboy448** [comment]
This needs thinking and may require refactoring the TPB definition.

These alt links have no impact on the API calls we make even if added.

https://github.com/Prowlarr/Prowlarr/blob/3455f3c92ae8b7ba17d69360ff3a9c9cf1d5c225/src/NzbDrone.Core/Indexers/Definitions/ThePirateBay.cs#L126

**Comment by Qstick** [comment]
Yml now
