### ISSUE TITLE
[FEAT]: Allow adding Qbittorrent when Qbittorrent is set to delete downloads

### ISSUE THREAD

**Issue by chibomorto** [Prowlarr/Prowlarr#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I’ve configured Prowlarr to use qBittorrent as download client. I also use qBbittorent as download client to other App (Sonarr, Radarr…). Is it possible to allow conection between Prowlarr and qBitorrent even when file deletion options (by ratio or by time) are activated on qBittorrent? I have that option activated so that seeds are deleted after media is imported.

### Describe the solution you'd like

If you disable file deletion, Prowlarr allows to connect do download client, and it keeps working after you renable those options. Why not allow it in the first place?

### Describe alternatives you've considered

Is it possible to simply issue a warning message that file deletion options are enabled in qBitorrent?

### Anything else?

Thank You for the great work!

[AB#1578](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1578)

**Comment by bakerboy448** [comment]
Backing up a bit,  is this Prowlarr throwing a validation error with Qbit saying that Qbit has delete downloads enabled?  Screenshot or two of some specifics may help clarify a bit :)

**Comment by chibomorto** [comment]
Thank you for your answer.
Here is the screenshot.
![qBit 1](https://user-images.githubusercontent.com/89774323/133237789-a81c9fc6-6ed8-47e9-99a6-cbffb6773b0a.jpg)

If I disable the option from qBitorrent side (“When seeding reaches xxx minutes”), I can configure configure Prowlarr and, then, re-enable the qBitorrent option to delete seeds and torrents. Doing this, Prowlarr works “without complaining”.

If I open Prowlarr download client options, and try to save it, even without changing options, Prowlarr throws the error “qBittorrent is configured to remove torrents when they reach their Shrare Rate Limit”, and dosen't allow to save the options.

![Inked1631612575335 - 1_LI](https://user-images.githubusercontent.com/89774323/133238496-afa66c88-5283-490f-9e69-16b06638d728.jpg)

**Comment by chibomorto** [comment]
Thank You.
