### ISSUE TITLE
[BUG]: Socks5 Indexer fails to add due to failing test - To be fixed with Net6

### ISSUE THREAD

**Issue by Roxedus** [Prowlarr/Prowlarr#503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to set up a Indexer Proxy to use a Socks5 is unsuccessful as test fails. 

### Expected Behavior

Having Socks5 indexer proxies working.

### Steps To Reproduce

Get yourself a Socks5 proxy, IE: https://virtualize.link/socks/ ~~Or any shady one from online lists~~
Try to set up said proxy, but test fail, hence no socks for me. 
![image](https://user-images.githubusercontent.com/7110194/133337154-313159ad-f3fd-44f1-b9c4-55663c8bdfb8.png)

Verifying the server is actually responding in the environment Prowlarr runs in:
```sh
$ curl --socks5 qbittorrentvpn:1337 https://prowlarr.servarr.com/v1/ping
Pong
```

### Environment

```markdown
- OS: Unraid 6.9.2
- Prowlarr: 0.1.1.927-ls141 by linuxserver.io
- Docker Install: Yes, I made the damn thing
- Using Reverse Proxy: Yes, but same behavior locally
- Browser: Chrome 93
```

### What branch are you running?

Nightly

### Anything else?

https://0bin.net/paste/iCEUnQuJ#jR4cuNuIj6hXNkQD8rM-lUEp9hE4XH3/JLmpGlhH/Mz

[AB#1584](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1584)

**Comment by lukjod** [comment]
works well on docker install on my qnap x64
![Zrzut ekranu 2021-09-15 195317](https://user-images.githubusercontent.com/1781446/133484542-2ab0a8e5-cf41-4e5b-833d-2c5d3832e48f.png)

**Comment by Roxedus** [comment]
Net6 does wonders :)
