### ISSUE TITLE
Doesn't recognize PTP indexer flags 

### ISSUE THREAD

**Issue by TRaSH-** [Prowlarr/Prowlarr#51]
**Describe the bug**
Prowlarr doesn't recognize PTP indexer flags like GP, Approved and Scene etc...

**To Reproduce**
Do a search and you see no indexer flags are recognized

**Expected behavior**
Recognize indexer flags

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: [Unraid]
 - Mono Version: [.NET Yes (5.0.5)]
 - Browser and Version [All browsers]
 - Prowlarr Version [0.1.0.253]

**Debug Logs**
In my opinion not relevant

**Comment by Qstick** [comment]
For posterity from Discord, Prowlarr recognizes flags just fine from PTP, however they are lost in the transfer from Prowlarr to Radarr. Radarr only supports Freeleech flag from Torznab currently, as well Prowlarr only sends download and upload factors. Changes need to be made on both sides after a standard is decided on for passing indexer specific flags through Torznab

**Comment by bakerboy448** [comment]
companion issue opened on Radarr as 6288 (not linking at this time)
