### ISSUE TITLE
[BUG]: Search bar at top of UI only works when not on search page

### ISSUE THREAD

**Issue by Azelphur** [Prowlarr/Prowlarr#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you go straight to `/search` and type a query in the search bar at the top of the page, Prowlarr seems to search indexers for empty string, giving you some random results.

Alternatively,

If you type a query in the search bar while on a different page, Prowlarr will return results correctly. However if you then enter a new query into the search bar, the results will not update.

### Expected Behavior

Searching while on the `/search` page should return correct results. Performing a second search should clear the results then retrieve new ones.

### Steps To Reproduce

1. Click the "Search" button on the left sidebar.
2. Insert a query into the "Search" bar in the header
3. Observe incorrect results.

Alternatively
1. While not on the search page, insert a query into the "Search" bar in the header
2. Wait for results to load, they will be correct
3. Insert a new, different query into the search bar in the header
4. Results will not update, and will remain the same as the original search.

### Environment

```markdown
- OS: ArchLinux
- Prowlarr: 0.1.1.875
- Docker Install: Yes (linuxserver/prowlarr)
- Using Reverse Proxy: Yes (Traefik)
- Browser: Firefox 91, also Google Chrome 92.0.4515.131
```

### What branch are you running?

Master

### Anything else?

Browser network debugger shows that, if you perform a search for the first time on the `/search` page, the ?query url parameter is blank. If you perform a search for the first time not on the `/search` page, and then perform a subsequent search, the `?query` url parameter will be what you initially searched for, rather than what you are currently searching for.

[AB#1598](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1598)

**Comment by Qstick** [comment]
You are on the search page, why not just use the query input that's there

**Comment by Azelphur** [comment]
That's an odd question - why have a search bar at all if it doesn't work? It only serves to confuse users.

That said, using the query input is a perfectly fine workaround, works great for anyone facing the problem until this issue is resolved

**Comment by Qstick** [comment]
> That's an odd question - why have a search bar at all if it doesn't work? It only serves to confuse users.

Hence why the issue is still open so the bug can be fixed. My comment was more out of curiosity. Why is it that you prefer the top search bar when you are on the search page and can use the main query options? Ease of use I would assume? But again just curious as I've not seen anyone prefer that and use it on the search page.
