### ISSUE TITLE
[FEAT]: Add the possibility to add another instance of Prowlarr as an indexer

### ISSUE THREAD

**Issue by bonny1992** [Prowlarr/Prowlarr#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The main "problem" here is that some indexers (mostly torrent trackers) require the IP to be of a specific country.
It can go well for one or two indexers, you put Prowlarr behind a proxy/vpn, but it's not exactly guaranteed to work.

For example, for some trackers I run Prowlarr at my place, on a RPi4.

### Describe the solution you'd like

Would be cool to being able to add another instance of Prowlarr as a indexer so ultimately you have only one place, centralized.

### Describe alternatives you've considered

I didn't consider some alternative, honestly. Except for what I'm doing right now, which is OKish.

### Anything else?

Nothing that comes into my mind right now

AB#1601

**Comment by Qstick** [comment]
This is why per Indexer proxies exist, also it's already possible using generic newznab or torznab

**Comment by bonny1992** [comment]
I'll be honest @Qstick, I did not notice the per indexer proxy function.

Sorry.

**Comment by Qstick** [comment]
No problem, now you know. Let is know if you have any issues with them
