### ISSUE TITLE
[FEAT]: Add one click selections for categories

### ISSUE THREAD

**Issue by AlecHex** [Prowlarr/Prowlarr#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

I thought if we could use the space we have at the bottom of the search page to add two one-click category selections. Most of us like to only search for one or two categories, usually movies or tv as a whole. 

There are two fixed categories which are movies and tv. Both are followed by a check-box that one can select in order to do a quicker search. I have uploaded a mockup picture as to what I am suggesting for a clearer understanding in the "anything else?" section of this feature request. 

### Describe alternatives you've considered

The only alternative to this was to do it the manual way and select from the entire drop down menu. I thought of this idea as everytime I had to make a search, I had to open the dropdown menu and select the categories. The movies are at 2000s and tv at 5000s and are sorted at numerical order which means a little bit of scrolling is involved and this idea would eliminate that.

### Anything else?

1st image is something i did through paint.
![Feature mockup](https://user-images.githubusercontent.com/46763830/134386989-13708000-0067-4bbf-941d-8de5356b3c5d.png)
2nd is the same but i just added the categories from the UI.
![Feature mockup 2](https://user-images.githubusercontent.com/46763830/134387530-fff8968f-f389-4636-9c89-fbb350efadb2.png)

[AB#1603](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1603)

**Comment by Qstick** [comment]
Have other plans for this page that are being worked on
