### ISSUE TITLE
[FEAT]: Dark Mode Skin

### ISSUE THREAD

**Issue by neo-neo1** [Prowlarr/Prowlarr#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

[With minimum effort it can look like this.
](https://i.imgur.com/4PCJQG1.png)

I don't mind orange nor the gray sidebar but for dark mode users the white background would be nice to eliminate. Those who use dark mode / dark skins in every application the white background in Prowlarr becomes like a glaring sun.

### Describe the solution you'd like

Selectable dark mode skin. Thanks in advance!

### Describe alternatives you've considered

N/A

### Anything else?

If needed for additional ideas you can draw from the several available third party dark skins for Sonarr/Radarr which are enabled with Stylish or another similar browser add-on. Having 1st party support rather then this hack would be optimal. [Link to Stylish skin](https://forums.sonarr.tv/t/darkerr-a-darker-theme-for-sonarr-radarr/14779) Others available as well.

[AB#1606](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1606)

**Comment by bakerboy448** [comment]
No plans.

use theme park https://github.com/GilbN/theme.park
