### ISSUE TITLE
[BUG]: PussyTorrents tracker returning all results

### ISSUE THREAD

**Issue by steve51184** [Prowlarr/Prowlarr#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When searching, PussyTorrents always shows results even when it shouldn't and makes 90% of results wrong when it's enabled

### Expected Behavior

When not searching for porn it should not show results

### Steps To Reproduce

Search for anything none porn related and you'll get hundreds of results you shouldn't

### Environment

```markdown
- OS: Debian
- Prowlarr: 0.1.8.1253
- Docker Install: no
- Using Reverse Proxy: yes
- Browser: chrome
```

### What branch are you running?

Master

### Anything else?

No

[AB#1617](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1617)

**Comment by bakerboy448** [comment]
Logs?  What are you searching? How are you searching?  What categories?

It does not appear the tracker supports any categories in their search. 
https://github.com/Prowlarr/Indexers/blob/906238df7b18934fa438c0e2e95c19f77c501a61/definitions/v1/pussytorrents.yml

**Comment by steve51184** [comment]
I'm searching for any term honestly anything will give results so 'the Simpsons' would give results for prom from PussyTorrents

And I'm searching via the webui and via a 3rd party app same results

**Comment by bakerboy448** [comment]
bug reports still need logs.

https://wiki.servarr.com/prowlarr/troubleshooting#logging-and-log-files

**Comment by Qstick** [comment]
This still borked?

**Comment by steve51184** [comment]
I'll get logs now.. is there a quick and safe way to get them? (API and cookiee etc

**Comment by Qstick** [comment]
If you want to debug this quick, hope on discord

**Comment by bakerboy448** [comment]
Still borked?

**Comment by steve51184** [comment]
> Still borked?

Yup just tested and it still doesn't work a year after I reported it :(

**Comment by bakerboy448** [comment]
Trace logs of this that were requested/required?

**Comment by steve51184** [comment]
[log.txt](https://github.com/Prowlarr/Prowlarr/files/9641404/log.txt)

**Comment by bakerboy448** [comment]
No bug here

`https://pussytorrents.org/torrents/browse?query=big+bang+theory+pilot&page=1&orderby=added`

tracker returns various/random results.

Prowlarr is returning what the tracker did for the search
` 2022-09-25 19:32:37.7|Info|ReleaseSearchService|Searching indexer(s): [IPTorrents, PussyTorrents, Rarbg, 1337x, TorrentGalaxy, PornLeech, NZBgeek, DrunkenSlug, Nzb.su, TorrentLeech, The Pirate Bay, NZBCat, ImmortalSeed, BitHDTV, BeyondHD, MyPornClub, TorrentSeeds (API), Empornium, DOGnzb, Torrenting, XWtorrents, MoreThanTV, RuTracker.RU, PornosLab, MMA-torrents] for Term: [big bang theory pilot], Offset: 0, Limit: 4000, Categories: []`

**Comment by steve51184** [comment]
Yeah the search is totally broken on there site it seems.. will get in touch with them and close this
