### ISSUE TITLE
[FEAT]: Manual per-indexer mappings/transforms for search requests

### ISSUE THREAD

**Issue by Webreaper** [Prowlarr/Prowlarr#521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Sonarr+thexem is all well and good, but occasionally I'd like to be able to just specify my own mappings for a series name on an indexer. So for example:

   `Married at First Sight (UK)` => `Married at First Sight` on a particular tracker.

Yes, I known I can submit a request to thexem, but there are sometimes reasons why doing this is sub-optimal. It would be great if I could set up a mapping in Prowlarr so that any searches for a show would perform two searches - the original show, and the alias that I specify. With some RegEx magic this could also be used to sort out renumbering issues, potentially.

### Describe the solution you'd like

On each indexer, the ability to specify a set of search string transforms - e.g., "text to find in the search, and text to replace it with", potentially supporting regex.

### Describe alternatives you've considered

I've used thexem, but sometimes requests aren't allowed, or aren't practical for various reasons. Having the ability to manually override search titles would be super-handy (and Sonarr are never going to support this, so Prowlarr seems like a good workaround).

There's some use-cases supported in the tool I wrote here: https://github.com/Webreaper/SonarrAutoImport but that only processes name transformations for already-downloaded files, for ingestion into Sonarr. I'd also like to apply the same name transformations for episodes in the search requests.

### Anything else?

Nothing else to add. :)

[AB#1640](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1640)

**Comment by bakerboy448** [comment]
Closing; we do not have plans for this at this time
