### ISSUE TITLE
[BUG]: Cardigann - Store Option Value and not Index Value  & Handle Config Updates

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1337x removed several download options; this broke existing implementations of the indexer

- broke in https://github.com/Prowlarr/Indexers/commit/62cb46cf32cd3472495c7bb8f62582cb6df4d9fe
- hotfix https://github.com/Prowlarr/Indexers/pull/45

This is caused by saving the index value and not the key per Ta
https://github.com/Prowlarr/Prowlarr/blob/1d20b9d429251ec3108568daee767c9904f3a217/src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannBase.cs#L250

### Expected Behavior

Correctly handle when options are removed from YML

### Steps To Reproduce

N/A

### Environment

```markdown
- OS: agnostic
- Prowlarr: 0.1.1.976
- Docker Install: agnostic
- Using Reverse Proxy: agnostic
- Browser: agnostic
```

### What branch are you running?

Nightly

### Anything else?

https://gist.github.com/bakerboy448/a72bae9a7e4de00de7c4cf4c8fd68b73

[AB#1713](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1713)

----

We also need to handle settings changes in YML and ensure the existing indexer updates accordingly
![image](https://user-images.githubusercontent.com/55419169/136259246-4427a650-f1ff-4cbf-8ecb-640a525df030.png)

**Comment by Qstick** [comment]
> We also need to handle settings changes in YML and ensure the existing indexer updates accordingly

Fixed

**Comment by bakerboy448** [comment]
@Qstick we can close this no?
And then merge the 1337x PR on indexers?

**Comment by bakerboy448** [comment]
bump Q

**Comment by IAmSHOCK** [comment]
Is this fixed? I have the same error that is in the gist.

**Comment by bakerboy448** [comment]
This was fixed many months ago.

Perhaps you're on an unsupported old prowlarr version?


Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.
