### ISSUE TITLE
[BUG]: (Indexer) (Torrent) - DesiTorrents - Convert to United from Gazelle

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#532]
Per https://github.com/Jackett/Jackett/pull/12346/files and as reported on discord;  DesiTorrents converted from Gazelle to United.

We need to adjust prowlarr for this.

[AB#1715](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1715)

**Comment by bakerboy448** [comment]
For the interim - Users can implement it as a custom YML which should work 

https://wiki.servarr.com/prowlarr/indexers#adding-a-custom-yml-definition

Download the jackett yml def from: https://raw.githubusercontent.com/Jackett/Jackett/master/src/Jackett.Common/Definitions/desitorrents.yml

rename the file, name, and id to `desitorrents-unitedyml`

**Comment by Qstick** [comment]
The yml shows 5.3.0 (custom). I'm assuming they left the api untouched?

**Comment by bakerboy448** [comment]
> The yml shows 5.3.0 (custom). I'm assuming they left the api untouched?

not sure - no site access.  ilike2burnthing may know?

**Comment by Qstick** [comment]
> > The yml shows 5.3.0 (custom). I'm assuming they left the api untouched?
> 
> yes mostly.

Thanks, I assume the changed part of "mostly" doesn't pertain to anything we are interacting with?
