### ISSUE TITLE
Indexer - ShowRSS - Returning Unrelated Results

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#536]
Reference the ToDo in code:

https://github.com/Prowlarr/Prowlarr/blob/1bfcb99f313d86dabda48b9799306c745943efd1/src/NzbDrone.Core/Indexers/Definitions/ShowRSS.cs#L144

X-Ref https://github.com/Prowlarr/Prowlarr/issues/535

[AB#1743](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1743)

**Comment by slimjim91** [comment]
Looks like a similar problem to what's happening with EZTV. Searching anything brings up unrelated junk. Seems like it needs the same post-filter

**Comment by bakerboy448** [comment]
@slimjim91 

Not at all

ShowRSS is C# and EZTV is not. EZTV is Cardigann/YML.

They have no relation to each other.

See https://github.com/Prowlarr/Indexers/pull/77
https://github.com/Prowlarr/Indexers/issues/78

**Comment by Qstick** [comment]
It's an RSS feed, it's not meant to be used for searches.

**Comment by bakerboy448** [comment]
@mynameisbogdan thoughts on purging ShowRSS and adding it as a default for generic RSS?
