### ISSUE TITLE
[BUG]: logs spam

### ISSUE THREAD

**Issue by ExorcistF1** [Prowlarr/Prowlarr#539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

at the start of pc, then prowlarr and vpn start at same time, vpn break internet when connecting to server, prowlarr start to create a lot of errors and warn messages in event list. (17 pages) 
Log Level:Info

### Expected Behavior

not so much for a few second without connection

### Environment

```markdown
- OS: win 11(194)
- Prowlarr:0.1.1.981
- Docker Install:
- Using Reverse Proxy:
- Browser:Edge 94
```

### What branch are you running?

Nightly

### Anything else?

![image](https://user-images.githubusercontent.com/8391676/136495158-85c0d825-e372-4af1-a71e-62e257b922eb.png)
![image](https://user-images.githubusercontent.com/8391676/136495237-3d128530-843e-439a-bb15-6458063bf542.png)

[AB#1744](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1744)

**Comment by bakerboy448** [comment]
Not a bug; among other things - indexer definitions are refreshed on start up.

your system  should be configured so prowlarr starts delayed & after the VPN is up
