### ISSUE TITLE
Proxy Indexers, not Apps

### ISSUE THREAD

**Issue by Shadow58624** [Prowlarr/Prowlarr#55]
**Is your feature request related to a problem? Please describe.**
I setup some indexers and afterwards an app. After that I remembered to use the proxy. I noticed I no longer was able to connect to the app via the internal docker hostname.

**Describe the solution you'd like**
Proxy only the indexers and not the apps, maybe

**Comment by TheCatLady** [comment]
You can just configure the `Ignored Addresses` setting (which exists in the other *arrs as well).

**Comment by Shadow58624** [comment]
Thank you very much! I'm going to close this now
