### ISSUE TITLE
[FEAT]: Language detection

### ISSUE THREAD

**Issue by Dnkhatri** [Prowlarr/Prowlarr#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently sonarr and radarr detect the language of the file by its name tags only. But site like avistaz have special langauge tags on the website so do not use language tags in file names.

### Describe the solution you'd like

 I would like prowlarr to pass the language information to sonarr and radarr.

### Describe alternatives you've considered

 none

### Anything else?

I think this needs modification in sonarr/radarr and prowlarr both so never submitted as a feature request as the devs were different for jackett and sonarr now with many of the devs being the same I think this feature request is feasible

[AB#1791](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1791)

**Comment by ta264** [comment]
Normally this sort of thing would happen by adjusting the release names that prowlarr sends to sonarr / radarr

**Comment by bakerboy448** [comment]
> I only had avistaz, cinamaz, privatehd in mind they are all sister sites with the same indexer I think. Should I just request a release name send to sonarr and radarr?

yes
