### ISSUE TITLE
Jackett Pull - FlareSolverr V2.0

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#555]
Review https://github.com/jackett/jackett/commit/baac47e4bd0efffe927c02a04a7d429c06bc6a5d

[AB#1792](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1792)

**Comment by Qstick** [comment]
This should work in next nightly.
