### ISSUE TITLE
[BUG]: Avistaz.to Parsing fails

### ISSUE THREAD

**Issue by eckozen84** [Prowlarr/Prowlarr#556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Withing the Apps setting, I have it configured for Sonarr and Radarr with sync level as "Add and Remove Only". Upon the addition of Avistaz.to in Prowlarr, Sonarr will automatically add to its list of indexers as expected. However, Radarr does not.

In addition to this, the same Avistaz error occurs every whenever Sonarr does an RSS sync.

### Expected Behavior

I expect Radarr to add Avistaz to its list of indexers upon its addition in Prowlarr.

### Steps To Reproduce

1. I have installed a fresh docker image of Prowlarr
2. Within the Apps setting, I have configured Sonarr and Radarr with sync level as "Add and Remove Only".
3. Proceed to add all my indexers as desired.
4. One by one, I see my indexers pop into Radarr/Sonarr indexer list as expected.
5. My last indexer to add to Prowlarr is Avistaz.to and I can see it Sonarr, but not Radarr.

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: 0.1.1.978
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome 94.0.4606.81
```

### What branch are you running?

Develop

### Anything else?

Docker logs of Prowlarr when attempting to add Avistaz.to

```
[Error] AvistaZ: An error occurred while processing indexer feed. https://avistaz.to/api/v1/jackett/torrents?in=1&type=1&search= 
[v0.1.1.978] System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at NzbDrone.Core.Indexers.Definitions.Avistaz.AvistazParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Avistaz\AvistazParser.cs:line 25
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 321
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 174
```
More detailed log: 
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/7403302/prowlarr.txt)

[AB#1798](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1798)

**Comment by arifer612** [comment]
I've been getting parsing errors since last night. Attached is my trace log.
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/7536710/prowlarr.trace.txt)

**Comment by Qstick** [comment]
They have something goofy going on with their API and currently randomly returning strings for movie ids. Ex. 

```
      "movie_tv": {
        "imdb": "https:\/\/www.imdb.com",
        "tmdb": "https:\/\/www.themovie",
        "tvdb": "https:\/\/thetvdb.com\/",
        "title": "Game Winning Hit \/ Play Ball \/ \u6bd4\u8cfd\u958b\u59cb",
        "tv_season": null,
        "tv_episode": null,
        "tv_full_season": false,
        "tv_complete": true
```

Normally results should look like this 

```
      "movie_tv": {
        "imdb": "tt15616218",
        "tmdb": "96262",
        "tvdb": "410613",
        "title": "Chimera",
        "tv_season": 1,
        "tv_episode": 6,
        "tv_full_season": false,
        "tv_complete": false
```

Have added a workaround in a3fd37b
