### ISSUE TITLE
Jackett Pull - RarBG - trap error=8 imdbid not found.

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#564]
[rarbg: trap error=8 imdbid not found. resolves #12466
](https://github.com/Jackett/Jackett/commit/c2694011754e29dba5fe852b3b03bb755a7d1712)

[AB#1824](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1824)

**Comment by Qstick** [comment]
We already handle this in our code.... SEARCH!!!!!
