### ISSUE TITLE
Jackett Pull - Remove TVVault

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#573]
https://github.com/Jackett/Jackett/issues/12447

> I had some words with the sysadmin and they are not interested in making changes for Jackett. We should remove this site.

TVVault is anti-automation and believes RSS feeds should be used instead

[AB#1843](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1843)

**Comment by Fiala06** [comment]
Yeah, they disabled my account and told me to not use any scripts etc.
