### ISSUE TITLE
[BUG]: SpeedApp - All Results being filtered due to false positive category mismatch

### ISSUE THREAD

**Issue by M4YH3M81** [Prowlarr/Prowlarr#574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have 9 indexers and SpeedApp is the only one that doesn't sync with Sonarr or Radarr

### Expected Behavior

SpeedApp indexer should sync from Prowlarr to Sonarr and/or Radarr

### Steps To Reproduce

1. Add SpeedApp indexer
2. Attempt to sync indexers with Sonarr and/or Radarr

### Environment

```markdown
- OS: Unraid 6.10 rc2
- Prowlarr: 0.1.1.1030
- Docker Install: Linuxserver:develop
- Using Reverse Proxy:
- Browser: Chrome
```

### What branch are you running?

Develop

### Anything else?

https://pastebin.ubuntu.com/p/cYmctrChFn/

[AB#1850](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1850)

**Comment by bakerboy448** [comment]
Seems like the issue was around matching up the categories here:

https://github.com/Prowlarr/Prowlarr/blob/develop/src/NzbDrone.Core/IndexerSearch/ReleaseSearchService.cs#L180-L182
