### ISSUE TITLE
[FEAT]: internal Flaresolverr tag to be applied to indexers that use Cloudflare protection

### ISSUE THREAD

**Issue by azumukupoe** [Prowlarr/Prowlarr#576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

as of now we have to manually tag indexers to bypass Cloudflare protection

### Describe the solution you'd like

if Flaresolverr tag is created and indexers are tagged internally, then users won't have to worry tagging indexers anymore

### Describe alternatives you've considered

the same way Jackett integrates Flaresolverr
well, actually Jackett labels indexers with "Flaresolverr" in definitions so maybe in essence it's the same solution

### Anything else?

I don't think so

[AB#1851](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1851)

**Comment by bakerboy448** [comment]
There's I believe less than 10 indexers of the over 500 supported that occasionally need Flaresolverr.

Seems like high effort, low reward, minimal benefit - how long does it take to tag an indexer? A few seconds?.  Those indexers don't even need flaresolverr all the time either.

defer to the others on this, but I don't see how the cost (effort) outweighs the benefit.

not to mention not all users may wish to have their indexer with a forced tag

**Comment by bakerboy448** [comment]
Closing; No plans at this time.

tags are easy enough to apply
Indexers requiring flaresolverr do not necessarily always need flaresolverr for every indexer for every user; so a global tag wouldn't make  sense really either.
