### ISSUE TITLE
[BUG]: OXtorrent does not work.

### ISSUE THREAD

**Issue by cedjo** [Prowlarr/Prowlarr#580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

cannot add oxtorrent as an indexer

### Expected Behavior

could add oxtorrent as indexer got redirected but does not seem to work.
same url in browser interface (oxtorrent.pl) got redirected to oxtorrent.pl and works

same indexer also works in jackett

### Environment

```markdown
- OS: ubuntu 20.04
- Using Reverse Proxy: no
- Browser: firefox

Version
    0.1.1.1030
Package Version
    0.1.1.1030-ls22 by linuxserver.io 
.NET
    Yes (5.0.9)
Docker
    Yes
Docker image
    ghcr.io/linuxserver/prowlarr:develop
DB Migration
    13
AppData directory
    /config
Startup directory
    /app/prowlarr/bin
```

### What branch are you running?

Develop

### Anything else?

[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/7473218/prowlarr.debug.txt)
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/7473219/prowlarr.trace.txt)
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/7473221/prowlarr.txt)

[AB#1864](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1864)

**Comment by bakerboy448** [comment]
Likely should be fixed by https://github.com/Prowlarr/Indexers/pull/58 when merged

in the interim you can grab the YML file from that pull request and add it as a custom indexer - see the wiki for instructions 

change the file name, ID, and name.  Say append `-local` or something
