### ISSUE TITLE
[BUG]: Speed.cd indexer login issue

### ISSUE THREAD

**Issue by Noosan1** [Prowlarr/Prowlarr#582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to add indexer. I receive login form errors.

### Expected Behavior

the indexer to be added

### Environment

```markdown
- OS: Debian 10
- Prowlarr: 0.1.1.1030
- Docker Install: no
- Using Reverse Proxy:
- Browser: chrome
```

### What branch are you running?

Master

### Anything else?

Logs: https://0bin.net/paste/qGmzKirW#yLgGvoVv3ys5KsoxuIyKTzodQii29sevbi+MOAiiwli

[AB#1869](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1869)

**Comment by bakerboy448** [comment]
Gonna need an invite
qstick (at) protonmail.com

**Comment by Qstick** [comment]
Fixed, thanks for reporting
