### ISSUE TITLE
[BUG]: *Arr App Sync fails if main base category is not selected

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For Radarr and Sonarr if one disabled 2000 (Movies) or 5000 (Series), but has other subcategories enabled.  The sync test fails.  It appears Prowlarr passes a 0 id indexer to *arr.

Prowlarr Radarr Cats
![image](https://user-images.githubusercontent.com/55419169/140879063-845d761e-7cda-42f3-ae55-be89b1bbcf6e.png)
Prowlarr Radarr Error
![image](https://user-images.githubusercontent.com/55419169/140879110-e69059d7-216a-4e44-bdce-04fb05b81696.png)

Same for Sonarr, but swap to the appropriate cats.

### Expected Behavior

Indexers should sync without issue if a non-main category is enabled.

### Steps To Reproduce

1. Disable 2000 | 5000 in Prowlarr => Settings => Applications => (Advanced) Categories
2. Enable Sub 2000 | 5000 categories
3. Attempt to Save
4. Save Fails

### Environment

```markdown
- OS: agnostic
- Prowlarr: 0.1.2.1052
- Docker Install: agnostic
- Using Reverse Proxy: agnostic
- Browser: agnostic
```

### What branch are you running?

Nightly

### Anything else?

Prowlarr Trace (Radarr Sync) - https://gist.github.com/bakerboy448/6df4ba775d7293ab0434055568980ab9
Radarr Trace (From Sync) - Note ID 0 - https://gist.github.com/bakerboy448/3f42ad13c723d1c152d90def4e0c54b2
Prowlarr Trace (Sonarr Sync) - https://gist.github.com/bakerboy448/51c5e9b15e89db1d28c2e36b6e4382cf
Sonarr Trace (From Sync) - https://gist.github.com/bakerboy448/7fc2e0e20c2e4819f7e5f8c3e8cfe34c

[AB#1886](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1886)

**Comment by neo-neo1** [comment]
Can form I can replicate this bug.

**Comment by Qstick** [comment]
FYI for future knowledge when you see 0, The 0 ID is a generic test endpoint that allows us to test if arr can call back and connect to Prowlarr without actually relying on an indexer working.
