### ISSUE TITLE
[BUG]: DanishBytes tracker - Not Returning Results & Cannot grab releases

### ISSUE THREAD

**Issue by VP-EN** [Prowlarr/Prowlarr#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the new release on the develop branch, I finally was able to test the commit https://github.com/Prowlarr/Prowlarr/commit/b309582d917a7a7925053a130be147a3f0406a37 that fixed [my previous issue](https://github.com/Prowlarr/Prowlarr/issues/568) with the tracker DanishBytes.

This fixed the API key issue, but searching through Prowlarr, selecting the DanishBytes tracker returns no results.. No matter what you put in.

If you manually visit the site: `https://danishbytes.org/api/torrents/v2/filter?search=&api_token=apiTokenRemoved`, you'll get plenty of results. But no results show up in Prowlarr.

Guessing it's because the categories on DanishBytes are weird.

### Expected Behavior

I expected the tracker to work, and for search results to return.

### Steps To Reproduce

1. Add Indexer
2. Find DanishBytes
3. Input the API Key found from `https://danishbytes.org/users/USERNAME/settings/security#api`
4. Press "Save" (or "Test")
5. Wait a few seconds
6. Prowlarr reports: `Indexers unavailable due to failures: DanishBytes`

### Environment

```markdown
- OS: Ubuntu 21.10
- Prowlarr: 0.1.2.1060
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Firefox
```

### What branch are you running?

Develop

### Anything else?

Trace logs:
https://0bin.net/paste/ABuMd+pv#KquKBzihIrIzUhauns32T60cpPNwMri0bTfZ8GAXZie

As I mentioned in the [other issue](https://github.com/Prowlarr/Prowlarr/issues/568), @piratkongen on GitHub is the go-to guy for specific API stuff on DanishBytes.

DanishBytes has an API page: `https://danishbytes.org/pages/5` but it looks quite messy.
Translated something that could be important I guess:
```
[GET] https://danishbytes.org/api/torrents/v2/filter - Get a list of torrents, filtered by search criteria

The API is using the same logic as the official torrent page (DanishBytes.org). 
Information about this can be gathered by:
1. Visiting https://danishbytes.org/torrents
2. Using Chrome Developer Panel (CTRL-SHIFT-I)
3. Opening the "Network" tab
4. You should now be able to see what parameters it's using as input, and how the returning data looks.
```

If you devs need an invite to DanishBytes, hit me up on Discord `VP-EN#7564`

**Comment by bakerboy448** [comment]
> 2021-11-11 18:02:44.2|Error|DanishBytes|An error occurred while processing indexer feed. 

> [v0.1.2.1060] System.InvalidOperationException: Nullable object must have a value.

Can you flip on log indexer response and grab that as well? - hidden page is settings/development

**Comment by VP-EN** [comment]
Output:
https://0bin.net/paste/KXp78Su8#2VEgNwh-1u5A+U8eUDJ9YZhjLYea8gVuG1N8JpJZls4

**Comment by Qstick** [comment]
Try 0.1.2.1074

**Comment by VP-EN** [comment]
> 
> 
> Try 0.1.2.1074

@Qstick I tried the latest nightly (v0.1.3.1077)

No more apparent error, but when I search using Prowlarr, nothing shows up in the search window.

I have some trace logs of me:
1) Opening the config of an already added DanishBytes tracker
2) Pressing "Test" then "Save", 
3) And afterwards searching for the term "paradise".
4) But no results show up in Prowlarr :(
I'm guessing that means it doesn't work

Trace Logs + the "Enhanced Indexer Logging" setting:
https://0bin.net/paste/Trc4eR+D#pbDYIbWI0ULK-BwutTalttbT/20iZID4dFfXVh2PRBd
