### ISSUE TITLE
[BUG] Adding indexer NorBits doesn't work.

### ISSUE THREAD

**Issue by mariusberget92** [Prowlarr/Prowlarr#600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot add the "NorBits" tracker to Prowlarr.
Turned on log level "Trace" and the trace can be found here: https://pastebin.com/Lr1Rm1AR

### Expected Behavior

Expected to be able to add NorBits to Prowlarr. 

### Steps To Reproduce

1. Add indexer Norbits.
2. Fill out form and press test/save.
3. Error.

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: 0.1.2.1060
- Docker Install: No.
- Using Reverse Proxy: No.
- Browser: Firefox.
```

### What branch are you running?

Develop

### Anything else?

Trace log file: [prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/7530590/prowlarr.trace.txt)

[AB#1902](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1902)

**Comment by bakerboy448** [comment]
Code wise - it looks like we're hitting this

```
            // Get login page -- (not used, but simulation needed by tracker security's checks)
            await ExecuteAuth(authLoginRequest);
```

yet setting the method to POST for that section of code as the error indicates does not work
nor does trying this; error is the same of needing POST for forums
![image](https://user-images.githubusercontent.com/55419169/141576822-5ec64d0b-12f1-4c8c-a4a8-fb58626628af.png)

**Comment by Qstick** [comment]
Lets try 0.1.3.1076
