### ISSUE TITLE
Allow empty username and password for qBittorrent download client

### ISSUE THREAD

**Issue by jcplaza** [Prowlarr/Prowlarr#603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you try to add a new download client of kind "QBittorrent" is mandatory to set a username and a password, however in the qBittorrent setup you can allow anonymous, bypassing the authentication in certain situations (clients in localhost or in a specific subnet)

![image](https://user-images.githubusercontent.com/24324605/141763443-717a8b35-9c6a-4d3f-be88-512e991d5d69.png)

### Expected Behavior

Allow empty username and password (or implement a chck-box) for alowwing anonymouns connections to qBittorrent UI

### Steps To Reproduce

Set up a qbitorrent server allowing anonymouns connections from your local LAN
In settings ---> Download Clients --> Push the "+" for adding a client. Choose the kind QBittorrent.

Set up the local IP and portof you qbittorrent, and leave empty username and password --> Push the "Test" button:
![image](https://user-images.githubusercontent.com/24324605/141763443-717a8b35-9c6a-4d3f-be88-512e991d5d69.png)

### Environment

```markdown
- OS: Docker over Libreelec in a RPI4
- Prowlarr: 0.1.1.1030
- Docker Install: 0.1.1.1030-ls22 by linuxserver.io
- Using Reverse Proxy: NO
- Browser: Chrome Versión 95.0.4638.69 (Build oficial) (64 bits)
```

### What branch are you running?

Develop

### Anything else?

I think it's all

[AB#1905](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1905)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

This is already supported and in fact I'm using it. Your issue is not a bug.

this is going to be a Qbit configuration error as the disabling only applies to localhost by default I believe. Localhost is literally the docker container and thus will never work.

for future reference all bug reports require trace logs as well

**Comment by jcplaza** [comment]
In the configuration of qbittorrent is possible to introduce a cidr subnet, in my case I've 192.168.1.0/24.

As you can see in the images I'm not using localhost as the destination, because it only represents the container itself, as you comment.

I've tried using the name of the service In a docker compose config, but with no luck. Maybe the internal SDN of the container is going out with other source ip out of my Lan subnet.


Thanks for your help
