### ISSUE TITLE
Blutopia Search Result Issues (API (Cardigann v3))

### ISSUE THREAD

**Issue by JonzaUK** [Prowlarr/Prowlarr#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I manually search for a episode e.g Dan Browns Lost Symbol S01E09, with Blutopia (API) the results include many different shows and episodes and season packs for series nothing todo with the episode/show I am searching for see attached screenshots

Even with the standard Blutopia added I search for the above mentioned episode and I get results only for Lost Symbol but it includes other episodes within the season? maybe seasons packs I didn't test other shows.

See attached screenshots

<img width="956" alt="Blutopia (Not API)" src="https://user-images.githubusercontent.com/21015102/142081814-b491ebcb-36bc-4765-b56c-a9f62b36527f.png">
<img width="956" alt="Blutopia API" src="https://user-images.githubusercontent.com/21015102/142081817-d7228c65-f886-49df-b7fd-09aab2b9d642.png">

### Expected Behavior

Search for series episode e.g Dan Browns Lost Symbol, results should return only the tv series episode I am searching for not other shows or other episodes within the show.

### Steps To Reproduce

Add Blutopia (API) to Prowlarr manually search episode in Sonarr... check results

Add Blutopia (Standard) to Prowlarr manually search episode in Sonarr... check results

### Environment

```markdown
- OS: Unraid 6
- Prowlarr: 0.1.3.1077
- Docker Install: Unknown
- Using Reverse Proxy: No
- Browser:Chrome
```

### What branch are you running?

Nightly

### Anything else?

**Logs Based on BakersPR**

Trace: https://gist.github.com/JonzaUK/26ec9feba5e965cee3229457e9db0d6b
Trace Debug: https://gist.github.com/JonzaUK/4f132e29dacf891b48f204c796a88400

Sorry I don't know specifically what I am looking for to catch the error... I turned on trace logs ran the manual search on both Blutopia and then copied the logs.

[AB#1913](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1913)

**Comment by bakerboy448** [comment]
Base is United C# (no logs for that)

Cardigann API Request
```
2021-11-16 23:12:38.0|Info|Cardigann|Adding request: https://blutopia.xyz/api/torrents/filter?api_token=(removed)&name=&tmdb=&imdb=10478054&tvdb=365190&sortField=created_at&sortDirection=desc&perPage=100&page=1&categories[]=2
```

Cardigann non-API request
```
https://blutopia.xyz/torrents?categories[]=2&name=&description=&mediainfo=&keywords=&uploader=&tmdbId=&imdbId=10478054&tvdbId=365190&malId=&startYear=&endYear=&playlistId=&collectionId=&sortField=created_at&sortDirection=desc&perPage=100&page=1&free=
```

```

**Comment by JonzaUK** [comment]
Re done the Logs, left the old logs in just in case as marked in the original post.

**Comment by bakerboy448** [comment]
We actually can't get C# logs - https://github.com/Prowlarr/Prowlarr/pull/609

The non-API indexer is using a very old depreciated cardigann definition - so sadly that won't be relevant.

**Comment by bakerboy448** [comment]
Note: API returning messy results is an issue in Jackett as well

**Comment by HDVinnie** [comment]
> Base is United C# (no logs for that) (blocked due to #609 - oops...)
> 
> Cardigann API Request
> 
> ```
> https://blutopia.xyz/api/torrents/filter?api_token=(removed)&name=&tmdb=&imdb=10478054&tvdb=365190&sortField=created_at&sortDirection=desc&perPage=100&page=1&categories[]=2
> ```

Few things wrong I see here.

1) Why are we passing empty keys like `name` and `tmdb`...if null it should not be in the request.
2) The keys are wrong. tmdb->tmdbId , imdb->imdbId , tvdb->tvdbId

https://blutopia.xyz/api/torrents/filter?api_token=APIKEYHERE&imdbId=10478054&tvdbId=365190&sortField=created_at&sortDirection=desc&perPage=100&page=1&categories[]=2

returns the 9 valid results of `Dan Browns Lost Symbol`

**Comment by bakerboy448** [comment]
> The keys are wrong. tmdb->tmdbId , imdb->imdbId , tvdb->tvdbId

jackett def issue; PR'd their fix, we'll pull into Prowlarr's defs.
Possibly fixed custom yml for the interim
https://gist.github.com/bakerboy448/55cd830d1090de51282afaacdb13b872

> Why are we passing empty keys like name and tmdb...if null it should not be in the request

Cardigann v3 bug it appears

**Comment by bakerboy448** [comment]
Jackett is updating the YMLs.
Will pull to Prowlarr Repo tomorrow and add it to the existing PR

**Comment by bakerboy448** [comment]
should be fixed https://github.com/Prowlarr/Indexers/commit/ad6363f9ada3276c67fc23b8423f517a093333e7
refresh the indexer definitions in a few minutes
