### ISSUE TITLE
GayTorrent.ru - Invalid torrent file specified

### ISSUE THREAD

**Issue by didyouexpectthat** [Prowlarr/Prowlarr#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Use Prowlarr to search indexer GayTorrent.ru for downloads
- Tell Prowlarr to add a torrent to the download client (qBittorrent)
- GayTorrent's leech protection returns HTML instead of TORRENT file. Unparasable.
- Tell Prowlarr to download the torrent file. It downloads a .torrent file, but it's really an HTML website talking about violation (See bottom).

**Message**: Task Error: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Invalid torrent file specified)

**Exception**:
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Invalid torrent file specified)
 ---> MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(Stream s)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.Download.TorrentFileInfoReader.GetHashFromTorrentFile(Byte[] fileContents) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentFileInfoReader.cs:line 14
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(ReleaseInfo release, IIndexer indexer, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 144
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(ReleaseInfo release, Boolean redirect, IIndexer indexer) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 116
   at NzbDrone.Core.Download.DownloadService.SendReportToClient(ReleaseInfo release, String source, String host, Boolean redirect) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 77
   --- End of inner exception stack trace ---
```

### Expected Behavior

- Use Prowlarr to search indexer GayTorrent.ru for downloads
- Tell Prowlarr to add a torrent to the download client (qBittorrent)
- Prowlarr will send the file to qBittorrent for download

### Steps To Reproduce

1. Add GayTorrent.ru as a tracker
2. Use a username/password
3. Attempt to download any file.

### Environment

```markdown
- OS: Debian 11
- Prowlarr: 0.1.2.1060
- Docker Install: Yes (0.1.2.1060-ls24 by linuxserver.io)
- Using Reverse Proxy: Yes (HAProxy)
- Browser: Chrome 95
```

### What branch are you running?

Develop

### Anything else?

Trace logs: https://gist.github.com/didyouexpectthat/b433b045a3d20ee1362c651a747f2c61

The HTML fil downloaded basically says: 
```
Download failed!
usage violation
Make sure, you click on the download buttons from search, browse or details Page
If it still does not work, try using a different Browser
```

GayTorrent.tu has some kind of leech protection when you try to download using username/password on a browser page.  You cannot use browser extensions to grab the file either. They have RSS capability which adds a bunch of query params to allow the download. Prowlarr doesn't take the "passkey", it only takes the username/password.  GayTorrent.ru seems to do is append the users' API key to the download URL which allows the user to bypass the leech protection. It's exposed when you are setting up RSS as an alternative download.  

The query parameters are:
URL:  https://www.gaytorrent.ru/download.php
id:  (some hash)
rss: 1  (this is RSS feed request)
n=(name of torrent file).torrent
k= (api key)

Full URL: https://www.gaytorrent.ru/download.php?id=12345&rss=1&n=sometorrentiwant.torrent&k=5a4b3c2d1a

[AB#1921](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1921)

**Comment by bakerboy448** [comment]
Curious, does it work in jackett? - we have the same definition as them

**Comment by didyouexpectthat** [comment]
Hi @bakerboy448, thanks for the quick triage.  Yes, it actually does work in Jackett v0.20.10.  According to Jackett....

```
Request finished HTTP/1.1 GET https://jackett/dl/gaytorrentru/?jackett_apikey={APIKEY}&path={somelongpath}&file={file name without .torrent} - - - 200 27433 application/x-bittorrent 843.7906ms
```

then my Browser add-on intercepts the .torrent download and sends it to qBittorrent successfully. In Prowlarr, doing the same action to download the torrent file downloads the aformentioned HTML-file-in-disguise. 

Here's the "enhanced logging" for Jackett. 
https://gist.github.com/didyouexpectthat/752dd39bf84eb7323338409b6ab19c0e

Unfortunately, they do not have a documented API.    I'll review the two definitions you shared to see if there's anything different. Let me know if you have other thoughts.

**Comment by garfield69** [comment]
FYI we recently patched the gaytorrent.ru indexer on jackett.
The site enforces a daily DL slot limit for some uses, in my case just 4 dl per day are allowed.
when I dl a torrent for the first time I get an intervening page stating the daily dl slots left and a prompt to continue or abort.
subsequent re-downloads of the same torrent do not get this page.
The patched indexer bypasses this page.
However I expect (albeit I did not test) that if a user exceeds their daily limit the dl will fail, as you might expect.

**Comment by bakerboy448** [comment]
@garfield69 as always thanks and much appreciated

@didyouexpectthat you can grab the yml from the indexer's PR and see if that will handle it, can overwrite existing (it'll be nuked next indexer refresh) or edit the filename, yml id, and yml name and drop it in the custom yml folder (wiki has details)
https://github.com/Prowlarr/Indexers/pull/69

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/dcaf1c0bf537f383665d6e855230f71500762487

hopefully fixed with the updated yaml garfield mentioned

refresh your indexer definitions and should be good to go;

closing for now; can reopen if needed
