### ISSUE TITLE
ToDo: flaresolverr v2 does not need useragent param | conditionalize or remove

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#620]
`2021-11-19T16:18:19-06:00 WARN REQ-1 Request parameter 'userAgent' was removed in FlareSolverr v2.`

![image](https://user-images.githubusercontent.com/55419169/142699290-ad2be876-a1c0-4858-87c8-89e06ca032f8.png)

[AB#1928](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1928)

**Comment by Qstick** [comment]
It just gets ignored, no use in adding complexity on our side
