### ISSUE TITLE
Error while parsing field (...) Selector "poster" didn't match

### ISSUE THREAD

**Issue by Don-Chris** [Prowlarr/Prowlarr#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to add the indexers (BiT-TiTAN, AnimeWorld (API)), the error message "Unable to connect to indexer, check the log for more details" appears. In the log files the following cause can be found in both cases:

> [v0.1.4.1126] System.Exception: Error while parsing field=poster, selector=poster, value=<null>: Selector "poster" didn't match {
  "id": "698159",
  "name": "MetArtX.21.11.22.Sonya.Blaze.Hot.Ice.2.XXX.1080p.MP4-WRB",
  }, "size": "766095435",
  "category": "5020",
  "seeds": "1",
  "leechers": "0",
  "snatchers": "0",
  "downloadFactor": "0",
  "uploadFactor": "1",
  "download": "https://bit-titan.net/api.php?downloadID=698159&apiKey=(removed) "added": "1637568602"
}

> [v0.1.4.1126] System.Exception: Error while parsing field=poster, selector=poster, value=<null>: Selector "poster" didn't match {
  "name": "[Amezawa Koma] Winter Vacance (COMIC X-Eros #39)",
  "release_year": null,
  "category": "H-Manga / Doujinshi",
  "type": "Digital",
  "resolution": "",
  "size": 18539442,
  "num_file": 1,
  "freeleech": 0,
  "double_upload": 0,
  "internal": 0,
  "uploader": "setryx",
  "seeders": 6,
  "leechers": 0,
  "times_completed": 6,
  "tmdb_id": "0",
  "imdb_id": "0",
  "tvdb_id": "0",
  "mal_id": "0",
  "igdb_id": "0",
  "created_at": "2021-11-21T22:27:12Z",
  "download_link": "https://animeworld.cx/torrent/download/14036.a0bc7d6e57b1e4ba6eb55483e0e81d51",
  "details_link": "https://animeworld.cx/torrents/14036"
}

### Expected Behavior

The Indexer should be working and should be added to the indexer list.

### Steps To Reproduce

1. Branch nightly, error at least since 18.11.2021. Confirmed in version 0.1.4.1126
2. Try to add Indexer BiT-TiTAN or Animeworld (API)
3. Look in the log file.

### Environment

```markdown
- OS: Ubunto 18.04.6 LTS
- Prowlarr: Prowlarr 0.1.4.1126
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Edge 96
```

### What branch are you running?

Nightly

### Anything else?

https://www.toptal.com/developers/hastebin/ahacijajov.swift
![image](https://user-images.githubusercontent.com/38617646/142830885-bc97a4a7-cbae-41a1-9654-0d8592ef5e27.png)

[AB#1957](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1957)

**Comment by bakerboy448** [comment]
Looks like posters needs to be optional it seems

**Comment by bakerboy448** [comment]
Interim workaround: add `optional: true` as a new attribute below poster for both of those in their yml definition
