### ISSUE TITLE
[yggtorrent] Prowlarr won't find anime episode when searching with title + episode number

### ISSUE THREAD

**Issue by Zareix** [Prowlarr/Prowlarr#631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When searching on YGGTorrent for a anime episode, it use title + episode number (Exx or xx) and won't find anything
Although when searching manually with title + SxxExx, it find episode
Which is an issue since when searching automatically it only use Exx or xx syntax.

### Expected Behavior

It should find the anime episode

### Steps To Reproduce

1. On prowlarr search page
2. Search for : "[An anime complete title] E06" (like "World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat E06")
3. Then search for "[An anime complete title] S01E06" (Like "World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat S01E06")

### Environment

```markdown
- OS: Raspbian 10
- Prowlarr: 0.1.3.1113
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Chromium 90
```

### What branch are you running?

Develop

### Anything else?

<img width="1501" alt="Capture d’écran 2021-11-23 à 18 29 29" src="https://user-images.githubusercontent.com/29818713/143077076-56fb5fa7-1308-49fc-8801-c24493cd4860.png">
<img width="1501" alt="Capture d’écran 2021-11-23 à 18 35 27" src="https://user-images.githubusercontent.com/29818713/143077101-b8a91350-1e91-4f43-956a-44c9a3115f4b.png">
>

[AB#1964](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1964)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

this is not a prowlarr issue, but rather is a sonarr support issue.

if releases are being released as S/E format and not absolute format then the series type should be set to standard not anime.

for manual searches the same concept applies
