### ISSUE TITLE
[YTS Indexer] only show 720p results

### ISSUE THREAD

**Issue by Darkham42** [Prowlarr/Prowlarr#636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Show query result including 720p only.

### Expected Behavior

Show query result including 720p, 1080p, 3D, 2160p

### Steps To Reproduce

Just search for anything with YTS indexer in Radarr or from Prowlarr himself.

### Environment

```markdown
- OS: Ubuntu Server 21.10
- Prowlarr: 0.1.3.1113
- Docker Install: yes
- Using Reverse Proxy: yes
```

### What branch are you running?

Develop

### Anything else?

There was a same issue on Jackett https://github.com/Jackett/Jackett/issues/12463

[AB#1981](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1981)

**Comment by bakerboy448** [comment]
the fix was https://github.com/Jackett/Jackett/commit/3ca7f6bbbe59bfe01b309aa4b3cc10ba27be78f7

@Qstick - they reordered the code, but I don't see anything similar for ours?

```
                    if (r.Details != null)
                        r.Guid = r.Details;
                    else if (r.Link != null)
                    if (r.Link != null)
                        r.Guid = r.Link;
                    else if (r.MagnetUri != null)
                        r.Guid = r.MagnetUri;
                    else if (r.Details != null)
                        r.Guid = r.Details;
```

unless maybe swap these?

https://github.com/Prowlarr/Prowlarr/blob/701c7d349ab2928ba7ce5abd342cb8870300bf19/src/NzbDrone.Core/Indexers/Definitions/Cardigann/CardigannParser.cs#L399-L400

**Comment by Qstick** [comment]
It’s in our HttpIndexerBase or IndexerBase I think

**Comment by bakerboy448** [comment]
> It’s in our HttpIndexerBase or IndexerBase I think

Just looked didn't see it in either and a GH code search doesn't find much either

**Comment by Qstick** [comment]
Yea, I know what I did. Overrode some of our code by accident when I brought the Jackett json stuff over
