### ISSUE TITLE
PixelHD indexer?

### ISSUE THREAD

**Issue by onthecliff** [Prowlarr/Prowlarr#640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I've noticed that PixelHD is not available to be added as an indexer. I apologize if this is not the correct way to request a new indexer.

### Describe the solution you'd like

Add PixelHD as an indexer.

### Describe alternatives you've considered

PixelHD (to my knowledge) does not provide users with API keys, so I could not create a generic torznab.

### Anything else?

No.

[AB#1995](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1995)

**Comment by bakerboy448** [comment]
https://requests.prowlarr.com/b/feedback/p/torrent-pixelhd
