### ISSUE TITLE
PTerClub doesn't generate a CAPTCHA.

### ISSUE THREAD

**Issue by onthecliff** [Prowlarr/Prowlarr#641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cannot add PTerClub as an indexer because when I try to refresh the CAPTCHA symbol, nothing appears.

### Expected Behavior

I expected a CAPTCHA to appear that I could solve and then use to add the indexer.

### Environment

```markdown
- OS: Synology DSM
- Prowlarr: 0.1.3.1113
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox
```

### What branch are you running?

Nightly

### Trace Logs?

Not sure if I need logs for this, if this isn't happening to other people I'll post them, but here's a screenshot https://i.imgur.com/l0Mffgx.jpeg

[AB#1996](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1996)

**Comment by bakerboy448** [comment]
Can't reproduce; likely some local networking issue grab some logs and swing by discord

![00281E13-CB2F-4A9E-B5E8-B196CB3A0A38](https://user-images.githubusercontent.com/55419169/143669489-eda777f3-22e0-49a2-bb6a-5765727df0a0.jpeg)



23:34:11.3|Trace|IndexerHttpClient|Req: [GET] https://pterclub.com/image.php?action=regimage&imagehash=ac7022bf38d208298bbd273c8d22a0bf
2021-11-26 23:34:11.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-11-26 23:34:11.5|Trace|IndexerHttpClient|Res: [GET] https://pterclub.com/image.php?action=regimage&imagehash=ac7022bf38d208298bbd273c8d22a0bf: 200.OK (203 ms)
2021-11-26 23:34:11.5|Trace|Http|Res: 296 [POST] /prowlarr/api/v1/indexer/action/checkCaptcha: 200.OK (687 ms)
