### ISSUE TITLE
IMDB, TVDB. OMDB IDs Not Exposed in API Results

### ISSUE THREAD

**Issue by sysmoon14** [Prowlarr/Prowlarr#656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

trying to use Prowlarr in conjunction with Nabarr ,  but it's failing because I'm not getting any tvdb, tmdb or imdb IDs back from Prowlarr.

This item from DOGnzb via Prowlarr look like this:
```
<newznab:attr name="category" value="5000" />
<newznab:attr name="category" value="5040" />
<newznab:attr name="rageid" value="0" />
<newznab:attr name="thetvdb" value="0" />
<newznab:attr name="imdb" value="0000000" />
<newznab:attr name="tmdb" value="0" />
<newznab:attr name="files" value="0" />
```

but the same item direct from DOGnzb's API returns:
```
<newznab:attr name="category" value="5000"/>
<newznab:attr name="category" value="5040"/>
<newznab:attr name="size" value="1009532026"/>
<newznab:attr name="grabs" value="0"/>
<newznab:attr name="guid" value="6c3b3963fec6bf978c250f7b7b864cc0"/>
<newznab:attr name="info" value="https://dognzb.cr/details/6c3b3963fec6bf978c250f7b7b864cc0"/>
<newznab:attr name="comments" value="0"/>
<newznab:attr name="tvdbid" value="245071"/>
<newznab:attr name="rageid" value="26645"/>
<newznab:attr name="season" value="S12"/>
<newznab:attr name="episode" value="E54"/>
<newznab:attr name="tvtitle" value="The Talk"/>
<newznab:attr name="rating" value="29"/>
<newznab:attr name="genre" value="Talk Show"/>
```

### Expected Behavior

The Prowlarr response should include the relevant IDs.

### Environment

```markdown
- OS: Ubuntu
- Prowlarr: 0.1.6.1173
- Docker Install: yes
- Using Reverse Proxy: Yes
- Browser: Chrome
```

### What branch are you running?

Nightly

### Trace Logs?

`2021-11-30 14:58:55.3|Info|ReleaseSearchService|Searching indexer(s): [DOGnzb] for Term: [], Offset: 0, Limit: 0, Categories: [5040]`

[AB#2016](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2016)

**Comment by bakerboy448** [comment]
Guessing it's due to not parsing those / not adding those to the release info, but I believe Q has an idea.

https://github.com/Prowlarr/Prowlarr/blob/develop/src/NzbDrone.Core/Indexers/Definitions/Newznab/NewznabRssParser.cs
