### ISSUE TITLE
YGGtorrent > cloudflare comeback but...

### ISSUE THREAD

**Issue by TheNexter** [Prowlarr/Prowlarr#659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Jackett work but Prowlarr no, prowlarr don't want use flaresolverr and the indexer not work :(

### Expected Behavior

Indexer not working

### Steps To Reproduce

Simple test

### Environment

```markdown
- OS: Linux
- Prowlarr: Latest version
- Docker Install: Yes
- Using Reverse Proxy: yes
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

No log need, just enable flaresolverr with prowlarr yggtorrent indexer :)

[AB#2021](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2021)

**Comment by Potjoe-97** [comment]
Why has the issue been closed ? I noticed the issue as well : despite flaresolverr logging a successful response, YGGtorrent is still failing in prowlarr. Flaresolverr is properly configured / tagged in prowlarr.

**Comment by bakerboy448** [comment]
@Potjoe-97 

Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

This was an invalid bug report.

https://github.com/Prowlarr/Prowlarr/issues/660

And was fixed in nightly last night
