### ISSUE TITLE
[Bittorrentfiles] Failing to login

### ISSUE THREAD

**Issue by kingofdunghill** [Prowlarr/Prowlarr#666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since #665 was closed and its a prowlarr side issue for sure, i repost the problem.

Trying to add Bittorrentfiles as an indexer. login credentials are correct as other configuration is. Test and save fail. Other tracker are all addable properly. With these bittorrentfiles login credentials i can connect to the indexer in jackett flawlessly.

Thx for your help.

### Expected Behavior

Tracker should be connectable and addable.

### Steps To Reproduce

1. just try to add the indexer bittforrentfiles with correct login credentials
2. will fail right now (pretty sure its a common issue, i think they have made changes recently)

### Environment

```markdown
- OS: Ubuntu 18.04
- Prowlarr: 0.1.6.1184
- Docker Install: ghcr.io/linuxserver/prowlarr:develop
- Using Reverse Proxy: no
- Browser: chrome
```

### What branch are you running?

Develop

### Trace Logs?

https://www.toptal.com/developers/hastebin/ayikaraxoq.js

[AB#2032](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2032)

**Comment by bakerboy448** [comment]
```
2021-12-03 19:48:52.0|Trace|IndexerHttpClient|Req: [POST] https://bittorrentfiles.me/signin.php: user=(removed)&pass=(removed)&returnto=
2021-12-03 19:48:52.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-03 19:48:52.9|Trace|IndexerHttpClient|Res: [POST] https://bittorrentfiles.me/signin.php: 200.OK (854 ms)
2021-12-03 19:48:52.9|Trace|IndexerHttpClient|Response content (3344 bytes):
[trimmed and paraphrased/translated]
Error is The login process could not be started due to missing data!
```

**Comment by bakerboy448** [comment]
Debugging this further; I can't see any issues with Cardigann or the POST for it; it seems to match my testing with chrome for what is posted to the site.

Does your username and/or password have any non-alphanumeric characters in it?

**Comment by kingofdunghill** [comment]
it has a dot in it. thats the problem? Will change it...

**Comment by bakerboy448** [comment]
Could be. Figure it's an easy test.  Let us know

**Comment by kingofdunghill** [comment]
Tried & and # instead of the dot (they require a special symbol in the password). username is only letters. At the moment I am banned again. Will still try something around and if it does not work just use jackett for the tracker. thx for help.

**Comment by bakerboy448** [comment]
looks like a `.` should be fine, but other special characters encoded for URLS _may_ not be

compared a chrome login post body with a Prowlarr post body,  a `.` is sent as-is, but Prowlarr encodes a `$` into its HTML equivalent of `%24`

Needless to say I'm stumped;  will need Qstick to take a look

**Comment by kingofdunghill** [comment]
No chance to get it working from my side. 

Log: "Der Anmeldevorgang konnte aufgrund fehlender Daten nicht gestartet werden!</p><br /><br />	<p>Hinweis: Cookies m&uuml;ssen aktiviert sein!"

That means: The login process could not be started due to missing data! Note: Cookies must be enabled.

**Comment by imba3r** [comment]
I have the same issue. Do you need more logs?
FYI If  I change the yml definition of the tracker to **cookie everything works as expected**.

Unfortunately the cookie expires after 24 hours so that is not really feasible.

**Comment by imba3r** [comment]
Changing the login method from `form` to `post` surprisingly also fixes it and adding `returnTo` like that also fixes it!

```
    path: signin.php
  - method: form
  - form: form
  + method: post
    inputs:
      user: "{{ .Config.user }}"
      pass: "{{ .Config.pass }}"
  +   returnto: "%2Fbrowse.php"
```

@bakerboy448 can we change the defintion like that?

![image](https://user-images.githubusercontent.com/355057/151199258-73820e45-8c6e-45d8-b8f8-e44bc643b531.png)

**Comment by bakerboy448** [comment]
> Changing the login method from `form` to `post` and adding `returnTo` like follows also fixes it!
> 
> ```
>     path: signin.php
>   - method: form
>   - form: form
>   + method: post
>     inputs:
>       user: "{{ .Config.user }}"
>       pass: "{{ .Config.pass }}"
>   +   returnto: "%2Fbrowse.php"
> ```
> 
> @bakerboy448 can we change the defintion like that?
> 
> ![image](https://user-images.githubusercontent.com/355057/151199258-73820e45-8c6e-45d8-b8f8-e44bc643b531.png)

Feel free to PR it up on the Repo
https://github.com/Prowlarr/indexers
