### ISSUE TITLE
YGGtorrent.re new link for the website

### ISSUE THREAD

**Issue by ptichalouf** [Prowlarr/Prowlarr#677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

New link for YGGtorrent the old one doesn't work anymore

https://yggtorrent.re/

### Expected Behavior

New link for YGGtorrent the old one doesn't work anymore

https://yggtorrent.re/

### Environment

```markdown
- OS: unraid
- Prowlarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

New link for YGGtorrent the old one doesn't work anymore

https://yggtorrent.re/

[AB#2093](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2093)

**Comment by Qstick** [comment]
Already been fixed

**Comment by ptichalouf** [comment]
Thanks for being so quick but i can't find the new url on my prowlarr i'm on the dev branch

**Comment by bakerboy448** [comment]
Run the indexer definition sync task
