### ISSUE TITLE
Torrent9 Cannot be added to Sonarr due to no TV results on Top

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#684]
Torrent9 cannot be added to Sonarr as there are no parsable TV results on the Top page which only lists movies per the Indexer Definition

> Thanks for the tip but I fear this didn't work.
I added Others in sonarr's settings in prowlarr but I still get this:
````
	8:36am	ApplicationService	NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://sonarr:8989/api/v3/indexer]	
8:36am	HttpClient	HTTP Error - Res: [POST] http://sonarr:8989/api/v3/indexer: 400.BadRequest [ { "isWarning": false, "propertyName": "", "errorMessage": "Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.", "severity": "error" } ]	
8:36am	Cardigann	Adding request: https://www.torrent9.pw/top	
8:36am	ReleaseSearchService	Searching indexer(s): [Torrent9 clone] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000]	
8:36am	ApplicationService	NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://sonarr:8989/api/v3/indexer]	
8:36am	HttpClient	HTTP Error - Res: [POST] http://sonarr:8989/api/v3/indexer: 400.BadRequest [ { "isWarning": false, "propertyName": "", "errorMessage": "Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.", "severity": "error" } ]	
8:36am	Cardigann	Adding request: https://torrent9.to/top_torrent.html	
8:36am	ReleaseSearchService	Searching indexer(s): [Torrent9] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000]	
8:
````
> Other indexers get added to sonarr without issues but it seems this one doesn't pass the sonarr test.
> Any help will be very much appreciated.
> Thanks in advance.

_Originally posted by @toxic0berliner in https://github.com/Prowlarr/Prowlarr/issues/394#issuecomment-987648687_

[AB#2106](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2106)

**Comment by bakerboy448** [comment]
@toxic0berliner Your indexer did not have any tv results that Sonarr could detect and parse on the test page `https://torrent9.to/top_torrent.html`

thus it cannot nor will be added to sonarr.

@garfield69 would it make sense to change Torrent9's query conditionalize the query based on the category being searched and just query those categories rather than Top?  Any reason in particular

**Comment by garfield69** [comment]
>would it make sense to change Torrent9's query conditionalize the query based on the category being searched and just query those categories rather than Top? Any reason in particular

The solution to using torren9 with Sonarr is described in the info box of the config, which used to read:
```html
Torrent9 only returns category <b>Movies</b> in its <i>Keywordless</i> search results page.</br>
To pass your apps' indexer TEST you will need to include the 131681(Movies) category.
```

At the time that this indexer was written, the web site only provided a category column on the rows of the torrent search page containing **keywords**. The website to this day still does not allow searches without a keyword.
So when Sonarr does a TEST, it performs a keywordless search query, and there was no way to return categories from the results of the web site home page which had, at that time, the 10 latest movies, 10 tv, 10 music, 10 games and 10 books, all without a category.

However, having just had a look at the web site today, I see that the web site's home page now includes a category column in the rows, so [f3dfeba082002674b96330a99102f245f2cb320d](https://github.com/Jackett/Jackett/commit/f3dfeba082002674b96330a99102f245f2cb320d) has been committed which will bring this indexer back to fully supporting categories for all queries.

**Comment by bakerboy448** [comment]
Awesome! as always, thanks garfield!

Fixed with https://github.com/Prowlarr/Indexers/commit/fb0fa556a0618609a01d46f8952f58651156e0a1

**Comment by toxic0berliner** [comment]
Awesome, thanks a lot! Confirmed working for me today! Great job and awesome reactivity!
