### ISSUE TITLE
Send language data in release name to  sonarr and radarr from avistaz network websites 

### ISSUE THREAD

**Issue by Dnkhatri** [Prowlarr/Prowlarr#694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

As Avistaz network websites have separate tag for audio and subtitle language the languages are not properly detected by sonarr and radarr.  

### Describe the solution you'd like

The solution would be to add the language tag to the release name send to sonarr and radarr.

### Describe alternatives you've considered

none

### Anything else?

https://github.com/Prowlarr/Prowlarr/issues/553

[AB#2118](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2118)

**Comment by bakerboy448** [comment]
So  to be clear this would be parsing the results from the site to additionally get audio and subtitle language and then add them to the release name?

An example site response would be useful :D

**Comment by Dnkhatri** [comment]
> So to be clear this would be parsing the results from the site to additionally get audio and subtitle language and then add them to the release name?
> 
> An example site response would be useful :D

I would not know how to get the site response etc normally the site name for the torrent is like this 
Melancholia S01E10 1080p WEB-DL AAC H.264-AppleTor with no mention of language as the language has a seperate tag

**Comment by Qstick** [comment]
Example API Item, we just need to figure out how we pass this along and add it to our nab response. Lang formats, etc.. 

```
    {
      "id": 187239,
      "url": "https:\/\/avistaz.to\/torrent\/187239-the-heartland-hero-2021-s01e54-1080p-web-dl-aac-20-h264-ordinaryperson",
      "download": "https:\/\/avistaz.to\/rss\/download\/(removed)\/(removed).torrent",
      "type_id": 2,
      "type": "TV-Show",
      "info_hash": "(removed)",
      "file_name": "The Heartland Hero 2021 S01E54 1080p WEB-DL AAC 2.0 H.264 - OrdinaryPerson",
      "file_size": 703242056,
      "file_count": 1,
      "seed": 5,
      "leech": 1,
      "completed": 4,
      "downloaded": 10,
      "upload_multiply": 1,
      "download_multiply": 1,
      "adult": false,
      "video_quality_id": 3,
      "video_quality": "1080p",
      "rip_type_id": 12,
      "rip_type": "WEB-DL",
      "movie_tv": {
        "imdb": null,
        "tmdb": null,
        "tvdb": "409041",
        "title": "The Heartland Hero",
        "tv_season": 1,
        "tv_episode": 54,
        "tv_full_season": false,
        "tv_complete": false
      },
      "audio": [
        {
          "id": 33,
          "language": "Chinese"
        }
      ],
      "subtitle": [
        {
          "id": 45,
          "language": "English"
        }
      ],
      "music_type": null,
      "created_at": "2021-11-14 23:11:49"
    },
```

**Comment by Dnkhatri** [comment]
HI any update on this can the language information be parsed and added to the filename

**Comment by Dnkhatri** [comment]
This seems to have been implemented as I see the correct language tags in sonarr v4

**Comment by bakerboy448** [comment]
This wasn't implemented yet.
Likely what you're seeing in Sonarr v4 is some of the various improvements

**Comment by Dnkhatri** [comment]
> just parsing from the sites was added and adding it to the release - don't think it was being acted on otherwise?
> 
> Likely what you're seeing in Sonarr v4 is some of the various improvements.
> 
> Edit: yeah sonarr's release model doesn't even pull in the language fields it appears https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Parser/Model/ReleaseInfo.cs
> 
> probably a positive side affect from the various language changes/improvements.

You are right going through some of the imports I am not sure what is happening. Although Prowlarr does seem to send the correct language tags now in the search results for sonarr to start the downloads while importing the episode for some shows the file language changes to English for some shows where as it stays correct for others

**Comment by bakerboy448** [comment]
Prowlarr has this implemented (tags are passed in the response)

consumers will need to have feature requests implemented to use the language torznab details

Radarr has implemented this already
https://github.com/Radarr/Radarr/commit/efd4abfa3eaab0b476ff8d69a7ef4fc98ae1fd7d
