### ISSUE TITLE
yggcookie -  Unexpected response status ServiceUnavailable code from API request

### ISSUE THREAD

**Issue by almottier** [Prowlarr/Prowlarr#698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 I have `Unexpected response status ServiceUnavailable code from API request` when testing YGGCookie now.

### Expected Behavior

It was working great for the last few days. Maybe they start to block Prowlarr User-Agent as I saw it was hapenning with other trackers.

### Environment

```markdown
- OS: Ubuntu
- Prowlarr: 0.1.8.1232
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: Chrome
```

### What branch are you running?

Nightly

### Trace Logs?

[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/7697591/prowlarr.txt)

[AB#2126](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2126)

**Comment by bakerboy448** [comment]
Those logs are just HTML and now Prowlarr logs.

many way it's not a Prowlarr bug if YGG is blocking the UserAgent that they said to use and would be allowed by Cloudflare.

you likely need flaresolverr again.

once again it seems that YGG is just anti-automation based on their repeated actions.


Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.
