### ISSUE TITLE
Enable redirecting to indexers on indexers' sortname 

### ISSUE THREAD

**Issue by kevgao** [Prowlarr/Prowlarr#703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Current redirect links are extremely tiny on indexers stat page and not obvious. 

### Describe the solution you'd like

It would be great if links are enabled to redirect to indexers/trackers on indexers' sortname.
 

### Describe alternatives you've considered

An alternative way is to show the website logo of the indexers and enable redirecting to the indexer by clicking on the logo.

### Anything else?

Current indexers stat page:

![current](https://user-images.githubusercontent.com/1236505/145701329-931ec81b-8855-49ce-83dc-2f8362f86a94.png)

Proposed indexers stat page:

![better](https://user-images.githubusercontent.com/1236505/145701336-ec74a7e3-4cea-4b3d-8476-10dafff67802.png)

[AB#2131](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2131)

**Comment by Qstick** [comment]
This competes with #546 

Can't do both

**Comment by bakerboy448** [comment]
IMO My votes for #546
The indexer link is easily accessed from (I)
