### ISSUE TITLE
Prowlarr not workIng with Blutopia

### ISSUE THREAD

**Issue by mason1171** [Prowlarr/Prowlarr#707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Blutopia changed freeleech functionality, breaking Prowlarr integration. BLU has 0%, 25%, 50%, 75% and 100% for freeleech now

### Expected Behavior

A searchable indexer

### Steps To Reproduce

1) Add BLU
2) Test

### Environment

```markdown
- OS: Unraid 4.9.1
- Prowlarr: 0.1.1.1030
- Docker Install: Yes
- Using Reverse Proxy: No
```

### What branch are you running?

Develop

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/7700075/prowlarr.txt)

[AB#2135](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2135)

**Comment by bakerboy448** [comment]
> - Prowlarr: 0.1.1.1030

You're extremely out of date; Update

**Comment by mason1171** [comment]
> > * Prowlarr: 0.1.1.1030
> 
> You're extremely out of date - almost two months behind; Update
> 
> With that said; yes they switched to the new UNIT3D beta API - so the definition will need to be updated.

Oh wow. Sorry. Thought I had auto update on. That fixed it. Thanks
