### ISSUE TITLE
Nzb Download Link incorrect for Sonarr

### ISSUE THREAD

**Issue by notschema** [Prowlarr/Prowlarr#71]
**Describe the bug**

Upon adding an application and setting the Prowlarr Server without a port if using as reverse proxy.

e.g entering radarr.domain.com it automatically appends the port resulting in radarr.domain.com:9696 and when it queries the download of the nzb/torrent fails

[v3.0.6.1196] System.Net.WebException: The operation has timed out.: 'http://prowlarr.domain.com.au:9696/4/download?apikey=(removed)' ---> System.Net.WebException: The operation has timed out.

**To Reproduce**

1. Go to /settings/applications
2. Add an application and set the Prowlarr Server as a domain instead of an Ip address appended with the port
3. Attempt to download something via Sonarr/Radarr with the server set as the reverse proxy URL

**Expected behavior**
It should not append the :9696 as it is behind a reverse proxy.

**Platform Information (please complete the following information):**
 - OS: 
 - Docker:  Yes
 - .NET Version (System -> Status):  5.0.6
 - Prowlarr Version: 0.1.0.315
 - Prowlarr Branch: nightly

I haven't submitted a bug report on Github before for anything, so let me know if anything is incorrect or if more info is needed.
I know this is a very early version of Prowlarr, so this will probably pop up / if it hasn't already.

**Comment by bakerboy448** [comment]
could not reproduce this with some quick testing: every test confirmed prowlarr will use exactly what the user inputs.

Also looks like you removed the most important part of bug reports from your post.

> Turn on Trace logs under Settings -> General and wait for the bug to occur again.
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**


to be clear: you're entering: `prowlarr.domain.com` as the Prowlarr URL in the application settings and then in the logs that is turning into `prowlarr.domain.com:9696` ?

screenshot & trace logs to confirm?

**Comment by notschema** [comment]
Sorry for not including the trace report, i was on mobile at the time and wasn't able to get it - but wanted to get it submitted so it was able to be seen.


_to be clear: you're entering: prowlarr.domain.com as the Prowlarr URL in the application settings and then in the logs that is turning into prowlarr.domain.com:9696 being sent to the app ?_

Yes that is correct - the logs are on Sonarr, not Prowlarr to clarify - Wasn't sure if to post it here or on Sonarr, as a bug as it is directly related

Line 3058 is what i am talking about.

![chrome_U5f3a4VEI1](https://user-images.githubusercontent.com/18462338/119485214-2b0fc880-bd9a-11eb-9a57-dd1b618bc185.png)
![chrome_7i7Ew5qZ1b](https://user-images.githubusercontent.com/18462338/119485305-3ebb2f00-bd9a-11eb-8dea-4f2d054ae1f2.png)



[Sonarr Log.txt](https://github.com/Prowlarr/Prowlarr/files/6538610/Sonarr.Log.txt)

**Comment by bakerboy448** [comment]
Full disclosure, on mobile so can't see actual line numbers, but a review of those sonarr logs seems to indicate the indexers are added just fine. And are correctly at the subdomain without the port, as matches your screenshot. Prowlarr Server Input for Sonarr (I'll assume typos and inaccurate obfuscation on your screenshot) `indexers.example.com.au`
Output (sonarr log): `http://indexers.example.com.au/`

so that matches sonarr's logs for the indexers.

regardless, I see no instances of the port being mysteriously appended in that log?

**Comment by notschema** [comment]
Yeah no problem, that's why i didn't include it originally - was a bit difficult.

On line 3058

21-5-25 10:36:42.9|Trace|HttpClient|Req: [GET] http://indexers.example.com.au:9696/1/download?apikey=(removed)&link=OHBDMjIxTGI0cHRrdVdpRGdSTVpMSlg4U1p1NlBld0lmMEdqaURvTmhYS21JRE00ZGNjQ0NvS09aUlVvRit2U3JzdCtGQUVKS2YvSk1PQ1g0elpIVEhuWGhxM01UOFF1Mmd3d3NRRVF2QzZyYlNnTklMY1BCSU1Rc3BDMWluem5DUWF5WFNFekdlOFl1dzI3ZWV6akRzcFdJc3VJNklRekUrVCtMbEVsT1JJPQ&file=24.S08E03.1080p.BluRay.X264-AVCDVD

After this occurs in the logs, it fails to fetch the nzb.
Let me know if you need me to do another trace or anything else.

**Comment by bakerboy448** [comment]
Relevant Log snip from sonarr

in this case we should not have the port and should probably be using the same prowlarr url the app config is set

> 21-5-25 10:36:42.9|Trace|HttpClient|Req: [GET] http://indexers.example.com.au:9696/1/download?apikey=(removed)&link=OHBDMjIxTGI0cHRrdVdpRGdSTVpMSlg4U1p1NlBld0lmMEdqaURvTmhYS21JRE00ZGNjQ0NvS09aUlVvRit2U3JzdCtGQUVKS2YvSk1PQ1g0elpIVEhuWGhxM01UOFF1Mmd3d3NRRVF2QzZyYlNnTklMY1BCSU1Rc3BDMWluem5DUWF5WFNFekdlOFl1dzI3ZWV6akRzcFdJc3VJNklRekUrVCtMbEVsT1JJPQ&file=24.S08E03.1080p.BluRay.X264-AVCDVD
