### ISSUE TITLE
Pull Radarr HTTP fixes & BSD Tests

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#715]
https://github.com/Radarr/Radarr/pull/6826

[AB#2165](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2165)

**Comment by Qstick** [comment]
Prowlarr doesn’t use the new client due to cookie handling issues, if anything this will just be a todo on #685 if the cookie issues ever get worked out there
