### ISSUE TITLE
[Bug] Advanced Settings in Settings area needs to be selected to see advanced settings in Indexers

### ISSUE THREAD

**Issue by muddro1** [Prowlarr/Prowlarr#716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When modifying an indexer, cannot modify some of the advanced settings such as priority. The Main indexer page does not include an option for advanced settings. You need to go to the settings tab, switch on advanced settings, then go back to Indexers, modify an indexer, and then you will have access to the advanced settings.

### Expected Behavior

Indexer tab to have a Hide/show Advanced settings option

### Environment

```markdown
- OS: UnRaid
- Prowlarr:     0.1.8.1259
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox
```

### What branch are you running?

Nightly

### Trace Logs?

Don't think this applicable

[AB#2169](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2169)

**Comment by bakerboy448** [comment]
This is not a bug.

This also already exists. The toggle is at the bottom of the indexer screen with the gear icon
