### ISSUE TITLE
add support for TVDB ID based searching for Avistaz

### ISSUE THREAD

**Issue by JassyLyn** [Prowlarr/Prowlarr#717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I think this feature will help for searching :)

### Describe the solution you'd like

It would be nice to add support for TVDB ID based searching for Avistaz!

### Describe alternatives you've considered

none

### Anything else?

none

[AB#2178](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2178)

**Comment by Qstick** [comment]
Avistaz have api docs? My account got removed due to inactivity

**Comment by bakerboy448** [comment]
yeah going to need API docs for this (and we can apply it to the sister sites as applicable as well)

or a user with access to the site to PR it

**Comment by Jessie722** [comment]
I really want to help but I don’t know how to get API docs at all.
I have a user. Can you tell me how doing this?

**Comment by bakerboy448** [comment]
Asking them is typically a good start :)

**Comment by JassyLyn** [comment]
> Asking them is typically a good start :)

Okay, I'll try :)

**Comment by Qstick** [comment]
I reached out to AvistaZ support today, the answer was they have no docs, I was wasting their time, and given I was not a "Member" and couldn't use the API anyway it didn't matter. Needless to say their support staff leaves a bit to be desired, but no worries. 

I've identified that they will accept `tvdb` and `tmdb` as search parameters to the API based on some old stuff I found online, so I'll add those. However, what we don't know is if they will accept an Id and search string together to limit the search down on episodes.. This may have to be a trial and error approach given the lack of support they are wanting to provide. 

@abixalmon apologize for the ping, but I noticed you were active on some old Jackett issues related to the API. Can you let us know about passing multiple parameters on a search (one being an id)? 

Ex.
```
https://avistaz.to/api/v1/jackett/torrents?tvdb=410350&search=S01E60
```
or in case of absolute episode numbers
```
https://avistaz.to/api/v1/jackett/torrents?tvdb=402331&search=E96
```

**Comment by Qstick** [comment]
Worked with @0-MegaMind-0 today (who was a big help) to test and resolve this. I believe the commit yesterday, which combines id and search, should clean up our implementation, add id capabilities, and return applicable episode and season releases for tv id searches. Closing this as resolved. 

Let us know if there are any issues @JassyLyn
