### ISSUE TITLE
TorrentSeeds now uses UNIT3D

### ISSUE THREAD

**Issue by Mouton99** [Prowlarr/Prowlarr#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

They were using a custom backend.

### Expected Behavior

Now they switched to UNIT3D.

### Steps To Reproduce

https://torrentseeds.org/

### Environment

```markdown
N/A
```

### What branch are you running?

Master

### Trace Logs?

N/A

[AB#2277](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2277)

**Comment by Mouton99** [comment]
Was able to download from the new TorrentSeeds using this custom definition:
[torrentseeds-api.yml.txt](https://github.com/Prowlarr/Prowlarr/files/7789209/torrentseeds-api.yml.txt)

(I copied Aither.cc and changed URL, categories, etc.)

**Comment by bakerboy448** [comment]
Cool!
On mobile for a few days, any chance you'd want to PR the YML to the prowlarr indexer repo and also Obsolete the C# implementation - similar to what was done with https://github.com/Prowlarr/Prowlarr/commit/80c31e8660c805d106f184eabd088f971bc9526a
