### ISSUE TITLE
Import indexers from Jackett

### ISSUE THREAD

**Issue by bdcarr** [Prowlarr/Prowlarr#737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I'm switching to Prowlarr from Jackett, and the task of manually setting up all my indexers again is daunting for lazy old me.

### Describe the solution you'd like

Some kind of import functionality where Prowlarr can read Jackett's config files and migrate your existing indexers over. 

### Describe alternatives you've considered

The alternative is to just set them up manually, which I'll do. If I were motivated, I suppose I'd write a script which read all the JSONs from Jackett's `Jackett/Indexers` folder, mapped their properties to properties in Prowlarr, then added them to the Prowlarr database. But that might be a much bigger job than it sounds.

### Anything else?

nope!

[AB#2279](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2279)

**Comment by bakerboy448** [comment]
Closing; No Plans

A lot has changed/Improved on our side. So there are cases when setting up indexer in Prowlarr requires different info
