### ISSUE TITLE
semiPublic is inaccurate

### ISSUE THREAD

**Issue by john-tompkins** [Prowlarr/Prowlarr#744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is currently (as of writing this) only 1 indexer included in the "semiPublic" filter when searching for a new indexer in the "Add Indexer" pop-up window.

### Expected Behavior

Unless I'm misunderstanding the definition of "semiPublic", any indexers that require a username/password should have this value versus "public".

### Steps To Reproduce

1. Open Prowlarr
2. Navigate to Indexers
3. Click "Add Indexer"
4. Filter "Privacy" by "semiPublic"

### Environment

```markdown
- OS: linux / synology
- Prowlarr: 0.1.9.1313
- Docker Install: n/a
- Using Reverse Proxy: no
- Browser: firefox
```

### What branch are you running?

Master

### Trace Logs?

ignoring for now.

[AB#2285](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2285)

**Comment by Qstick** [comment]
The problem

https://github.com/Prowlarr/Prowlarr/blob/7f28f64cbee676ce289a8c00c37b23c73fc68e29/src/NzbDrone.Core/Indexers/IndexerFactory.cs#L97
