### ISSUE TITLE
[REQ] Tracker Request - Great Poster Wall

### ISSUE THREAD

**Issue by xiNeRoar** [Prowlarr/Prowlarr#755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

This is a private tracker of Chinese content and it is open registration currently. Please add it to prowlarr. Thank you very much.

https://greatposterwall.com/register.php

### Describe the solution you'd like

Add this tracker to prowlarr

### Describe alternatives you've considered

No idea

### Anything else?

No

[AB#2293](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2293)

**Comment by bakerboy448** [comment]
Closing

Tracker Requests do not go on GitHub.
