### ISSUE TITLE
Add "privacy" option to custom filters

### ISSUE THREAD

**Issue by jeff47** [Prowlarr/Prowlarr#759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

In the Indexers display, you can create a custom filter based on a number of attributes, but privacy is missing.

### Describe the solution you'd like

Add a field so Indexers can be filtered based on privacy, in addition to name/app profile/type etc.

### Describe alternatives you've considered

none?

### Anything else?

n/a

[AB#2303](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2303)

**Comment by jeff47** [comment]
Wow that was fast!

**Comment by Qstick** [comment]
Thanks for the request!
