### ISSUE TITLE
Problem with tracker abn

### ISSUE THREAD

**Issue by guicouv** [Prowlarr/Prowlarr#763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the address of the abn tracker is not available

### Expected Behavior

the address must appear

### Steps To Reproduce

add indexer abn

### Environment

```markdown
- OS: ubuntu 20.04
- Prowlarr:0.1.9.1313
- Docker Install: yes 
- Using Reverse Proxy: no
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

Request Failed. POST /api/v1/indexer/action/getUrls: (Line: 2, Col: 3, Idx: 7) - (Line: 2, Col: 3, Idx: 7): While scanning a multiline plain scalar, found invalid mapping.

[AB#2322](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2322)

**Comment by bakerboy448** [comment]
Nothing has changed for Abnormal in months

Just the error are not trace logs

**Comment by guicouv** [comment]
It's ok now. Thanks
