### ISSUE TITLE
Search => Save does not work when a Reverse Proxy is Used as `localhost` is returned for DownloadURL instead of the proxied url

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When doing a manual search - it is not possible to Download the torrent if Prowlarr is accessed via a Reverse Proxy or externally due to the downloadurl being the localhost and not the proxy access

### Expected Behavior

DownloadURL should be dynamic based on how Prowlarr is being accessed

### Steps To Reproduce

1. Put Prowlarr behind a reverse proxy
2. Add an Indexer
3.  Search in Prowlarr
4. Attempt to grab the torrent or nzb
5. Unable to grab as the opening window is localhost.
6. Network call confirms the returned downloadurl is localhost

### Environment

```markdown
- OS: agnostic
- Prowlarr: 0.1.10.1370
- Docker Install: agnostic
- Using Reverse Proxy: yes
- Browser: agnostic
```

### What branch are you running?

Nightly

### Trace Logs?

N/A & No relevant context

request
`Request URL: https://mydomain.tld/prowlarr/api/v1/search?query=test&indexerIds=38&type=search`

snippet of a response

```
downloadUrl: "http://127.0.0.1:9696/prowlarr/38/download?apikey={removed}&link=TmdhV1I0cU5iM1lJVDJKZXRDaGJaWUlNZ2NWR1JBYXFhN0pkQ3RoT3JobkFwZDNJUm9xczNBMW9WYkNjV3h6cEdOSXZrQjFRRXFuSmpvSktHQUtaTzNISWZOcWFPcU1VR2hoNFYxa3NIdjdtL2ltTXYwdmhjdU41d1VtZjh5Y282V09vSTZHMTA2MVl2Z2hUUmxRRGVCc284MUMrdjZCblRVcTVxbTJydE5hTlB0ZDVpSG9YSEs2VkFmQVVSbnkxNW56RmI0RmJBZ0g5UW5tdGdETm9KZz09&file=the+test+case+s01+-+Downloader.exe"
```

NGINX conf
```nginx
location /prowlarr {
  proxy_pass http://127.0.0.1:9696/prowlarr;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Proto https;
  proxy_redirect off;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $http_connection;
  set $app prowlarr;
  include /etc/nginx/snippets/theme-park.conf;
  auth_basic "What's the password?";
  auth_basic_user_file /etc/htpasswd.d/htpasswd.bakerboy448;

}

location /prowlarr/api {
  auth_request off;
  proxy_pass http://127.0.0.1:9696/prowlarr/api;
}
```

[AB#2324](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2324)

**Comment by bakerboy448** [comment]
Appears likely due to this line
https://github.com/Prowlarr/Prowlarr/blob/5d32bcf8b9140468da4cd64765f615c4fb15b643/src/Prowlarr.Api.V1/Search/SearchController.cs#L165

which is fed presumably bad data from

https://github.com/Prowlarr/Prowlarr/blob/5d32bcf8b9140468da4cd64765f615c4fb15b643/src/Prowlarr.Api.V1/Search/SearchController.cs#L142

relating to

https://github.com/Prowlarr/Prowlarr/blob/5d32bcf8b9140468da4cd64765f615c4fb15b643/src/Prowlarr.Api.V1/Search/SearchController.cs#L133-L134

**Comment by Qstick** [comment]
No issues here with this via RP

**Comment by bakerboy448** [comment]
Fixed with

Adding the $host to the api route
