### ISSUE TITLE
Pull Jackett Commit - secretcinema: drop artist from release titles. resolves Jackett #12799

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#770]
[secretcinema: drop artist from release titles. resolves Jackett 12799](https://github.com/Jackett/Jackett/commit/f1c6dca9bf19f9241d7219582d20c308b325f8e3)
https://github.com/Jackett/Jackett/issues/12799

[AB#2342](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2342)

**Comment by Qstick** [comment]
We already do this
