### ISSUE TITLE
Environment variable configuration

### ISSUE THREAD

**Issue by onedr0p** [Prowlarr/Prowlarr#777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

There's currently no support for configuring Prowlarr with environment variables.

### Describe the solution you'd like

Support for setting environment variables for configuration, specifically options set in config.xml.

Precedence could probably be

1. use environment variables, if not set...
2. use command line arguments, if not set..
3. read from config.xml / UI settings

### Describe alternatives you've considered

N/A

### Anything else?

List of environment variables (which is currently everything in config.xml) could be:

```bash
PROWLARR_LOG_LEVEL
PROWLARR_URL_BASE
PROWLARR_UPDATE_MECHANISM
PROWLARR_API_KEY
PROWLARR_BIND_ADDRESS
PROWLARR_PORT
PROWLARR_SSL_PORT
PROWLARR_ENABLE_SSL
PROWLARR_LAUNCH_BROWSER
PROWLARR_SSL_CERT_PATH
PROWLARR_SSL_CERT_PASSWORD
PROWLARR_POSTGRES_HOST
PROWLARR_POSTGRES_PORT
PROWLARR_POSTGRES_USER
PROWLARR_POSTGRES_PASSWORD
PROWLARR_POSTGRES_MAIN_DB
PROWLARR_POSTGRES_LOG_DB
```

[AB#2364](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2364)

**Comment by Qstick** [comment]
Does this work now after Postgres?

**Comment by onedr0p** [comment]
I wasn't aware any of these changes were made.

**Comment by Qstick** [comment]
We use environmental variables for spinning up test instances to run Postgres integration tests during build, I just don't know if that side of it made it here from Radarr yet

**Comment by onedr0p** [comment]
This is an news to me, I'm probably not the best person to answer 😅 I thought this might have needed a restructuring of the way the config is handled already by changing config.xml to config.json.

**Comment by onedr0p** [comment]
Oh I found the commit on Radarr https://github.com/Radarr/Radarr/commit/bd53092f0c0e2202ae459dd3d9a7a998f310442a

I am not using Postgres to try though. This issue is more for adding support for configuring all options in the `config.xml` via environment variables.

**Comment by thezak48** [comment]
Addition to this FR, Add set auth type env

**Comment by traverseda** [comment]
Would be great if that works with OIDC urls, if those happen in the future. Very exciting to see this on the agenda, I think https://12factor.net/config has some good explanations on why this kind of change makes it a lot easier to deploy apps like this.

**Comment by onedr0p** [comment]
This is implemented
