### ISSUE TITLE
Convert UNIT3D Indexers from Cardigann to API

### ISSUE THREAD

**Issue by Qstick** [Prowlarr/Prowlarr#78]
Now that we have API implementation, we want to convert these as we can as they are much faster than scraping. Requires UNIT3D 5.3 to be installed on Indexer

- [x] aither
- [x] AnimeWorld 
- [ ] asianCinema
- [x] blutopia
- [ ] chilebt
- [ ] concertos
- [ ] danishbytes
- [ ] desireLeasers
- [ ] esharenet
- [ ] freetorrent
- [ ] hdolimpo
- [ ] hush
- [ ] imortuos
- [ ] jptv
- [ ] legacyhd
- [ ] nordicplus
- [ ] piratadigital
- [ ] portugas
- [ ] purovicio
- [ ] racing4everyone
- [ ] redbits
- [x] shareisland
- [ ] tellytorrent
- [ ] theshinning
- [ ] torrentdb
- [ ] torrentland
- [ ] trackeros
- [ ] tvchaosuk

[AB#32](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/32)

**Comment by sadstan123456** [comment]
Request to add BeyondHD to list

**Comment by bakerboy448** [comment]
BHD is already using the API

**Comment by Pfuenzle** [comment]
You can add AnimeWorld as completed
https://github.com/Prowlarr/Prowlarr/pull/132

**Comment by bakerboy448** [comment]
DanishBytes Jackett has converted to C# https://github.com/Jackett/Jackett/commit/01ce1174f20c93f50d710afa9fc412b220a74c17

**Comment by bakerboy448** [comment]
Removed the following from the OP list as they are covered on

- sharewood

**Comment by bakerboy448** [comment]
Closed due to UNIT3D support in Cardigann v3.
