### ISSUE TITLE
HD-Torrent Validation error

### ISSUE THREAD

**Issue by BaukeZwart** [Prowlarr/Prowlarr#783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

can't validate HD-Torrent.
Test is giving "Unable to connect to indexer" error.

### Expected Behavior

Pas Test and validate.

### Steps To Reproduce

Add HD-Torrents
Fill in credentials
Hit the test button.

### Environment

```markdown
- OS: Synology HD-Torrents
- Prowlarr: 0.2.0.1395
- Docker Install: Hotio
- Using Reverse Proxy: NPM (also tried without RP)
- Browser: Chrome 97.0.4692.71
```

### What branch are you running?

Nightly

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/7882118/prowlarr.trace.txt)

[AB#2377](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2377)

**Comment by bakerboy448** [comment]
Not a bug. You're blocked by Cloudflare.

**Comment by BaukeZwart** [comment]
Thanks @bakerboy448 routing the hdt trough Flashsolver fixed it.
