### ISSUE TITLE
MoreThanTV being disabled due to failures after searching

### ISSUE THREAD

**Issue by klepp0906** [Prowlarr/Prowlarr#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hopefully you guys recall the issue we discussed in discord surrounding specific searches and it causing the indexer to fail and be disabled in Prowlarr.   (Homeland was the first offender i found, trying to avoid finding others)

baker said it had to do with an integer parse or some such.

one interactive search of homeland season 8 results in
![image](https://user-images.githubusercontent.com/10392920/149857817-feb9671e-80cf-4647-af42-4bcaacfe85d9.png)
and returns no results from mtv.

### Expected Behavior

results to be returned from MTV and for the indexer to not fail and be disabled in prowlarr :)

### Steps To Reproduce

with MTV added to sonarr via prowlarr and enabled as an indexer, add the series homeland (2011) to sonarr.
attempt an interactive search of homeland season 8
it will return results from all indexers except for MTV and the indexer will have been disabled within prowlarr

### Environment

```markdown
- OS: Windows 10
- Prowlarr: 0.2.0.1395
- Docker Install:
- Using Reverse Proxy:
- Browser: Brave
```

### What branch are you running?

Nightly

### Trace Logs?

here is the prowlarr trace
https://0bin.net/paste/EKEWQ7Ni#Ei8dn0NxM3fK9UGTpHoXuWg2uFeOrbLTb4eSfXcmQAq

here is the sonarr trace
https://0bin.net/paste/YekPYjj8#9V+DB7KCkAWY5IXdrTGoAOIsnuIIaCbXDsE2iKephWE

[AB#2398](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2398)

**Comment by bakerboy448** [comment]
https://discord.com/channels/767843854736949299/767843855109718067/932635125278191637
