### ISSUE TITLE
MTV is miscalculating sizes resulting in items being declined

### ISSUE THREAD

**Issue by klepp0906** [Prowlarr/Prowlarr#788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

while searching for a particular season it appears my preferred choice of torrent was being refused due to surpassing the size limit.  Upon further inspection it seems that the results being returned for that item are for ALL torrents of that show/season on MTV.

easier to explain with pictures. 

exhibit A) the torrent I want from MTV in the search results of sonarr
![image](https://user-images.githubusercontent.com/10392920/149858869-fea2a092-3261-46d0-a41f-eea162435f78.png)

exhibit B) the same torrent on MTV's website
![image](https://user-images.githubusercontent.com/10392920/149858938-21650cad-f68c-42c5-b34c-c7225ee5785f.png)

exhibit C) all other torrents for that show/season on the website which cumulatively make up the GB size being returned in the search resulting in it being ginormous and refused
![image](https://user-images.githubusercontent.com/10392920/149859078-be27cfcc-9a26-485b-8c30-7e9db3a26a22.png)

### Expected Behavior

for a proper file size to be returned so (in this case) the file(s) are not removed from consideration if nothing else. 

### Steps To Reproduce

add the mtv indexer to prowlarr and proceed to add The Originals (2013) as a series.
perform an interactive search for season 4 and note the size of the "The.Originals.S04.720p.HDTV.DD5.1x264-BTN" torrent shown  here https://www.morethantv.me/torrents.php?id=248058#torrentinfo217727

i can only assume this will present with other shows/seasons as well. 

### Environment

```markdown
- OS: Windows 10
- Prowlarr: 0.2.0.1395
- Docker Install:
- Using Reverse Proxy:
- Browser: Brave
```

### What branch are you running?

Nightly

### Trace Logs?

prowlarr

https://0bin.net/paste/8s7xpPus#VnLETgh9BSTHT+P5yRJv0lZzMflmVQajeLPZC+VW-0u

sonarr
[sonarr.trace.1.txt](https://github.com/Prowlarr/Prowlarr/files/7885742/sonarr.trace.1.txt)
[sonarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/7885743/sonarr.trace.txt)
[sonarr.trace.0.txt](https://github.com/Prowlarr/Prowlarr/files/7885744/sonarr.trace.0.txt)

[AB#2399](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2399)

**Comment by bakerboy448** [comment]
@DevYukine

**Comment by DevYukine** [comment]
This is a known issue i already described in the PR https://github.com/Prowlarr/Prowlarr/pull/771 and is because on the Torrent Search Page it actual shows the grouped result instead each torrents own result, this will not be fixable until MTV adds a proper API (or heavily do more request for each search which is not acceptable).

Just try to search for whatever on the torrent page and see it yourself.
![image](https://user-images.githubusercontent.com/20647088/149866112-b74df6fa-c3d4-4d1c-8324-fb890bc86171.png)

**Comment by Qstick** [comment]
The best we can do here some type of hacky approach by splitting the combined size by number of children, or proportioning each child by their quality (more work, slower, and a waste if an API is coming)
