### ISSUE TITLE
Rolling counter for API limits

### ISSUE THREAD

**Issue by BEisem** [Prowlarr/Prowlarr#789]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Many NZB indexers utilize a rolling counter for API limits, so that API hits drop off after 24 hours. Prowlarr uses a counter that resets to 0 every 24 hours. So the API counter on Prowlarr can be wildly out of sync for certain times of the day. Most indexers will simply disable your API when you go over, but there are some indexers that can actually ban or delete your account for going over. For this reason, the current implementation can be quite dangerous if you don't pay attention to your API usage.

### Describe the solution you'd like

I would like to see the option of using a rolling counter for API limits. This can either be selectable by the user, or automatically set each indexer based on the counter type used by the indexer.

### Describe alternatives you've considered

There are no alternatives at this point, since only one type of counter is available.

### Anything else?

n/a

[AB#2403](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2403)

**Comment by bakerboy448** [comment]
This would also be useful for BTN's hourly rate limit.

Id imagine we'd have a toggle/drop down
- Daily - Reset all hits / grabs Daily at 0000 local host system time
- Rolling - Use all hits / grabs for an indexer based on the last XX hours

**Comment by Qstick** [comment]
Not a fan on f the option, but we can switch to rolling which will always be more conservative

**Comment by BEisem** [comment]
The rolling counter is working great, thank you. But I think it is still resetting to 0, which a rolling counter should never do. Am I seeing this correctly? Or does the daily reset still need to be removed?

**Comment by bakerboy448** [comment]
Doesnt look like there is a reset in the file?

It looks for all the queries for a given indexer from history within the prior 24hrs (vs. previously since the start of the day)

**Comment by BEisem** [comment]
My log definitely reset to zero last night ...

```
2022-01-21 04:38:16.9|Debug|IndexerLimitService|Indexer ****** has performed 935 of possible 970 queries in last 24 hours, proceeding
2022-01-21 04:51:09.0|Debug|IndexerLimitService|Indexer ****** has performed 0 of possible 970 queries in last 24 hours, proceeding
```
