### ISSUE TITLE
Add expiration date to info. modal

### ISSUE THREAD

**Issue by Fringe09** [Prowlarr/Prowlarr#797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Only way to know the expiration of an Indexer is to edit it. Would be nice to see it in the info. modal.

### Describe the solution you'd like

See expiration date in the info. modal.

### Describe alternatives you've considered

None.

### Anything else?

No.

[AB#2490](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2490)

**Comment by bakerboy448** [comment]
Relating to https://github.com/Prowlarr/Prowlarr/issues/456
