### ISSUE TITLE
HDBits and PTP Query Limit Handling

### ISSUE THREAD

**Issue by newadventure079** [Prowlarr/Prowlarr#798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Propose a fix similar to #761 so we dont go over the rate limit for PTP and HDBits.  I dont know what those rate limits are right off hand but I'm hoping a dev can talk to the staff.  

But if we get an error message returned to us like `Rate-limit exceeded` or a http status code `403` returned, we can throw a `RequestLimitReachedException` so we dont query anymore for a while

HDBits:
```
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://hdbits.org/download.php
<h1>Error</h1><p>Rate-limit exceeded. Please try again in 15 minutes.</p>
```
PTP:
```
[v0.1.10.1375] NzbDrone.Core.Exceptions.ReleaseDownloadException: Downloading torrent failed
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [403:Forbidden] [GET] at [https://passthepopcorn.me/torrents.php
```

### Describe the solution you'd like

Similar fix to #761

### Describe alternatives you've considered

n/a

### Anything else?

n/a

[AB#2495](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2495)

**Comment by bakerboy448** [comment]
I think branch `indexer-resp-handling` should do it (covers BTN as well) if you wanna test

hotio builds our PRs if you're on docker it'd be `pr-indexer-resp-handling`

**Comment by newadventure079** [comment]
@bakerboy448 Thank you!
