### ISSUE TITLE
IPTorrents error "Query successful"

### ISSUE THREAD

**Issue by Kazz3r24** [Prowlarr/Prowlarr#809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I noticed in Radarr and Sonarr I wasn't getting any results from IPTorrents, so I went to test the indexer in Prowlarr and receive the following error (no changes have ever been made since it was working up until today that I noticed).

In the logs I do see mention of Cloudflare, do I need to setup FlareSolverr now?

"Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings."

### Expected Behavior

I usually see results from IPT normally in all apps until today, for some reason there's an issue with Categories or something, not sure how to fix it. I've tried replacing my cookie, but that didn't help and I didn't want to remove the indexer out of a fear of not being able to re-add it for whatever reason.

### Steps To Reproduce

1. Search for movie/episode in respective ARR app.
2. No results from IPT present.
3. Test indexer in Prowlarr to receive error.

### Environment

```markdown
- OS: Ubuntu 18.04
- Prowlarr: 0.2.0.1439
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: NA
```

### What branch are you running?

Nightly

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/7962873/prowlarr.trace.txt)

[AB#2512](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2512)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

Yes you need flaresolverr 

Leaving open to discuss if we should handle this error better and tell users they need flaresolverr / are blocked by cloudflare

**Comment by Kazz3r24** [comment]
Just my 2 cents, but better error handling to tell users the need flaresolverr would have prevented me from opening this in the first place <3.

**Comment by L0garithmic** [comment]
The irony, I was trying to switch from jackett, which TOLD me I needed flaresolver, but I didn't want to install another app. Then I install Prowlarr and get the same error lol. Can you guys implement flaresolver???

**Comment by bakerboy448** [comment]
No plans to implement flaresolverr directly into Prowlarr.

Just install it, run it, and then connect Prowlarr to it.

Note that to enable Flaresolverr the proxy for FS and your tracker(s) need to have a matching tag.
