### ISSUE TITLE
Add "Search for freeleech only" to MAM

### ISSUE THREAD

**Issue by ikestupor** [Prowlarr/Prowlarr#810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Just want to browse freeleech on prowlarr.

### Describe the solution you'd like

Add option to search for freeleech only on Myanonamouse. This would be the same check box used on Torrentleech and others.

### Describe alternatives you've considered

Search page could alternatively have a checkbox for freeleech, or Tracker flags in general

### Anything else?

I can see freeleech flags on the search results page, but no way to filter on that, or to specify before searching.

[AB#2516](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2516)

**Comment by bakerboy448** [comment]
Bool of free in their API on the response 

https://github.com/Prowlarr/Prowlarr/issues/518#issuecomment-930435317

**Comment by ikestupor** [comment]
Ah, fair enough!

**Comment by ikestupor** [comment]
@bakerboy448 actually, I think tor[searchType]=fl will work, based on the url from their gui.

**Comment by DreadDragoon** [comment]
fl_vip | boolean | if the item is freeleech and/or vip
