### ISSUE TITLE
TDay interactive search results not accurate

### ISSUE THREAD

**Issue by psi70y** [Prowlarr/Prowlarr#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just noticing that results coming back from TorrentDay on Sonarr are not as sharp as the results I am still getting from Jackett.

For example I search for The Book of Bobba Fett S01E06 and all indexers display results for S01E06 except Tday which will display other Bobba Fett episodes. This is happening for all shows. Do not seem to be getting this problem from Jackett. 

### Expected Behavior

Interactive search results should only contain the actual searched episode

### Steps To Reproduce

Go to Sonarr
Go to any show
go to any episode
click interactive search

### Environment

```markdown
- OS: MacOS 12.2
- Prowlarr: 0.2.0.1426
- Sonarr: 3.0.6.1342
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Safari 15.3
```

### What branch are you running?

Develop

### Trace Logs?

Screenshot - [https://i.imgur.com/D0Xgb0R.png](https://i.imgur.com/D0Xgb0R.png)

Trace Logs - [https://gist.github.com/psi70y/326cbb0c1f1d53147e34dcae9f4152a2](https://gist.github.com/psi70y/326cbb0c1f1d53147e34dcae9f4152a2)

[AB#2532](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2532)

**Comment by bakerboy448** [comment]
@psi70y  does `https://tday.love/t.json?29;30;24;32;31;33;46;14;26;7;34;2;q=tt13668894%20S01E01` work?

I.e. including Season & Episode after the ID?

**Comment by psi70y** [comment]
> @psi70y does `https://tday.love/t.json?29;30;24;32;31;33;46;14;26;7;34;2;q=tt13668894%20S01E01` work?
> 
> I.e. including Season & Episode after the ID?

@bakerboy448 
This is the output

`[{"t":6020328,"c":7,"size":1131224521,"files":1,"seeders":121,"leechers":0,"completed":703,"ctime":1640787010,"category":"TV/x264","name":"The Book of Boba Fett S01E01 Chapter 1 720p DSNP WEB-DL DDP5 1 Atmos H 264-NOSiViD","imdb-id":"tt13668894"},{"t":6020325,"c":34,"size":6445060724,"files":1,"seeders":227,"leechers":0,"completed":1216,"ctime":1640786871,"category":"TV/x265","name":"The Book of Boba Fett S01E01 Chapter 1 2160p WEB-DL DDP5 1 Atmos HDR H 265-NOSiViD","imdb-id":"tt13668894"},{"t":6020215,"c":34,"size":498059279,"files":5,"seeders":1243,"leechers":59,"completed":6870,"ctime":1640777462,"category":"TV/x265","name":"The Book of Boba Fett S01E01 1080p HEVC x265-MeGusta","imdb-id":"tt13668894"},{"t":6020083,"c":34,"size":5872191679,"files":4,"seeders":217,"leechers":10,"completed":1084,"ctime":1640772696,"category":"TV/x265","name":"The Book of Boba Fett S01E01 2160p WEB h265-KOGi","imdb-id":"tt13668894"},{"t":6019938,"c":24,"size":320326790,"files":5,"seeders":206,"leechers":0,"completed":1207,"ctime":1640766197,"category":"TV/480p","name":"The Book of Boba Fett S01E01 480p x264-mSD","imdb-id":"tt13668894"},{"t":6019931,"c":2,"size":337559444,"files":5,"seeders":697,"leechers":0,"completed":4591,"ctime":1640765787,"category":"TV/XviD","name":"The Book of Boba Fett S01E01 XviD-AFG","imdb-id":"tt13668894"},{"t":6019930,"c":34,"size":403535762,"files":5,"seeders":318,"leechers":14,"completed":1595,"ctime":1640765693,"category":"TV/x265","name":"The Book of Boba Fett S01E01 720p HEVC x265-MeGusta","imdb-id":"tt13668894"},{"t":6019929,"c":46,"size":145100102,"files":5,"seeders":100,"leechers":0,"completed":930,"ctime":1640765590,"category":"TV/Mobile","name":"The Book of Boba Fett S01E01 AAC MP4-Mobile","imdb-id":"tt13668894"},{"t":6019917,"c":7,"size":1975753540,"files":6,"seeders":2525,"leechers":5,"completed":14703,"ctime":1640765117,"category":"TV/x264","name":"The Book of Boba Fett S01E01 1080p WEB h264-KOGi","imdb-id":"tt13668894"},{"t":6019916,"c":7,"size":1133351669,"files":6,"seeders":263,"leechers":0,"completed":1257,"ctime":1640765093,"category":"TV/x264","name":"The Book of Boba Fett S01E01 720p WEB h264-KOGi","imdb-id":"tt13668894"}]`
