### ISSUE TITLE
Information within the documentation

### ISSUE THREAD

**Issue by DarrenPIngram** [Prowlarr/Prowlarr#83]
It would be good if you could explain (within the project's documentation) how this application may be similar/comparable to Jackett and, of course, highlight the existing and planned differences that will make the application stand out. Jackett is already well-established and by doing the foregoing it may help the project gain additional traction and usage.

**Comment by Roxedus** [comment]
The [FAQ](https://wiki.servarr.com/Prowlarr_FAQ) has some of these points already covered, so that would be a good place to base that on.

**Comment by DarrenPIngram** [comment]
Indeed, but it is hardly "snappy" and, to be frank, I don't expect most
people who learn about the application/stumble across it will necessarily
look inside the deep FAQ until they are suitably curious about the
application to install it and learn more about it/fix issues.

So some snappier text in the project's home page on the lines that I
outlined may be beneficial, I humbly submit.

‌

**Comment by Qstick** [comment]
To @Roxedus point we could likely pull some of that language or points from the FAQ to use in a more upfront way on the page. We do have plans to expand on the current page and documentation, just not a top priority. That being said we’d welcome a PR with some recommendations should you feel up to it.

**Comment by DarrenPIngram** [comment]
As things become a little more fixed and ready that could be a possibility.

‌
