### ISSUE TITLE
Windows Region Portugal - An error occurred while processing indexer feed. DateTime parsing failed for "sábado, 31 ago 2019 08:25:24 +2"

### ISSUE THREAD

**Issue by jvvilar** [Prowlarr/Prowlarr#835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While doing a manual search, the indexer TorrentLeech throws the following:

Message:
```
An error occurred while processing indexer feed. https://www.torrentleech.org/torrents/browse/list/exact/1/query/skylines/orderby/added/order/desc: Error while parsing field=date, selector=addedTimestamp, value=sábado, 31 ago 2019 08:25:24 +2: DateTime parsing failed for "sábado, 31 ago 2019 08:25:24 +2": NzbDrone.Core.Parser.InvalidDateException: TimeAgo parsing failed, unknown unit: :
   at NzbDrone.Core.Parser.DateTimeUtil.FromTimeAgo(String str) in D:\a\1\s\src\NzbDrone.Core\Parser\DateTimeUtil.cs:line 94
   at NzbDrone.Core.Parser.DateTimeUtil.FromUnknown(String str, String format) in D:\a\1\s\src\NzbDrone.Core\Parser\DateTimeUtil.cs:line 133
```
NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannException: Error while parsing field=date, selector=addedTimestamp, value=sábado, 31 ago 2019 08:25:24 +2: DateTime parsing failed for "sábado, 31 ago 2019 08:25:24 +2": NzbDrone.Core.Parser.InvalidDateException: TimeAgo parsing failed, unknown unit: :
   at NzbDrone.Core.Parser.DateTimeUtil.FromTimeAgo(String str) in D:\a\1\s\src\NzbDrone.Core\Parser\DateTimeUtil.cs:line 94
   at NzbDrone.Core.Parser.DateTimeUtil.FromUnknown(String str, String format) in D:\a\1\s\src\NzbDrone.Core\Parser\DateTimeUtil.cs:line 133
   at NzbDrone.Core.Indexers.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannParser.cs:line 144
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 320
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 174

### Expected Behavior

I would expect no exception to happen.
I believe it's noteworthy that although my Windows language is en-us, my regional format is set to Portuguese (Portugal), since this seems to be a Culture error when parsing dates.

### Environment

```markdown
- OS: Windows 10
- Prowlarr: 0.2.0.1448
- Docker Install: No
- Using Reverse Proxy: No
```

### What branch are you running?

Develop

### Trace Logs?

2022-02-07 14:50:34.2|Error|Cardigann|An error occurred while processing indexer feed. https://www.torrentleech.org/torrents/browse/list/exact/1/query/skylines/orderby/added/order/desc

[v0.2.0.1448] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannException: Error while parsing field=date, selector=addedTimestamp, value=sÃ¡bado, 31 ago 2019 08:25:24 +2: DateTime parsing failed for "sÃ¡bado, 31 ago 2019 08:25:24 +2": NzbDrone.Core.Parser.InvalidDateException: TimeAgo parsing failed, unknown unit: :
   at NzbDrone.Core.Parser.DateTimeUtil.FromTimeAgo(String str) in D:\a\1\s\src\NzbDrone.Core\Parser\DateTimeUtil.cs:line 94
   at NzbDrone.Core.Parser.DateTimeUtil.FromUnknown(String str, String format) in D:\a\1\s\src\NzbDrone.Core\Parser\DateTimeUtil.cs:line 133
   at NzbDrone.Core.Indexers.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannParser.cs:line 144
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 320
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 174
   
RequestUri: https://www.torrentleech.org/torrents/browse/list/exact/1/query/skylines/orderby/added/order/desc;StatusCode: OK;ContentType: application/json;ContentLength: 44200;ContentSample: 
{
  "numFound": 146,
  "torrentList": [
    {
      "fid": "1430390",
      "filename": "Skylines.Academy.Microsoft.AZ-500.Certification.Azure.Security.Technologies-RiDWARE.torrent",
      "name": "Skylines Academy Microsoft AZ-500 Certification Azure Security Technologies-RiDWARE",
      "addedTimestamp": "2019-08-31 08:25:24",
      "categoryID": 23,
      "size": 1736833435,
      "completed": 155,
      "seeders": 3,
      "leechers": 0,
      "numComments": 0,
      "tags": "",
      "new": false,
      "imdbID": "",
      "rating": 0,
      "genres": "",
      "tvmazeID": "",
      "igdbID": "",
      "download_multiplier": 1
    }
  ],
  "facets": {
    "tags": {
      "name": "tags",
      "title": "Tags",
      "type": "field",
      "items": {
        "Drama": 50,
        "Music": 50,
        "Strategy": 34,
        "simulator": 34,
        "rar": 33,
        "Action": 24,
        "Adventure": 24,
        "Sci-Fi": 24,
        "FREELEECH": 14,
        "nonscene": 2,
        "Appletosh": 1,
        "Crapple": 1,
        "Sport": 1,
        "scifi": 1
      }
    },
    "size": {
      "name": "size",
      "title": "Size",
      "type": "range",
      "items": {
        "[0 TO 786432000]": {
          "count": 28,
          "label": "0MB - 750MB"
        },
        "[786432000 TO 1610612736]": {
          "count": 33,
          "label": "750MB - 1.5GB"
        },
        "[1610612736 TO 4831838208]": {
          "count": 49,
          "label": "1.5GB - 4.5GB"
        },
        "[4831838208 TO 16106127360]": {
          "count": 28,
          "label": "4.5GB - 15GB"
        },
        "[16106127360 TO *]": {
          "count": 8,
          "label": "More than 15GB"
        }
      }
    },
    "added": {
      "name": "added",
      "title": "Added",
      "type": "range",
      "items": {
        "[NOW/MINUTE-24HOURS TO NOW/MINUTE+1MINUTE]": {
          "count": 0,
          "label": "Last 24hrs"
        },
        "[NOW/MINUTE-48HOURS TO NOW/MINUTE+1MINUTE]": {
          "count": 0,
          "label": "Last 48hrs"
        },
        "[NOW/MINUTE-72HOURS TO NOW/MINUTE+1MINUTE]": {
          "count": 0,
          "label": "Last 72hrs"
        },
        "[NOW/HOUR-7DAYS TO NOW/HOUR+1HOUR]": {
          "count": 0,
          "label": "Last week"
        },
        "[NOW/HOUR-14DAYS TO NOW/HOUR+1HOUR]": {
          "count": 1,
          "label": "Last 2 weeks"
        },
        "[NOW/HOUR-1MONTH TO NOW/HOUR+1HOUR]": {
          "count": 1,
          "label": "Last month"
        }
      }
    },
    "seeders": {
      "name": "seeders",
      "title": "Seeders",
      "type": "range",
      "items": {
        "[0 TO 50]": {
          "count": 142,
          "label": "0 - 50"
        },
        "[51 TO 200]": {
          "count": 4,
          "label": "51 - 200"
        },
        "[201 TO *]": {
          "count": 0,
          "label": "More than 200"
        }
      }
    },
    "name": {
      "name": "name",
      "title": "HD Resolution",
      "type": "range",
      "items": {
        "720p": {
          "count": 23,
          "label": "720p"
        },
        "1080p": {
          "count": 40,
          "label": "1080p"
        },
        "2160p": {
          "count": 0,
          "label": "2160p"
        }
      }
    }
  },
  "facetswoc": {
    "categoryID": {
      "name": "categoryID",
      "title": "CategoryID",
      "type": "field",
      "items": {
        "13": 15,
        "14": 5,
        "17": 41,
        "23": 11,
        "24": 2,
        "26": 6,
        "27": 6,
        "32": 19,
        "36": 1,
        "37": 4,
        "38": 4,
        "39": 1,
        "42": 7,
        "43": 1,
        "44": 19,
        "48": 4
      }
    }
  },
  "order": "desc",
  "orderBy": "added",
  "page": 1,
  "perPage": 100,
  "lastBrowseTime": 1644241832,
  "userTimeZone": "UTC"
};FeedUrl: https://www.torrentleech.org/torrents/browse/list/exact/1/query/skylines/orderby/added/order/desc

A lot of results were removed, I kept the JSON result for the relevant result in the exception. As mentioned, although my Windows language is en-us, my regional format is set to Portuguese (Portugal)

[AB#2557](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2557)

**Comment by jvvilar** [comment]
After a quick look at the code, it seems that here:

```
var match = _TimeAgoRegexp.Match(str);
if (match.Success)
{
   var timeago = str;
   return FromTimeAgo(timeago);
}
```
It matches "ago" in:
`private static readonly Regex _TimeAgoRegexp = new Regex(@"(?i)\bago", RegexOptions.Compiled);`

Except in this case, "ago" is short for "Agosto" (August) and it just goes downhill from there.

Curiously, the JSON has a standard timestamp:
`"addedTimestamp": "2019-08-31 08:25:24"`
but what reaches the parser is the long date/time representation of the timestamp in local culture
`sábado, 31 ago 2019 08:25:24 +2`

**Comment by bakerboy448** [comment]
Think this should be resolved with the various date/time changes and updates.

Is this still an ongoing issue?

**Comment by jvvilar** [comment]
This issue made it unusable for me, so I moved back to Jackett and haven't tried Prowlarr again. I can't say if it is still present.
