### ISSUE TITLE
3DTorrents - Failure to Login - No Results Found

### ISSUE THREAD

**Issue by SteffanCline** [Prowlarr/Prowlarr#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to add the tracker 3D Torrents I get the following error ```Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.``` The indexer works fine in Jackett. I copied the .yml file from Jackett to Prowlarr and it still fails in prowlarr. Discussed the issue with @bakerboy448 on Reddit https://www.reddit.com/r/prowlarr/comments/somvpe/query_successful_but_no_results_were_returned/

### Expected Behavior

Expected to add the tracker and it saves without the error.

### Steps To Reproduce

Add the 3D torrent indexer with valid credentials and captcha. Attempt to save and then get the error ```Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.``` Tested this with and without FlareSolverr - no change,

### Environment

```markdown
- OS: Ubuntu 21
- Prowlarr: 0.2.0.1448
- Docker Install: No
- Using Reverse Proxy: Yes as /prowlarr. Issue occurs by port or by proxy
- Browser: Any
```

### What branch are you running?

Develop

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/8046427/prowlarr.trace.txt)
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/8046428/prowlarr.txt)
[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/8046429/prowlarr.debug.txt)

[AB#2567](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2567)

**Comment by Qstick** [comment]
Still busted?
