### ISSUE TITLE
Update via browser from 0.1.9.1313 to 0.2.0.1448 fails on Ubuntu 20.04.3

### ISSUE THREAD

**Issue by milesizzo** [Prowlarr/Prowlarr#845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Automatic update from 0.1.9.1313 to 0.2.0.1448 fails on Ubuntu server 20.04.3. Update was initiated from the web interface.

Rollback also failed, leaving a broken installation. The same behaviour occurred in Radarr (https://github.com/Radarr/Radarr/issues/7026).

### Expected Behavior

The update should succeed.

If the update fails it should successfully roll back to the previous version, rather than leaving the installation half deployed.

### Steps To Reproduce

1. Deploy 0.1.9.1313
2. Follow prompt to install update
3. (I noticed that I had to click "install update" twice before it registered - not sure if that's important)
4. Update spinner is shown
5. Service never resumes

### Environment

```markdown
- OS: Ubuntu 20.04.3
- Prowlarr: 0.1.9.1313
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome 98.0.4758.82 (64-bit)
```

### What branch are you running?

Master

### Trace Logs?

From `/var/lib/prowlarr/UpdateLogs`:

[2022.02.14-05.47.txt](https://github.com/Prowlarr/Prowlarr/files/8059991/2022.02.14-05.47.txt)

[AB#2579](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2579)

**Comment by bakerboy448** [comment]
No issues with the updater - something - not Prowlarr - wiped the critical files/folders in your /tmp dir

**Comment by milesizzo** [comment]
No worries. I thought I'd report it anyway in case someone else has the same issue and comes across this. My solution was to wipe the install directory and do a fresh deploy.

**Comment by bakerboy448** [comment]
Yup that's the solution - just an in place upgrade/reinstall

**Comment by raphaelmaria** [comment]
I solved the same problem on Ubuntu 20.04.3 LTS by chance.
I stopped the Daemon, "removed" the line -data=/var/lib/prowlarr
and restarted it.
The splash screen appeared.
![220222](https://user-images.githubusercontent.com/26657697/155252176-f64f4b0f-9d9a-4e6c-a7e3-ec67c7de04c9.png)

**Comment by bakerboy448** [comment]
> I solved the same problem on Ubuntu 20.04.3 LTS by chance.
> 
> I stopped the Daemon, "removed" the line -data=/var/lib/prowlarr
> 
> and restarted it.
> 
> The splash screen appeared.
> 
> ![220222](https://user-images.githubusercontent.com/26657697/155252176-f64f4b0f-9d9a-4e6c-a7e3-ec67c7de04c9.png)
> 
> 

Changing the config directory to the default is not the solution

The correct solution is to fix the permissions on appdata.

**Comment by raphaelmaria** [comment]
Also re-evaluate the permissions, man.
but even correct, the service starts and the web interface does not load, the permissions are according to my environment where on the same equipment I have a Radarr and Sonarr working perfectly.

Follow print
![220223](https://user-images.githubusercontent.com/26657697/155304333-75e6b1c1-c7cd-4d6c-b4a1-8d7b67b3964e.png)

**Comment by bakerboy448** [comment]
> Also re-evaluate the permissions, man.
> but even correct, the service starts and the web interface does not load, the permissions are according to my environment where on the same equipment I have a Radarr and Sonarr working perfectly.


Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

Based on your screenshot you're running everything as root which is highly insecure and not recommended at all.
