### ISSUE TITLE
Add AudioMP3 and AudioLossless to Orpheus

### ISSUE THREAD

**Issue by SenorSmartyPants** [Prowlarr/Prowlarr#852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I want to set Lidarr app to only receive MP3 and lossless trackers, not all Audio trackers. Please add those categories.

### Describe the solution you'd like

            caps.Categories.AddCategoryMapping(3010, NewznabStandardCategory.AudioMP3);
            caps.Categories.AddCategoryMapping(3040, NewznabStandardCategory.AudioLossless);

### Describe alternatives you've considered

I could manually disable the trackers after they are imported into Lidarr.

### Anything else?

https://github.com/Prowlarr/Prowlarr/blob/3610becc64bd1d14be208402824905110822b9eb/src/NzbDrone.Core/Indexers/Definitions/Orpheus.cs#L36-L42

[AB#2588](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2588)

**Comment by bakerboy448** [comment]
The format is 

```
        caps.Categories.AddCategoryMapping(<CategoryNumberOnTheSite>, <NewznabStandardCategory>, <NameOfCategoryOnTheSite>);
```

What are the category IDs and names on Orpheus for MP3s and Lossless?

If those don't exist then what you want isn't possible
