### ISSUE TITLE
TheScenePlace shows Null Seeders - Possible Cardigann Logic issue

### ISSUE THREAD

**Issue by AzureBelmont** [Prowlarr/Prowlarr#858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

we're not matching at if (dom.Matches(selector.Selector)) which is choking and causing the exception to be thrown back to the parser.   It's not actually switching to the else like it should.  Our code matches Jackett it seems here - so I'm stumped.
NzbDrone.Core.Indexers.Cardigann.CardigannBase.HandleSelector

            if (selector.Selector != null)
            {
                if (dom.Matches(selector.Selector))
                {
                    selection = dom;
                }
                else
                {
                    selection = QuerySelector(dom, selector.Selector);
                }

                if (selection == null)
                {
                    if (required)
                    {
                        throw new Exception(string.Format("Selector \"{0}\" didn't match {1}", selector.Selector, dom.ToHtmlPretty()));
                    }

                    return null;
                }
            }

### Expected Behavior

For it to show seeders and peers. Along with file size information. 

### Environment

```markdown
- OS: Windows 11
- Prowlarr:0.2.0.1543
- Docker Install: no
- Using Reverse Proxy: no
- Browser: firefix or edge
```

### What branch are you running?

Nightly

### Trace Logs?

https://www.toptal.com/developers/hastebin/guzubiruse.php-template

[AB#2651](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2651)

**Comment by AzureBelmont** [comment]
@bakerboy448 hey on this I didn't check at the time but noticed I still wasn't getting pulls and a couple others looked and has same issue. The size for everything is showing 0B. https://imgbox.com/k6FVWPhO

**Comment by Qstick** [comment]
Is this a YML issue/update? @garfield69 thoughts?

**Comment by garfield69** [comment]
>Is this a YML issue/update? 

all I can tell you is that the Jackett thesceneplace indexer is showing sizes
![image](https://user-images.githubusercontent.com/6933240/163688802-dd9acde6-af47-4bc6-b5ba-f0203f0f4baf.png)
so the issue would appear to be localised to your prowlerr implementation.

**Comment by garfield69** [comment]
if the user could test the jackett indexer and show that this is also not showing sizes then that would be helpful.
The site has a history of having different html presentations for different user classes so we have fallen down this rabbit hole before.

**Comment by Qstick** [comment]
> if the user could test the jackett indexer and show that this is also not showing sizes then that would be helpful. The site has a history of having different html presentations for different user classes so we have fallen down this rabbit hole before.

That's what I was afraid of. Thanks garfield

**Comment by izatwin** [comment]
I am having this issue as well. Prowlarr is not giving Radarr file sizes, but it is able to show me seeders and peers.

**Comment by bakerboy448** [comment]
Still occurring in recent builds?
Would need details as to what user  and the page layout

**Comment by bakerboy448** [comment]
Closing; Can reopen if users report this is still occurring and provide the required info.
