### ISSUE TITLE
Additional App Support

### ISSUE THREAD

**Issue by Qstick** [Prowlarr/Prowlarr#86]
Support other Apps for Sync

- [ ] Medusa
- [ ] Sick*
- [x] Mylar3
- [x] LazyLibrarian

[AB#33](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/33)

**Comment by philborman** [comment]
Can we add lazylibrarian to ti's list? The api allows add/delete/amend newznab and torznab providers

**Comment by kingfenix** [comment]
Mylar has created some API endpoints specifically for this usage. Using these API endpoints in mylar3, prowlarr should be able to add mylar as a built in application to choose from for syncing indexers. Also the indexers would use category 7030.
listProviders - https://github.com/mylar3/mylar3/wiki/listProviders
addProvider - https://github.com/mylar3/mylar3/wiki/addProvider
delProvider - https://github.com/mylar3/mylar3/wiki/delProvider
changeProvider - https://github.com/mylar3/mylar3/wiki/changeProvider

**Comment by philborman** [comment]
LazyLibrarian is broadly similar but returns plain text instead of json, could easily be amended to match mylar3 syntax if required

**Comment by p0psicles** [comment]
Medusa likes to be able to use prowlarr's api to get an overview of available providers. So the user can check the ones that should be added. Is there any documentation on the api we can use?

**Comment by bakerboy448** [comment]
[Mylar3 added](https://github.com/Prowlarr/Prowlarr/commit/77892a3885a0675e9cc53a48a6fe9b28011cb7a6)

**Comment by ajax-lives** [comment]
With how outdated Sick* and Medusa are - plus the extremely small (and shrinking) user bases, is this still (or ever was) a priority?

To be honest, if they were going to use Prowlarr, it'd be easier to probably go ahead and move to Sonarr/Radarr while their at it?

**Comment by p0psicles** [comment]
In what way is Medusa outdated? Medusa shines in plenty of features that sonarr is lacking. There are a lot of users that tried sonarr and returned to Medusa.

**Comment by ajax-lives** [comment]
> In what way is Medusa outdated? Medusa shines in plenty of features that sonarr is lacking. There are a lot of users that tried sonarr and returned to Medusa.

Poor wording on my part, apologies.

Medusa doesn't really fit into the ecosystem, is what I meant.

Although most Sick* forks are no longer indev, as far as I am aware.

**Comment by ajax-lives** [comment]
Other than SickChill and SickRage?

**Comment by Qstick** [comment]
Closing this as a bulk issue, someone can request other apps individually if needed
