### ISSUE TITLE
YGG Sonarr enhanced episode does not support 4 digit numbers

### ISSUE THREAD

**Issue by Francoisdsr** [Prowlarr/Prowlarr#863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Enhance sonarr compatibility with anime by renaming episode (xxx to exxx). Works only if episode is at the end of the query. Can disturb movies search. (back to the future 3 -> back to the future e3)
This is the option that have an issue 
For my example, i tried to search for the 1012 of One Piece
When the option isn't select, prowlarr search for One Piece 1012
But when selected, it search for One Piece E101 2

### Expected Behavior

It should search for One Piece E1012, it seems like this option only work for 3 digits episode and not 4 like in my case 

### Steps To Reproduce

Try to search for the same episode as me (or any >= 1000) with and without the option I mentioned and then see the logs of prowlarr and you'll see that when the option is selected, the episode is cut after the third digit.

### Environment

```markdown
- OS: raspberry pi os 64 bit 
- Prowlarr:
- Docker Install: linuxserver/prowlarr
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

[Info] ReleaseSearchService: Searching indexer(s): [YGGtorrent] for Term: [One Piece 1012], Offset: 0, Limit: 100, Categories: [5070]
[Info] Cardigann: Adding request: https://www3.yggtorrent.re/engine/search?category=all&name=%22One%22%20%22Piece%22%20%221012%22&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=seed
[Info] Cardigann: Adding request: https://www3.yggtorrent.re/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=seed
[Info] ReleaseSearchService: Searching indexer(s): [YGGtorrent] for Term: [One Piece 1012], Offset: 0, Limit: 100, Categories: [5070]
[Info] Cardigann: Adding request: https://www3.yggtorrent.re/engine/search?category=all&name=%22One%22%20%22Piece%22%20%22E101%22%20%222%22&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=seed

[AB#2665](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2665)

**Comment by bakerboy448** [comment]
Try changing      

`args: ["(.*)(\\.|\\s|\\-)(\\d{2,3})(\\.|\\s|\\-*)(.*)", "{{ if .Config.enhancedAnime }}$1 E$3 $5{{ else }}$1$2$3$4$5{{ end }}"]`

to

`args: ["(.*)(\\.|\\s|\\-)(\\d{2,4})(\\.|\\s|\\-*)(.*)", "{{ if .Config.enhancedAnime }}$1 E$3 $5{{ else }}$1$2$3$4$5{{ end }}"]`

in the ygg definition

**Comment by Francoisdsr** [comment]
Thanks, it work now
