### ISSUE TITLE
Can't add YTS indexer to Prowlarr

### ISSUE THREAD

**Issue by jrblack10** [Prowlarr/Prowlarr#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When saving or testing YTS indexer...
Unable to connect to indexer, check the log for more details

I have tried each individual Base URL, with no success but with different errors.
https://yts.mx  -  Unable to connect to indexer, check the log for more details
The other 3 base url - Unable to connect to indexer. Unexpected response status ServiceUnavailable code from API request

Attached is my log file.
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/8163301/prowlarr.txt)
 

### Expected Behavior

I would expect the indexer to test successfully and save to my list of other indexers.

### Steps To Reproduce

Version 0.2.0.1448
.NET Yes (6.0.0)
DB Migration 15
Database Sqlite 3.36.0
AppData directory C:\ProgramData\Prowlarr
Startup directory C:\ProgramData\Prowlarr\bin
Mode Service
Uptime 00:24:21

Go to Indexers
Click Add Indexer
type YTS in search indexers text box
Click on the single result
Click the Test or Save button

### Environment

```markdown
- OS: Windos 10 Pro
- Prowlarr: 0.2.0.1448
- Docker Install:
- Using Reverse Proxy: No
- Browser: Chrome (up to date)
```

### What branch are you running?

Master

### Trace Logs?

[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/8163348/prowlarr.txt)

[AB#2733](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2733)

**Comment by bakerboy448** [comment]
you're blocked by cloudflare and need flaresolverr
