### ISSUE TITLE
Show the Categories in Indexer Add Modal

### ISSUE THREAD

**Issue by Chris230291** [Prowlarr/Prowlarr#872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Adding indexers can be tedious and not knowing which categories they use means trial and error.

### Describe the solution you'd like

Instead of "adding" indexers, all indexers would show under the "indexers" tab.
Enable/Disable them with a checkbox in the left most column and configure settings using the existing settings icon on the right.
Doing it this way would make adding much quicker and discovery of which trackers have what categories much easier.
Have a filter to hide any disabled trackers if people are fussy about having them all listed.

Thanks,
Chris

### Describe alternatives you've considered

no

### Anything else?

no

[AB#2737](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2737)

**Comment by bakerboy448** [comment]
So you want to overwhelm users with 5-600 indexers - the majority of which are private and users typically only use 1% to avoid needing to add indexers?

you'd still need to configure ever indexer you add.  What benefit do you gain from overwhelming the user and moving things 1 click closer? 

It sounds like what you actually want is to just display the supported high level categories on the add indexer modal?

**Comment by Chris230291** [comment]
> It sounds like what you actually want is to just display the supported high level categories on the add indexer modal?

Yes I suppose you are right. Showing the categories before you add would be enough.

> you also do not need many indexers at all. Anything more than a dozen or so at most and you're likely not actually getting any benefit. This is especially true with public trackers that scrape each other.

hmmm, I have added all of the public and a dozen or so semi-private ones. As long as there is no negative impact (other than slowing down response times), I think I'll leave them as is.

**Comment by VorlonCD** [comment]
Showing the categories when adding an Indexer would indeed be very helpful.
