### ISSUE TITLE
NZB Indexer WtF[nZb] returns results without Categories - Results in Red `Unknown` Category in Prowlarr GUI

### ISSUE THREAD

**Issue by VP-EN** [Prowlarr/Prowlarr#879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adding and searching the `WtF[nZb]` indexer results in getting a red "Unknown" category.

### Expected Behavior

For there to be visible categories

### Steps To Reproduce

**Steps to reproduce**
1. Add Indexer
2. Choose "Generic Newznab"
3. Input WtF[nZb] in title
4. Input `https://0ccec98d8962a17294688363537bfe2e.wtfnzb.pw` as URL
5. Keep `/api` in API path
6. Input my apikey and press Test (green checkmark)
7. Press Save and close the Add Indexer window
8. Go to Search (in Prowlarr), select the WtF[nZb] and search for whatever, in my case "fanget"
9. See the Unknown (red color) category and this message:
10. `Please report this issue to the GitHub as this shouldn't be happening`

### Environment

```markdown
- OS: Ubuntu 20.04 LTS
- Prowlarr: v0.2.0.1448 
- Docker Install: Yes (hotio)
- Using Reverse Proxy: Yes
- Browser: Firefox
```

### What branch are you running?

Master

### Trace Logs?

https://paste.ec/paste/ttN3LRYA#WSrK6SqR-cEL+0Ki6AM698lwVXyPhH4WN15qq3tWrVh

https://paste.ec/raw/ttN3LRYA#WSrK6SqR-cEL+0Ki6AM698lwVXyPhH4WN15qq3tWrVh (easier to load)

Huge log sorry. The ApiKey present in the log has been changed, and is no longer usable.

[AB#2772](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2772)

**Comment by bakerboy448** [comment]
Not a Prowlarr Issue.  The Site is failing to return a category for some releases. Note the empty Category Value.

```xml
<item>
	<title>Fanget.Paa.Politiets.Kamera.S05E04.DANiSH.1080p.WEB.h264-HYGGE [13da5ca18]</title>
	<guid isPermaLink="true">(removed)</guid>
	<link>(removed)</link>
	<comments>(removed)</comments> 	
	<pubDate>Thu, 24 Feb 2022 19:55:26 +0100</pubDate> 
	<category></category> 	
	<description>Fanget.Paa.Politiets.Kamera.S05E04.DANiSH.1080p.WEB.h264-HYGGE [13da5ca18]</description>
	<enclosure url="(removed)" length="1310586095" type="application/x-nzb" />
	<newznab:attr name="category" value="" />
	
	<newznab:attr name="size" value="1310586095" />
	<newznab:attr name="guid" value="122297ccead9f8595995375d62fe6b2d" />
	<newznab:attr name="sha1" value="e905a7ea3ed49a46e4285bb04d08c7c83547a37d" />

</item>
```

**Comment by VP-EN** [comment]
Anything I can do as a user of the site? Try and write to the admins?

**Comment by bakerboy448** [comment]
Yup

**Comment by VP-EN** [comment]
Anything specific to tell them? 😁
Searching through prowlarr returns no categories, something like that?

**Comment by bakerboy448** [comment]
I'd just go with some of their results fail to return categories

**Comment by VP-EN** [comment]
Alright. The admins basically told me, that they removed the categories from the API searches. And that they don't care about the API, so they're not going to change it.
Gonna close the issue

**Comment by bakerboy448** [comment]
So they're intentionally now breaking newznab standard and no longer can be used by any \*arr then - yikes

**Comment by VP-EN** [comment]
> So they're intentionally now breaking newznab standard and no longer can be used by any *arr then - yikes

Quite ridiculous.

You can see their answer here:
https://anopic.us/Qucv1iFKAaEqV6tRyCAF8Vstu9QKzK8sTGw2KGaI.jpg
