### ISSUE TITLE
Error when adding HDTorrents

### ISSUE THREAD

**Issue by BoBogsted** [Prowlarr/Prowlarr#884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello when i try to add HDTorrents as a indexer i get this error 
2022-03-11 02:55:26.6|Warn|IndexerHttpClient|HTTP Error - Res: [POST] https://hdts.ru/login.php: 503.ServiceUnavailable

### Expected Behavior

working as intended

### Environment

```markdown
- OS: Linux a12248ca6cf6 5.14.15-Unraid
- Prowlarr: 0.2.0.1448
- Docker Install: yes 
- Using Reverse Proxy: no
- Browser: Google Chrome 99.0.4844.51
```

### What branch are you running?

Master

### Trace Logs?

[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/8231408/prowlarr.txt)

[AB#2786](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2786)

**Comment by bakerboy448** [comment]
The tracker is down or otherwise not accessible.  This is not a Prowlarr bug
