### ISSUE TITLE
Basic Authentication support when running behind a Reverse Proxy.

### ISSUE THREAD

**Issue by Koomongous** [Prowlarr/Prowlarr#889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When running Prowlarr behind a VPN and a Reverse Proxy with Basic Authentication enabled, it cannot communicate with Sonarr/Radarr. This can be solved by making the Reverse Proxy public, or whitelisting the VPN's Public IP within the Reverse Proxy, which is a potential security hazard and not preferred.

### Describe the solution you'd like

I recently saw a feature within the app LunaSea which allows the user to enter the Basic Authentication details (Username and Password) for Sonarr/Radarr and then converts them to base64 encoding. This allows the app to login to the Reverse Proxy and communicate with Sonarrr/Radarr.

I suggest implementing a similar Basic Authentication option under the Advanced Settings for each App.

### Describe alternatives you've considered

Making the Reverse Proxy public, or whitelisting the VPN's Public IP within the Reverse Proxy, which is a potential security hazard and not preferred.

### Anything else?

![Screenshot 2022-03-15 003840](https://user-images.githubusercontent.com/71297607/158283592-61715fb9-24b5-47a9-ab8f-0fa0c006a786.png)

[AB#2792](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2792)

**Comment by bakerboy448** [comment]
Generally speaking you should not be going through a reverse proxy to communicate between the \*Arrs anyway - no benefit and only lots of headaches.  Low likelihood of this getting implemented.

The better question is why do you have your api paths requiring double authentication?
The APIs with your setup require both the basic auth and the apikey - there is no need for that and it also does not match the reverse proxy examples in the docs nor SWAG's configs either.

**Comment by Koomongous** [comment]
Due to some weird issue my prowlarr won't work with proxies so I am required to run it through a VPN. By using a Reverse Proxy it can now communicate with my arrs but I use Access Lists to stop just anyone accessing my network, meaning it can only communicate by either entering the Basic Auth or by having it's IP whitelisted. Normally I wouldn't run it like this but I've found that it works.

I realise it's a very edge case problem but it would be nice to have that option one day.
