### ISSUE TITLE
Rarbg not being added to radarr

### ISSUE THREAD

**Issue by TomW1605** [Prowlarr/Prowlarr#89]
everything else added fine. i couldnt find anything relevant in the logs but i am not sure what i was looking for so let me know if you want me to post the full trace log

**Comment by Qstick** [comment]
Need some logs, as it's working fine here

![image](https://user-images.githubusercontent.com/376117/120412202-27dd8500-c324-11eb-841c-ea1d2a5ed11a.png)

**Comment by TomW1605** [comment]
ok apparently it was a temporary glitch. it is working now and i cant find the logs from when it was not working. if it happens again i will make a new issue with some logs
