### ISSUE TITLE
Fix RarBG Categories - Categories are not Standardized nor Mapped Properly

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#893]
RarBG Code
![image](https://user-images.githubusercontent.com/55419169/158710792-d6d0c9c9-b51a-485b-ad30-9bf378f5dd96.png)

Categories Radarr gets - non-standard, not mapped, and generally janky.  
**Radarr is supposed to only be displaying Movie categories as well** - perhaps a Radarr bug as well as a Prowlarr bug?

![image](https://user-images.githubusercontent.com/55419169/158710845-169a0f66-e7ae-4d10-be82-54d56c08655a.png)
![image](https://user-images.githubusercontent.com/55419169/158710863-08c99382-5e3b-4e29-be33-33d358c5f79a.png)
![image](https://user-images.githubusercontent.com/55419169/158710885-80fd9783-24c9-4cc2-ae06-31aa6c562cdb.png)
![image](https://user-images.githubusercontent.com/55419169/158710957-226f3c9a-aaa4-4852-9309-3d31d209a782.png)
![image](https://user-images.githubusercontent.com/55419169/158710997-af6c38ab-57e7-4310-af95-a96448a7a960.png)

[AB#2799](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2799)

**Comment by Qstick** [comment]
Radarr allows one to see any Movie/TV/Indexer Custom category, that isn't a bug
