### ISSUE TITLE
FlareSolverr is not applied on all requests to a tracker; only initial

### ISSUE THREAD

**Issue by alexreg** [Prowlarr/Prowlarr#896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error message "Unable to connect to indexer. Unexpected response status ServiceUnavailable code from API request" when testing or using indexer that requires and is set up to use FlareSolverr.

### Expected Behavior

Test should succeed, and FlareSolverr should be applied on all HTTP requests.
As explained by @bakerboy448 on Discord, "we only are applying flaresolverr to the first request".

### Steps To Reproduce

1. Set up indexer for 1337x (https://1337x.unblockit.day/) that uses FlareSolverr.
2. Run 'Test'.
3. Observe above error message.

### Environment

```markdown
- OS: macOS 12.2.1
- Prowlarr: 0.2.0.1448
- Docker Install: Docker Desktop 4.5.0
- Using Reverse Proxy: no
- Browser: Safari 15.3
```

### What branch are you running?

Develop

### Trace Logs?

See <https://gist.github.com/alexreg/268629fe92e20eb7775becd31779c123>. (Too long to paste here.)

[AB#2804](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2804)

**Comment by Qstick** [comment]
FS is not meant to apply to every request. It's meant to be used to get a good cookie for us to use on all future requests. Attempting to solve and figure out a new cookie on every request would only slow things down greatly.

**Comment by Qstick** [comment]
I'll take a peek

**Comment by alexreg** [comment]
@Qstick Much appreciated.

**Comment by alexreg** [comment]
Quick update: this seems to be an issue with the specifics of local configuration. No need to worry.
