### ISSUE TITLE
include dead torrents in indexer setting toggle

### ISSUE THREAD

**Issue by MassaCreto** [Prowlarr/Prowlarr#897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

With a specific indexer, when using incldead=1, the results are less (11 results with a specific key phrase) than using incldead=0 (24 results). The current workaround is to edit the yml file for that indexer and change the value manually. It would be great to have that value changed with a toggle button in the indexer settings.

### Describe the solution you'd like

A toggle button, that would change the incldead from =1 to =0 and vice versa in the indexer settings modal.

### Describe alternatives you've considered

current workaround: edit the yml file manually and adjust the setting for the indexer.

### Anything else?

already raised a pull request in the indexer definitions to fix the search results for the specific yml, but this could be impacting other indexers, that are not in my scope of interest. https://github.com/Prowlarr/Indexers/pull/152

[AB#2809](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2809)

**Comment by bakerboy448** [comment]
If the torrents are dead and have no seeders then why would one want them returned?  Users will then complain that their torrents are not downloading.

This flag is not something all trackers support so there is no global setting that would make sense.  It would need to be added on a tracker by tracker basis and not a global flag or setting that is an option for all trackers.

**Comment by bakerboy448** [comment]
Closing; 

No plans to add a global toggle for every single tracker.

Trackers can be updated in a case by case basis to either change their search path or add a settings option to toggle to include dead torrents or not and the indexer definition updates the  search accordingly.

So far only 1 tracker has been reported and it has been a YML one which does not require any Prowlarr code changes to add such functionality.
