### ISSUE TITLE
[FEAT] - Control Indexers synced/used per App

### ISSUE THREAD

**Issue by TomW1605** [Prowlarr/Prowlarr#90]
it would be good to be able to decide what indexers are added to what apps.

eg i have 14 indexers that can technically do ebooks and audiobooks but there are only 5 i actually want readarr to use. i know this can be somewhat fixed by using priorities but that can mess with other apps.

[AB#35](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/35)

**Comment by newadventure079** [comment]
I was wondering the same thing for Sonarr and TV.  I saw there's tags and thought maybe it could be solved via those.  Tags are broken right now so I dont know the answer.

**Comment by neo-neo1** [comment]
> it would be good to be able to decide what indexers are added to what apps.

Agreed. I'm curious when or if it'll ever be added? As tags don't control this functionality currently either.

**Comment by bakerboy448** [comment]
> > it would be good to be able to decide what indexers are added to what apps.
> 
> Agreed. I'm curious when or if it'll ever be added? As tags don't control this functionality currently either.

The Feature Request is open and thus it'll be added eventually.

For those wanting this feature, just +1 the original OP (👍)

**Comment by bakerboy448** [comment]
This can now be accomplished with tags
https://github.com/Prowlarr/Prowlarr/commit/af50a1d3a8405e8d79a82dd9535909cb3f4213f5
