### ISSUE TITLE
remove queue check

### ISSUE THREAD

**Issue by Hakker** [Prowlarr/Prowlarr#911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Prowlarr says the torrent client hasn't got queue checked.

### Expected Behavior

ignore the queue all together. I find this a client setting not something Prowlarr should check for and if you want it then add it as a checkbox.

### Steps To Reproduce

check the queue box in your torrent client.

### Environment

```markdown
- OS: Linux/Docker
- Prowlarr: 0.2.0.1448
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Firefox 98
```

### What branch are you running?

Master

### Trace Logs?

not needed. I find it personally a bug it could be a feature depending on how you see it I guess.

[AB#2859](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2859)

**Comment by bakerboy448** [comment]
- What torrent client?

- Also curious why you selected `master` when no such branch exists?

**Comment by Qstick** [comment]
Indeed we need a bit more info on this one.

**Comment by Hakker** [comment]
Client is Qbittorrent.
As for the branch it's the latest Linux server docker images I expert that to be made from the main branch which hou van select from the pull down.

**Comment by Qstick** [comment]
Torrent Queueing effects how we prioritize downloads based on the priority you select in Qbit settings, either leave the priority as the default `Last` or enable queuing in qBit.
