### ISSUE TITLE
add the sync  / and advance settings (DONE) /  button to the indexer page

### ISSUE THREAD

**Issue by TomW1605** [Prowlarr/Prowlarr#92]
both these buttons are in settings but may regularly need to be accessed from the indexer page. i see no reason not to have them there as well.

[AB#36](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/36)

**Comment by Qstick** [comment]
Yea, the main reason I haven't yet is it screws with mobile view. I need to put some work in to clean that up and collapse options when they don't all fit

**Comment by Qstick** [comment]
a570fd2a8f138fb89c5b0ae43ddb7919f6bf26e3 for advance settings
