### ISSUE TITLE
Mtv responds with a html page instead of the torrent

### ISSUE THREAD

**Issue by quorn23** [Prowlarr/Prowlarr#922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My trace log
[https://0bin.net/paste/t-mjIxK-#t9AH7lfW65epT6FObeacqcESf4qz5CKPkGTwIGRSigB](https://0bin.net/paste/t-mjIxK-#t9AH7lfW65epT6FObeacqcESf4qz5CKPkGTwIGRSigB)

and here one posted by vityav in discord as well

[https://0bin.net/paste/Q+nT5wCY#TVUaFdAfdNx-ez7db0bti+RJCunIVqMl5Ex7WhQjesB](https://0bin.net/paste/Q+nT5wCY#TVUaFdAfdNx-ez7db0bti+RJCunIVqMl5Ex7WhQjesB)

Prowlarr says the searches are failing, but the link it shows results just fine.
The trace logs show it's pulling down the entire html of the page with all the torrents, 
The generic error seems to be: "Unexpected Response content"

In my understanding this GHI can be assigned to Yukine

### Expected Behavior

Have a working search/hit as per normal functionality like with other trackers.

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: Version 0.2.0.1632
            Package Version nightly-3873014 by hotio 
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: Firefox
```

### What branch are you running?

Nightly

### Trace Logs?

Tracelogs:

[https://0bin.net/paste/t-mjIxK-#t9AH7lfW65epT6FObeacqcESf4qz5CKPkGTwIGRSigB](https://0bin.net/paste/t-mjIxK-#t9AH7lfW65epT6FObeacqcESf4qz5CKPkGTwIGRSigB)

[https://0bin.net/paste/Q+nT5wCY#TVUaFdAfdNx-ez7db0bti+RJCunIVqMl5Ex7WhQjesB](https://0bin.net/paste/Q+nT5wCY#TVUaFdAfdNx-ez7db0bti+RJCunIVqMl5Ex7WhQjesB)

[AB#2893](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2893)

**Comment by DevYukine** [comment]
Hey could you do me a favor and only provide the relevant logs? disable all indexer besides MTV and then do a MTV only search so it will only include those, these 0bin's contain so much logs (which aren't related to MTV) that my browser always says the tab run out of memory and the other one was timed only so it was deleted

**Comment by missingfile** [comment]
Sorry to hijack DevYukine. Hope this PR is welcome.

Reference: https://github.com/Jackett/Jackett/pull/13106

**Comment by DevYukine** [comment]
> Sorry to hijack DevYukine. Hope this PR is welcome.
> 
> Reference: [Jackett/Jackett#13106](https://github.com/Jackett/Jackett/pull/13106)

No worries, i gladly accept someone who already made a pr 😄

**Comment by quorn23** [comment]
> Hey could you do me a favor and only provide the relevant logs? disable all indexer besides MTV and then do a MTV only search so it will only include those, these 0bin's contain so much logs (which aren't related to MTV) that my browser always says the tab run out of memory and the other one was timed only so it was deleted
> 
> that would help me idenitfying the issue

I would if i could, but at the moment MTV just fails in prowlarr in general, i'll disable the rest and restart prowlarr and if that works i'll edit an updated log in this post.

**Comment by missingfile** [comment]
Please stop pasting these. They contain your passkey.

**Comment by bakerboy448** [comment]
> Please stop pasting these. They contain your passkey.

Where's the passkey / what's its formatting as? If it's something stupid like "value="abc123456def" that probably can't be fixed without it being a bit overzealous  and cleanse things it should not be and if that's in the response it seems like rather poor site design IMO. But as far as I'm aware we have everything known and cleansed in the logs.

**Comment by missingfile** [comment]
There's 28 references to 5c879...

**Comment by quorn23** [comment]
> There's 28 references to 5c879...

Thanks, removed them, but they seem to change with any restart

**Comment by missingfile** [comment]
Actually staff have been resetting your key every time you've posted them publicly.

**Comment by quorn23** [comment]
> Actually staff have been resetting your key every time you've posted them publicly.

oof! Big thanks to the staff then. I'll create an additional issue for the cleansing the logs from it.
