### ISSUE TITLE
Add support for app

### ISSUE THREAD

**Issue by patsaindon** [Prowlarr/Prowlarr#937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Would be nice to add support for Whisparr app.

### Describe the solution you'd like

Would be nice to add support for Whisparr app.

### Describe alternatives you've considered

None

### Anything else?

No

[AB#2934](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2934)

**Comment by bakerboy448** [comment]
Already complete in nightly :)

https://github.com/Prowlarr/Prowlarr/commit/6ab226c43aac991d517ff7fab2ffdb99d9432839
