### ISSUE TITLE
Exoticaz Unable to Parse Category

### ISSUE THREAD

**Issue by crotoc** [Prowlarr/Prowlarr#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

2022-04-07 02:05:26.1|Error|ExoticaZ|An error occurred while processing indexer feed. https://exoticaz.to/api/v1/jackett/torrents?in=1&type=0&search=SSIS-356

### Expected Behavior

Search exoticaz and get results from the search.

### Environment

```markdown
- OS: gentoo
- Prowlarr: 
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Trace Logs?

https://0bin.net/paste/fYUx5Uzx#-jwH95oIvphJ41Sm4Rmd34yRcXdQItvghMzi0QjNbbK

[AB#2935](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2935)

**Comment by bakerboy448** [comment]
```
"category":{"1":"Video Clip"},
```

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/blob/fa2025cfd4b538d24a4a11bec6f5b13f8711fce0/src/Jackett.Common/Indexers/ExoticaZ.cs#L42-L49

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Prowlarr/commit/ce78f916574400d9dad0140b76a221d676d09d6c

currently in nightly only

**Comment by crotoc** [comment]
I tried nightly version "[Info] Bootstrap: Starting Prowlarr - /app/prowlarr/bin/Prowlarr - Version 0.3.0.1712", it throws error of Avistaz category type still.

Please see the trace file here:
https://0bin.net/paste/cKv8PhVk#TucxBeWz3mCCmYXBTWQot1AFyeLFm3KVHj9ed6Bbkj7

Error place:
2022-04-26 15:55:08.8|Error|ExoticaZ|An error occurred while processing indexer feed. https://exoticaz.to/api/v1/jackett/torrents?in=1&type=0&search=yua+mikami

**Comment by crotoc** [comment]
@bakerboy448 Please help have a check if it's an easy fix. Thanks very much!

**Comment by bakerboy448** [comment]
> @bakerboy448 Please help have a check if it's an easy fix. Thanks very much!

Probably easiest if someone can get and provide a list of their api category numbers and names from the site

**Comment by crotoc** [comment]
How can I get this for you?

**Comment by crotoc** [comment]
I sent them a support ticket and we will see. Hope they can provide. If not, maybe you can give me an instruction about how to get it.

**Comment by crotoc** [comment]
![image](https://user-images.githubusercontent.com/12446554/166583387-d3b58f2c-8492-4f07-ac27-91cfb9549926.png)

I check the html code of their website. Is this what we need?

**Comment by garfield69** [comment]
@bakerboy448  I notice that the Jackett exoticaz has some overrides for the avistaztracker abstract, does your code have similar?

**Comment by abixalmon** [comment]
Categories
```
1	Video Clip
2	Video Pack
3	Siterip Pack
4	Pornstar Pack
5	DVD
6	BluRay
7	Photo Pack
8	Books & Magazines
```

**Comment by garfield69** [comment]
I'm not a C# dev so take this evaluation with a pinch of salt.
The avistaz abstract that exoticaz references is set up to handle audio, movie and tv cateory types.
exoticaz is a 3x site, with xxx categories.
overrides are required to add 3x support to the avistaz abstract.

**Comment by crotoc** [comment]
@abixalmon Thanks very much!
Hope this helps! @bakerboy448

**Comment by crotoc** [comment]
@Qstick @bakerboy448 I figured that the problem is still there using nightly build of 0.4.0.1816. Is it because the #823 is blocked and has not been merged.

**Comment by Qstick** [comment]
Need new logs

**Comment by crotoc** [comment]
https://0bin.net/paste/2PvoUIx7#OWQFMTcw4BWfeXZhSYt-tTb+WIgcTNVmShf3Tg/d9aE

The error place:
2022-06-20 21:01:59.4|Error|ExoticaZ|An error occurred while processing indexer feed.

**Comment by Qstick** [comment]
Thanks, I'll have another look tonight

**Comment by crotoc** [comment]
Thank you! :)
