### ISSUE TITLE
Button to add NZB search result to cart instead of download

### ISSUE THREAD

**Issue by herkalurk** [Prowlarr/Prowlarr#951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

When doing a manual search in prowlarr, the only options for NZB related results is to either download the NZB file, or send it to your pre configured download application.

I'd love to see a 3rd button which allows prowlarr to send an API call back to the NZB index to add said release to the respective cart of the site where the result sits.

### Describe alternatives you've considered

Aside from manually searching on the web UI and adding to cart there. of each site, no.

### Anything else?

For newznab (which is most of the NZB hosts), it's a simple API call `https://FQDN/api?t=cartadd&id=GUID&apikey=KEY`

[AB#2979](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2979)

**Comment by Qstick** [comment]
No plans for this right now. maybe some day down the road.
