### ISSUE TITLE
Change or add MTV to use its API

### ISSUE THREAD

**Issue by menzo2003** [Prowlarr/Prowlarr#952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

MTV has added a Torznab API that seems to work very well. Using the API is way easer that extracting cookies strings that are used now.

### Describe the solution you'd like

Change the MTV preset to use the API or Add a second MTV entry that uses the API while it is in beta.

### Describe alternatives you've considered

It is useable as a generic torznab indexer but a preset would be better.

### Anything else?

info: https://www.morethantv.me/forum/thread/3080

[AB#2981](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2981)

**Comment by bakerboy448** [comment]
If they're Torznab then no changes are needed; Simply add them as Generic Torznab.

**Comment by KyleSanderson** [comment]
Shouldn't the old code be removed if there's a much better way? I too saw this, then looked at the issues and found this issue.
