### ISSUE TITLE
Fou-du-cinema 404 error

### ISSUE THREAD

**Issue by bckthomas** [Prowlarr/Prowlarr#955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://fou-du-cinema.net/login.php return 404, the new url to log in is https://fou-du-cinema.net/account-login.php

### Expected Behavior

Login to fou-du-cinema indexer

### Environment

```markdown
- Prowlarr: 0.2.0.1678
```

### What branch are you running?

Master

### Trace Logs?

IndexerHttpClient|HTTP Error - Res: [GET] https://fou-du-cinema.net/login.php: 404.NotFound
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

2022-04-14 12:49:31.1|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[AB#2993](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2993)

**Comment by garfield69** [comment]
the site has upgraded to TT3.0.  Source available at the usual place ;-)

**Comment by bakerboy448** [comment]
Fixes PR'd as usual :)

interim fix is to grab the definition file from jackett or the PR and drop it in. Note: that it'll be overwrote to the old one when the indexer def refresh task runs
