### ISSUE TITLE
noname-club(l) search russian terms not working

### ISSUE THREAD

**Issue by spirkaa** [Prowlarr/Prowlarr#959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Search russian terms not working.

### Expected Behavior

Working search on noname-club(L) indexer with russian terms like in Jackett

### Steps To Reproduce

Try to search anything in russian or `S01`

### Environment

```markdown
- OS: linuxserver/prowlarr
- Prowlarr: 0.3.0.1687
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: Chrome
```

### What branch are you running?

Nightly

### Trace Logs?

3 search actions performed:
- Severance (success)
- Severance S01 (fail because of keywordsfilters re_replace `S01` to `сезон 1`)
- Разделение (fail)

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/8496536/prowlarr.trace.txt)

Can be related to https://github.com/Jackett/Jackett/pull/6994

[AB#2998](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2998)

**Comment by bakerboy448** [comment]
Relevant Section of Trace
https://gist.github.com/bakerboy448/6d76833716cac5ad733d011fae13dd90
