### ISSUE TITLE
Do not reset options that are not passed by prowlarr

### ISSUE THREAD

**Issue by sarakha63** [Prowlarr/Prowlarr#972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello

For now if we use Full sync to keep in sync , indexers are synced that's good

But if we change the categories, or some other options such as "don't use year" in radarr, on every sync those options are reseted which is annoying.

### Expected Behavior

All options in radarr/ sonarr/ lidarr must be kept intact for those that arent configurable in prowlarr

categories
multi language
ignore year when seaching

are some examples

### Environment

```markdown
- OS: Debian (not os related)
- Prowlarr:0.2.0.1678 (not version related)
- Docker Install: Yes (not related)
- Using Reverse Proxy: No
- Browser: Not Ui related
```

### What branch are you running?

Nightly

### Trace Logs?

no related logs, i suppose it's the way prowlarr does it

I think prowlarr if the indexer already exists should query the info and then post 'by only replacing it's infos'

**Comment by bakerboy448** [comment]
Known side affect of fully sync and warned of such in the docs.

Use add/remove instead id you don't want that to occur.

**Comment by sarakha63** [comment]
> Known side affect of full sync and warned of such in the docs.
> 
> Use add/remove instead id you don't want that to occur.

Yes but i made some test as i now code. And it's possible to query the indexer object if exists on first place and only replace prowlarr's field then push back

as of course when you push an update all fields that are not present are reverted to default (which should not be handled like that on the apps side i guess and would be better if they handled on their side the fact that only fields received are updated)
