### ISSUE TITLE
[Xthor] Issues finding releases

### ISSUE THREAD

**Issue by Reymouth** [Prowlarr/Prowlarr#986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Building the link with "&freeleech=" when the torrent is not freeleech does not work

Ex: https://api.xthor.tk/?passkey=(removed)&category=13%2B15%2B17%2B123%2B109%2B&search=4400+4400+S01E01&tmdbid=&freeleech=

### Expected Behavior

Building the link without &freeleech= when the torrent is not freeleech does not work

Ex: https://api.xthor.tk/?passkey=(removed)&category=13%2B15%2B17%2B123%2B109%2B&search=4400+4400+S01E01&tmdbid=

### Steps To Reproduce

1. Call via the API a torrent not in freeleech (Not functional with the construction of the current link)
2. Call via the API a torrent in freeleech (functional with the construction of the current link)

Similar to issue : https://github.com/Jackett/Jackett/issues/13220

### Environment

```markdown
- OS: Unix 5.4.0-96 (64bit OS)
- Prowlarr: 0.3.0.1730
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome 100.0.4896.127
```

### What branch are you running?

Develop

### Trace Logs?

An error occurred while processing indexer feed. https://api.xthor.tk/?passkey=(removed)&category=13%2B15%2B17%2B123%2B109%2B&search=4400+4400+S01E01&tmdbid=&freeleech=: Value cannot be null. (Parameter 'value')

[AB#3107](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3107)

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/pull/181

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/commit/fb6cb9525f1037cede4eb796f86a1a8533a9c260
