### ISSUE TITLE
Support Raw Search for Rutracker.org

### ISSUE THREAD

**Issue by striker72199** [Prowlarr/Prowlarr#987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When the *arr's send search requests to Prowlarr for rutracker.org, puncutation is removed. For example, prowlarr sends Совсем пропащии instead of Совсем пропащий which leads to no results being found. In a prowlarr manual search using Совсем пропащий, results are found.  This can be seen on any of the files hosted on rutracker.

### Describe the solution you'd like

The definition for the rutracker indexer should have the correct flag indicating that raw search is supported. 

### Describe alternatives you've considered

Using a different tracker.

### Anything else?

None.

[AB#3108](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3108)

**Comment by Qstick** [comment]
@bakerboy448 this good?

**Comment by bakerboy448** [comment]
C# indexer, so not yet done.

**Comment by Qstick** [comment]
> C# indexer, so not yet done.

Yea, I mean should it be done? Is it legitimate request based on what you know?
