### ISSUE TITLE
Pull Jackett Commit 'core: cardigann json no results enhancement #13223' [989]

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#990]
Pull https://github.com/jackett/jackett/commit/4f7644b69216b3d7d694cf4f9184aa01776b24cd

```
git cherry-pick -ex 4f7644b69216b3d7d694cf4f9184aa01776b24cd
```

[AB#3116](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3116)

**Comment by garfield69** [comment]
do not pull that commit, use https://github.com/Jackett/Jackett/commit/626f03707f9b4b44ad76da6857e99b0c2e718aea instead.
